### ISSUE TITLE
Migrate Prometheus middleware

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#10]
Move the prometheus middleware from inside the old wascc-host repository to the `crates` directory inside this repository as its own standalone crate and ensure that this new middleware conforms to the new standard.

**Comment by Spora-GH** [comment]
have replied to the opentelemetry issue, will be uploading a WIP solution on Monday that absorbs this into configurable telemetry middleware, with context propagation across the lattice

**Comment by autodidaddict** [comment]
No longer applicable.
