### ISSUE TITLE
[FEATURE] `TestWashInstance` should have `stop_*` methods

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmCloud#1032]
**Is your feature request related to a problem? Please describe.**

Right now we have some nice handlers for starting things, but discovered there is nothing for stopping

**Describe the solution you'd like**

`TestWashInstance` should have stop methods for actors and providers

**Comment by connorsmith256** [comment]
Resolved by https://github.com/wasmCloud/wasmCloud/pull/1050 !
