### ISSUE TITLE
[BUG] Can't compile wash-cli on arm mac

### ISSUE THREAD

**Issue by zshehov** [wasmCloud/wasmCloud#1038]
Running `cargo install wash-cli` results in a compilation error: 

**To Reproduce**
1. Run command `cargo install wash-cli`
2. See error
```wash-lib-0.14.0/src/config.rs:102:49
    |
102 |         let mut builder = CtlClientBuilder::new(nc)
    |                           --------------------- ^^ expected `Client`, found `async_nats::Client`
    |                           |
    |                           arguments to this function are incorrect
    |
    = note: `async_nats::Client` and `Client` have similar names, but are actually distinct types
note: `async_nats::Client` is defined in crate `async_nats`
   --> .../async-nats-0.31.0/src/client.rs:50:1
    |
50  | pub struct Client {
    | ^^^^^^^^^^^^^^^^^
note: `Client` is defined in crate `async_nats`
   --> .../async-nats-0.33.0/src/client.rs:52:1
    |
52  | pub struct Client {
    | ^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `async_nats` are being used?
```

**Expected behavior**
Successful installation of `wash-cli`

**Environment (please complete the following information) **
 - OS: MacOS Sonoma
 - Shell: zsh

**Additional context**
2 versions of `async_nats` are compiled during the installation:
- async-nats v0.31.0
- async-nats v0.33.0

**Comment by rvolosatovs** [comment]
Hey @zshehov, thank you for report, until #1042 is merged, you should be able to install `wash-cli` via:
```
cargo install wash-cli --git https://github.com/rvolosatovs/wasmcloud --branch fix/update-wadm
```

Or use our binary releases

**Comment by vados-cosmonic** [comment]
Hey @zshehov would you mind posting the output of [`cargo tree`](https://doc.rust-lang.org/cargo/commands/cargo-tree.html) here?

The workaround noted by @rvolosatovs above should work to get you moving (please let us know if it doesn't), but I'm curious exactly which dependency is causing `async_nats` `0.33` to be pulled in.

**Comment by rvolosatovs** [comment]
Actually, let's keep this one open until we have a new release

**Comment by zshehov** [comment]
Hey, thanks for the quick reaction guys, that's awesome!

**Comment by connorsmith256** [comment]
@zshehov This should be fixed now: `cargo install wash-cli` should successfully install v0.24.0. Thanks for the report and your patience!
