### ISSUE TITLE
[FEATURE] OTEL over NATS

### ISSUE THREAD

**Issue by hwinkel** [wasmCloud/wasmCloud#1040]
**OTEL Traces and Metrics over NATS**

Can the NATS Connectivity used to encapsulate the transport of the OTEL trace and later metrics data?
It would be good to use the NATS lattice to forward the telemetry data regardless of the topology and
not rely on 1:1 HTTP connections.

**Comment by thomastaylor312** [comment]
Hi @hwinkel! So for many of the things inside of the wasmcloud host we use [this crate](https://github.com/wasmCloud/wasmCloud/tree/main/crates/opentelemetry-nats) to put the otel data in the NATS headers. However, we were planning on removing it from everything except for the NATS provider as we use a field in our `Invocation` type to send the trace data. Can you give me a little more info on your use case? If there are some good reasons why we shouldn't remove it, it would be great to know!

**Comment by thomastaylor312** [comment]
So we will likely be adding support back for otel NATS headers via our forthcoming wRPC work in #1128

**Comment by thomastaylor312** [comment]
@brooksmtownsend We can mark this as closed now, right?
