### ISSUE TITLE
[BUG] wasmCloud bot app is not correctly set up in the repository

### ISSUE THREAD

**Issue by rvolosatovs** [wasmCloud/wasmCloud#1046]
**Describe the bug**

wasmCloud bot app is not correctly set up in the repository. It appears that it's not installed. It may also be that the wrong app ID is used.

**To Reproduce**
1. https://github.com/wasmCloud/wasmCloud/actions/runs/6932414237/job/18856290231

**Expected behavior**
Success

**Screenshots**
Here's what app configuration page should look like when it's correctly set up
![Screenshot 2023-11-20 at 16 15 07](https://github.com/wasmCloud/wasmCloud/assets/12877905/b2a9d99e-aa35-48bb-8da3-3dad4e896c20)

**Comment by brooksmtownsend** [comment]
@rvolosatovs I tried to update this, let me know if that fixed it. I needed to install the app in the organization

**Comment by rvolosatovs** [comment]
Done, see #1047
