### ISSUE TITLE
[BUG] StartProviderAck does not include provider_ref

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#106]
**Describe the bug**
When starting a provider via the command interface, the resulting Ack does not include the provider reference and is instead blank.

**To Reproduce**
1. Launch a wasmcloud host (using `wash up` is a simple option)
2. Run `ctl start provider wasmcloud.azurecr.io/httpserver:0.11.1 -o json`
3. Examine `provider_ref` field

**Expected behavior**
Similar to `actor_ref` which is included in the ack [here](https://github.com/wasmCloud/wasmCloud/blob/main/crates/wasmcloud-host/src/control_interface/handlers.rs#L264), similar logic should be added to the `start_provider` logic further down in the `handlers` file.

**Environment (please complete the following information) **
- OS: [e.g. Linux, MacOS, Windows]: MacOS
- Architecture: [e.g. x86_64, arm64]: x86_64
- Shell [e.g. bash, zsh, powershell]: zsh
- wasmcloud version [e.g. `0.15.0`]: 0.15.1

**Comment by autodidaddict** [comment]
Just as long as we know that we can't include information that requires the entity to have been started, since the ack for the provider start is returned _prior_ to the provider being loaded/started (e.g. we can't include its public key)

**Comment by brooksmtownsend** [comment]
Yeah it looks like the provider_ref is available as part of the command (as it's what information we need to try to start a provider) so we'd just be returning that
