### ISSUE TITLE
[BUG] Update actor does not support updates with different OCI references

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#108]
**Describe the bug**
When using the control interface to update an actor, you cannot update an actor with an OCI reference that differs from the original reference.

**To Reproduce**
1. Launch a wasmcloud host (I'm using the `wash up` command)
2. `ctl start actor wasmcloud.azurecr.io/echo:0.2.0`
3. `ctl update actor <HOST_ID> MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5 wasmcloud.azurecr.io/echo:0.2.1`
4. See update actor acknowledgment `Actor MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5 updated to wasmcloud.azurecr.io/echo:0.2.1`
5. See error log:`
12:42:31:ERROR:wasmcloud_host::actors::actor_host:/Users/btownsend/.../wasmcloud-host-0.15.0/src/actors/actor_host.rs:74:Live updated targeted at this actor but the image ref does not match`
6. Confirm in host inventory, running actor: `MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5   wasmcloud.azurecr.io/echo:0.2.0 `

**Expected behavior**
As long as public key matches, claims match, and revision is greater than the original actor, I expect the `0.2.0` version of the actor to be removed from the host and replaced with the `0.2.1` version

**Environment (please complete the following information) **
- OS: [e.g. Linux, MacOS, Windows]: MacOS
- Architecture: [e.g. x86_64, arm64]: x86_64
- Shell [e.g. bash, zsh, powershell]: zsh
- wasmcloud version [e.g. `0.15.0`]: `0.15.1`

**Comment by autodidaddict** [comment]
I'm looking into this and I've found the problem and there are a couple of other subtle things that also need to be corrected. @brooksmtownsend I will  submit a PR for this one once the PRs on wasmCloud for the actix upgrades are merged.
