### ISSUE TITLE
Update event subscribers to use suffixed subjects

### ISSUE THREAD

**Issue by connorsmith256** [wasmCloud/wasmCloud#1091]
As of https://github.com/wasmCloud/wasmCloud/pull/1090, the host emits events on `wasmbus.evt.{latticeID}.{eventName}`. Some subscribers (tests in wash, the washboard, and wadm) still subscribe to the non-suffixed subject. 

These clients should be updated prior to wasmCloud 1.0

**Comment by brooksmtownsend** [comment]
Hijacking this issue just to drop a nice-to-have, it would be really nice to have a defined list of all the events we publish and, optimally, some kind of JSON schema or other specifier for the expected fields on those events. Unsure if https://cloudevents.io/ has a good tool to do this

**Comment by ahmedtadde** [comment]
hey @brooksmtownsend , do you have an idea/tip of how one would go about taking a survey of all events that are published? For the particular case of `wasmbus.evt.{latticeID}`, @connorsmith256 I haven't been able to located its use in `wadm` and `wash` tests (although, it seems like @vados-cosmonic already made such changes for tests some weeks ago). [ I only found one place](https://github.com/ahmedtadde/wasmCloud/blob/eb28511acc3d86a49f97616d39d9b6920824db07/washboard-ui/src/lattice/lattice-service.ts#L137) in `washboard-ui` where it is being used.

**Comment by brooksmtownsend** [comment]
@ahmedtadde that's a good question. We do want to have a place where we officially note all of the events that are published, but for now it's best discovered by looking for calls to `publish_event`.

1. `host_heartbeat`
2. `host_started`
3. `host_stopped`
4. `actor_start_failed`
5. `actors_start_failed`
6. `provider_started`
7. `provider_start_failed`
8. `provider_stopped`
9. `config_set`
10. `config_deleted`
11. `linkdef_set`
12. `linkdef_deleted`
14. `actors_started`
16. `actors_stopped`

Soon to be added
1. `actor_scaled`
2. `actor_scale_failed`

There but soon to be gone 
13. `actor_started`
15. `actor_stopped`

**Comment by connorsmith256** [comment]
- [ ] wadm https://github.com/wasmCloud/wadm/pull/241
- [ ] control interface and wash https://github.com/wasmCloud/wadm/pull/241
- [ ] washboard @lachieh

**Comment by lachieh** [comment]
Clients are all done, good to close?

**Comment by connorsmith256** [comment]
@lachieh yep!
