### ISSUE TITLE
Refactor Claims

### ISSUE THREAD

**Issue by connorsmith256** [wasmCloud/wasmCloud#1093]
The current `Claims` struct is hard to work with, especially during ser/deser. This has led to the need to create helper structs that work around these difficulties.

We should:
- refactor `Claims` to be an enum with variants that have easily accessible fields
- remove `StoredClaims` from the host and use `Claims` directly
- update `GetClaimsResponse` to use `Claims` directly, instead of a `HashMap<String, String>`
- update wash and other clients to use the typed data

**Comment by rvolosatovs** [comment]
refs #1119 , if that RFC is accepted we can just remove the claims altogether
