### ISSUE TITLE
[FEAT] Make wash claims aware of wasmcloud.toml

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#1101]
## Feature
Just like `wash build` infers information about a project from the `wasmcloud.toml` file, it should be a one step process to run `wash claims sign` to sign an existing wasm file without building.

## Alternatives considered
Instead of adding this support, we could make the signing process a core piece of the `build` command. I don't see any reason why having flexibility here would be bad, running the sign command without worrying about the build process at all is valuable and this would essentially just reduce the number of parameters necessary to supply with `wash claims sign`. 

## Origin

              One thing about the `--sign-only` flag: Would it be better user experience for `wash sign` to be `wasmcloud.toml` aware? It feels like that would be more discoverable and ergonomic from my POV

_Originally posted by @thomastaylor312 in https://github.com/wasmCloud/wasmCloud/issues/938#issuecomment-1808926592_

**Comment by connorsmith256** [comment]
Closing since this is obviated by https://github.com/wasmCloud/wasmCloud/issues/1219
