### ISSUE TITLE
[BUG] Smithy-powered actor w/ interface-httpserver=0.12 & wasmbus-rpc=0.15 fails

### ISSUE THREAD

**Issue by vados-cosmonic** [wasmCloud/wasmCloud#1103]
**Describe the bug**
While attempting to run the usual command line tooling (`wash up`, `wash start (provider|actor)`, `wash link put`) with a custom, locally built derivation of the `echo` actor, I found that `wasmcloud` (started by `wash up`, so version `0.80.0` at this point in time) failed with a nasty error:

<details>
<summary> 📜 Logs (click to open)</summary>

```
2023-11-28T15:03:46.995200Z  INFO wasmbus_rpc::provider: Linking actor with provider
2023-11-28T15:03:46.995237Z  INFO wasmcloud_provider_httpserver: httpserver starting listener for actor addr=127.0.0.1:44789 actor_id=MCNN2KATN5XSZSQG557JZOGI4PWXYJTHXFDF4MRTECW437CEYEMEKAW6
2023-11-28T15:03:46.996858Z  INFO warp::filters::trace: processing request
thread 'tokio-runtime-worker' panicked at 'range end index 18446744073709551614 out of range for slice of length 0', /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/nkeys-0.3.2/src/crc.rs:48:21
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::slice::index::slice_end_index_len_fail
   3: nkeys::crc::extract_crc
   4: nkeys::decode_raw
   5: nkeys::KeyPair::from_public_key
   6: <wasmcloud_runtime::capability::builtin::ActorIdentifier as core::convert::From<&str>>::from
   7: <wasmcloud_host::wasmbus::Handler as wasmcloud_runtime::capability::builtin::Bus>::identify_wasmbus_target::{{closure}}
   8: <wasmcloud_runtime::capability::builtin::Handler as wasmcloud_runtime::capability::builtin::Bus>::identify_wasmbus_target::{{closure}}
   9: wasmcloud_runtime::actor::module::wasmbus::handle::{{closure}}::{{closure}}
  10: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  11: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  12: wasmcloud_runtime::actor::module::wasmbus::host_call::{{closure}}
  13: wasmtime::store::AsyncCx::block_on
  14: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  15: wasmtime_runtime::instance::Instance::from_vmctx
  16: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1,A2,A3,A4,A5,A6,A7,A8),R>>::into_func::native_call_shim
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: wasmtime_runtime::traphandlers::catch_traps::call_closure
  30: wasmtime_setjmp_13_0_0
  31: wasmtime_runtime::traphandlers::<impl wasmtime_runtime::traphandlers::call_thread_state::CallThreadState>::with
  32: wasmtime_runtime::traphandlers::catch_traps
  33: wasmtime::func::invoke_wasm_and_catch_traps
  34: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  35: wasmtime_fiber::unix::fiber_start
  36: wasmtime_fiber_start_13_0_0
  37: wasmtime_fiber::Fiber<Resume,Yield,Return>::resume
  38: wasmtime::store::<impl wasmtime::store::context::StoreContextMut<T>>::on_fiber::{{closure}}::FiberFuture::resume
  39: <wasmtime::store::<impl wasmtime::store::context::StoreContextMut<T>>::on_fiber::{{closure}}::FiberFuture as core::future::future::Future>::poll
  40: wasmtime::func::typed::TypedFunc<Params,Results>::call_async::{{closure}}
  41: wasmcloud_runtime::actor::module::Instance::call::{{closure}}::{{closure}}
  42: wasmcloud_runtime::actor::module::GuestInstance::call::{{closure}}::{{closure}}
  43: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  44: <wasmcloud_runtime::actor::module::GuestInstance as wasmcloud_runtime::capability::builtin::IncomingHttp>::handle::{{closure}}
  45: <wasmcloud_runtime::actor::IncomingHttpInstance as wasmcloud_runtime::capability::builtin::IncomingHttp>::handle::{{closure}}
  46: wasmcloud_host::wasmbus::ActorInstance::handle_invocation::{{closure}}::{{closure}}
  47: wasmcloud_host::wasmbus::ActorInstance::handle_call::{{closure}}::{{closure}}
  48: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
  49: <futures_util::stream::stream::for_each_concurrent::ForEachConcurrent<St,Fut,F> as core::future::future::Future>::poll
  50: tokio::runtime::task::core::Core<T,S>::poll
  51: tokio::runtime::task::harness::Harness<T,S>::poll
  52: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  53: tokio::runtime::scheduler::multi_thread::worker::Context::run
  54: tokio::runtime::context::scoped::Scoped<T>::set
  55: tokio::runtime::scheduler::multi_thread::worker::run
  56: tokio::runtime::task::core::Core<T,S>::poll
  57: tokio::runtime::task::harness::Harness<T,S>::poll
  58: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2023-11-28T15:03:48.998341Z ERROR wasmbus_rpc::rpc_client: sending request error=timeout: deadline has elapsed
2023-11-28T15:03:48.998361Z ERROR wasmbus_rpc::rpc_client: sending request error=nats: timeout: deadline has elapsed topic=wasmbus.rpc.default.MCNN2KATN5XSZSQG557JZOGI4PWXYJTHXFDF
```

</details>

After some investigation, it looks like this is a failure in `nkeys`, in particular a `usize` underflow:

https://github.com/wasmCloud/nkeys/blob/v0.3.2/src/crc.rs#L48
https://doc.rust-lang.org/std/primitive.usize.html#associatedconstant.MAX

>  thread 'tokio-runtime-worker' panicked at 'range end index 18446744073709551614 out of range for slice of length 0', /nix/store

So:
`18_446_744_073_709_551_615`
`18_446_744_073_709_551_614`

The fix should be made upstream, but there are a few questions:

- How could we catch this *before* this happened? i.e. @ the release of *either* `wasmcloud@0.80.0`, `wasmcloud-interface-httpserver=0.12` or `wasmbus-rpc=0.15` would have given us a chance to catch this bug
- How could the CRC data be empty despite all the tooling giving the thumbs up? Are there some changes that need to be made to `wash` to prevent/double check?
- This failure in what is essentially input parsing should not have crashed the host (we can't do much of an upstream dep `panic`s, but maybe worth thinking about some resiliency here).

**To Reproduce**
1. Build an actor with `wasmcloud-interface-httpserver=0.12` & `wasmbus-rpc=0.15`
1. Observe/Check that `wash build`, `wash inspect`, etc all succeed
1. Observe/Check that `wash start provider` (i.e. the httpserver) and `wash start actor file:///....` and related commands succeed
1. Attempt to `wash link put`
1. Observe :boom: 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information) **
 - OS: [e.g. Linux, MacOS]
 - Shell [e.g. bash, zsh, powershell]
 - wasmcloud Version [e.g. 0.78.0]

**Additional context**

**Comment by connorsmith256** [comment]
@vados-cosmonic I don't think I can reproduce this... Here's what I did:

- `wash new actor` (using hello template)
  - updated `wasmbus-rpc` to 0.15 and `wasmcloud-interface-httpserver` to 0.12
- `wash build`
- `./target/debug/wasmcloud --log-level trace --allow-file-load`
- `wash start provider wasmcloud.azurecr.io/httpserver:0.19.0`
- `wash start actor file:///Users/connor/scratch/wasmbus-15-test/build/wasmbus_15_test_s.wasm`
- `wash link put MAGY77XTT2T56WPTGKF4FQO4EAB72WMM4WKKPM7PWK5ATJASGQ7GUQOU VAG3QITQQ2ODAOWB5TTQSDJ53XK3SHBEIFNK4AYJ5RKAX2UNSCAPHA5M wasmcloud:httpserver address=0.0.0.0:4321`
  - `2023-11-28T19:25:47.594679Z  INFO handle_link_put{actor_id=MAGY77XTT2T56WPTGKF4FQO4EAB72WMM4WKKPM7PWK5ATJASGQ7GUQOU provider_id=VAG3QITQQ2ODAOWB5TTQSDJ53XK3SHBEIFNK4AYJ5RKAX2UNSCAPHA5M contract_id=wasmcloud:httpserver link_name=default}: wasmcloud_provider_httpserver: httpserver starting listener for actor addr=0.0.0.0:4321 actor_id=MAGY77XTT2T56WPTGKF4FQO4EAB72WMM4WKKPM7PWK5ATJASGQ7GUQOU`
- `curl 127.0.0.1:4321` (got back hello world)

**Comment by vados-cosmonic** [comment]
Thanks for trying it out -- one thing I'm realizing I forgot to mention is `interface-keyvalue`, I'm thinking that might have something to do with it, I forgot to mention the `wasmcloud-interface-keyvalue` dep. The functionality I was trying to achieve is more `kvcounter` than `echo`.

Looks like I was holding it wrong, attempting to use `wasmbus-rpc=0.15` like this:

```rust
        // Create a sender that can send to Wasm host
        let sender = KeyValueSender::via(WasmHost::default());
```

What I should have been using was `KeyValueSender::new()`, the `nkeys` issue was unrelated but happened to pop up it looks like -- closing this for now
