### ISSUE TITLE
Drop deprecated wasmbus.evt.{latticeID} subject

### ISSUE THREAD

**Issue by connorsmith256** [wasmCloud/wasmCloud#1104]
As of https://github.com/wasmCloud/wasmCloud/pull/1090, the host now emits events on `wasmbus.evt.{latticeID}` as well as `wasmbus.evt.{latticeID}.{eventName}`

Prior to 1.0, we should drop the former, as it is deprecated. Clients which wish to continue subscribing to all events can do so with a `wasmbus.evt.{latticeID}.>` subject filter

**Comment by connorsmith256** [comment]
Note this is blocked by https://github.com/wasmCloud/wasmCloud/issues/1091

**Comment by brooksmtownsend** [comment]
Completed in #1613
