### ISSUE TITLE
[RFC] Formalize the wasmCloud Control Interface

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#1108]
# RFC: Formalize the wasmCloud Control Interface

## Introduction
The wasmCloud control interface is how any client can instruct a wasmCloud host to take an action over NATS. This can be anything from adding or removing labels, starting and stopping actors/providers, or even shutting down the host itself. In a sense, the control interface is the API server of wasmCloud, and as we approach 1.0 it should be scrutinized and stabilized in a way that protects us from future change.

## Motivation

Currently there are X aspects of the control interface that I think we should look at and consider before we call the control interface protocol "stable" for 1.0:
1. The topic format should be standard where possible, e.g. `wasmbus.ctl.<version>.<lattice>.<noun>.<verb>.<host_id>`
2. The topic format should be versioned by an API version (see `<version>` above) to protect from future changes that are over-the-wire incompatible
3. Our set of operations on the control interface should encompass the foreseeable list of operations that we want to have for interacting with the host

## Detailed Design

You can see a list of all control interface topics at https://wasmcloud.com/docs/hosts/lattice-protocols/control-interface, but for enumeration you can see them below. Similar to the redesign in `wash-cli`, I propose that we follow a noun -> verb ordering for control interface topics. Regarding 2 above, the version should be present after the standard topic prefix. Additionally, I'm proposing we add two additional control interface topics which are up for discussion.

| Current                                       | Proposed |
|-----------------------------------------------|----------|
| `wasmbus.ctl.{lattice_prefix}.auction.provider` |     `wasmbus.ctl.{version}.{lattice_prefix}.provider.auction`     |
| `wasmbus.ctl.{lattice_prefix}.auction.actor`    |      `wasmbus.ctl.{version}.{lattice_prefix}.actor.auction`    |
| `wasmbus.ctl.{lattice_prefix}.cmd.{host-id}.la` (deprecated) |     Remove in favor of scale    |
| `wasmbus.ctl.{lattice_prefix}.cmd.{host-id}.sa` |      Remove in favor of scale    |
| `wasmbus.ctl.{lattice_prefix}.cmd.{host-id}.scale` |     `wasmbus.ctl.{version}.{lattice_prefix}.actor.scale.{host_id}`     |
| `wasmbus.ctl.{lattice_prefix}.cmd.{host-id}.upd` |     `wasmbus.ctl.{version}.{lattice_prefix}.actor.update.{host_id}`     |
| `wasmbus.ctl.{lattice_prefix}.cmd.{host-id}.lp` |     `wasmbus.ctl.{version}.{lattice_prefix}.provider.launch.{host_id}`     |
| `wasmbus.ctl.{lattice_prefix}.cmd.{host-id}.sp` |      `wasmbus.ctl.{version}.{lattice_prefix}.provider.stop.{host_id}`    |
| `wasmbus.ctl.{lattice_prefix}.cmd.stop`         |    `wasmbus.ctl.{version}.{lattice_prefix}.host.stop.{host_id}`    |
| `wasmbus.ctl.{lattice_prefix}.get.links`        |     `wasmbus.ctl.{version}.{lattice_prefix}.link.get`     |
| `wasmbus.ctl.{lattice_prefix}.get.claims`       |    `wasmbus.ctl.{version}.{lattice_prefix}.claims.get`      |
| `wasmbus.ctl.{lattice_prefix}.get.{host-id}.inv` |      `wasmbus.ctl.{version}.{lattice_prefix}.host.get.{host_id}`    |
| `wasmbus.ctl.{lattice_prefix}.ping.hosts`       |      `wasmbus.ctl.{version}.{lattice_prefix}.host.ping`    |
| `wasmbus.ctl.{lattice_prefix}.linkdefs.put`     |     `wasmbus.ctl.{version}.{lattice_prefix}.link.put`     |
| `wasmbus.ctl.{lattice_prefix}.linkdefs.del`     |      `wasmbus.ctl.{version}.{lattice_prefix}.link.del`    |
| `wasmbus.ctl.{lattice}.labels.{host_id}.put` | `wasmbus.ctl.{version}.{lattice}.label.put.{host_id}` |
| `wasmbus.ctl.{lattice}.labels.{host_id}.del` | `wasmbus.ctl.{version}.{lattice}.label.del.{host_id}` |
| `wasmbus.ctl.{lattice}.get.config.{entity}.{key}` | `wasmbus.ctl.{version}.{lattice}.config.get.{entity}.{key}` |
| `wasmbus.ctl.{lattice}.get.config.{entity}` | `wasmbus.ctl.{version}.{lattice}.config.get.{entity}` |
| `wasmbus.ctl.{lattice}.config.put.{entity}.{key}` | `wasmbus.ctl.{version}.{lattice}.config.put.{entity}.{key}` |
| `wasmbus.ctl.{lattice}.config.del.{entity}.{key}` | `wasmbus.ctl.{version}.{lattice}.config.del.{entity}.{key}` |
| `wasmbus.ctl.{lattice}.config.del.{entity}` | `wasmbus.ctl.{version}.{lattice}.config.del.{entity}` |

The following topics can be added as they are implemented:
| N/A | `wasmbus.ctl.{version}.{lattice_prefix}.provider.update` |
| N/A | `wasmbus.ctl.{version}.{lattice_prefix}.link.update` |

## Backwards Compatibility

- This will require significant breaking changes on the first rollout that we can mitigate by subscribing to the old topics, but only temporarily
- The `{version}` in the topic, if omitted, can always be considered as `v1`. I propose for ease of use we go ahead and include the `v1` in the topic right away to avoid complicated matching on the topics.

## Alternatives Considered

I considered verb -> noun ordering but that would go against what we already have in place with wash-cli. Additionally, it's worth considering how much we want to add the two new topics above for updating providers and links, as I think the idea of live updating those two like actors is a good idea but may not exactly fit.

## Unresolved Questions

1. I'm unsure if we should keep `launch provider` as above for when we have WASI providers, or if we should change that preemptively to `scale provider`. Scaling a provider at the moment only makes sense for values of `0` or `1` as we don't allow providers to run duplicate copies.
    A: When we get to this point, we can use the version on the topic to add more commands! 😄 
3. I used plurals in the topic above when referring to multiple things (e.g. ping hosts vs get host)
    A: Resolved in proposal

## Conclusion

Please leave comments below on what you think of this proposal. Implementation details we can figure out at the time of PR, but I really want feedback on the:
1. Topic format
2. Launch provider topic
5. Execution of formalizing the types in the control interface. I'm pretty sure we can just continue with the current types

**Comment by connorsmith256** [comment]
Thank you for writing this up 🙌 ❤️ 

> The topic format should be standard where possible, e.g. wasmbus.ctl.<version>.<lattice>.<noun>.<verb>.<host_id>

I noticed in the table `host_id` often came after the `lattice` (as it does today). Are you proposing moving it to the end? 

> Similar to the redesign in wash-cli, I propose that we follow a noun -> verb ordering for control interface topics

I noticed most of the entries in the table use verb -> noun. Was that intended?

FWIW, I think I prefer noun -> verb. One (small) advantage with that order is enabling easier subject filtering. E.g. `nats sub wasmbus.ctl.v2.default.links.>` would let me subscribe on all link-related traffic. Whereas `nats sub wasmbus.ctl.v2.default.put.>` isn't as useful

> The {version} in the topic, if omitted, can always be considered as v1. I propose for ease of use we go ahead and include the v1 in the topic right away to avoid complicated matching on the topics.

This sounds good 👍 
 
> Additionally, it's worth considering how much we want to add the two new topics above for updating providers and links, as I think the idea of live updating those two like actors is a good idea but may not exactly fit.

I think these are good for parity's sake. Updating a link as an atomic operation would also remove race conditions present today.

Why no filled entry for the registry config topic or label put/del?

> I'm unsure if we should keep launch provider as above for when we have WASI providers, or if we should change that preemptively to scale provider

I think this is TBD. I know @rvolosatovs and @ricochet have been thinking about WASI providers

> I used plurals in the topic above when referring to multiple things (e.g. ping hosts vs get host)

I would be okay with `wasmbus.ctl.v2.default.host.ping` and `wasmbus.ctl.v2.default.host.get`, to eliminate the need for plurals.

Likewise with `wasmbus.ctl.v2.default.link.get` (for all links) and `wasmbus.ctl.v2.default.link.get.{linkID}` (for one link), hypothetically

I would make an exception for `claims`, which is a (singular) collection of things, like pants 👖

**Comment by connorsmith256** [comment]
Oh, and do we want topics to delete claims? https://github.com/wasmCloud/wasmCloud/issues/851

**Comment by connorsmith256** [comment]
And how about https://github.com/wasmCloud/wasmCloud/issues/998 ?

**Comment by autodidaddict** [comment]
From a security standpoint, I think noun->verb works better. For example, if you want to restrict some credential to only having the ability to interact with providers, under the verb->noun you'd have to specify all known verbs (or *). But to grant access to provider methods in noun->verb, it's just `provider.*` or `provider.get` etc

**Comment by brooksmtownsend** [comment]
@connorsmith256 

> I noticed in the table host_id often came after the lattice (as it does today). Are you proposing moving it to the end?

Not quite, mostly just moving to right after the lattice ID for operations that require a host ID. I believe I set that up in the table where I was proposing topics. The only downside here is that sometimes the 5th piece of the topic is the noun (see below), and sometimes it would be the host ID. Perhaps it would be better to make the host ID the last positional argument.

For example,
```
wasmbus.ctl.{version}.{lattice_prefix}.actor.auction
wasmbus.ctl.{version}.{lattice_prefix}.{host_id}.actor.update
```
v.s.
```
wasmbus.ctl.{version}.{lattice_prefix}.actor.auction
wasmbus.ctl.{version}.{lattice_prefix}.actor.update.{host_id}
```

In the latter, you could do `nats sub wasmbus.ctl.v1.default.actor.>` for all actor operations, but in the former you can't. 

> FWIW, I think I prefer noun -> verb.

I preferred verb -> noun for the parity with wash, but I totally agree that filtering on the topics would be nice re: @autodidaddict's suggestion.

- [ ] I propose we switch noun -> verb and move host ID to the end of the topic, officially making the standard `wasmbus.ctl.{version}.{lattice_prefix}.{noun}.{verb}.{optional_host_id}`

> Why no filled entry for the registry config topic or label put/del?

I didn't dig for it when writing the RFC 😢 

> I would be okay with wasmbus.ctl.v2.default.host.ping and wasmbus.ctl.v2.default.host.get, to eliminate the need for plurals. ...  would make an exception for claims, which is a (singular) collection of things, like pants

I'm cool with this, and I would also be okay just singularizing everything.

**Comment by brooksmtownsend** [comment]
One thing you could do at least is subscribe on `wasmbus.ctl.*.*.*.*.{host_id}` 😄

**Comment by thomastaylor312** [comment]
I have no additional comments beyond what has already been said and I like how this is looking

**Comment by brooksmtownsend** [comment]
@thomastaylor312 / @connorsmith256 this is ready for a final review, topics are updated above to match all current ones I could find in the host. Any other comments? 👍🏻 / 👎🏻

**Comment by connorsmith256** [comment]
@brooksmtownsend the updated table looks great. I don't see `.claims.del`. Assuming https://github.com/wasmCloud/wasmCloud/issues/1219, will we also drop `.claims.get`?

I think we'll want `wasmbus.ctl.{version}.{lattice}.log.set.{host_id}` (https://github.com/wasmCloud/wasmCloud/issues/998), but I haven't opened my PR for that yet 😅

**Comment by brooksmtownsend** [comment]
@connorsmith256 re: claims del, did that make it in yet? I tried to find that PR but couldn't unfortunately 😢 

re: log set, totally agreed and that can be added no problem as long as the format matches this one

**Comment by connorsmith256** [comment]
@brooksmtownsend no, there's no way to delete claims today. There's [an issue](https://github.com/wasmCloud/wasmCloud/issues/842) for the user story here, but if [the RFC to remove claims](https://github.com/wasmCloud/wasmCloud/issues/1219) is accepted, wouldn't we drop the `.claims.get` command?

IOW: shouldn't we either have _both_ `.get` and `.del`, or _neither_, in 1.0?

Now that I wrote this out, I may have misunderstood the linked claims RFC... Is it just to drop _capabilities_ from the stored claims, or to drop signing claims altogether?

**Comment by thomastaylor312** [comment]
I think we rename the claims topic regardless so this isn't blocked and then we can remove the claims topics down the road once we decide on that

**Comment by connorsmith256** [comment]
So long as that doesn't require another RFC/ADR, I'm good with that :) We know what the topic(s) would look like, if we were to include them 👍
