### ISSUE TITLE
[FEATURE] Pin wit definitions, version wasmcloud core wits @1.0

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#1125]
**Is your feature request related to a problem? Please describe.**
When we release wasmCloud 1.0, we should version our core wits to @1.0 and pin to appropriate versions (e.g. wasi-cli and wasi-http-proxy @0.2).

**Describe the solution you'd like**
This is an issue that's not quite ready to work on and should be completed after a few more months of testing with our core wits and updates to interfaces like the `wasi-cloud` proposal. 

I'm marking this as blocked by time and this should just serve as a tracking function to ensure we version our wits.

**Comment by thomastaylor312** [comment]
This should be closed by #1810

**Comment by thomastaylor312** [comment]
Closed in #1810
