### ISSUE TITLE
[FEATURE] Add time support to the wasmcloud:extras contract

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#113]
**Is your feature request related to a problem? Please describe.**
Per today's community meeting, some of us are potentially writing actors that might need to generate time stamps, query the "wall clock", etc. 

**Describe the solution you'd like**
Add time-related operations to the extras contract and therefore the embedded extras provider.

**Describe alternatives you've considered**
Not using "wall time" (requires potentially re-architecting solutions)

**Additional context**
Please use this issue thread as a discussion forum for suggesting the different types of time-related operations we might want to support.

**Comment by brooksmtownsend** [comment]
Consider making this a contract `wasmcloud:time` or equivalent, and its own provider. There are security implications with including the time capability with every wasmcloud host.

**Comment by brooksmtownsend** [comment]
Closing in favor of the following two issues:
https://github.com/wasmCloud/actor-interfaces/issues/69
https://github.com/wasmCloud/capability-providers/issues/60

**Comment by autodidaddict** [comment]
This was supposed to be closed in favor of [https://github.com/wasmCloud/actor-interfaces/issues/69](https://github.com/wasmCloud/actor-interfaces/issues/69)
