### ISSUE TITLE
Templatize standard README.md for example walkthroughs

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmCloud#1140]
We should have a standard README template for all example actors that has:

- Description of the actor
- List of needed contracts/interfaces
- How to run
- Examples of how to use the wadm manifest to run it

**Comment by connorsmith256** [comment]
I think @brooksmtownsend has been doing this with the new examples so far:
- https://github.com/wasmCloud/wasmCloud/tree/main/examples/rust/actors/http-hello-world
- https://github.com/wasmCloud/wasmCloud/tree/main/examples/golang/actors/http-hello-world

@thomastaylor312 is there more you'd like to see here? Should we actually create a template file, or is referencing the new examples as templates sufficient?

**Comment by thomastaylor312** [comment]
I think the ideal is that we have a template README.
