### ISSUE TITLE
NATS messaging provider should allow inbox prefix to be overridden via config 

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#1195]
The host configuration for the NATS provider should contain an optional override for the inbox prefix, which could then also be overridden by individual link definition values. The motivation behind this is that not everyone has an environment where the default inbox of `_INBOX.>` is allowed. Some secure users are not permitted to use that prefix and so must use a custom one.

**Comment by connorsmith256** [comment]
Removed "good first issue" label for now since the NATS provider is in limbo and will be migrated to WIT soon

**Comment by connorsmith256** [comment]
https://github.com/wasmCloud/wasmCloud/pull/1252 migrates the NATS provider to WIT, so once that's merged, this will be unblocked
