### ISSUE TITLE
[RFC] Implement Invocation Response Signing

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#1220]
## Introduction

Terminology: 
- **cluster seed** is a cluster private NKEY
- **cluster issuer** is a cluster public NKEY 

Currently, wasmCloud supports invocation request signing with a supplied cluster seed at runtime, which is verified by the host that receives the invocation by ensuring that the cluster issuer is among the allowed issuers. This provides a level of security to ensure that every single invocation is coming from a trusted source.

We validate that incoming invocations are from a valid source, but we do not validate that responses to that invocation are coming from a valid responder. We should implement invocation signing on the `InvocationResponse` side and reject responses that are not signed with a trusted cluster issuer.

## Motivation

From https://github.com/wasmCloud/wasmCloud/issues/1119, the conclusion around invocation signing was that it's not sufficient to just check invocation requests and that implementing response signing and verification is the proper method of providing this level of security in wasmCloud.

## Detailed Design

When a wasmCloud host creates the InvocationResponse object, it should be signed with its `cluster_seed` that is supplied at runtime. After a host makes an Invocation and receives an InvocationResponse, it should first validate that the response was signed with a trusted `cluster_issuer` before delivering it back to the component that made the invocation in the first place.

## Backwards Compatibility

As this change is completely in the RPC framework, component developers will not need to make any changes and workloads will be backwards compatible. The capability provider SDK will need to update to sign invocation responses. 

Once a host requires invocation response signing, it will not be compatible with older versions of the host as older versions will not sign invocations.

## Alternatives Considered

We could remove invocation signing entirely, which would lean harder into the security of our NATS configuration. This would simplify the process of validating invocations, and remove a level of defense-in-depth that is meant to protect a compromised RPC lattice connection from then handling arbitrary invocations and responses.

## Unresolved Questions

I would like to hold on work on this until the successor RFC of #1128 is out as that will likely affect the way we send invocations over the lattice. 

## Conclusion

For now, I'd like to align on deciding to sign invocation responses or remove invocation request signing. With #1128's implications, we may need to change the way we think about invocations anyways.

**Comment by connorsmith256** [comment]
> Once a host requires invocation response signing, it will not be compatible with older versions of the host as older versions will not sign invocations.

Note that newer versions of the host also won't be compatible with older versions of _providers_. This is unfortunate, but if we're going to continue enforcing signed invocations, it seems like a bullet we need to bite
