### ISSUE TITLE
[RFC] Rename `lattice_prefix` to `lattice`

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#1221]
## Introduction

In wasmCloud, we have the concept of a Lattice which is a seamless connected network of wasmCloud hosts over NATS. As a measure of isolation and namespacing, wasmCloud hosts start with a `lattice_prefix` argument which is used on each RPC and control interface message that is sent or handled by that host and its actors/providers. 

By default, this is `default`, and covers the 95% use case of developers that are just running in one lattice. 

Some example topics with `default` and `custom` lattice prefixes, showing the namespacing ability:
```
wasmbus.rpc.default.MBSNVBOSBQL6L4G3NZERCQAAEMTFWGJUWOO2X4MV3EIDMVJZNOL2IIZO
wasmbus.evt.default.host_started
wasmbus.rpc.custom.MBSNVBOSBQL6L4G3NZERCQAAEMTFWGJUWOO2X4MV3EIDMVJZNOL2IIZO
wasmbus.evt.custom.host_started
```

## Motivation

In the interest of clarity and transferrable knowledge, this RFC proposes renaming `lattice_prefix` to `namespace`. For a developer new to the wasmCloud ecosystem, lattice is a new term and I think it deserves to be the emphasis of learning. Lattice prefix introduces another term where `namespace` could be equivalent and mean essentially the same thing.

Additionally, other orchestration frameworks like `nomad` and `kubernetes` use namespace as a way of identifying logically separate jobs/workloads, so platform developers looking at wasmCloud will have an immediate transfer of knowledge.

## Detailed Design

The first step of this design is to, at the CLI level of wasmcloud and wash, rename `lattice-prefix` to `namespace` and support `lattice-prefix` as an alias. The same thing should happen for our public APIs like the control interface and wadm, where the name of types should be changed to `namespace` but still serialized as `lattice_prefix`.

Our documentation should be updated to refer to this "namespace" as a way of providing logically separate relationships within a single lattice connection.

## Backwards Compatibility

Mentioned in the above are methods of providing backwards compatibility using serde aliases to preserve over-the-wire compatibility. Lattice prefix should be deprecated and, once wasmCloud hits 1.0, removed in favor of all tooling that uses `namespace`. 

## Alternatives Considered

We could rename this to `lattice_namespace` as well, which would preserve the connection to the lattice. I feel that simply using namespace is simple enough and does not reduce clarity.

## Conclusion

For folks evaluating wasmCloud and WebAssembly, there are _many_ new terms to get used to. We can do our part as a mature project to increase transferrable knowledge to our project.

**Comment by thomastaylor312** [comment]
I think I'm in favor of this, but with one counterpoint argument: I do worry about `namespace` possibly causing confusion from the other direction. In things like linux (network namespaces) and nomad/kubernetes, "namespace" is an application boundary or a boundary of resource uses on a machine. A namespace for us (right now) means entirely separate nodes (what we call hosts) possibly running in an entirely different area. For a developer, it just shows up as a application level boundary, but for wasmCloud operators, it is more than that.

But, I also admit this is minor, so as long as we have documented what a separate namespace means, I'm all good with this idea

**Comment by connorsmith256** [comment]
@thomastaylor312 covered most of what I was going to say, but for completeness (emphasis mine):

> Lattice prefix introduces another term where namespace could be equivalent and mean _essentially the same thing._

There's certainly overlap between a k8s/nomad namespace and a wasmCloud lattice prefix, but there is one big difference: wasmCloud lattices can easily span networks in a way that other namespaces can't. I'm _slightly_ concerned with overloading this term, especially in situations where wasmCloud is deployed in/alongside a k8s/nomad environment.

(As a specific example, consider a wasmCloud host running in a k8s cluster. The pod might have a k8s namespace `foo`, while the wasmCloud host has a lattice namespace `bar`, and `bar` can also be used in another k8s namespace in the same cluster, or an entirely different cluster.)

In its most general sense, "namespace" defined as a segmentation of resources makes sense in a wasmCloud context. I'm just _slightly_ concerned with using the same term where multiple contexts are present.

Am I overthinking this? Would folks just get used to saying "wasmCloud namespace" and "k8s namespace?" Or maybe most deploys would have a 1:1 relationship anyway?

**Comment by brooksmtownsend** [comment]
> Am I overthinking this? Would folks just get used to saying "wasmCloud namespace" and "k8s namespace?" Or maybe most deploys would have a 1:1 relationship anyway?

Considering this, it's definitely more accurate to consider a wasmCloud "namespace" a networking namespace, and the reason we called it a lattice prefix in the first place is because it's a segment on a NATS topic 🤔 

Am I overthinking this? Should this piece of the topic just be called the "lattice" instead of introducing extra terminology? I touched on this above but "lattice" is certainly something that there isn't a good word to overlap which is why we have it.

**Comment by thomastaylor312** [comment]
I think using just "lattice" is probably the cleanest option mentioned so far

**Comment by connorsmith256** [comment]
> I think using just "lattice" is probably the cleanest option mentioned so far

That sounds like a positive incremental change to me 👍

**Comment by brooksmtownsend** [comment]
I'd love to start with our user-facing tools, then worry about the internal representation.
1. Rename documentation mentions of lattice prefixes to just lattice
2. Rename the wash and wasmcloud --lattice-prefix to --lattice (easy backwards compat change)
3. Rename internally (low priority)

**Comment by connorsmith256** [comment]
@brooksmtownsend will you take care of converting this to an ADR?

**Comment by connorsmith256** [comment]
I filed https://github.com/wasmCloud/wasmCloud/issues/1356 to track removing the last uses of `lattice_prefix` (after the next releases)
