### ISSUE TITLE
[RFC] Facilitate actor to actor calls using runtime links

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#1222]
## Introduction

The current method of communicating between actors is by using either the actor public key or a specified call alias in the claims of an actor. As per https://github.com/wasmCloud/wasmCloud/blob/main/adr/0006-actor-to-actor.md, we allow actor-to-actor communication by default as it's not a risk of privilege escalation. 

With #1219 and leaning more into runtime linking as permission for components to communicate, it feels natural to link actors to each other at runtime to allow them to communicate. Just like interacting with capabilities allows you to communicate using a `link_name`, the `call_alias` provides this flexibility of specifying the target of your invocation which is fully realized at runtime when a link is created.

This RFC proposes two changes
1. Require actors to be linked together at runtime to communicate, less so as a security measure than a runtime assertion that two components should be able to talk to each other
2. Use the `link_name` on the actor <-> actor link to specify a call alias, which is then interpreted at runtime to forward the invocation to the target actor. 

## Motivation
Original suggestion in #1119 

Actor-to-actor calls work just fine today. The purpose of this change is to alleviate a pain in actor-to-actor call development which is the hard-coding of a call alias within an actor. Hard coding this, even as a call alias, does not allow for runtime flexibility of changing the target of an invocation like you can for capability providers. 

## Detailed Design

Runtime links will need to change somewhat for this to work, allowing actors to link to other actors and use a call alias as the link name. The first changes that will need to happen in order for this feature to be implemented is to examine our tooling and assumptions that an actor would be linked to a provider, and changing those to simply refer to an "origin" and "target" for a runtime link.

## Backwards Compatibility

This will introduce breaking changes when it comes to the runtime configuration of actor-to-actor calls as links will now be required.

`wadm` will be affected by this as the idea of link targets assume providers only.

## Alternatives Considered

We could continue with not requiring actor links and use call aliases as we do today, which doesn't provide complete runtime linking flexibility but does work in the status quo.

## Unresolved Questions

Runtime links today are bidirectional, a link from an actor to a `wasmcloud:messaging` provider both allows for sending and receiving messages. With actor call aliases considered as link names, this inherently assumes that an origin actor will be invoking a target actor via a call alias and they won't be referring to each other by the same alias. Will this change require that we enforce an origin and target on a runtime link and make it unidirectional?

## Conclusion

This RFC is part of a broader topic of rethinking runtime links, starting with considering linking actors together at runtime.

**Comment by thomastaylor312** [comment]
Love this! Just want to call out one more time that we will need to answer the question of bidirectional linking before we go to 1.0

**Comment by connorsmith256** [comment]
Yeah, I think we'll need unidirectional linking, both for 1) separating actor --> provider and provider --> actor calls (e.g. only supporting one direction for `wasi:messaging`, and 2) for actor --> actor calls

I also got thinking about actor/provider config separate from runtime links, and was wondering if unidirectional linking would cause issues, but I don't think that will be the case

**Comment by brooksmtownsend** [comment]
I feel like this could work in our favor if we consider the import/exports of wit and if we tie those concepts to linking then we have a direction from the actor component perspective. Food for thought for that RCC

**Comment by brooksmtownsend** [comment]
This is proposed in #1389 and we'll track this effort there for simplicity 🙂
