### ISSUE TITLE
[BUG] Rust documentation is outdated and inaccurate

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#131]
**Describe the bug**
There are a number of places in the rust documentation for the host API where the information given is incorrect or outdated. There are even places where it still references wascc.

**Environment**
- wasmcloud version [e.g. `0.15.3`]

**Comment by brooksmtownsend** [comment]
Adding to this, all of the functions on the wasmcloud-host `Host` struct should be documented extensively, including the meaning of all parameters and return types.

For example, with `set_link`, we ask for a parameter called `actor`. It's unclear if `actor` should be the actor reference (OCI) or the ID (public key)

**Comment by autodidaddict** [comment]
Yeah, excellent call out. Every public function that appears in docs.rs needs to be evaluated for accurate and _complete_ documentation. We should also try and include example invocations of every function as well, using all of the rustdoc goodies.
