### ISSUE TITLE
[Bug] Unable to run wasmcloud from docker

### ISSUE THREAD

**Issue by ritesh089** [wasmCloud/wasmCloud#1343]
### Affected project(s)

- [ ] documentation
- [X] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

While running wasmcloud via docker, the example rust actor deployment throws an error stating that file loading is disabled.

ERROR:
`wasmcloud_1  | 2024-01-17T03:34:31.070863Z DEBUG handle_scale_actor: wasmcloud_host::wasmbus: handling scale actor actor_ref="file:///Users/riteshrai/git/wasm/wasmcloud/hello/build/hello_s.wasm" max_concurrent=1
2024-01-17T03:34:31.071378Z ERROR wasmcloud_host::wasmbus: failed to scale actor actor_ref=file:///Users/riteshrai/git/wasm/wasmcloud/hello/build/hello_s.wasm err=failed to fetch actor
wasmcloud_1  | 
wasmcloud_1  | Caused by:
wasmcloud_1  |     unable to start actor from file, file loading is disabled
`

### Steps to reproduce

Run the docker instructions in :
https://wasmcloud.com/docs/tour/hello-world?lang=tinygo&env=docker
from a mac.

### Expected behavior

curl localhost:8080
Hello, world

### Environment

- OS: [e.g. Linux, MacOS]
- Shell [e.g. bash, zsh, powershell]
- wasmcloud Version [e.g. 0.81.0]

**Comment by vados-cosmonic** [comment]
Thanks for the report @ritesh089 ! 

To get you moving, would you mind starting your host with `wash up --allow-file-load` ? This is the option to enable loading from local files (also available as env var `WASMCLOUD_ALLOW_FILE_LOAD`)

It doesn't look like it's mentioned in the guide so we'll update that.

**Comment by ritesh089** [comment]
I dont use wash up . I am unable to use wash up due to network limitations .
I used the docker-compose to start wasm cloud and used the wash app deploy using wadm.

I made a PR to enable file Load in the docker-compose .
https://github.com/wasmCloud/wasmCloud/pull/1345/files

**Comment by vados-cosmonic** [comment]
Ah thank you for clarifying! This explains why it wasn't working for you -- the docker compose file does it a little bit differently.

Thanks for contributing a PR to fix it, it looks good to me so far, minus the DCO issue!

**Comment by vados-cosmonic** [comment]
This was resolved by https://github.com/wasmCloud/wasmCloud/pull/1345, Thanks again @ritesh089 !
