### ISSUE TITLE
[CHORE] Remove remaining uses of lattice prefix

### ISSUE THREAD

**Issue by connorsmith256** [wasmCloud/wasmCloud#1356]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the solution you'd like

https://github.com/wasmCloud/wasmCloud/pull/1341 renamed `lattice_prefix` to just `lattice` in most places, but for backwards compatibility reasons, there are still a few uses. After v0.82.0 of the host and v0.26.0 are released, in anticipation for v0.83 and v0.27, we should remove the remaining uses

**Comment by brooksmtownsend** [comment]
I think I've taken care of the rest of these
