### ISSUE TITLE
[FEATURE] WADM OCI image pull capability from private registry/ mirror.

### ISSUE THREAD

**Issue by ritesh089** [wasmCloud/wasmCloud#1357]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

I am working behind a private OCI registry and cannot directly fetch the images used in the example WADM .
I was able to work around the docker-compose images by prefixing the dockerproxy registry info.
But the OCI references in WADM.yaml do not work with or without the registry prefix .
I get the following error :
```
ERROR wasmcloud_host::wasmbus: failed to scale actor actor_ref=wasmcloud.azurecr.io/hello:0.1.7 err=failed to fetch actor
wasmcloud_1  | 
wasmcloud_1  | Caused by:
wasmcloud_1  |     0: failed to fetch actor under OCI reference `wasmcloud.azurecr.io/hello:0.1.7`
wasmcloud_1  |     1: failed to fetch OCI path
wasmcloud_1  |     2: failed to fetch OCI bytes
wasmcloud_1  |     3: error sending request for url (https://wasmcloud.azurecr.io/v2/): error trying to connect: tcp connect error: Connection refused (os error 111)
wasmcloud_1  |     4: error trying to connect: tcp connect error: Connection refused (os error 111)
wasmcloud_1  |     5: tcp connect error: Connection refused (os error 111)
wasmcloud_1  |     6: Connection refused (os error 111)
```

I am using the following wadm :
```cat wadm.yaml 
# Metadata
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hello
  annotations:
    version: v0.0.1
    description: "wasmCloud Hello World Example"
spec:
  components:
    # Your actor component, started from the wasmCloud example OCI artifact
    - name: hello
      type: actor
      properties:
        image: wasmcloud.azurecr.io/hello:0.1.7
      traits:
        # One replica of this actor will run
        - type: spreadscaler
          properties:
            replicas: 1
        # The link configuration tells the httpserver to listen on 8080
        - type: linkdef
          properties:
            target: httpserver
            values:
              address: 0.0.0.0:8080

    # The httpserver capability provider, started from the official wasmCloud OCI artifact
    - name: httpserver
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpserver:0.19.1
        contract: wasmcloud:httpserver
        
        ```
        Please let me know how I can get around this error.

### Describe the solution you'd like

Any solution that can get the example actors working inside a vpn that cannot access external oci registry.

### Describe alternatives you've considered

I have appended the private registry mirror prefix that works for all the docker images in docker compose .

example :
image: nats:2.10.7-alpine

 image: {registryname}/dockerproxy/nats:2.10.7-alpine
 
 This approach works in docker-compose but does not work from inside the wadm.

**Comment by connorsmith256** [comment]
Hey @ritesh089, if you're unable to pull references from the public wasmcloud registry, there are a couple options:
- push artifacts to a private registry you can access, and configure the host to pull from it. Here's a docs page on that: https://wasmcloud.com/docs/deployment/oci/#configuring-access-to-a-private-registry
- build artifacts yourself and reference them in wadm with `file://` references. You can see an example of that in our quick start: https://wasmcloud.com/docs/tour/adding-capabilities
- run a local registry, and push artifacts to it. The [docker compose example](https://github.com/wasmCloud/wasmCloud/blob/main/examples/docker/docker-compose-full.yml) sets up a registry container for this. There are a [couple tips](https://wasmcloud.com/docs/developer/workflow/#running-a-local-oci-registry) for this in our docs as well

Let me know if these sources help resolve your issue!
