### ISSUE TITLE
[BUG] CPU bound instances don't spread on all CPU cores

### ISSUE THREAD

**Issue by JT117** [wasmCloud/wasmCloud#1365]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

To observe the scaling of an actors, I update the hello-world example to calculate a pbkdf2 hash, with fixed value and salt.
I put the whole project here : https://github.com/JT117/pbkdf2_wasm

```rust
use pbkdf2::password_hash::{PasswordHasher, SaltString};
use pbkdf2::Pbkdf2;
use wasmbus_rpc::actor::prelude::*;
use wasmcloud_interface_httpserver::{HttpRequest, HttpResponse, HttpServer, HttpServerReceiver};
use wasmcloud_interface_logging::{info, warn};

#[derive(Debug, Default, Actor, HealthResponder)]
#[services(Actor, HttpServer)]
struct HelloWorldActor {}

/// Implementation of the HttpServer capability contract
#[async_trait]
impl HttpServer for HelloWorldActor {

    #[tracing::instrument]
    async fn handle_request(&self, _ctx: &Context, _req: &HttpRequest) -> RpcResult<HttpResponse> {
        let password = b"hunter42dfkjsdhfkhdfkhjjhsdfjhsdfhsdkjfhsdhjfksjdhfsdjhfkjshdfkjsdhfkjshdfkhsdfnqsknfezhfhsdkfksdjnfkjsdhfksjdhfjhsdfkhsdkfhksjsqjdqslkjdlqkjd";
        match SaltString::from_b64("aWF0aGlua3NvaWFt") {
            Ok(salt) => {
                match Pbkdf2.hash_password(password, &salt) {
                    Ok(hash) =>
                        Ok(HttpResponse::ok(hash.to_string())),
                    Err(e) => {
                        warn!("Error: {}", e);
                        Ok(HttpResponse::bad_request("Error"))
                    }
                }
            },
            Err(e) => {
                warn!("Error: {}", e);
                Ok(HttpResponse::bad_request("Error"))
            }
        }
    }
}
```
When I use jmeter/hey/drill with 10 threads, I can see that the work is only done by one CPU core at a time.

![image_720](https://github.com/wasmCloud/wasmCloud/assets/621318/2c123a6e-1f6a-44d7-a998-fd7b0ebad2ae)

### Steps to reproduce

1. set the wasmcloud RPC timeout high enough to actually wait for the response :
    export WASMCLOUD_RPC_TIMEOUT_MS=10000
2. start wasmcloud 0.81.0
    wash up
3. deploy the wadm file
    wash app deploy hello-world/wadm.yaml 
4. bench with any kind of app
5. observe the cpu core loads

### Expected behavior

I'm expecting the load to spread to all my cpu cores to reach real 100% CPU usage

### Environment

- OS: Tried with Ubuntu 22.04, ArchLinux, MacOS
- Shell zsh
- wasmcloud Version 0.81.0

### Screenshots / Logs / Additional context

The same code on the latest Elixir runtime pre 0.78.0 is working as expected (spread on all cores), switching to the rust runtime restrain the load on one core

**Comment by thomastaylor312** [comment]
Closed in #1376
