### ISSUE TITLE
[FEATURE] Migrate to oxlint where possible

### ISSUE THREAD

**Issue by lachieh** [wasmCloud/wasmCloud#1378]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [X] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the solution you'd like

The oxc linter AKA [oxlint](https://oxc-project.github.io/docs/guide/usage/linter.html) is shaping up to be much quicker than currenltly used eslint tooling.

I would like to:
- Audit the existing ruleset that we have in use today 
- Migrate to oxlint where possible
- discuss rules that are not covered by oxlint and either 1) remove the rule, 2) keep existing eslint rule + tooling or 3) contribute the rule to the oxc project
- create a package for the oxlint + eslint config that other workspace packages can import. This may mean that a couple of configs exist (i.e. lib, react, react-lib, etc.)
- update existing workspace packages to use the new config definitions

### Additional context

The tooling should continue to work with editors, which means testing things like the VSCode extension for oxlint, and also making sure the new changes work with GitHub Actions

**Comment by DonIsaac** [comment]
Hi there 👋 Oxlint maintainer here. Is there anything I can do to help get you guys set up?

**Comment by lachieh** [comment]
Hi @DonIsaac! This one is definitely more of a matter of priorities right now, not that we don't want to implement. The wasmCloud team has a few rustaceans which is what piqued my interest in oxlint originally, but seeing the performance gains is what made me want to implement it.

Currently I'm following oxc-project/oxc#1117 as the reminder to check back in as eslint-plugin-import is definitely the slowest of the bunch.

This is our current eslint config which is shared around the various packages:
https://github.com/wasmCloud/wasmCloud/blob/main/typescript/packages/eslint-config/index.js

If you've got pointers on migration, or insights into rules you can see won't work, that'd be helpful. I also wouldn't turn down a PR 😉
