### ISSUE TITLE
[FEATURE] Control interface event subscription

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#140]
**Is your feature request related to a problem? Please describe.**
Currently, the control interface does not have functionality that allows us to subscribe to the lattice event stream. Most of the time we can get away with this, as it's not always necessary with a wasmcloud host to have fine-grained control over the event stream. However, the ability to monitor the event stream allows us to write interactions with a host with a better idea of the state of the lattice.

For example:
1. You start an actor that you have on disk that uses the `telnet` provider
1. You issue a command to a host to start the `telnet` provider.
1. The host must then (assuming it doesn't have that provider cached) download the provider from our OCI registry
1. While this is happening, you may want to write a line of code that ensures that your actor is present, your provider is present, and the link between them has been established before you proceed to make any requests.

Step 4 above is not possible today, but if you are able to monitor for events you would be able to ensure that those resources were appropriately started and linked.

**Describe the solution you'd like**
Following the above example again, it would be desirable to either have a `wait_for_event` handler on the control interface or an equivalent method of ensuring that an event occurred.
For example (to wait for an actor, provider, and link worked appropriately):
1. Start resources as described in steps 1-3 above
1. `control_interface::wait_for_event(ActorStarted)`
1. `control_interface::wait_for_event(ProviderStarted)`
1. `control_interface::wait_for_event(LinkEstablished)` (note: I do **not** see this in the current ControlEvent enum)

**Describe alternatives you've considered**
An alternative solution with a similar gain would be to implement a `wait` option on control interface commands. This, unfortunately, does introduce a blocking call to the command itself, requiring one command to fully complete before the next one may begin.

**Additional context**
This solution should enable an elegant fix for #83 

When approaching this issue, it will be important to consider that if implemented as above the user will need to be careful not to call the `wait_for_event` function after the event has occurred, or you will block forever. Keeping this in mind, it may be appropriate to implement the function instead as `event_exists` to simply check for the existence of a specific event.

cc @autodidaddict

**Comment by autodidaddict** [comment]
One approach I had looked into was in making the control interface client simply subscribe to the entire event stream and then expose either a channel or an iterator that developers could then use to capture events as they choose. I worry that "wait for event" might solve our problem but might preclude or limit other things people might want to do with that stream.

**Comment by autodidaddict** [comment]
So, something like:
```rust
for evt in ctl.events_iter() {
   // do a thing
}
```

**Comment by autodidaddict** [comment]
As a potential inspiration, take a look at the `Subscription` struct from the [nats](https://docs.rs/nats/0.9.14/nats/subscription/index.html)] crate. You can either define a handler via `with_handler` or it supports `IntoIter` as a trait, allowing you to treat it like any other `Iter`, where in our case it would be `Iter<Item=ControlEvent>`
