### ISSUE TITLE
[BUG]Typescript HTTP Hello World example is missing configuration file

### ISSUE THREAD

**Issue by LostInBrittany** [wasmCloud/wasmCloud#1402]
### Affected project(s)

- [X] documentation
- [X] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

In the [Wasmcloud HTTP Hello World for Typescript](https://wasmcloud.com/docs/tour/hello-world?lang=typescript), the doc says to use `wash new actor` to scaffold the project starting from the GitHub Wasmcloud Typescript example folder.

The command fails, as `project-generate.toml` file is missing. The file exists for the other langages examples.

### Steps to reproduce

1. Run command 
    ```bash
    wash new actor --git wasmcloud/wasmcloud --subfolder examples/typescript/actors/http-hello-world hello
    ```

1. See the error trace:
    ```bash
    $ wash new actor --git wasmcloud/wasmcloud --subfolder examples/typescript/actors/http-hello-world hello
    🔧   Cloning template from repo wasmcloud/wasmcloud subfolder examples/typescript/actors/http-hello-world...
    🔧   Using template subfolder examples/typescript/actors/http-hello-world...
    
    Failed to generate project
    
    Caused by:
        0: Invalid template folder: Required configuration file `project-generate.toml` is missing.
        1: ⛔   File not found within template
    ```

### Expected behavior

The project is created, as with Rust or TinyGo

### Environment

- OS: MacOs
- Shell: zsh
- wasmcloud Version: wash 0.25.0

**Comment by brooksmtownsend** [comment]
@LostInBrittany thank you so much for filing this issue and then, fixing it! You actually saved me from some pain of hitting this exact problem in #1399 too ❤️
