### ISSUE TITLE
[FEATURE] Rebuild sqldb-* contracts and implementations

### ISSUE THREAD

**Issue by vados-cosmonic** [wasmCloud/wasmCloud#1408]
### Affected project(s)

- [X] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [X] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

In order to refactor and convert the `sqldb-*` providers (and get them using provider bindgen), we need to recreate the actual contracts they use because they are currently not secure enough.

### Describe the solution you'd like

In general we need to:

- [ ] Recreate/change the contracts that power `sqldb-*` providers
- [ ] Convert the `sqldb-*` providers to use provider bindgen

### Describe alternatives you've considered

N/A

### Additional context

See https://github.com/wasmCloud/wasmCloud/issues/470

**Comment by brooksmtownsend** [comment]
This is captured in the RFC #1914 right?

**Comment by vados-cosmonic** [comment]
Yup! Let's close this in favor of that RFC -- and for any work we'll track it via that RFC.
