### ISSUE TITLE
[FEATURE] Revisit env_logger configuration to capture default logs

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#141]
**Is your feature request related to a problem? Please describe.**
When launching the wasmcloud binary, the `env_logger` configuration [here](https://github.com/wasmCloud/wasmCloud/blob/49a8ddb7b95ee475422158118543d8418e57665b/src/wasmcloud.rs#L86-L91) attempts to read the `RUST_LOG` environment variable and set the logging capture to that value. For example, if the user has exported `RUST_LOG=info`, our env_logger will output and show all info, warn, and error logs. If that value is not set, then by default the env_logger will capture `wasmcloud=info,wasmcloud_host=info`, which just captures info/warn/error logs for the wasmcloud binary and the wasmcloud_host crate. This configuration does not capture logs from capability providers _or_ the logs that are output from actors using the `wasmcloud:logging` capability.

**Describe the solution you'd like**
Ideally, if the user does not specify a `RUST_LOG` environment variable, the wasmcloud binary will capture and display logs that come from capability providers and actors.

**Describe alternatives you've considered**
At the very least, this behavior should be documented in our troubleshooting guide as logging behavior. There is no documentation on this behavior currently, so users of the `wasmcloud:logging` capability may not know their logs are being lost due to this subtlety.

**Additional context**
I've done some testing here, and the correct value for `env_logger` is not `RUST_LOG=info`, it's simply `info`. You can see in our code that we attempt to get the _value_ for the environment variable https://docs.rs/env_logger/0.8.3/env_logger/constant.DEFAULT_FILTER_ENV.html.

**Comment by autodidaddict** [comment]
Closing this issue as it is no longer applicable for wasmcloud OTP / wasmcloud 0.50+
