### ISSUE TITLE
[BUG] "musl" based wasmcloud host fails to load providers and actors from remote due to dns resolution error

### ISSUE THREAD

**Issue by wamli** [wasmCloud/wasmCloud#1433]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

The wasmcloud host which I use, **wasmcloud-x86_64-unknown-linux-musl (v0.81.0)**, cannot locate entities in remote registries due to a dns resolution error:

```
$ wash up --nats-websocket-port 4001
🏃 Running in interactive mode.
🎛️  If you enabled --nats-websocket-port, start the dashboard by executing `wash ui`
🚪 Press `CTRL+c` at any time to exit
2024-02-01T09:51:45.826587Z  INFO async_nats::options: event: connected
2024-02-01T09:51:45.827320Z  INFO async_nats::options: event: connected
[..]
Caused by:
    0: failed to fetch provider under OCI reference `wasmcloud.azurecr.io/httpserver:0.19.1`
    1: failed to fetch OCI path
    2: failed to fetch OCI manifest
    3: error sending request for url (https://wasmcloud.azurecr.io/v2/): error trying to connect: dns error: failed to lookup address information: Name does not resolve
    4: error trying to connect: dns error: failed to lookup address information: Name does not resolve
    5: dns error: failed to lookup address information: Name does not resolve
    6: failed to lookup address information: Name does not resolve
```
**Interesting observation:** `wash pull wasmcloud.azurecr.io/httpserver:0.19.1` is totally relaxed and pulls it.

### Steps to reproduce

1. `wash up`
2. `wash app deploy wadm.yaml` where "wadm.yaml" can be any app which will try to load a provider and/or an actor from a remote registry, e.g. not localhost.

### Expected behavior

My expectation was that artifacts like **wasmcloud.azurecr.io/httpserver:0.19.1** should be downloaded without problem.

### Environment

- OS: **Linux (Ubuntu)**
- Shell: **bash**
- wasmcloud Version: **v0.81.0**
- deployment: **"local"**, e.g. NOT in a container

**Comment by brooksmtownsend** [comment]
Thank you @wamli !
> Interesting observation: wash pull wasmcloud.azurecr.io/httpserver:0.19.1 is totally relaxed and pulls it.

This is the strangest part for me, which makes this issue a little different than https://github.com/wasmCloud/wasmCloud/issues/1357. It means that there isn't just a complete corporate proxy preventing pulls from AzureCR, but that the host specifically is failing to do so 🤔

**Comment by brooksmtownsend** [comment]
@rvolosatovs do you have any thoughts on what could be going on here? I'm unsure if you've seen this as a side effect from the x86 MUSL build or if this is unfamiliar

**Comment by rvolosatovs** [comment]
@wamli this looks like a TLS connection issue, are you behind a (corporate?) proxy by any chance?

**Comment by rvolosatovs** [comment]
If it is what I think it is, then #1772 should fix the issue.

**Comment by brooksmtownsend** [comment]
@wamli have you been able to reproduce this after #1772 merged?
