### ISSUE TITLE
[FEAT] Security examples

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#1441]
These examples should cover a few scenarios to illustrate defense-in-depth security in wasmCloud. In our documentation we have a few key pages talking about the ways we secure wasmCloud applications but we don't have exact code examples for what happens when you try and violate one of these principles.

In order to run these, Docker compose, bash/justfile/README scripts, and documentation is the key here. Diagrams definitely welcome.

1. Launching two wasmCloud hosts that don't share a cluster issuer to show denying invocations
1. Launching a "bad" actor that is not signed
1. Launching a "bad" actor whos hash does not match the module bytes
1. Launching a "bad" actor that tries to use a capability that's not allowed
1. Bonus: Policy service

**Comment by brooksmtownsend** [comment]
Policy service example added in #1613

**Comment by thomastaylor312** [comment]
Looks like @brooksmtownsend called out that there was only one more thing to address to show the example and we did that. Closing this issue
