### ISSUE TITLE
[FEAT] Ensure Kafka provider can run multiple copies without duplicate handling

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#1442]
The current implementation of the [messaging-kafka](https://github.com/wasmCloud/capability-providers/tree/main/messaging-kafka) provider is fairly experimental and created as an example. I would love it if the Kafka provider was closer to being ready for a real workload by ensuring that, while running multiple Kafka providers, it can consume/produce from/to a Kafka stream without duplicate handling of messages. This is a great issue to take on if you're familiar with Kafka and want to take a stab at writing a wasmCloud provider 😄

**Comment by thomastaylor312** [comment]
Going to keep this pinned for now

**Comment by thomastaylor312** [comment]
I know it would be a rewrite, but Go has good client support, so it might be better to have the provider written in Go if there isn't a good client available for Rust

**Comment by vados-cosmonic** [comment]
Yeah a rewrite is definitely out of scope of this issue though -- though it's probably a reasonable way forward!

@thomastaylor312 Do you want to close this one and then flesh out your idea in a rewrite? Can't tell if you mean  you're referring to [`sarama`](https://github.com/IBM/sarama), [`segmentio/kafka-go`](https://github.com/segmentio/kafka-go), or [`confluentinc/confluent-kafka-go`](https://github.com/confluentinc/confluent-kafka-go), but a new issue would be a great place to kick off that discussion.

**Comment by thomastaylor312** [comment]
I think a new issue wouldn't replace this per se as it would be a full rewrite. Just wanted to capture here in case someone really interested in Kafka could possibly just do a rewrite

**Comment by vados-cosmonic** [comment]
Yup, so it looks like to do this for Rust, with the current state of SDKs, we have to use *both* `rskafka` (supports admin commands like creating topics) and `kafka-rs` (supports consumer groups). 

There are a few options:

(1) Use both, support current functionality + new robustness hoped for by this issue
(2) Use only `kafkra-rs` and require topics to be pre-created (normally, they normally would be in a realistic setup)
(3) ??? (there are some other options here, like using a lib based on `librdkafka`), but I'd like to stay pure Rust

What do you think @thomastaylor312 & @brooksmtownsend ? I'm leaning towards (2), but it *is* nice to have topics get auto-created.

**Comment by thomastaylor312** [comment]
I think for now we do 2.
