### ISSUE TITLE
[BUG] wasmCloud does not support removing a link definition

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#146]
**Describe the bug**
A developer cannot use the control interface or the host API to purge a link definition from the lattice cache and in turn invoke the `Unbind` operation on a capability provider for the linked actor.

**To Reproduce**
1. Look at the host API
2. See no methods to remove link definitions
3. Look at the control interface API
4. See no methods to remove link definitions

**Expected behavior**
We should be able to remove a link definition, which should purge that link definition from the lattice _and_ invoke the `Unbind` operation on every instance of the affected provider.

**Additional Context**
The current design around link definitions is that they are remembered by the lattice. You can add and remove an actor and, when the actor returns to the lattice (is restarted) it will resume as if nothing had happened, and will not need to be re-linked to the provider. This has the unfortunate downside of having no way to do things like stop HTTP server processes and release listening ports without stopping the entire host.

**Comment by brooksmtownsend** [comment]
@autodidaddict This was fixed by #147, right?

**Comment by autodidaddict** [comment]
yep
