### ISSUE TITLE
[BUG] provider `debug` messages not getting through to host

### ISSUE THREAD

**Issue by vados-cosmonic** [wasmCloud/wasmCloud#1487]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

While working on a provider, I used `tracing::debug` and was not able to get logs to move through the host, despite setting `WASMCLOUD_LOG_LEVEL=debug` at the top level when running `wash up`.

`info` messages made it through, but `debug` did not.

### Steps to reproduce

1. Modify a provider to emit `debug` level messages during normal operation ~~preferably at startup~~ 
2. Start a host at the debug log level (i.e. `WASMCLOUD_LOG_LEVEL=debug wash up`)
3. Notice that logs are not produced

### Expected behavior

`debug` log levels should have been passed to the host

### Environment

- OS: Linux
- Shell: zsh
- wasmcloud Version 0.81.0

**Comment by connorsmith256** [comment]
@vados-cosmonic when you say "at startup", do you mean in `main`, before `start_provider`? Any tracing log macros will be ignored prior to `start_provider` at this time

Assuming you mean after the provider is up and running, I think the best way to debug would be to confirm:
- what log level did the provider receive via the `HostData`
- what env var for `RUST_LOG` was set on the child process

**Comment by connorsmith256** [comment]
Okay good to know. In that case it sounds like the provider isn't parsing the `log_level` included in the `HostData`. Was this a provider built using the WIT SDK, or smithy?

**Comment by vados-cosmonic** [comment]
A bit late but this was built with the WIT SDK that's currently on `main`

**Comment by connorsmith256** [comment]
Well, [that would do it](https://github.com/wasmCloud/wasmCloud/blob/main/crates/host/src/wasmbus/mod.rs#L3170) 😅

**Comment by connorsmith256** [comment]
@vados-cosmonic as soon as v0.82.0 is released, we can ship [this](https://github.com/wasmCloud/wasmCloud/pull/1502)

**Comment by vados-cosmonic** [comment]
Wow @connorsmith256 thank you for getting on this so fast, PR looks great to me (There was a `TODO`!).
