### ISSUE TITLE
[FEATURE] Add wait support to `wash scale`

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmCloud#1491]
### Affected project(s)

wasmCloud CLI (wash)

### Is your feature request related to a problem? Please describe.

Starting actors and providers using wash waits for the appropriate event to confirm that everything worked. However, the scale command does not have the same behavior

### Describe the solution you'd like

I would like the scale command to wait for an `actor_scaled` event by default and to have the `--skip-wait` flag like other commands

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by siddharthkhonde** [comment]
hi @thomastaylor312 , was wondering if this is still open? happy to look into it :)

**Comment by brooksmtownsend** [comment]
Just a note that in a recent PR we did rename this to `component_scaled`, so make sure to use that event 😄

**Comment by thomastaylor312** [comment]
Yep, you're good to work on this

**Comment by vados-cosmonic** [comment]
Hey @siddharthkhonde are you still working on this by any chance? If not it'd be great if we could free it up for others to work on!
