### ISSUE TITLE
[BUG] `wash app deploy` succeeds but does not deploy on Windows

### ISSUE THREAD

**Issue by vados-cosmonic** [wasmCloud/wasmCloud#1519]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

As [reported by Markus on the wasmCloud Slack](https://wasmcloud.slack.com/archives/CS5RBTLD7/p1707900040443569?thread_ts=1707345059.419669&cid=CS5RBTLD7)  at present it seems that `wash app deploy` completes but does not properly deploy apps on native Windows.

It was noted that this problem does *not* occur on wasmCloud when running in WSL2

### Steps to reproduce

1. `wash app deploy your-app.yaml`
2. `wash app list`
3. Notice that the app list says that your app is undeployed

### Expected behavior

The application should have been successfully deployed

### Environment

- OS: Windows
- Shell: Powershell
- wasmcloud Version: latest

**Comment by ricochet** [comment]
I can confirm that this is now working with the 1.0 rc!
