### ISSUE TITLE
[BUG] Unable to create Python and TypeScript actors from Hello-World project

### ISSUE THREAD

**Issue by joni-jones** [wasmCloud/wasmCloud#1520]
### Affected project(s)

- [X] documentation
- [X] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

The [documentation](https://wasmcloud.com/docs/tour/hello-world?lang=typescript) specifies how to create `hello-world` actors using official wasmCloud templates for Rust, Golang, TypeScript, and Python. But the provided command doesn't work for Python and TypeScript and fails with the following error:
```
Invalid subfolder path: No such file or directory (os error 2)
```
It looks like `v0.81.0` tag doesn't have these examples https://github.com/wasmCloud/wasmCloud/tree/v0.81.0/examples/python/actors/http-hello-world.

Running this command with `--branch main` fixes the problem.

### Steps to reproduce

1. Run `wash new actor hello --git wasmcloud/wasmcloud --subfolder examples/typescript/actors/http-hello-world  --branch v0.81.0` or `wash new actor hello --git wasmcloud/wasmcloud --subfolder examples/python/actors/http-hello-world  --branch v0.81.0`
2. Error `Invalid subfolder path: No such file or directory (os error 2)`

### Expected behavior

The actor is created successfully

### Environment

- OS: MacOS
- Shell: zsh
- wasm Version: 0.25.0

**Comment by joni-jones** [comment]
I created a project from the branch you pointed above `fix/0.81-examples`, but `wash build` fails with the following error:

**Comment by brooksmtownsend** [comment]
🤔 @joni-jones is this simply because the `build` directory doesn't exist?

**Comment by joni-jones** [comment]
It looks like. I created it manually and `build` succeseded. I think it should be stated in the documentation explicitly.

**Comment by brooksmtownsend** [comment]
I agree @joni-jones , I'll take a look at where we can put that alongside the custom build command docs. For now I opened a PR to ensure that the build folder is there for our examples
