### ISSUE TITLE
[BUG] `make` from Capability Provider tutorial fails

### ISSUE THREAD

**Issue by joni-jones** [wasmCloud/wasmCloud#1532]
### Affected project(s)

- [X] documentation
- [X] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [x] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

I'm trying to implement a Capability Provider from the official WasmCloud [tutorial](https://wasmcloud.com/docs/developer/interfaces/creating-an-interface) but `make` command for building Rust crate is failing with the following error:
```
make
cd rust && cargo build
   Compiling wasmcloud-examples-payments v0.1.0 (/Users/<username>/dev/wasm_hello_world/payments/rust)
error: failed to run custom build command for `wasmcloud-examples-payments v0.1.0 (/Users/<username>/dev/wasm_hello_world/payments/rust)`

Caused by:
  process didn't exit successfully: `/Users/<username>/dev/wasm_hello_world/payments/rust/target/debug/build/wasmcloud-examples-payments-419c609ccc7089a6/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=/Users/<username>/dev/wasm_hello_world/payments/codegen.toml
  cargo:rerun-if-changed=/Users/<username>/dev/wasm_hello_world/payments/./payments.smithy
  cargo:rerun-if-changed=/Users/<username>/Library/Caches/smithy/wasmcloud.github.io/wasmcloud-core.f2facc62766ec8c4.smithy
  cargo:rerun-if-changed=/Users/<username>/Library/Caches/smithy/wasmcloud.github.io/wasmcloud-model.6e8584f5be28601b.smithy

  --- stderr
  Error: Formatter("failed to start: No such file or directory (os error 2)")
make: *** [all] Error 101

```

### Steps to reproduce

1. Follow the official tutorial for creating an interface for a Capability Provider
2. After replacing `payments.smithy` with the example provided on Github run `make`

### Expected behavior

Rust cargo should be build successfully.be built

### Environment

- OS: MacOS
- Shell: zsh
- wash CLI Version: 0.25.0

**Comment by vados-cosmonic** [comment]
Hey @joni-jones do you by any chance have a custom `wasmcloud.toml` in your project? 

I'm a little surprised by this log line:

```
error: failed to run custom build command for `wasmcloud-examples-payments v0.1.0 (/Users/<username>/dev/wasm_hello_world/payments/rust)`
```

Following the steps in the walkthrough, there isn't a custom build command for the Rust project (you generally shouldn't need one on a "tier 1" language we support like Rust)

**Comment by joni-jones** [comment]
Hi, @vados-cosmonic .

Only one thing I changed besides  replacing `payments.smithy` is changing package name to `wasmcloud-examples-payments` in `Cargo.toml`. I don't have any other `*.toml` files in the project.

**Comment by vados-cosmonic** [comment]
Ah thanks @joni-jones -- that's helpful! It seems like the the [`weld`](https://github.com/wasmCloud/weld) bit of the build is breaking (in `build.rs`...) not sure what exactly is missing since you seem to have the toolchain installed...

Do you happen to have `rustfmt` installed?

**Comment by joni-jones** [comment]
> Do you happen to have rustfmt installed?

No, I don't.

**Comment by vados-cosmonic** [comment]
Ah, that's it then! Please install `rustfmt` -- the code-gen actually does attempt to [format the generated code](https://github.com/wasmCloud/weld/blob/2548332e38e70dada5967c2edfee34508a1141c4/codegen/src/codegen_rust.rs#L1628).

**Comment by joni-jones** [comment]
@vados-cosmonic thanks, it works now. I think all these preconditions should be specified in the guide, because from the error it's not clear what exactly is causing that error.

**Comment by ricochet** [comment]
Great call out @joni-jones! We updated our docs
