### ISSUE TITLE
[FEATURE] Replace NATS with compatible server?

### ISSUE THREAD

**Issue by sunny-g** [wasmCloud/wasmCloud#1542]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [X] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

I'm using [`libp2p`](https://libp2p.io) for some other projects and was wondering what would be required to use it as the underlying networking/transport layer beneath wasmcloud.

It seems that if I can write and spawn a NATS API-compatible server, I can `wash up` and connect to a running `my-nats-server` rather than spawning the default `nats-server`, but I'm wondering if there are alternative approaches, such as implementing alternatives to the NATS-based providers (`wasi:messaging`).

### Describe the solution you'd like

Between the docs describing what's needed to [implement a custom host](https://wasmcloud.com/docs/hosts/custom-host/fromspec) and the source here in the repo, I think I can at least re-implement some of the basic functionality behind NATS, but some additional guidance or pointing out a faster, less intrusive path would be appreciated.

**Comment by ricochet** [comment]
Implementing a capability-provider that implements `wasi-messaging` would be easy-peasy, but I don't think that's what you're looking for. Another useful capability provider that I also don't think you're looking for would be an ipfs-based implementation of `wasi-blobstore`.

While nothing is impossible, NATS is deeply integrated in several aspects of wasmCloud beyond the networking and transport layer:
- Jetstream is used for our distributed lattice cache. You could re-implement with memcached, redis, etc. Jetstream is also used for declarative state management via [`wadm`](https://github.com/wasmCloud/wadm/)
- Chunking of requests via Jetstream ObjectStore
- The control-interface crate and provider. See https://wasmcloud.dev/reference/lattice-protocols/control-interface/. An implementation that uses the crate is [`wadm`](https://github.com/wasmCloud/wadm/)

Depending on what you're looking to achieve:
- **Integrate with existing libp2p networks**: I think a libp2p proxy capability provider should be able integrate a wasmCloud lattice to a libp2p mesh.
- **Implement libp2p for RPC calls in wasmCloud**: We're actively replacing the previous wasmbus RPC protocol to wRPC. See https://github.com/wasmCloud/wasmCloud/issues/1389. This protocol should be implementable for libp2p. Reference implementation: https://github.com/rvolosatovs/wrpc/blob/dev/crates/transport-nats/src/lib.rs
- **Connect Web App that uses libp2p as a dependency**: The [wasmCloud_js](https://github.com/wasmCloud/wasmcloud-js) host could use some TLC but it should be possible to add an adapter at this layer.

**Comment by sunny-g** [comment]
@ricochet Thanks for the comprehensive response! Yes I didnt enumerate the potential p2p-equivalent providers as it seemed like their dependence on NATS meant NATS would be a more "suitable" target for replacement.

One question I didn't explicitly ask but seems to be answered is "is NATS heavily depended on outside of providers" and the answer seems to be yes (It seems like `wasmcloud` + `wadm` depend on certain NATS clustering behaviors), which suggests a `nats-server + jetstream`-compatible server would be sufficient, though a daunting task to complete.

Perhaps put more directly, would it be sufficient "upcycle" a stock installation of `wash`, `wasmcloud` and `nats-server` to enable p2p clustering and management by implementing my own `wasi-messaging`, `wasi-blobstore` and `control-interface` providers, or would some additional NATS-specific configuration be required? If I limited myself to only creating new / replacing existing providers, what core clustering/lattice functionality would I be missing?

For context, this was spurred by the pain I encounter with NAT traversal and generally running simple services from home, not to mention the domain and SSL configuration pains that would follow. I know you can't anticipate all of my desired use cases but the goals is roughly "spin up wasmcloud against a network identified by public keys instead of IP addresses" b/c the underlying networking stack handles the rest.

**Comment by ricochet** [comment]
I wonder how "out there" of an option would it be to upstream into NATS for a libp2p mode? Seems daunting but this would also be a value add for many projects.

**Comment by sunny-g** [comment]
I think the p2p nature conflicts a bit with some of the core assumptions made around cluster authentication and dialing, but would otherwise be a really great addition, which incidentally makes replacing `nats-server` a bit more difficult than it otherwise would be, but would make replacing NATS-based providers a bit easier, assuming there are no leaky abstractions (dependencies on NATS behaviors rather than APIs).

**Comment by sunny-g** [comment]
Decided it would be sufficient to target `wasi-cloud-core` for making `wasmcloud` more p2p rather than NATS, as you'll always want to define your cluster separately from the rest of the network, and NATS is a pretty battle-hardened piece of tech!

Thanks @ricochet for the discussion and helpful links!
