### ISSUE TITLE
[FEATURE] wRPC MVP Integration

### ISSUE THREAD

**Issue by vados-cosmonic** [wasmCloud/wasmCloud#1548]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [x] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [x] capability providers
- [x] provider bindgen
- [x] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

This is a tracking issue to coordinate our work on `wrpc`, as we merge the MVP into the host.

### Describe the solution you'd like

`wrpc` usable and merged in the host

### Describe alternatives you've considered

N/A

**Comment by vados-cosmonic** [comment]
We shouldn't forget to add some proper typing for `operation` that we're passing around which is currently stringly-typed:

[See this comment](https://github.com/wasmCloud/wasmCloud/pull/1527#discussion_r1491538347)

- [ ] Properly type the `operation` that moves around the host, since we don't have to do backwards compat with Smithy anymore (this should be similar to `TargetInterface`)

**Comment by vados-cosmonic** [comment]
`PolicyRequestTarget` (and the policy service interaction in general) needs to be re-done to match with what's available in a post-wrpc world:

[See this comment](https://github.com/wasmCloud/wasmCloud/pull/1527#discussion_r1491536678)

- [ ] Change policy service interaction to match what will be available

**Comment by vados-cosmonic** [comment]
Also, we'll need to eventually derive async `Encode` as well, see [this comment](https://github.com/wasmCloud/wasmCloud/pull/1603#pullrequestreview-1909164117) after some work is done in upstream `wrpc_transport`.

**Comment by brooksmtownsend** [comment]
Just so I don't lose track of it, we're instrumenting traces for custom interfaces but need to make sure that for all of our well-known ones (like HTTP, blobstore, etc) that we're using the `wasmcloud_host::wasmbus::wasmcloud_transport::Client` to send those invocations. Might need a bit of modification of handlers in order to pass around the context.

**Comment by brooksmtownsend** [comment]
One more, I'd love to refactor the Bus trait 
```rust
    /// Identify the target of component interface invocation
    async fn identify_interface_target(
        &self,
        interface: &CallTargetInterface,
    ) -> anyhow::Result<Option<TargetEntity>>;
```
to both drop the notion of a `TargetEntity`, and not return a Result to be clear. We'll immediately fail to invoke the target if the target is `None` so that should be easily handled.
```rust
    /// Identify the target of component interface invocation
    async fn identify_interface_target(
        &self,
        interface: &CallTargetInterface,
    ) -> Option<WrpcInterfaceTarget>;
```

We can rename, of course.

**Comment by brooksmtownsend** [comment]
A note for onlookers when it comes to wRPC support for interfaces, we plan on supporting the following interfaces in wasmCloud:
- WASI 0.2.0 (including `wasi:http`)
- Keyvalue (Depending on formalization of wasi:cloud, `wasi:keyvalue` or similar)
- Blobstore (Depending on formalization of wasi:cloud, `wasi:blobstore` or similar)
- Messaging (Depending on formalization of wasi:cloud, `wasi:messaging` or similar)
- Custom interfaces with all data types. See [WIT Types](https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md#types) for what constitutes as a type, but generally enums, structs, and all simple data types are included. Custom interfaces will **not** support resources, streams, and asynchronous functions for wasmCloud 1.0, but support for those is possible and will be added in a future release.

For all of the interfaces that depend on formalization of `wasi:cloud`, we will either offer that functionality using the wasi:cloud interface or a similar interface like `wasmcloud:keyvalue` in the case that the interface just isn't quite ready yet. Once that interface is available, however, we plan on deprecating our `wasmcloud:*` interface and polyfilling that to use the `wasi:cloud` interface, supporting it until 2.0.

**Comment by vados-cosmonic** [comment]
Some more things before we can merge `feat/wrpc`:

- [ ] Update all providers to use the stuffed-into-target-config setup for config
- [ ] Build messaging-triggered actor to replace HTTP-triggered actor that was critical to most other tests
- [ ] Update all provider tests (ex. `tests/kv-vault.rs`) to use the target config setup

Also related to the topics that `wasmbus.rpc` should be listening on:

- [ ] `wasmbus.rpc.<lattice>.<provider>.linkdefs.put` is not getting the traffic it should during a link put.

**Comment by vados-cosmonic** [comment]
Would be great to have a test for the [new policy code](https://github.com/wasmCloud/wasmCloud/pull/1625#issuecomment-1983560812)

- [ ] Add tests for the policy service changes

**Comment by vados-cosmonic** [comment]
Adding OTEL to more bindgen'd code would be good:

- [ ] Add missing [`TraceContext` to `get_wrpc_client()`](https://github.com/wasmCloud/wasmCloud/pull/1633#discussion_r1518178980)

**Comment by vados-cosmonic** [comment]
Some more things:

- [ ] re-add integration tests for providers (i.e. files that were removed from `tests` in https://github.com/wasmCloud/wasmCloud/pull/1633)
- [ ] re-add `wash call` integration test (i.e. tests that were removed in https://github.com/wasmCloud/wasmCloud/pull/1645)

**Comment by vados-cosmonic** [comment]
Add a check for an invocation coming in should have had a link set the other way -- i.e. when an actor comes in and connects to a provider, and the provider needs to call some interface on the actor (an example of this is `blobstore`'s `chunk-receiver` legacy interface)

- [ ] Validate invocations coming in to make sure they're from linked providers

**Comment by rvolosatovs** [comment]
is this now done? @vados-cosmonic @brooksmtownsend

**Comment by vados-cosmonic** [comment]
@rvolosatovs As far as I know no, the points that still have checkboxes next to them are unfinished, or at the very least need to be re-checked if they were finished during some other work.

**Comment by brooksmtownsend** [comment]
Only remaining work here is to validate traces and add a test for `wash call`.

**Comment by brooksmtownsend** [comment]
WIth #1869 , we're done!
