### ISSUE TITLE
[RFC] `wash app dev`

### ISSUE THREAD

**Issue by lachieh** [wasmCloud/wasmCloud#1594]
### RFC Title

RFC: Introduce `dev` command to wash app management

### Introduction

This RFC proposes that a new `dev` command be added to the `wash app` subcommand which will make iterating on components as part of applications easier.

### Motivation

As we gain more experience building applications with `wadm`, the wasmCloud team and a number of community members have experienced some friction relating to the the dev cycle experience of writing, iterating and deploying components.

### Detailed Design

- `wash app dev` will:
  - look for `*.wadm.yaml`[^1] in the current directory and load it if there is only one present. If there are multiple, it will list all applications.
  - for each `component` in the loaded manifest, it will look for a `build` key[^2] which should be a path to a `wasmcloud.toml` file. If one exists, it will attempt to run the build command inside the `wasmcloud.toml`.
    - once all components are built, it will put and deploy the application through `wadm`
    - start watching the parent folders of each `wasmcloud.toml` file found for changes.
    - when a change is detected in a component folder, run the build command, then stop all the components with the same ID so that wadm will reload them from disk
  - for each component that does not have a `build` key, start watching the file in the `image` path
    - when a change is detected in a component folder, stop all the components with the same ID so that wadm will reload them from disk
  
[^1]: adding the `wadm` suffix before the filetype helps with identifying the files, but also allows for dev tooling and IDEs to assume schema.
[^2]: This is a new field in the the wadm oam schema. Inspiration from the [Docker Compose Build](https://docs.docker.com/compose/compose-file/build) configuration.

### Backwards Compatibility

New command. Shouldn't need too much consideration in backwards compatibility.

### Unresolved Questions

- Is there a problem adding a new key to the oam spec?
- Are there safeguards to put in place around production workloads?

### Conclusion

Adding `wash app dev` will make for a really smooth developer experience.

**Comment by brooksmtownsend** [comment]
@lachieh thank you for formalizing this, I think we need exactly this for the developer iteration loop for wasmCloud apps. The inspiration from `docker compose` makes a lot of sense for how wash can work here.

> Is there a problem adding a new key to the oam spec?
Nope! OAM is extensible, and we define our own information for those components. We make the most use of the `Application` specification, and information about where we would add `build:` is at https://github.com/oam-dev/spec/blob/master/7.application.md#properties.

> Are there safeguards to put in place around production workloads?
I think it's key here that `wash app dev` should only be used in development environments. To protect production, we could limit the initial use case to only work with file references and not support pushing to a local registry, then production workloads should not use `--allow-file-load` based on our recommendation. You would also have to be running `wash` and `wasmcloud` on the same machine, so this is another good reason for our Docker container to not include `wash` in the base image (or if we can switch to alpine, not allow it to be installed)

**Comment by thomastaylor312** [comment]
So I do have some minor concerns about having a new key called `build`. It feels a bit odd to me to pollute a deployment artifact with build details (i.e. a wadm manifest is closer to a kubernetes deployment or nomad job than to docker compose). The only other option I could think of is to use some identifier for the `image` key like `build://` or `git://` which dev tools would use as an indicator to replace that with a file reference.

- For the identifier option, the pros are that it helps us avoid pollution of the manifest
- For the `build` option, it gives us more flexibility to evolve and add more options

Any thoughts here?

**Comment by noelenwenede** [comment]
A few questions @lachieh:

> for each component that does not have a build key, start watching the file in the image path


This approach doesn't consider source file changes. Does this mean we expect the devs to manually rebuild the image as part of the workflow?

With respect to the `build` key being added to the Application specification, how does this affect `Providers` since they don't have a `wasmcloud.toml` file?

Since actors will always have `wasmcloud.toml` file in it's root, can we iterate over a `file reference` for an image to find the root folder and use it as a build key?

In what other ways are we expected to use the build key since it's addition to the specification may require making changes to the docker image?

Finally, does this initial work on `wash app dev` consider providers and interfaces?

**Comment by lachieh** [comment]
I will add that the primary goal with this RFC is to improve the DX around wadm applications and the idea of using the app manifest is to reduce the need for Yet Another Config File™. Since almost all of the config is already in the wadm manifest, I figured we could use that. In other conversations I have also heard [tilt.dev](https://tilt.dev) mentioned more than a couple of times as a tool to take inspiration from, but I'm not quite sure how to implement something like that without another file.

**Comment by noelenwenede** [comment]
> They don't need one, but [they are supported](https://wasmcloud.com/docs/reference/config#type-config---provider). In this proposed case, we would need a way to know what commands to run to build the provider, and where build the output would be so the provider spec would need some extra fields to match the actor spec.

I didn't know Providers could have a `wasmcloud.toml` file thanks for clearing that up. This means it could be an easy way of standardising the build key for both Actors and Providers. The previous CLI wrapper I built around `wash` used `make` to build the Providers and it was relatively slow compared to building Actors.

With respect to the below statement:

> Which docker image are you referring to? I had not planned for anything else yet, but I imagine that the build key could contain extra meta information like git path, owner/team, build timeout limit, etc. It's fairly open but I didn't have any specific requirements at this stage.

I was referring tho the comment by @brooksmtownsend:

> I think it's key here that wash app dev should only be used in development environments. To protect production, we could limit the initial use case to only work with file references and not support pushing to a local registry, then production workloads should not use --allow-file-load based on our recommendation. You would also have to be running wash and wasmcloud on the same machine, so this is another good reason for our Docker container to not include wash in the base image (or if we can switch to alpine, not allow it to be installed)

I assumed this recommendation would need to be a required step following the addition of the `build` key to the application specification.

I'll have a look at [tilt.dev](https://tilt.dev/) and will get an implementation plan ready for this weekend, reviews on that document should clear my knowledge gaps and help align our thought process.

**Comment by lachieh** [comment]
Thanks, @noelenwenede. That's great. Regarding tilt, it's more about the general feeling of "run a command and file changes trigger only necessary compilation/deployment". They have a more complex `Tiltfile` written in Starlark, but we definitely don't need to go as far as an interpreter.

As for the Docker container, what @brooksmtownsend suggests makes sense. Having the container launch wasmcloud + NATS on start without the need for wash is probably best. We should definitely make those changes, but can definitely be tackled in a separate PR.

**Comment by noelenwenede** [comment]
@lachieh @brooksmtownsend

## wash app dev

The wash app dev command streamlines WADM-based application development by automating 
component builds and deployment. It targets components with a defined build key, 
compiles them, and deploys the application. Critical to iterative development, 
it also implements a watch mechanism on component parent directories, triggering 
rebuilds and seamless lattice restarts upon detecting source changes. 
This facilitates a robust live development environment, optimising the feedback loop 
for efficiency and minimising manual intervention in the build and deployment cycle.

To achieve `wash app dev`, the following steps are performed:
1. Get Application Manifest
2. build components from Manifest with build key
3. Deploy Application
4. Watch parent directories of referenced components for changes then rebuild and restart


#### Get Application Manifest
1. **Scan the Current Working Directory**: Search for files matching the `*wadm.yaml` pattern.
    - If **no file is found**, terminate the process.
    - If **one file is found**, store a reference to this file.
    - If **multiple files are found**, prompt the user to select one, and store a reference to the selected file.

2. **Parse the Selected File**: Process the selected `*wadm.yaml` file to extract the application manifest detailing a list of components and their specs, including optional build keys, is extracted.

3. **Process Build Keys**:
    - Identify components needing build and deployment through their **build key**.
    - If **no build key is provided** for any component, exit the process.

4. **Return References**: Provide references to the application manifest and specifications for components identified for build and deployment.


#### Build Components
1. For each identified component, execute the build process using the provided build key in project directory.
2. For Actors:
    - **Compile**: For this I can create and handle a new `BuildCommand` and return `module` key, exit on failure.
3. For Capability Providers:
    - **Compile**: For this I can create and handle a new `BuildCommand` and return `module` key, exit on failure.


#### Deploy Application
An `AppCliCommand` command for `put` and `deploy` can be executed for this?

#### Watch for Changes, Rebuild, Restart
1. Use `notify` crate to watch for changes in the parent directories of the components identified for build.
2. Upon detecting changes, trigger a rebuild of the affected component.
3. Upon successful rebuild, issue a new `StopCommand`. 
4. The host will restart the component with the new image.


###Questions:
> **Compile**: For this I can create and handle a new `BuildCommand` and return `module` key

1. Can I get the module key without inspecting the build output?

2. don't expect interfaces to change often to be considered for live development, is this assumption correct?
3. Do we want capture and output logs from all running instances of providers?
4. Should we listen for host events to report when components are started and stopped?

**Comment by brooksmtownsend** [comment]
This proposal looks awesome, and I added a few comments and attempted to address each question 🙂 

>For Capability Providers:
Compile: For this I can create and handle a new BuildCommand and return module key, exit on failure.

Just a nit here, the key should be a service key 🙂 And, we recently added `wash build` support for providers, so this should be easy!

>An AppCliCommand command for put and deploy can be executed for this?

That sounds correct to me, we can reuse the deploy function that we use for `wash app deploy` in an idempotent way (e.g. an error stating the manifest already exists is good, because it exists)

> Use notify crate to watch for changes in the parent directories of the components identified for build.
Upon detecting changes, trigger a rebuild of the affected component.

I think this will work really well, my only concern is around projects where we may trigger many many changes in things that don't affect the component. For example, if I decide to run `npm ci`, that will change tons of files in `node_modules`. Perhaps here we can essentially "queue" up a hot reload, and only actually rebuild after a second or two of inactivity?

>Delete the application

I actually think we can stop at Undeploy, and leave the manifest in the store!

For your questions:
> Can I get the module key without inspecting the build output?
I think you can, but only if the component was built before on that machine. It might just be easier to use the build output for the module key, but if you wanted to check you could get the name of the component and find the private key under `~/.wash/keys/<name>_module.nk`, parse that using `KeyPair::from_seed()`, and then use that keypair's public key. `wash_lib::cli::extract_keypair` could be helpful here.

Backing up a little bit, if this is in the interest of stopping the component that's currently running, soon we will *require* that folks supply an identifier in the wadm manifest, so this might get a lot easier 😄 

> don't expect interfaces to change often to be considered for live development, is this assumption correct?
Thankfully, the interfaces won't be something we need to worry about as an interface change will now result in `wit-bindgen` regenerating the interface code for that specific actor. Put another way, an interface change will simply be a change in the actor's code, so no worries here!

> Do we want capture and output logs from all running instances of providers?
For the first iteration of `wash app dev`, I think it would be acceptable to just look at the logs from the host which should include the provider logs as well. 

> Should we listen for host events to report when components are started and stopped?
I think this would be a good log line to have! Trying to get real fancy here might get complicated quickly, as you're essentially monitoring state at that point which is `wadm`'s job. So if this gets complicated let's approach it after the first MVP.

> Do we want to support environment variables in .wadm.yaml files?
This is definitely something we've talked about before, and I think it would be a nice touch to add to `wash` to be able to insert environment variables that are present when you `wash app [put|deploy]`. I see this as a separate feature, but certainly won't complain if it's done here.

**Comment by noelenwenede** [comment]
> That sounds correct to me, we can reuse the deploy function that we use for wash app deploy in an idempotent way (e.g. an error stating the manifest already exists is good, because it exists)

How do we handle manifest changes (to add a new component or remove an existing component) between `dev` runs? I think this situation will yield more steps adding an extra layer to the developer experience which I am assuming we want to avoid.

> I think this will work really well, my only concern is around projects where we may trigger many many changes in things that don't affect the component. For example, if I decide to run npm ci, that will change tons of files in node_modules. Perhaps here we can essentially "queue" up a hot reload, and only actually rebuild after a second or two of inactivity?

Yes queuing up the hot reload is what I'm aiming for.

> Backing up a little bit, if this is in the interest of stopping the component that's currently running, soon we will require that folks supply an identifier in the wadm manifest, so this might get a lot easier 😄

I really like this. So as part of this addition we will have the build key and an identifier to the manifest specification?

I also agree with not over complicating things so I'm fine to kick off with what has been agreed here.

Finally, I've gone through the contribution guide, can I class this RFC as an issue for the proposal (this might be me trying to cut corners 😊) or do I need to create a new one?

**Comment by lachieh** [comment]
Something I just thought about; we haven't discussed prerequisites for running `wash app dev`. I think the assumption is that there would be a wasmCloud host, NATS server/leaf and a wadm instance running. For MVP, we can error if there's something missing (i.e. ``No wasmCloud host found. Do you need to run `wash up`?``) but I'd also be ok with starting those automatically for a better DX.

**Comment by brooksmtownsend** [comment]
Hey @noelenwenede , @lachieh checking back in here, now that 1.0 is out what do we think about resuming work here? I'd love to get this going 😄

**Comment by noelenwenede** [comment]
Hey @lachieh @brooksmtownsend, I haven't pushed any changes yet. I got really tied up with some other commitments but I have more time now. I'll pick up were I left off and I should have  WIP PR for review at some point next week.

**Comment by raskyld** [comment]
Hey, just my 2 cents, I use https://skaffold.dev a lot at work.

What it does is basically what you want, but for Go projects.
My experience using it as been awesome so I would recommend to take inspiration from it.

I share the opinion of @thomastaylor312, it feels weird to have build related config in the deployment manifest.

I don't think the *Yet Another Config File* is a problem, it puts the config related to development life-cycle in a single source of truth. It could allow customisation for specific projects, for example, limiting which directory should be watched by `notify`.

If DX is a concern, we could do like `skaffold init` which helps the user generate an initial config file using interactive prompts.

**Comment by brooksmtownsend** [comment]
Hey @noelenwenede just checking in here, would love to see how it's going! Just wanted to encourage WIP PRs anytime 🙂

**Comment by vados-cosmonic** [comment]
Hey @noelenwenede do you mind if I pick this up -- I'd like to see if I can get something up for `wash app dev`!

**Comment by vados-cosmonic** [comment]
Hey @brooksmtownsend @thomastaylor312 what do you y'all think about having paths to `wasmcloud.toml` files be supported as part of `wash app deploy`? We could implement it similarly to how we do perform relative path resolution now -- i.e. if someone is using `file://../wasmcloud.toml`, we can detect that and perform a `wash build` (from inside `wash` of course) and use the output. 

I'm also open to using a new scheme for this (ex. `wash` or `wash+build` or something like that, etc) rather than `file`!

**Comment by lachieh** [comment]
This would solve the concern of having the extra build key that only wash knows about. I don't moving it into it's own scheme also because then the validation crate can give a helpful error during the put operation and clients (wash + js-lattice-client) won't need to change their behavior.

**Comment by noelenwenede** [comment]
> Hey @noelenwenede do you mind if I pick this up -- I'd like to see if I can get something up for `wash app dev`!

Yes please. I've been really tied up and not been able to make any progress on this.

**Comment by thomastaylor312** [comment]
After further discussion, we have decided to go more in the direction of what is proposed in #2508. The first phase of work doesn't yet cover running with multiple components, but that will be in the second phase. See the background section of that issue to understand why we aren't going to focus the inner dev loop on a wadm manifest. You can also take a look at the wasmCloud community meeting from this week for a more in depth discussions: https://www.youtube.com/live/sTu3fgtJkoI?si=MQIF1yn3Lqa4xvEf
