### ISSUE TITLE
[BUG] `wash stop actor <name-to-search-for>` bails when non-running resources with same name are found

### ISSUE THREAD

**Issue by lachieh** [wasmCloud/wasmCloud#1595]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

When running the `wash stop actor <name-to-search-for>` command, it will bail when non-running resources with same name are found.

```
➜  http-hello-world git:(main) ✗ wash stop actor typescript-http-hello-world
Multiple matches found with the provided search term: [MDCA66HME6DG27ZVPHIQQ53VCAT3WXD5TMMLJQPAFZMJ25ROHF3I2RRJ (typescript-http-hello-world), MDTVI55U6KLYGKI7MPMTTRBH2XNRZNRTSJT5YNMEAWQZQKKGSZXL3QG4 (typescript-http-hello-world)]

➜  http-hello-world git:(main) ✗ wash stop actor MDCA66HME6DG27ZVPHIQQ53VCAT3WXD5TMMLJQPAFZMJ25ROHF3I2RRJ
No matches found with the provided search term

➜  http-hello-world git:(main) ✗ wash stop actor MDTVI55U6KLYGKI7MPMTTRBH2XNRZNRTSJT5YNMEAWQZQKKGSZXL3QG4
No matches found with the provided search term
```

### Expected behavior

Stopped things can't be stopped. Only running resources should be listed when attempting to stop a resource.

### Environment

wash 0.26.0

**Comment by thomastaylor312** [comment]
Thanks for the report here. This will definitely be a little bit difficult as claims does keep everything around. We'd also have to check claims against running resources which means querying inventory as well

**Comment by brooksmtownsend** [comment]
I think this is going to get a lot easier when we're stopping/scaling components based on their component ID, rather than looking up an optional name and looking for the public key 🙂

**Comment by brooksmtownsend** [comment]
This is now obsolete that we stop components based on IDs 🚀
