### ISSUE TITLE
[FEATURE] Support updating provider configuration at runtime

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#1648]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

Right now, provider configuration is supplied to a provider as it starts. Even if that configuration changes after the provider starts, the provider will not be notified of the changes.

### Describe the solution you'd like

I would like to use the nice `ConfigBundle` API in the host to watch for changes in provider config and deliver them to the provider at runtime.

**Comment by siddharthkhonde** [comment]
hi @brooksmtownsend, was wondering if this open? happy to look into it :)

**Comment by brooksmtownsend** [comment]
Hey @siddharthkhonde this one might need a bit more detail and will be tackled post 1.0, I would suggest looking at a few of the other issues you mentioned and we can come back to this one!

**Comment by Aditya1404Sal** [comment]
I would love to work on this feature! 
can I get it assigned to me please ?

**Comment by vados-cosmonic** [comment]
Hey @Aditya1404Sal there were some recent changes to `ConfigBundle` and I think we have to update this ticket (at the very least I think the scope might have changed/be larger than it sounded) -- would you mind picking something else up? 

Sorry for the inconvenience 🙇

**Comment by Aditya1404Sal** [comment]
Hey @vados-cosmonic I understand :smile: , I'll pick up some other issue :+1:
