### ISSUE TITLE
[DOCS] Documentation on wasmcloud-control-interface

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#165]
**Is your feature request related to a problem? Please describe.**
At the moment, the crate `wasmcloud-control-interface` still has pretty barebones documentation. Similar to our recent improvements for the `wasmcloud-host` crate, we should write Rust documentation for the control interface.

**Describe the solution you'd like**
Public structs shown on https://docs.rs/wasmcloud-control-interface/0.3.0/wasmcloud_control_interface/ have annotations, it would be nice to be able to highlight the `Client` type in some way as that has all of the important methods for interacting with the control interface.

**Describe alternatives you've considered**
I've considered removing the control-interface entirely so we don't have to write documentation but I think that isn't the best path forward.

**Comment by autodidaddict** [comment]
This has been taken care of, as the control interface crate `Client` type now has full documentation and even a couple of good examples.
