### ISSUE TITLE
[FEATURE] Unify `wash start actor|component` and `wash start provider` into a single `wash start`

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#1658]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

Right now we have a nesting of `wash start` commands, but it would be awesome to be able to simply `wash start ./my_component.wasm` or `wash start my.oci.ref/repo:v1` instead of having to specify the type of component. We have enough information based off of the reference (see if it's a local file or not) and we can inspect it in order to discover the artifact type.

### Describe the solution you'd like

I would like `wash start` to intelligently discover a local file, or inspect an OCI reference's type (actor component or provider) in order to auction the resource and then subsequently start the resource. Because components must be scaled, we can simply scale with a `max-instances` of 1.

**Comment by ahmedtadde** [comment]
hey @brooksmtownsend, I am eyeing this and I have some questions:
- can we deterministically distinguish between an actor component and provider component by probing a `DecodedWasm::resolve()` or `DecodeWasm::package()`. If yes, what's the differentiation prop(s) to look for. 
- If the answer to the previous question is no... then, would `ProviderArchive::try_load(artifact_bytes)` suffice to check that we are dealing with a provider component? if that fails, we check for token claims as way to assert that we are dealing with an actor component?


I mainly scanned the code for the `InspectCommand` thinking it would have some tidbits that help with differentiation between the two kinds of components. If there is somewhere else that you believe/intuit that I should look for such an insight, please do let me know.

**Comment by thomastaylor312** [comment]
As discussed in #1725, this feature probably won't work out, so closing this issue
