### ISSUE TITLE
[BUG] kubernetes wasmCloud host does not show up in local washboard

### ISSUE THREAD

**Issue by Fasibru** [wasmCloud/wasmCloud#1672]
### Affected project(s)

- [X] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [X] other / not sure

### Describe the bug

When deploying wasmCloud via helm chart you cannot right away open a local washboard and see the kubernetes host. The [documentation](https://github.com/wasmCloud/wasmCloud/tree/main/chart#running-the-chart) only mentions to forward port 4222 which is not enough.

### Steps to reproduce

1. Deploy helm chart on e.g. local k8s cluster
2. Follow documentation to forward port 4222
3. Start `wash ui`
4. Connection to NATS not working (and k8s wasmCloud host not showing up)

### Expected behavior

After deploying the helm chart and following the documentation the washboard should show the k8s wasmCloud host.

### Environment

- OS:  MacOS
- Shell: zsh
- wasmcloud Version 0.81.0
- helm Chart Version 0.7.2

**Comment by thomastaylor312** [comment]
If I were to take a guess, you'll have to enable websockets on the NATS server, which we don't have an option for right now in the chart as far as I know. So we'll have to fix that or figure out a better way to do this by starting the washboard in the chart

**Comment by Fasibru** [comment]
> If I were to take a guess, you'll have to enable websockets on the NATS server, which we don't have an option for right now in the chart as far as I know. So we'll have to fix that or figure out a better way to do this by starting the washboard in the chart

That's what I was tackling in the PR https://github.com/wasmCloud/wasmCloud/pull/1735. I have essentially added websockets support and wadm to the helm chart. But I wonder now if we should really put effort into the current helm chart or focus on a helm-chart for the operator and potentially wadm?

**Comment by thomastaylor312** [comment]
Yeah I think focusing on support for the operator would be better. 

Before I close however, I think @lachieh had some ideas about doing something that doesn’t involve web sockets as well so it plays nicer with the operator. Any additional details to add here @lachieh

**Comment by lachieh** [comment]
You're correct in that the washboard needs websocket support. We've been discussing moving the washboard NATS connection to the server side so that the client can just interact with the server and not have to worry about enabling websockets on the NATS server. That move would solve this, _and_ it would allow the washboard to run inside of k8s.

**Comment by thomastaylor312** [comment]
@Fasibru You can close this issue if you wish. Otherwise I'll keep it open until we get this stuff into the operator and washboard

**Comment by Fasibru** [comment]
I'll close it. I think a new issue for the operator would be better in this case.
