### ISSUE TITLE
[BUG] rust actor template does not work

### ISSUE THREAD

**Issue by fliepeltje** [wasmCloud/wasmCloud#1721]
### Affected project(s)

- [X] documentation
- [X] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

Using the quickstart, I cannot create a rust actor.
The output I get is

```bash

🔧   Cloning template from repo wasmCloud/wasmCloud subfolder examples/rust/actors/http-hello-world...

Failed to generate project

Caused by:
    ⛔   Invalid subfolder path: No such file or directory (os error 2)

```

Seems like the directory should point to `examples/rust/components/http-hello-world` instead of `examples/rust/actors/http-hello-world`

### Steps to reproduce

1. run `wash new actor hello --template-name hello-world-rust`

### Expected behavior

I expected a project directory to be created.

### Environment

- OS: Linux
- Shell zsh

**Comment by t3hmrman** [comment]
Hey @fliepeltje would you mind confirming that `wash` works for you now? The fix has been merged to `main` so it should be usable now

**Comment by vados-cosmonic** [comment]
Hey @fliepeltje would you mind confirming that `wash` works for you now? The fix has been merged to `main` so it should be usable now

**Comment by fliepeltje** [comment]
> Hey @fliepeltje would you mind confirming that `wash` works for you now? The fix has been merged to `main` so it should be usable now

I have veriefied it and it indeed works as intended! :+1:
