### ISSUE TITLE
[FEATURE] Provide simple way to reset/wipe `wadm` store/s

### ISSUE THREAD

**Issue by lachieh** [wasmCloud/wasmCloud#1740]
### Affected project(s)

- [x] documentation
- [X] wasmCloud CLI (wash)

### Is your feature request related to a problem? Please describe.

During a debugging session with a community member, I noticed that even after deleting everything in `~/.wash`, the wadm store stayed in tact. This didn't turn out to be a problem, but I would have thought that the JetStream storage location would have been contained in the `~/.wash` folder also.

### Describe the solution you'd like

I'd love a way to be able to delete everything nats/wadm/wash related with a `wash` subcommand, or by deleting a single folder.

### Proposed Action

After discussion (see thread), the proposed action to take is to:
- Add a `--purge` option to `wash down` which will delete everything in the `~/.wash/` folder.
- Move the JetStream storage location inside `~/.wash`

**Comment by thomastaylor312** [comment]
For anyone who'd like to implement this, you can find the default names of the streams to delete [here](https://github.com/wasmCloud/wadm/blob/f83bdff1949b0ad048d825213a0d50a83c0a3739/bin/main.rs#L32) and the name of the KV buckets to delete [here](https://github.com/wasmCloud/wadm/blob/f83bdff1949b0ad048d825213a0d50a83c0a3739/bin/main.rs#L122C26-L122C36) and [here](https://github.com/wasmCloud/wadm/blob/f83bdff1949b0ad048d825213a0d50a83c0a3739/bin/main.rs#L155). It might be worth making those publicly exported constants as part of the wadm crate to make it easier, but that is optional. A wash command could delete those streams and KV buckets to get a completely empty state.

I would also highly recommend asking for confirmation unless a `--force` flag is passed

**Comment by lachieh** [comment]
@thomastaylor312 what would you suggest as a command? I was thinking either a subcommand on `wash app` like `wash app reset`, or a larger scoped command like `wash wipe`. Could also be a flag on `wash down` like `--wipe` which deletes everything wash related.

What do you think about setting the JS storage location to somewhere inside `~/.wash`?

**Comment by thomastaylor312** [comment]
We could definitely set the storage location inside of `~/.wash` which would make it cleaner as well. As for where it goes, that is a good question. It doesn't feel like a top level command and it feels weird under `wash app` to me. Something on the `wash down` command feels like a good place to start.

Though this brings up the point I've been thinking on for the past few months: Is wash an administrative tool or a dev tool? I don't think it can continue being both in the long term without becoming super bloated, but it feels weird to split into two tools right now

**Comment by lachieh** [comment]
Good with `wash down --wipe` or maybe `--reset` since feels a little less like a toilet instruction.

**Comment by lachieh** [comment]
Great, I've updated the description.

**Comment by lachieh** [comment]
@brooksmtownsend did the Jetstream folder move into ~/.wash? Should it?
