### ISSUE TITLE
[FEATURE] Support updating/changing provider config after `init()`

### ISSUE THREAD

**Issue by vados-cosmonic** [wasmCloud/wasmCloud#1747]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

Provider `init()` (https://github.com/wasmCloud/wasmCloud/pull/1676) provides access to config at initialization time, but given that config can change over time on a given Host, we should have interfaces for dealing with changed/updated config.

### Describe the solution you'd like

An additional method on the `Provider` trait is probably reasonable to give provider developers a chance to react to upstream config changes that affect their provider.

### Describe alternatives you've considered

N/A

**Comment by ahmedtadde** [comment]
would this be a duplicate of https://github.com/wasmCloud/wasmCloud/issues/1648

**Comment by vados-cosmonic** [comment]
Oh yeah you're right -- thanks @ahmedtadde -- looks like @brooksmtownsend already filed this
