### ISSUE TITLE
[FEATURE] Keyvalue, blobstore and HTTP specific provider libraries

### ISSUE THREAD

**Issue by rvolosatovs** [wasmCloud/wasmCloud#1756]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

Currently implementing blobstore and keyvalue providers requires a lot of boilerplate, which is copy-pasted. HTTP suffers from the the issue, but custom HTTP providers are more rare and there is less boilerplate, so priority for that one is lower.

We should at least move the subscription setup and the processing loop of keyvalue and blobstore to separate crates or modules in `provider-sdk` crate.
We could have traits like:

- `provider_sdk::interfaces::KeyvalueAtomic`

- `provider_sdk::interfaces::BlobstoreBlobstore`

etc…

Users could then implement this trait and pass implementations directly to `run_provider_handler`

Some things to consider here are the response typing - for example, currently, provider implementations depend on the fact `Some(Vec<u8>)` or `Some(Bytes)` can be used in place of `stream<u8>` on the client's side. Implementations also depend on the fact that e.g. `anyhow::Result<T>` can be transmitted in place of `result<T, string>`.

These kinds of tricks would not be possible if we had a statically typed result type for user-provided handlers specified in the trait.

Perhaps, as a first step we could start with passing the `wrpc_transport::Client` into the handler and let the users figure out what they want to send. Another option is to have handler signatures all return `Result<impl Encode, impl Encode>`, however it's not clear how cases where the implementation may need to send an error in the middle of transmission would be handled - such a situation could arise when e.g. the provider could start the transmission of the response stream and an error occurs on the stream async - the implementation then must communicate the error to the server by transmitting the error string on the error subject.

### Describe the solution you'd like

I think as the first step we should start with something like:

```rust
// somewhere in `provider_sdk`
pub struct Context {
   pub wrpc: wasmcloud_core::wrpc::Client,
   pub result_subject: wasmcloud_core::wrpc::Subject,
   pub error_subject: wasmcloud_core::wrpc::Subject,
   pub source: Option<String>,
}

// probably in `provider_sdk::interfaces::keyvalue`
pub fn serve_atomic(provider: impl AtomicProvider, until: impl Future<Output = ()>)
pub fn serve_eventual(provider: impl EventualProvider, until: impl Future<Output = ()>)

pub trait AtomicProvider {
   async fn serve_increment(ctx: Context, bucket: String, key: String, value: u64)
   // etc.
}

pub trait EventualProvider {
   async fn serve_get(ctx: Context, bucket: String, key: String)
   // etc.
}
```

**Comment by thomastaylor312** [comment]
This all sounds great to me. I think we start with something like you outlined and then iterate from there
