### ISSUE TITLE
replace `serde_yaml`

### ISSUE THREAD

**Issue by rvolosatovs** [wasmCloud/wasmCloud#1767]
`serde_yaml` is unmaintained, we need to find an alternative https://github.com/dtolnay/serde-yaml/releases/tag/0.9.34

**Comment by thomastaylor312** [comment]
Oh this is fun. Thanks for the heads up

**Comment by thomastaylor312** [comment]
Looks like that still depends on serde_yaml under the hood and is more focused on config (though I really want to try it for config stuff now)

**Comment by brooksmtownsend** [comment]
Though I think this is an important issue to keep track of, it doesn't seem like there is a defacto replacement at this time so I'm going to remove it from our prioritized v1.1 roadmap. We should certainly still be looking for alternatives here
