### ISSUE TITLE
[RFC] Embracing Emoji-Based Conventional Commits

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#1790]
### RFC Title

RFC: Embracing Emoji-Based Conventional Commits

### Introduction

This RFC proposes the transition of wasmCloud's repository commit messages to an emoji-only format. By replacing traditional text-based commit messages with emojis, we aim to streamline communication, enhance global understandability, and inject a dose of creativity and fun into our development practices.

### Motivation

The traditional text-based commit messages in wasmCloud's repositories, while informative, often fail to capture the essence and immediacy of the changes made. Emojis, as a universal language, offer a concise and engaging alternative that can transcend linguistic barriers and foster a more inclusive community. Additionally, this approach can make the log scanning process faster and more enjoyable.

### Detailed Design

| Commit Type | Emoji | Description |
|-------------|-------|-------------|
| `feat`      | ✨    | New feature additions |
| `fix`       | 🐛    | Bug fixes |
| `docs`      | 📚    | Documentation updates or improvements |
| `style`     | 💅    | Cosmetic changes that do not affect the meaning of the code |
| `refactor`  | 🔨    | Code changes that neither fixes a bug nor adds a feature |
| `perf`      | 🚀    | Performance improvements |
| `test`      | 🧪    | Adding missing tests or correcting existing tests |
| `build`     | 🏗️    | Changes that affect the build system or external dependencies |
| `ci`        | 🤖    | Changes to CI configuration files and scripts |
| `chore`     | 🛠️    | Other changes that don't modify `src` or test files |
| `revert`    | ⏪    | Reverting a previous commit |

With this change, the previous 10 commits of the repository would look like this:
```
🏗️(nix): update dependencies
🐛(ci): remove capability setting from par build
🐛(runtime): rustdoc spelling
🔨(host): Actor -> Component
🔨(wash-cli): remove capability claims
🔨(wash-lib)!: remove capability claims
🐛(tests): lint
🐛(wash-lib)!: remove usage of capability signing
📚(provider-messaging-kafka): remove --capid usage in README
📚(provider-archive): remove capid from docs
🔨(vendor): remove --capid from old makefiles
🐛(tests): remove capid from provider creation
🔨(test-util): wascap::jwt::Actor -> wascap::jwt::Component
✨(host)!: remove capabilities
🔨(runtime): wascap::jwt::Actor -> wascap::jwt::Component
✨(provider-archive)!: remove capabilities
✨(wascap)!: remove capability signing from wascap
🛠️(wash): Updates wash to use new host version
🏗️(deps): Bump the prod-dependencies group
🤖(github): update CODEOWNERS
```

### Backwards Compatibility

In order to reduce the burden of long-term maintenance, I propose we squash all previous commits in wasmcloud/wasmcloud into an initial commit message, e.g. "🚀: we have liftoff". This will simplify all future commits and start us off with a clean slate.

### Alternatives Considered

Alternatively, and the direction I'm leaning, we could fully embrace emojis not just for the commit types, but for the projects and messages too. Taking the above example commits, it will look like this:

```
🏗️(📦): 🆙
🐛(🤖): 🔧
🐛(📖): ✏️
🔨(👤): 🔄🎭
🔨(🧼🔑): ❌🔑
🔨(📚🔑): ❌🔑❗
🐛(🔍): 🧹
🐛(📚🔑): ❌🔏❗
📚(📨🔊): ❌🆔
📚(🗃️): ❌🆔
🔨(🏷️): ❌🆔
🐛(🔍): ❌🆔
🔨(🔧📜): 🔄🎭
✨(👤): ❌🚀
🔨(🖥️): 🔄🎭
✨(🗃️): ❌🚀
✨(🔏): ❌🔏❗
🛠️(🚿): 🆙📆
🏗️(📈): 🔺
🤖(👥): 🆙👀
```

This has the benefit of being immediately compliant with internationalization standards as emojis are language agnostic, just like Wasm.

My only concern here is that this would be too efficient, allowing mere mortals to parse the commit history of the entire repository in less than a second. We may want to stick with using words as well to slow us down.

### Unresolved Questions

- How will we ensure that the chosen emojis are universally accessible and render consistently across different platforms and environments?
- Are we concerned about the wasmCloud logo not being an official emoji? How can we propose this as an icon to make it into operating systems worldwide?
- What code changes can we make, e.g. renaming variables and files to emojis, to embrace this new common standard?
- As mentioned in alternatives, will this be too efficient?

### Conclusion

This RFC suggests standardizing and improving our conventional commit process using the powerful language of emojis. Please let me know your feedback below, bonus points if it includes emojis 😉

**Comment by jocrau** [comment]
I suggest to add an emoji for changes to the CI system that makes build fail. Something like
<img width="55" alt="Screenshot 2024-04-01 at 11 43 28 AM" src="https://github.com/wasmCloud/wasmCloud/assets/249273/5e8b693e-8b92-4e6e-b24d-89732c4220cf">

**Comment by brooksmtownsend** [comment]
> I suggest to add an emoji for changes to the CI system that makes build fail. Something like <img alt="Screenshot 2024-04-01 at 11 43 28 AM" width="55" src="https://private-user-images.githubusercontent.com/249273/318489553-5e8b693e-8b92-4e6e-b24d-89732c4220cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5ODY2NjYsIm5iZiI6MTcxMTk4NjM2NiwicGF0aCI6Ii8yNDkyNzMvMzE4NDg5NTUzLTVlOGI2OTNlLThiOTItNGU2ZS1iMjRkLTg5NzMyYzQyMjBjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxNTQ2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNThmMTlkNTA4ZjYzNDg5OGVlZjNiNmFhN2FiOWM3ZjEzODY1NDcwNmZjMzczOWEwM2M2ZDYwMmI4N2JlMjRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KSAeHYVpcC0ublYi2vDfrcw3XOpuoDWW-Its-F1Vvcg">

I can't believe I've overlooked CI here! I think this is a good start too, sad robot for failed builds and happy robot for all green.
