### ISSUE TITLE
Instrument host using the tracing crate

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#18]
The tracing crate allows you to instrument your code and then choose from any number of subscribers..  this greatly reduces the overhead of trying to support multiple instrumentation outbound targets. It also has a number of really compelling features.

Once this is done, we can then implement the prometheus / open telemetry issues (#10 ) with subscribers to the tracing output rather than hard-coded paths.

[https://docs.rs/tracing/0.1.22/tracing/index.html](https://docs.rs/tracing/0.1.22/tracing/index.html)
[https://crates.io/crates/tracing-opentelemetry](https://crates.io/crates/tracing-opentelemetry)
[https://docs.rs/tracing-subscriber/0.2.15/tracing_subscriber/fmt/index.html](https://docs.rs/tracing-subscriber/0.2.15/tracing_subscriber/fmt/index.html)

**Comment by brooksmtownsend** [comment]
Related to #9 #11

**Comment by autodidaddict** [comment]
No longer applicable to OTP.
