### ISSUE TITLE
[FEATURE] Rename `Actor` to `Component`

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#1827]
### Affected project(s)

- [X] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

In the leadup to wasmCloud 1.0, we discussed and decided to rename "actor" to "component" as there is nothing special about a component that runs in wasmCloud, it's just a WebAssembly component 😄 In all of our protocols, events, and public APIs we've attempted to do this already to avoid breaking changes, but we have not updated all internal naming from actor -> component.

### Describe the solution you'd like

This is okay as a slow-burn issue as it's not critical to do immediately, but I wanted to file this issue for two reasons:
1. If there are new features that touch code that mention actors, go ahead and rename it to components while you're in there
2. If any community members see "actor" and that drives confusion, I want to be clear that it's just a WebAssembly component 🚀 

### Describe alternatives you've considered

We could do this as a part of a big refactor, which is fine, I just want to be conscious about doing that while it might cause larger merge conflicts amidst other work

### Additional context

We discussed this rename in the 2024-03-13 community meeting: https://wasmcloud.com/community/2024/03/13/community-meeting

**Comment by nitame** [comment]
Hello, as this issue is labeled good first issue, I would like to try to do this issue or at least one of the tasks included in it. Is it ok? Or does anyone want to do it?
Thanks,

**Comment by thomastaylor312** [comment]
@nitame you can go ahead and work on this! Should just be rename of internal variables, function parameters, etc. Let us know if you have any questions!

**Comment by brooksmtownsend** [comment]
Pinning good here, but @nitame is knocking this out quickly so we should be able to wrap this up!

**Comment by brooksmtownsend** [comment]
@nitame You've done a ton of work here, I think we can close this up! If there are any other dangling references we can certainly take care of them, but I believe the vast majority are taken care of now. Any other last ones we should fix?

**Comment by nitame** [comment]
@brooksmtownsend Yes you can close this issue. As you said, I think there are a few remaining references to actors, but it could surely be handled on the go with BSR.
