### ISSUE TITLE
[SPIKE] Replacing nats::asynk with nats (synchronous)

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#185]
**Describe the bug**
A NATS maintainer mentioned some performance downsides to using `async_nats`, and we've generally run into a bit of friction getting it to work properly for us in the past. We should investigate the level of effort required to replace this library with synchronous nats, and if we have anything preventing us from doing so.

**Additional context**
At the very least, our usage of `nats 0.8.6` to use `nats::asynk` should be updated to https://docs.rs/async-nats/0.9.16/async_nats/index.html, where the async code is living now instead. This will enable us to get updates to this library.

**Comment by autodidaddict** [comment]
This issue is essentially irrelevant now that we're doing OTP, since we don't use NATS from Rust anywhere in the new design.
