### ISSUE TITLE
[CHORE] Add a README to `wasmcloud-core`

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#1854]
[https://crates.io/crates/wasmcloud-core](https://crates.io/crates/wasmcloud-core) has no README!

We should say something about it 😄😄

**Comment by thomastaylor312** [comment]
![tenor-205800860](https://github.com/wasmCloud/wasmCloud/assets/4294228/ba01f214-988f-499b-a399-5c276111be6f)

**Comment by lachieh** [comment]
Test

**Comment by lachieh** [comment]
Test comment
