### ISSUE TITLE
[FEATURE] Implement `wasi:keyvalue/batch`

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmCloud#1867]
To fully implement the wasi:keyvalue interface, we need to implement the batch operations as well. See https://github.com/WebAssembly/wasi-keyvalue/blob/main/wit/batch.wit for the interface

### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

**Comment by ossfellow** [comment]
Where does this need to be implemented? If it’s about the providers, then currently, both redis-keyvalue and nats-keyvalue providers implement this interface; vault-kv is the only provider that doesn’t implement it.

**Comment by thomastaylor312** [comment]
I think we might have missed closing this issue when we did implement it in the other providers. Vault KV would also be nice to have if you're interested in doing that

**Comment by brooksmtownsend** [comment]
This is a great first issue for folks looking to learn more about how the connection between Wasm component interfaces and wRPC works in wasmCloud. Take a look at the implementation of wasi:keyvalue/store and wasi:keyvalue/atomics for inspiration here.
