### ISSUE TITLE
[BUG] `component_scaled` events are published twice when a component stops

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#1888]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

When a component is scaled to a max instances value of `0`, we emit two `component_scaled` events that assert that it was scaled to zero.

### Steps to reproduce

```bash
wash start component wasmcloud.azurecr.io/http-hello-world:0.1.0 asd
nats sub "wasmbus.evt.>"
wash stop component asd
```

### Expected behavior

I expect to see one event.

### Environment

- OS: [e.g. Linux, MacOS]
- Shell [e.g. bash, zsh, powershell]
- wasmcloud Version [e.g. 0.81.0]

**Comment by yerzham** [comment]
Related to this error, when running the following command for the running component:
```bash
wash scale component <host-id> wasmcloud.azurecr.io/http-hello-world:0.1.0 asd
```
There are also two `component_scaled` events, but one asserts that it is unbounded (max_instances: 4294967295), and the consequent event asserts that it is scaled to 0.

Similarly, when using
```bash
wash update component asd wasmcloud.azurecr.io/http-hello-world:0.1.0
```
It emits `component_scaled` about the updated component, but emits two `component_scaled` events that an old component is scaled to 0.

I have identified the root issue and will create a pull request soon.
