### ISSUE TITLE
[BUG] wasmcloud requires NATS connection to start

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#189]
**Describe the bug**
If `nats-server` is not running when the wasmcloud binary starts, it will exit with a ConnectionRefused error. `wasmcloud` does not require nats to run and should, in the absence of a nats connection, run as usual without lattice.

**To Reproduce**
1. Install `wasmcloud` binary
2. Run `wasmcloud` without `nats-server` running
3. See error

**Expected behavior**
If a nats connection is not present, `wasmcloud` should still run fine, albeit without a lattice or control interface connection. This means that in the absence of a nats connection supplying a manifest is best practice as you cannot interact with the host after the process starts.

**Environment**
- wasmcloud version `0.18.1`

**Comment by autodidaddict** [comment]
I think the desired behavior should be:
* If starting with a manifest, seamlessly detect single- or multi-player mode
* If running w/out a manifest, stop the application if no NATS is detected, with a message indicating that without a manifest or NATS, the host cannot be told to start workloads.

**Comment by VestigeJ** [comment]
I was looking at this last night - was going to post notes then but I couldn't stay awake. 

The nats snap author from Canonical opted not to run it right away but to instead wait for configuration. The bare minimum configuration file placed at the following should be enough to start the nats.service 

 /var/snap/nats/common/server/nats.cfg 
'''
listen: 0.0.0.0:4222
'''

I tried using the snap config for this functionality but didn't get it working yet. 

'''
layout:
  /etc/nats.cfg:
    bind-file: $SNAP_COMMON/server/nats.cfg
'''

My manual steps for this process:
'''
sudo snap install nats
sudo mkdir /var/snap/nats/common/server
vim /var/snap/nats/common/server/nats.cfg
'''
//Insert listening interfaces/ports/tokens/keys
'''

sudo snap start --enable nats.server
 


I'll add more notes soon when I can today.
