### ISSUE TITLE
[BUG] HTTPServer provider reports a failed health check

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#1925]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

The HTTPserver provider reports the following warning log every health check:
```rust
2024-04-17T16:17:09.234789Z  WARN wasmcloud_host::wasmbus: failed to request provider health, retrying in 30 seconds
```

### Steps to reproduce

1. `wash up -d`
2. `wash start component ghcr.io/wasmcloud/http-server:0.20.0`
3. View logs

### Expected behavior

I expect for the health check to work!

### Environment

- OS: [e.g. Linux, MacOS]
- Shell [e.g. bash, zsh, powershell]
- wasmcloud Version [e.g. 0.81.0]

**Comment by yerzham** [comment]
The steps to reproduce should be:
1. `wash up -d`
2. `wash start provider ghcr.io/wasmcloud/http-server:0.20.0 http-server-1`
3. View logs or subscribe to `wasmbus.evt.default.health_check_passed` nats subject

Based on my manual checks on the current main branch, the health check for the HTTP server is passing. I might try to reproduce it some other way.

**Comment by brooksmtownsend** [comment]
I can't reproduce this in `main` so I'm going to close this for now as it'll be fixed by the next patch release of wasmCloud, but if this comes back we can re-open this issue. Thanks for checking as well @yerzham !
