### ISSUE TITLE
[FEATURE] Improve error output for incorrectly configured links.

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#1927]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

When linking on an incorrect interface, or when an interface link is not present, the errors can be opaque and appear like a stacktrace.

### Describe the solution you'd like

Though we eventually do need to return errors and we might not be able to prevent a panic inside of the component, it would be great to output proper logs to help narrow down issues.

**Comment by vados-cosmonic** [comment]
Another reason that this can happen is that there isn't a link with the right name. It's possible that *a* link is configured, but not one that matches the expected link name.
