### ISSUE TITLE
[BUG] Packagecloud does not include Pop!_OS as a supported OS

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#193]
**Describe the bug**
When following the install instructions on wasmcloud.dev, I have to override the os/dist variables to install the packagecloud repository on Pop!_OS 20.10.

**To Reproduce**
1. Launch a Pop!_OS VM
2. Run: curl -s https://packagecloud.io/install/repositories/wasmcloud/core/script.deb.sh | sudo bash
3. See error

**Expected behavior**
As Pop!_OS is similar to Ubuntu, and overriding the dist information with `os=ubuntu dist=groovy` works just fine to add the repository, we should add `Pop` to the release action for packagecloud.

**Screenshots**
![image](https://user-images.githubusercontent.com/12040685/117155938-35d2d100-ad8b-11eb-9581-5bef45369a3d.png)

**Environment (please complete the following information) **
- OS: [e.g. Linux, MacOS, Windows] Pop!_OS 20.10
- Architecture: [e.g. x86_64, arm64] x86_64
- Shell [e.g. bash, zsh, powershell] bash
- wasmcloud version [e.g. `0.15.0`] 0.18.1

**Comment by billyoung** [comment]
@brooksmtownsend unfortunately PopOS is not supported by packagecloud. To retrieve a list of supported OS's you can run the following (with an API token):

```curl https://{TOKEN}@packagecloud.io/api/v1/distributions.json | jq```

**Comment by brooksmtownsend** [comment]
Ah thanks @billyoung , we'll likely just want to let any pop users to override that flag. Closing this
