### ISSUE TITLE
[FEATURE] split console and OTEL log levels

### ISSUE THREAD

**Issue by rvolosatovs** [wasmCloud/wasmCloud#1932]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

Currently there's only one log level for both stderr and OTEL logging

### Describe the solution you'd like

stderr logging levels and OTEL logging levels should be separate - we should log at `info` level to stderr by default, but default to `debug` to OTEL

**Comment by brooksmtownsend** [comment]
Not stale ❌ This should be done shortly!
