### ISSUE TITLE
CHORE: Provide error when non-empty values are used for buckets with kvredis provider

### ISSUE THREAD

**Issue by ericgregory** [wasmCloud/wasmCloud#1939]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

Per discussion with @rvolosatovs the kvredis provider currently accepts differentiated names for buckets, and this may foster an incorrect perception that the provider uses multiple, separate buckets when it in fact uses a single global bucket. 

### Describe the solution you'd like

The provider should error if anything other than an empty string is used.

**Comment by brooksmtownsend** [comment]
What are our thoughts on a warning log here? I'm concerned that existing applications using `wasi-keyvalue` may unexpectedly fail if they were using a bucket before

**Comment by thomastaylor312** [comment]
I think the Right™ answer here is to error because the thing providing is saying "I don't know what you're referring to." Maybe start with a warning message for the next release and then turn it into a hard error after that
