### ISSUE TITLE
[RFC] Embedded Runtime (SPIKE)

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#194]
This story refers to a research spike that might result in a usable runtime. The goal is to explore possibilities for running wasmCloud actors on a host runtime that is designed for small, embedd(ed|able) devices. Devices like this include, but are not limited to, Particles, Arduinos, ESP32xx, nRF52840, and much more. Some of these devices may not be fast enough, some may not have enough RAM to be able to load and interpret a WebAssembly module.

The trick will be finding the overlap between supported targets by the chosen compilation language (likely C), and the targets that are capable of smoothly running/interpreting a wasm module using wasm3's micro runtime or WAMR or something similar.

Requirements:
* Host runtime will offer a _fixed_ set of capabilities, likely to include as a mandatory access to a timer and GPIO
* Host runtime will communicate with the rest of the lattice over MQTT link. NATS supports MQTT and so leaf nodes can be made available in physical proximity to edge devices to bridge connectivity to the cloud.
* Host runtime should support remote requests to schedule/start an actor (resources permitting)
* Host runtime should support requests for actor live update/hot swap (resources permitting)
* Cryptographic functions like generation of an nkey and signing invocations may become a limiting/inhibiting factor

**Comment by vshymanskyy** [comment]
Feel free to contact / ask any questions.

**Comment by autodidaddict** [comment]
Another thought.... I feel a little uncomfortable saddling these "micro-hosts" with all the responsibilities and roles of a full blown wasmCloud host. I don't want these hosts to have to constantly await messages from a remote control interface, nor do I want them to have to manually manage the anti-forgery stuff that full-size hosts have to deal with. In the major use case for these microhosts, they're going to be running a single actor and a bunch of hard-coded capabilities chosen at compile-time by the **Sketch** author.

One possibility for separating these roles and responsibilities might be the introduction of a lattice "micro proxy" between the regular lattice and the sub-section containing an arbitrarily chosen set of micro-hosts.

It might look something like this:

```
   .-------[ L A T T I C E ]------------------------------.
   |                                                      |       .------------------.
   |    .------.    .------.     .------.                 |<----  | host group proxy | -----> { micro hosts }
   |    | host |    | host |     | host |                 |       `------------------'
   |    `------'    `------'     `------'                 |
   |                                                      |
   `------------------------------------------------------'
 ```
This would essentially allow the host group proxy to pretend to individually be each of the hosts on the other side. This introduces 1 hop worth (10ms is the avg "latency budget spend" for a proxy hop) of latency between the main lattice and the "far edge" devices, but it also allows this proxy to deal with things like network partition events so that it can hold onto/queue outbound requests, cache things it might need, etc -- all to alleviate the burden on these already constrained devices.

This host group proxy might also be able to act as a source of the raw data for the OCI images. We don't want these tiny little devices to have to spend their network budget connecting to OCI registries, not to mention the many situations where these devices won't have access to an OCI registry.

So a recap of the division of roles might be as follows:

### Host Group Proxy
1. Create signing keys for each micro host
2. Sign/verify invocation anti-forgery tokens
3. Cache actor images retrieved from OCI (or elsewhere?)
4. Expose some means (OCI API?) to allow the microhosts to download actors

### Micro Host
1. Run actor wasms (1 actor per host)
2. Listen for/query link definitions to update configuration as necessary
3. Allow Sketch authors to provide implementations of contract abstractions exposed through C++ facades in the wasmcloud-arduino library(s).

This reduces the micro host dependencies down to:
* `OCI client` (or something proprietary if we decide against it)
* `Message Pack` - still need to encode/decode messages between providers and actors
* `MQTT` - need to connect to a microhost proxy via MQTT

Microhosts will not need encryption capabilities or JSON

**Comment by autodidaddict** [comment]
Further thoughts...

There's a way to do this that would be substantially simpler than all of the previously discussed options. In this option, instead of building a "host group proxy" that has some proprietary functionality in it, all we truly need is a capability provider that proxies requests to the corresponding hardware "behind" it via MQTT.

Let's take a concrete example - GPS location.

Assume we have a `wasmcloud:location` capability contract. We could instantiate the `wasmcloud-embedded-location` provider and add it to a plain vanilla wasmcloud host. This provider reads environment variables to obtain an MQTT connection. It then forwards invocations over MQTT to a device that implements the location functionality and sends responses back. As the device publishes data, the embedded location provider would then simply use the dispatch to send that data to the corresponding actor.

In short, each time we want to provide an implementation for one of these contract IDs, we simply create a provider that proxies over MQTT. Everything would be backwards compatible with all existing lattice and wasmCloud functionality.

The MQTT protocol used by the devices might look like this:
* On startup, the device publishes to a topic corresponding to the contract ID, e.g. `wasmcloud.location.hb` that contains a unique identifier for the device. This heartbeat is then published every **n** seconds.
* The capability provider keeps track of all discovered devices via the heartbeats.
* When the provider receives a `handle_call`, it will dump the bytes onto `wasmcloud.location.req` and get a reply and then send the reply back as the return value.
* When a device publishes to `wasmcloud.location.pub` that data will be placed inside an invocation (devices do not know what an invocation is) without modification and sent to all actors with active link definitions

In this implementation, the `link_name` field of a link definition would refer to a specific instance of this provider. Each instance maintains its _own unique swarm_ on the other side. In other words, you can use the link name disambiguation to have a swarm of location providers behind the name `trucks` and another one behind the name `cars` , with each reporting locations of their respective devices. These would segment traffic by having different connection strings.

**Comment by autodidaddict** [comment]
To sum up, what is being proposed here is this:

* wasmCloud will support all the host runtimes that we release as binaries when we cut releases, which includes arm and releases capable of running on Raspberry Pis, etc. 
* wasmCloud host _will require a supported operating system_ (Linux, Windows, Mac)
* We will define a number of capability contracts around IoT capabilities, including `location` , `sensors`, `addressableleds`, `temperature`, etc.
* We will define a clear protocol (tentatively called "wasm link") that defines how external devices can interact with a "hub" via "capability gateways" running on said hub. This will include tutorials on how to make them as well as _supported_ first party implementations of a set number of our contracts.
* wasmCloud will encourage and support community efforts around writing code on constrained/embedded devices but we will not issue releases for non-OS devices.
* Where possible, we will create unofficial community libraries like an **Arduino** library that can be used to communicate with "wasm link" capability gateways.

**Comment by autodidaddict** [comment]
Closing as we have decided that the last post in this issue reflects our current thinking on the matter. An ADR will be created to capture this decision.

**Comment by stephenandary** [comment]
Would FPGAs fit into this spike? Could
https://github.com/fabianschuiki/llhd or https://github.com/yupferris/kaze make it possible to include them here with arduino?
