### ISSUE TITLE
[BUG] Failed to start wasmCloud on host with available memory

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#1961]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

```
ubuntu@instance-20240402-0943:~$ uname -a
Linux instance-20240402-0943 6.5.0-1020-oracle #20~22.04.1-Ubuntu SMP Thu Mar 14 18:34:01 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@instance-20240402-0943:~$ free
               total        used        free      shared  buff/cache   available
Mem:          970224      180816      288380        1084      501028      635332
Swap:              0           0           0
ubuntu@instance-20240402-0943:~$ ~/.wash/downloads/v1.0.0/wasmcloud_host
2024-04-19T16:21:17.904061Z  INFO async_nats::options: event: connected
2024-04-19T16:21:17.904077Z  INFO async_nats::options: event: connected
Error: failed to initialize host

Caused by:
    0: failed to build runtime
    1: failed to construct engine
    2: failed to create table pool mapping
    3: mmap failed to allocate 0x61a80000 bytes
    4: Out of memory (os error 12)
```

### Steps to reproduce

I ran this example on a pretty vanilla Oracle cloud instance running on Linux, with a little over 250mb free memory. This should be reproducible with a memory limited Docker container as well, though on my mac limiting the memory doesn't achieve the same effect.

### Expected behavior

I got an error running the host attempting to allocate 164MB, which I assume should be possible with this amount of memory that is free, but perhaps we are trying to allocate a few pages here. This appears to be during the instantiation step of the engine, so from my understanding this is allocating memory to use with Wasm components.

### Environment

- OS: [e.g. Linux, MacOS]: Ubuntu 22.04, x86_64
- Shell [e.g. bash, zsh, powershell]: bash
- wasmcloud Version [e.g. 0.81.0]: 1.0.0

**Comment by thomastaylor312** [comment]
@brooksmtownsend this is likely from the pooling allocator. I tried to have it be smart about allocating memory using the available memory but I couldn't figure out something that worked. Probably worth revisiting now that we're past 1.0

**Comment by brooksmtownsend** [comment]
It has come to my attention that `0x61a80000` is not 164MB, it's actually 1.64 GB, which is definitely more memory than is available here. This probably needs to be tunable and maybe even lower but I know #1616 did a lot of work in the performance aspect

**Comment by brettjrea** [comment]
There does seem to be some problems regarding the math and conversions and absurd amounts of memory being requested, but regardless the fallback to the dynamic allocator strategy should also kick in as shown here.                 
https://github.com/wasmCloud/wasmCloud/blob/2b98f76f6eebdb63f570cae6d95cf3d024b98ca5/crates/runtime/src/runtime.rs#L251

**Comment by brooksmtownsend** [comment]
That's right @brettjrea, we just got a fix out in #2052 which should solve this, closing for now and we can re-open if we can reproduce the problem again 🚀

**Comment by brettjrea** [comment]
That's right. I did see that. Thanks for the quick response. Sorry for repeating the information.

**Comment by brooksmtownsend** [comment]
No not at all! I appreciate the reminder, and I'm glad the fix showed up as something that would resolve this 😄 Thank you @brettjrea

**Comment by brettjrea** [comment]
I see the 1.0.2 release being built, thanks for taking quick action! I don't have much time today to test but you know I have too!

**Comment by brooksmtownsend** [comment]
```
~$ wash up --nats-connect-only --wasmcloud-version v1.0.2
🏃 Running in interactive mode.
🎛️   To start the dashboard, run `wash ui`
🚪 Press `CTRL+c` at any time to exit
2024-05-08T14:11:49.437567Z  INFO async_nats::options: event: connected
2024-05-08T14:11:49.438426Z  INFO async_nats::options: event: connected
2024-05-08T14:11:49.439534Z  WARN wasmcloud_runtime::runtime: failed to construct engine with pooling allocator, falling back to dynamic allocator which may result in slower startup and execution of components. err=failed to construct engine
2024-05-08T14:11:49.440899Z  INFO wasmcloud_host::wasmbus: bucket already exists. Skipping creation. bucket=LATTICEDATA_default
2024-05-08T14:11:49.441430Z  INFO wasmcloud_host::wasmbus: bucket already exists. Skipping creation. bucket=CONFIGDATA_default
2024-05-08T14:11:49.444624Z  INFO wasmcloud_host::wasmbus: wasmCloud host started host_id="NDNXGOFWQCEEJHYXGWCAXC54DTU3VEOIFYUJMJYXZ4YRNRVVV5J2SHY6"
```

Confirmed on my original machine to resolve the issue

**Comment by brettjrea** [comment]
I had to rebuild my components, but it is indeed working for me now. I like to code from my phone, so this was going to drive me crazy!
Thank you!
