### ISSUE TITLE
[FEATURE] Prevent component updates when the component image reference did not change

### ISSUE THREAD

**Issue by yerzham** [wasmCloud/wasmCloud#1972]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

When a component is updated with the same image reference, the host emits events that a component is scaled to the same component image and then scaled to 0 (the old component getting scaled out). So there is no (obvious) way to differentiate if the component scaled to 0 or just updated with the same image ref.

### Describe the solution you'd like

The host should reject a component update if the component image reference did not change.

Wash CLI should also somehow display the corresponding update error.

I suppose wadm is also capable of preventing it? 

PS. maybe the component image hash (digest) is a better reference for tracking if the component should be capable of being updated?

**Comment by brooksmtownsend** [comment]
> I suppose wadm is also capable of preventing it?

Yes wadm won't ever issue an update command with the same image reference, so we're set there 😄 

> PS. maybe the component image hash (digest) is a better reference for tracking if the component should be capable of being updated?

Definitely, we do have the ability to store the digest of a component and determine if it needs to be updated. We do take the opinion that an image reference should be immutable, and to avoid using `latest`, but we may want to bring that back up in the future as we work more with files and updating "latest" to "latest latest"

**Comment by yerzham** [comment]
Closed by #1978
