### ISSUE TITLE
[BUG] wash-cli: component update must error if no host-id provided and multiple hosts running the component

### ISSUE THREAD

**Issue by yerzham** [wasmCloud/wasmCloud#1980]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

The `wash-cli` component update command sends an update to a first-found host with the component (which might have been already updated after multiple update commands), even though multiple hosts are running the component and the user did not specify a host id. 

### Steps to reproduce

1. Run wasmCloud with two or more hosts
2. Subscribe to `wasmbus.evt.default.component_scaled` nats channel
3. Run `wash start component wasmcloud.azurecr.io/http-hello-world:0.1.0 test` two or more times
4. Run `wash update component test ghcr.io/brooksmtownsend/http-hello-world-rust:0.1.0`
5. Observe from `wasmbus.evt.default.component_scaled` that only one host updated, or observe from wasmCloud host logs that only one of them updated the component.

### Expected behavior

The component update command must error if no host-id is provided and multiple hosts are running the component. 

`UpdateComponentCommand` docs state:
> If no host ID is passed, a host will be selected based on whether or not the component is running on it. If more than 1 host is running this component, an error will be returned with a list of hosts running the component.

Alternatively, update the documentation to describe a different behavior. For example, if no host-id provided, update all hosts components.

### Environment

- wasmcloud Version 1.0.0
- wash Version 0.27.0

**Comment by yerzham** [comment]
I can add a fix in `wash-cli` if there are no expected changes to the documentation instead. I will wait for confirmation

**Comment by yerzham** [comment]
Seems to align with the goal of "preventing a user from unintentionally running two different versions on two different hosts" described in #1818.

**Comment by vados-cosmonic** [comment]
Hey @yerzham are you still working on this by any chance?
