### ISSUE TITLE
[BUG] Blobby example, unknown "wasi:blobstore/blobstore" target

### ISSUE THREAD

**Issue by brianw-0** [wasmCloud/wasmCloud#1996]
### Affected project(s)

- [ ] documentation
- [X] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

This error occurs when running the Blobby example under wasmCloud/examples/rust/components. When the blobby component receives a curl command, it attempts to check if the blobstore container exists, and instead returns the error "unknown `wasi:blobstore/blobstore` target"

Nothing from the example code has been modified, so the wadm.yaml, wit, and source files remain the same as in the public repo.

### Steps to reproduce

1. wash up
2. wash app deploy wadm.yaml (from the blobby example folder)
3. curl [http://localhost:8080](http://localhost:8080)

### Expected behavior

I expected the example code to continue executing and create the corresponding container with name "default".

### Environment

* OS: Ubuntu 22.04.1
* Shell: bash
* wash: 0.27.0
* wasmcloud: 1.0.0

### Screenshots / Logs / Additional context

Running the commands from the wasmCloud/examples/rust/components/blobby directory:

```
> wash app deploy wadm.yaml
Successfully deployed model blobby v0.0.1

> curl localhost:8080
Error when communicating with blobstore: unknown `wasi:blobstore/blobstore` target
```

**Comment by brooksmtownsend** [comment]
I didn't consider that merging the PR would mark this as "completed", I was able to make it work with this fix but please let me know if it works for you! If it doesn't we can reopen

**Comment by brianw-0** [comment]
Thank you for the fast response!  I applied the fix but I still get a blobstore error (although slightly different this time): 
```
Error when communicating with blobstore: function failed: failed to lookup creation date: creation time is not available on this platform currently
```

**Comment by brooksmtownsend** [comment]
Woah, that's surprising. That error is coming back from the standard Rust library, so it must be an issue we need to compensate for in our blobstore provider. I suppose we could just default at 0, or the UNIX epoch, if the OS doesn't support the creation time.

Thoughts @thomastaylor312 ? Not sure if you've seen this handled in a different way

**Comment by thomastaylor312** [comment]
Honestly I think that fix will work just fine

**Comment by brooksmtownsend** [comment]
Alrighty @brianw-0 , if you wouldn't mind trying with `ghcr.io/wasmcloud/blobstore-fs:0.6.1` that should fix the creation time issue 😄 One more bug squashed

**Comment by brianw-0** [comment]
Sorry for the late response - yes, it appears that the errors are gone.  Thank you for your help!

**Comment by brianw-0** [comment]
Sorry for the late response - yes, it appears that the errors are gone.  Thank you for your help!
