### ISSUE TITLE
[RFC] Expose a Control Interface API Directly From the wasmCloud Host

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#200]
# Expose a Control Interface API from the wasmCloud Host

## Summary

This request for comment applies to the desire to expose an administrative API from the wasmCloud host itself that is local and non-lattice. This would include exposing Kubernetes-friendly endpoints for health and readiness checks, and service functionality that can query the host inventory, start and stop actors, start and stop providers, and set and remove link definitions. In short, expose the lattice control interface but directly from the host for when there is no NATS available for "remote" control.

## Motivation

Developer experience is among the most important things for wasmCloud. We absolutely must provide a simple, low-friction experience to developers for every interaction point between developers and wasmCloud. In today's code base, the wash REPL has to perform some fairly intricate shenanigans to be able to communicate with a wasmCloud host and we absolutely do not support the control interface without using lattice.

The developer-visible end result of this is that they will finally be able to start an _empty_ wasmCloud host, leave it running in the background, and use any combination of CLI and API calls to load providers and actors into that host without ever needing NATS installed. We can finally apply our guiding principle of opt-in complexity to controlling a host from out of process.

## Design Detail

The design here should be fairly simple. We intend to expose a gRPC endpoint from the wasmCloud host that acts as a control interface endpoint that exposes the same functionality that is normally available remotely through lattice. It should be easy to share code and just add additional endpoints over top of the existing business logic.

## Drawbacks

An argument could be made that a drawback of this approach is that we're duplicating code. I think this drawback can be mitigated through careful and appropriate code design and following architectural patterns. Another drawback that people could potentially suggest is that the addition of this endpoint will add size, bloat, and degrade performance. We think that all of these can be mitigated as well, though only evidence will prove that out.

## Rationale and Alternatives

This approach is basically an industry standard when it comes to microservices running in the cloud. Daemon processes that are running under scheduling systems of any kind (not just Kubernetes) need to expose _at the very least_ endpoints that indicate health and readiness. Countless other cloud native products expose telemetry endpoints as well as other queryable endpoints. An example of an excellent control API is the set of [REST endpoints](https://docs.nats.io/nats-streaming-concepts/monitoring/endpoints) that come with NATS out of the box, proving that the addition of these kinds of endpoints doesn't hinder performance at all.

Without these endpoints, many different types of infrastructure can't tell if a wasmCloud process is healthy or not and, as mentioned earlier, without this endpoint the only way to manipulate and query the contents of a host process is through the use of a lattice connected via NATS.

## Prior Art

We mentioned the NATS endpoints in the previous section. For further examples, take a look at the [Spring Boot actuator](https://howtodoinjava.com/spring-boot/actuator-endpoints-example/) endpoints, which offer a full range of service functionality essentially "for free" for any developers building microservices using Spring Boot.

**Comment by autodidaddict** [comment]
Thoughts on priority or whether this should even be implemented given the OTP rewrite? @brooksmtownsend @stevelr

**Comment by brooksmtownsend** [comment]
I think this is worth keeping in mind for later, depending on how wasmCloud users feel about using the control interface. Definitely not relevant to the Rust runtime.
