### ISSUE TITLE
[FEATURE] Update lattice controller provider to be compatible with 1.0

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#2004]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

The lattice controller provider currently uses an outdated control interface version and WIT interface for interacting with hosts on a 1.0 lattice.

### Describe the solution you'd like

Based on the protocol updates to the wasmCloud control interface, https://crates.io/crates/wasmcloud-control-interface, the WIT interface for the provider should be updated (and versioned at @1.0.0). That way we can use the lattice controller to manage a lattice through components.

**Comment by vados-cosmonic** [comment]
Hey @brooksmtownsend if this isn't planned should we remove the lattice controller from the repo for now? Thinking this might have been some unruly automation closing the ticket...?
