### ISSUE TITLE
[FEATURE] Rename published components OCI artifacts

### ISSUE THREAD

**Issue by vados-cosmonic** [wasmCloud/wasmCloud#2008]
### Affected project(s)

- [ ] #2019
- [X] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

The current published component artifacts have a `component-` prefix, which is nice for determining whether an image is a component, but somewhat repetitive when the name of the component is something shorter like `echo-messaging`.

It would be nice to have a more concise name (though overall typing might not actually be decreased).

### Describe the solution you'd like

We should:

- [ ] Update automation to produce and push `ghcr.io/wasmcloud/components/<name>:<tag>` artifacts
- [ ] Update documentation (`README`s, wasmcloud.com repo) to reference the new locations
- [ ] Delete the older versions of the images with the old naming scheme

### Describe alternatives you've considered

We considered a few different naming schemes:

- `ghcr.io/wasmcloud/<name>:<tag>`
- `ghcr.io/wasmcloud/component-<name>:<tag>` (current)
- `ghcr.io/wasmcloud/examples/components/<name>:<tag>`
- `ghcr.io/wasmcloud/components/<name>:<tag>`
- `ghcr.io/wasmcloud/components/<name>-<lang>:<tag>` (✅)

**Comment by joonas** [comment]
I would also encourage us to include the language a given component example is written in as a suffix of the `name`, so for example:
```
ghcr.io/wasmcloud/component-http-hello-world:0.1.0
```
would become:
```
ghcr.io/wasmcloud/components/http-hello-world-rust:0.1.0
```

This makes it possible to show the same example written in multiple languages, and makes it obvious which component example is being talked about.

**Comment by vados-cosmonic** [comment]
Awesome that sounds even better -- will update the original description in case someone else wants to work on this!
