### ISSUE TITLE
[BUG] wash plugin directory should use ID and not Name

### ISSUE THREAD

**Issue by ricochet** [wasmCloud/wasmCloud#2039]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

Names will typically have spaces and that's perhaps less expected and desired for dir paths.

We doc that this is the plugin_id at:
https://wasmcloud.com/docs/ecosystem/wash/plugin_developer

### Steps to reproduce

Install a plugin then check it's scratch dir.

### Expected behavior

Uses <plugin_id>

### Environment

- wash 0.28.0

**Comment by thomastaylor312** [comment]
The scratch dir used ID, but the name of the installed plugin binary was using the name field. That should be fixed in #2040
