### ISSUE TITLE
[RFC] Interfaces 2.0:  replace WIDL with Smithy IDL

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wasmCloud#205]
# Interfaces 2.0

## Introduction

This RFC proposes a new interface design language, [Smithy](https://awslabs.github.io/smithy/) to replace [WIDL](https://github.com/wapc/widl-spec) for defining wasmcloud-related messages and parameters. 

## Motivations

We would like to formally specify all of wasmcloud's external apis, and some internal apis, with an IDL. Today we use WIDL to define interfaces of actors and capability providers - messages going into and out of Web Assembly. In a near-future version of wasmcloud, capability providers will be implemented in languages other than Rust, and messages will be sent via other transports such as NATS. We wish to use a common interface definition language (IDL) for all APIs, regardless of transport or language. A common definition language could be the basis for common tooling - for generating documentation, SDKs, code stubs for senders and receivers, test tools, and administrative tools. These kinds of interfaces and targets are beyond the current scope of WIDL.

We have several of the same goals for interface specification as we did originally for WIDL: language-agnostic, transport-agnostic, and serialization-agnostic. Importantly, we do not wish to create yet-another-IDL. A custom IDL carries with it a high burden for maintenance of the spec and the tooling, whereas an existing spec language provides greater upside and opportunities to leverage tools and automation arising from a larger community.

Although it is important to have a well-specified IDL, it is even more important to have a well-specified semantic model. The semantic model is the representation of an interface after parsing the IDL file, and removing whitespace and comments. The semantic model has entities such as "Service", "Method", "Field", and "Parameter". (Some might call this model an AST). The semantic model should be independent of the syntax of the IDL, and it should be possible for multiple sufficiently fjlexible IDLs (such as Smithy and Protobuf, for example) to define interfaces that are converted to the same semantic model. The semantic model should have a standard representation in JSON, and should be readable or writable to/from any programming language, and used as the basis for all tooling (other than the IDL parser). The model could be used for runtime reflection, so you could query whether an object supports a particular method, and, it should be possible to introduce a handshake protocol where both sides of a connection confirm that they are using the same version of an interface. The latter can be done in part by computing a hash over a normalized representation of the semantic model.

WIDL and its current set of code generators were created to address a specific set of needs, but the context in which the tooling exists continues to evolve. It is reasonable to expect new requirements will come up, including, for example:
- Runtime reflection
- Interface versions
- Web Assembly support for multi-valued return types
- Exceptions or error handling
- Async functions (particularly in Capability providers)
- Streaming APIs

These might not be the exact next six extensions needed for WIDL, but it is certain that ability to evolve is a key requirement. Some of these requirements are more about code generation than IDL. Ideally, an IDL would not need to be changed at all to support features like these. Using Smithy, for example, a trait (a kind of annotation) could be used to list the types of errors or exceptions that a function may return. Using Smithy, the design effort required to add error handling support is at the level of complexity of naming: what to call the trait and its parameters. With WIDL, the same naming decisions would be required, but the level of complexity of the capability is far higher, because the decisions to be made also include possible WIDL syntax changes, ensuring the syntax is unambiguous for the parser, deciding whether a declaration should require a semicolon or newline to terminate, etc. Because WIDL was created from the ground-up, additive capabilities are not just features - some rise to the level of complexity of language design. In contrast, traits are one aspect of Smithy's design for api evolution that is intended to enable a wider range of changes that aren't breaking changes.
  
Although WIDL has meet wasmcloud's needs in the past, we believe there is an opportunity to use an IDL that is more flexible for meeting future needs; has lower ongoing development and maintenance costs due to its maturity; and, more importantly, has greater leverage and tooling potential due to its larger community of developers and users.

## Options considered

When considering these options, important criteria include:

- State/quality of the software now: At a minimum, it shouldn't have major blockers. How good is the code quality, test coverage, and documentation? How well does its feature set reduce the gap toward what we want to build? 
  
- Flexibility: Was it designed to be flexible? How likely is it to be able to adapt as we continue to learn and iterate?
  
- Vision alignment: Is the vision clearly stated and in alignment with where we think we're going? This is important because, as the software inevitably evolves and changes, closer alignment means that the changes are more likely to support or possibly accelerate our own efforts, and less likely to cause friction.
  
- Number of contributors, size of community, breadth of ecosystem: These are indicators that it's likely to have some forseeable period of activity, maintenance, and ongoing support; and that we'll find other users with common interests who may become contributors or collaborators in our projects, or visa-versa. A diverse community is also a good indicator for the 'flexibility' criteria, as it demonstrates that it does meet the needs of users with diverse needs.

Non-criteria - that wouldn't sway a decision: 
- minor bugs, or a few minor features. These we could fix or change with a small amount of effort.

### Smithy

From Smithy's [homepage](https://awslabs.github.io/smithy/index.html):

> Smithy is designed to work with any programming language, describe services running in any environment, and work with any kind of transport or serialization format.

Amazon started the Smithy project in 2018 and uses it today to model 250+ AWS services, and generate SDKs and code for a large number of languages on multiple platforms. It was created to solve exactly the problems we have now. It already has orders of magnitude more developers and users than WIDL has. It recently launched 1.0, and it's hard to tell how much use it's had outside the realm of Amazon-related APIs. (Users of Amazon API gateway, and other Amazon apis and sdks use it indirectly. These don't count as smithy users if they only use generated SDKs, but they contribute to the importance of Smithy's stability, maintenance, and support). Its [main github repo](https://github.com/awslabs/smithy) has several maintainers and is active.

### Extending WIDL

We considered extending WIDL, but that approach has some significant limitations. Over the last several weeks, I have had several conversations with WIDL's developer, and have learned that there are ambitious plans for WIDL, and that it's goals are more in alignment with Smithy's than it appears from the documentation. 

#### WIDL is not well specified

Until [a few weeks ago](https://github.com/jsoverson/widl-wip/tree/master/widl-spec) there was no formal grammar specification for WIDL. (There is a partial spec published in April on the widl website). It was originally based on graphql, but some features have been removed and others added. The lack of a spec creates friction for developers and tool authors, who have to discover the spec by reading source code or trial and error. A more significant issue is that the lack of a formal language spec means you never know when it's "done", and the criteria for altering the language is uncertain.

#### There is no specification for a semantic model

It was the original intention of WIDL that any tool requiring such a model would perform a parsing step first.

#### Annotations are not strictly typed

Annotations are an important part of schema definitions, and are the primary mechanism used to provide metadata needed for code generation and semantic understanding of the schema and IDL file. Examples of annotations might include:

- `@capability(capabilityId: "wasmcloud:httpserver")` - indicates that the operation is part of the httpserver capability contract
- `@length(min:1, max:255)` indicates that a string must be non-empty, and can have no more than 255 characters.
- `@sensitive` - indicates a field is "sensitive", such as a field used to store a password or credit card number. This annotation could be used to signify that loggers code should never write the field to debug logs.

Although WIDL does support annotations, they are not strictly typed, so they cannot be validated at compile time. Smithy, on the other hand, requires that annotations (traits) and their parameters are declared. Each trait parameter is fully specified, including whether each field (such as the min and max in `@length`, above) is required or optional, so errors can be caught at compile-time, not slip through to cause hard-to-debug runtime errors. \[edit: I have learned through talking with Phil that there is a language feature called "directives" that has support for strict typing of annotations - but it's undocumented (not even findable with google), and none of the wasmcloud code generators use it. So it's difficult to evaluate at this time.\]

#### Roles don't fully express directionality

One characteristic of an interface declaration is directionality - whether a message can be received by an actor or provider. It is useful to be able to express directionality in the IDL because it further documents the interface and it can affect code generation. In WIDL, `role`s were intended to accomplish this, but the role definition contains the entire interface, so an interface that could be implemented either by an actor or a provider would require duplicating the interface definition under the second role. In Smithy, directionality can be indicated by a trait `@actorReceiver` or `@providerReceier`, and an interface that can be handled by either can be declared with both traits.

### GraphQL, JSON Schema, OpenAPI

These formats all have excellent tooling and support for multiple target languages, but have significant barriers for our use:

- GraphQL and JSON Schema do not support the rich type system of wasm, having only one type Number, rather than more specific integer types.

- OpenAPI is tightly tied to REST and HTTP, thus fails our requirement to be transport-independent.

### Protobuf, Avro, CapnProto, FlatBuffers

These formats have type systems that are rich enough for Web Assembly, but they are associated with specific serialization formats. We considered each of these in the context of adopting just the IDL, and writing new tooling for code generation. 

Because none of these were written to provide a parser as a distinct component separate from code generation, it would be a non-trivial task to use them to create a toolset. The FlatBuffers and CapnProto parsers are implemented in C, and Avro's tooling is in Java, so building browser-based tooling would be additional effort.

We spent some time trying to use protobuf to model WIDL interfaces and found that a subset of protobuf could come pretty close to describing most of the current actor interfaces specified in WIDL today, but some minor changes would still be required. Also, there are several features of protobuf that are awkward to use, and the requirement to use `option` for extensions and annotations feels both inflexible and verbose.

Using any of these IDLs would be taking it in a direction divergent from its original design goals. When comparing to Smithy on the basis of clean syntax, available tooling in multiple languages, and ease of building new tooling in multiple languages, Smithy comes out ahead. Importantly, wasmcloud's goals are more aligned with Smithy's than any of the alternatives we evaluated.

## Smithy project links

[Home page](https://awslabs.github.io/smithy/index.html)

Smithy's [projects and implementations](https://awslabs.github.io/smithy/implementations.html) include:

- Specifications for the [data model](https://awslabs.github.io/smithy/1.0/spec/index.html), [IDL](https://awslabs.github.io/smithy/1.0/spec/core/idl.html), [ABNF grammar](https://awslabs.github.io/smithy/1.0/spec/core/idl.html#smithy-idl-abnf), and [JSON AST](https://awslabs.github.io/smithy/1.0/spec/core/json-ast.html)

- [Atelier](https://github.com/johnstonskj/rust-atelier) a Rust SDK and various tools.
- [java api](https://awslabs.github.io/smithy/javadoc/1.8.0/),
- [Visual Studio Code Plugin](https://github.com/awslabs/smithy-vscode)
- [IntelliJ plugin](https://github.com/awslabs/smithy-intellij)
- [LSP](https://github.com/awslabs/smithy-language-server) - Language server protocol for the Smithy IDL

- There are code generators for Typescript, Go, and Rust. These are fairly new and it isn't clear how useful they are yet. The code generators are all written in java or kotlin.

- Even though Smithy is protocol-agnostic, there are [MQTT protocol bindings](https://awslabs.github.io/smithy/1.0/spec/mqtt.html), for a pub-sub interface that may be useful for wasmcloud-embedded!

### This is a breaking change and will cause disruption

Existing WIDL-based tooling will be deprecated. There are no plans to change the binary over-the-wire messaging format, so actors built with WIDL tooling will still work for a period of time.

Note: With the wasmcloud-OTP change, the existing capability provider protocol will change, and all capability providers will need to be updated. So if Smithy were rolled out at the same time as wasmcloud-OTP, then the only incremental breaking change would be for actors.
  
New feature development will use Smithy-based tooling, so at some point in the future, use of the Smithy tooling will become a requirement. 

Although the wasmcloud community is growing, we do not believe it would be practical to try to maintain two parallel independent IDL efforts - i.e., to continue maintaining both WIDL and Smithy while attempting to provide feature parity. There is much greater value to be achieved by consolidating efforts on tooling, and spending less effort on IDL. Putting IDL design and maintenance behind us is one of the key motivations for moving to Smithy.

To mitigate the disruption and help ease migration, we should
 - create documentation, how-to guides, and sample code
 - convert existing actor-interfaces to Smithy
 - consider creating automated tools to convert WIDL files to Smithy

All WIDL files that I've seen are small enough that they can be converted by hand in a few minutes, and there are command-line lint tools to verify that the Smithy syntax is correct, so it's probably not worth writing automated conversion tools.

### We have no influence on the Smithy roadmap

Amazon has stated that they hope Smithy will be used by others for use cases beyond Amazon APIs. The 1.0 release was recent (May '21) and as far as we know, there hasn't been much time for a community to develop outside Amazon.

There are Smithy sdks and tools in typescript, go, and rust, but they are not at equal levels of maturity. At the moment, it appears that the majority of Amazon's efforts are going into the java-based tooling: code generators for typescript, go, and rust are implemented in java.

All indications are that the initial goals of Smithy are in close alignment with ours, and Smithy is a better fit than all other IDLs we evaluated. This is a good sign that they are likely to go in the right direction. The level of maturity of the tools is not a blocker. The tools are usable now, and already have documentation, maturity and capabilities beyond WIDL's today, and they seem to be moving forward at a faster pace.

We hope to see a growing community around Smithy, inside and outside Amazon, and we would like to be a contributing part of that community.

As with any open source software (Smithy is licensed under Apache-2), if at any time Amazon decides to take a direction that is incompatible with our needs, we (and others) can fork the code and use that. If that happens, hopefully by then the community outside Amazon will have some momentum of its own.

# Appendix - Examples

## Smithy definition of `wasmcloud:httpserver` interface

[WIDL](https://github.com/wasmCloud/actor-interfaces/blob/main/http-server/httpserver.widl)

```text
// Smithy IDL for a simple http server
namespace org.wasmcloud.example.httpServer

use wasmcloud.core#actorReceiver
use wasmcloud.core#CapabilityContractId
use wasmcloud.core#U32

/// this trait indicates that the actor handles the messages in the service
@actorReceiver
/// this trait indicates that the service conforms to the httpserver capability contract
@capability(contractId: "wasmcloud:httpserver")
service HttpServer {
  version: "0.1",
  operations: [ HandleRequest ]
}

/// HttpRequest contains data sent to actor about the http request
structure HttpRequest {
  @required
  method: String,
  @required
  path: String,
  @required
  queryString: String,
  @required
  header: Headers,
  @required
  body: Blob,
}

/// HttpResponse contains the actor's response to return to the http client
structure HttpResponse {
  /// statusCode should be 200 if the request was correctly handled
  @required
  statusCode: U32,
  @required
  status: String,
  @required
  header: Headers,
  @required
  body: Blob,
}

operation HandleRequest {
  input: HttpRequest,
  output: HttpResponse,
}

/// Headers is a list of http headers
map Headers {
  key: String,
  value: String,
}
```

### Comments on the sample above

This is slightly more verbose than WIDL. 
- Fields in WIDL are required by default, and in Smithy, as in protobuf 3, fields are optional by default, so each field above has a `@required` trait.
- Maps and lists are slightly more verbose because they need to be declared separately, rather than inline as `map<string,string>` or `[string]`. The extra verbosity ensures the ability to declare traits for the key, value, and member types. For example, the trait `@length(min:1)` could be added to the header key type to indicate that empty keys are not allowed. 
- The `U32` import is required because Smithy's native integer types are all signed. The `@unsignedType` trait was created to signal to code generators to generate unsigned types in rust or go. Following is a snippet from wasmcloud.core.smithy:
```text
/// The unsignedInt trait indicates that one of the number types is unsigned
@trait(selector: "long,integer,short,byte")
@range(min:0)
structure unsignedInt { }

// unsigned 64-bit int
@unsignedInt
long U64

// unsigned 32-bit int
@unsignedInt
integer U32

// unsigned 16-bit int
@unsignedInt
short U16

// unsigned byte
@unsignedInt
byte U8
```

**Comment by alsuren** [comment]
Worth mentioning some things about the old code generator. I suspect that other capability providers have the same issue, due to how the code is generated, but I haven't looked too hard:

The kv store methods take String rather than &str, so the caller needs to do a bunch of cloning.

The kv store methods return `Result<_, Box<dyn std::error::Error + Send + Sync>>`. This does not implement `std::error::Error`, because the blanket impl is for `Box<dyn std::error::Error + Send + Sync + 'static>`, so you can't use ? to convert into an `anyhow::Error` (hence the `.map_err(|e| anyhow!(e))?` dance).

[Example of the above points](https://github.com/wasmCloud/examples/pull/53/files#diff-b14d0ddc60ee65be271725a4f208debecba784ec4dcc9abb39b62782a21f101cR100-R108)

```rust
fn get_todo(url: &str) -> Result<Todo> {
    let todo_str = kv::default()
        .get(url.to_string())
        .map_err(|e| anyhow!(e))?
        .value;
    let todo = serde_json::from_str(&todo_str)?;

    Ok(todo)
}
```

The error type is not an enum that we can get hold of, so we can't cleanly match on "NOT FOUND" errors coming from the kv store and respond appropriately. This means that we ended up hacking things for our "get" endpoints to catch all errors and pretend they are 404s. This feels a little dirty: 


[Example](https://github.com/wasmCloud/examples/pull/53/files#diff-b14d0ddc60ee65be271725a4f208debecba784ec4dcc9abb39b62782a21f101cR133-R165)

```rust
    match (msg.method.as_ref(), trimmed_path) {
        ("GET", url) => get_todo(url)
            .map(|todo| Response::json(todo, 200, "OK"))
            .or_else(|_| Ok(Response::not_found())),
```
...
```rust

    }
    .or_else(|e| {
        Ok(Response::internal_server_error(&format!(
            "Something went wrong: {:?}",
            e
        )))
    })
```

Hopefully we can look out for them when we make the switch to smithy.

**Comment by stevelr** [comment]
Hi David,
You are right that this is a code generator issue (rather than strictly a widl vs smithy issue). 

These are some of the things I wanted to address in the code generator. The new rust code generator addresses both the issues you brought up:
- using references for fn parameters, to reduce the need for copying, and
- error return is a Public enum

**Comment by autodidaddict** [comment]
As things like directionality (which entity is handling which operations) are super important to me, I thought I would show an example of what it might look like to build out the `wasmcloud:messaging` interface. This interface has 2 functions that are called by the actor and 1 function that is _handled_ by the actor. 

Making the division of responsibilities clear to both the developer reading the specification _and_ anyone reading/consuming the generated code is of paramount importance to me. I think the following illustrates directionality in a way that we've never been able to do with `widl` _roles_:

```
@actorReceiver
@capability(contractId: "wasmcloud:messaging")
service MessagingActor {
  version: "0.1",
  operations: [ HandleMessage ]
}

@providerReceiver
@capability(contractId: "wasmcloud:messaging")
service MessagingProvider {
  version: "0.1",
  operations: [Publish, Request]
}

...
```

The only thing I struggle with is the fact that since we have 2 different declarations for services, we have two different versions of the service contracts, whereas there is only one conceptual version for the aggregate contract that is named `wasmcloud:messaging`. While we could put in generator rules that requires all of the services implementing the same _contract ID_ must have the same version number, it still feels a little bit awkward to me and actually reminds me of widl's Roles a little.

**Comment by stevelr** [comment]
I completely agree that it's important to make the division of responsibilities clear.

Since we're kind of new to this, I'd like to do some experimentation to try some different approaches.

On how to indicate directionality, I've thought of three ways to do it:
1. `@actorReceiver` and `@providerReceiver` are individual traits.
2. we make them tags, as in `@tags["actorReceiver", "providerReceiver"]
3. make them members of a wasmbus property that contains all wasmcloud-protocol-related properties
```
@wasmbus( contractId: "wasmbus:httpserver", actorReceiver: true, ... )
```

To keep this post short, I won't go into all the tradeoffs between these approaches here, but one thing they have in common is they provide explicit documentation on the directionality and responsibilities of the implementor.

On the subject of whether a service should contain all operations in both directions, I think there are two main approaches:

1. The namespace (e.g., "org.wasmcloud.interface.httpserver" is the thing that ties everything together, and there would be one namespace per smithy file. A namespace may encompass multiple services, operations, structures, and other definitions. One advantage of having services be uni-diretional is that that they map to "traits" in Rust, or Interfaces in Go/Java. It communicates to the implementor (such as the KV store provider) that they must implement all the methods of the service or it isn't complete, and if code generator creates the traits, the provider will get a compile-time error if they didn't implement one of the methods.

2. Service incorporates all operations related to the capability contract. To provide separation of responsibility, I think we're likely to put each capbility into its own smithy model file, which means there will be a 1:1 correlation between a service and a namespace.
To signal to the code generator that a set of operations belong together in a trait (to get the compile-time enforcement), we'd have to define an additional structure somehow in the same namespace that lists the trait/initerface name and the list of operations. I haven't explored what this kind of declaration would look like, but my gut says it would be way more verbose/complicated than using a service for that purpose.

If you want to programmatically query a model to get all operations related to a capability, both approaches can do that.

**Comment by jsoverson** [comment]
Before I add anything — this RFC, along with the OTP rewrite, bring very promising ideas to wasmcloud. Nothing I say should be taken as "don't do this." I only want to add perspective for future decisions.

The cost of changes like this and the OTP rewrite is very high. I've convinced multiple teams to build off wasmcloud and I've acted like a proxy to iron out instability and ensure their success. I've monkey-patched broken providers, out-of-sync interfaces, and built developer tools. My purpose was to get people back to working ASAP whenever there was a hiccup. That's not sustainable with such sweeping changes.

I apologize if a lot of that work wasn't in the open. I had been sitting on some posts and tools, waiting for things to be stable enough so that they wouldn't be a maintenance headache. I would be surprised if I was the only one in the same situation though. Wasmcloud is promising and the team has done well building a community.

Again, please don't take this as a "don't do this," at least based on this comment alone. I've already decoupled everything to insulate from future changes. I hope to retain support at the lattice level but comments like `actors built with WIDL tooling will still work for a period of time` leave me wary still.

It will be critical to wasmcloud's success to define its surface area going forward so people like me don't make assumptions on what is a public interface.

**Comment by autodidaddict** [comment]
Closing this RFC as work to convert things to smithy-based generation has already begun. Existing codegen will still work, but providers and actor interfaces written for the new OTP runtime will use smithy-based generation and the `weld` tooling.
