### ISSUE TITLE
[FEATURE] Sign release artifacts

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#2062]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

Our current binaries and containers for wasmCloud and wash-cli are released via a "signed" tag in the repository, but the artifacts themselves are not signed.

### Describe the solution you'd like

It would be great to use a tool like sigstore [cosign](https://github.com/sigstore/cosign) to sign our images and binaries, or even use [wolfi](https://github.com/wolfi-dev) as a base image for wasmCloud.

### Describe alternatives you've considered

Please suggest alternatives as this isn't personally my area of expertise and I attempted to find the industry standard 😄

**Comment by joonas** [comment]
I think we should give [GitHub's recent announcement of Artifact Attestations support](https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/) a careful read and pull in a bunch of the tooling featured there.

**Comment by brooksmtownsend** [comment]
We now have wolfi base images for our release artifacts 👍🏻 #2074
