### ISSUE TITLE
[FEATURE] wash push should emit the sha256 digest of a component or a provider

### ISSUE THREAD

**Issue by protochron** [wasmCloud/wasmCloud#2076]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

wash does not currently emit the sha256 digest of the published artifact, which means you have the pull the artifact if you want to do anything with that value.

### Describe the solution you'd like

wash push should output the sha256 digest after pushing an artifact, just like the Docker CLI and other command line tools that manage OCI artifacts. wash inspect on an OCI repository should also include the digest in the JSON output,and on the plain text output.

**Comment by joonas** [comment]
I'd love to see this output follow something to the effect of what `docker push` gives you:

```shell
$ docker push ttl.sh/<a-random-uuid>:1h
The push refers to repository [ttl.sh/<a-random-uuid>]
437a471d7470: Pushed 
30a65065753d: Pushed 
3eebec8c8185: Pushed 
fefbbfcfd1d5: Pushed 
6e5a1bc9659a: Pushed 
1h: digest: sha256:433fcc333da279a51ee7277a064016fcccdc8747e01053f9025ff00b970d0d53 size: 1374
```

Specifically the bit at the bottom that outputs:
```
<tag-name>: digest: <digest-value> size: <size>
```
