### ISSUE TITLE
[FEATURE] Add standalone validation crate for verifying wadm manifests

### ISSUE THREAD

**Issue by lachieh** [wasmCloud/wasmCloud#2090]
Validating wadm manifests is currently handled by a simple JSON schema check, but the DX around this (particularly the errors surfaced) leaves a lot to be desired. We also will need to be running validation checks in a number of projects including wash, wadm and perhaps a Language Server. We should create a standalone crate that contains this logic so that it can be used in many of these places.

**Comment by brooksmtownsend** [comment]
(psst https://github.com/wasmCloud/wadm/pull/274 is working towards this)

**Comment by vados-cosmonic** [comment]
This is done -- [`wadm-types`](https://crates.io/crates/wadm-types) is the standalone crate here
