### ISSUE TITLE
[FEATURE] Display max instances count in `wash get inventory` and washboard output

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#2095]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [X] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

In order to know the scale of my components, I need to put the inventory out in JSON output mode.

### Describe the solution you'd like

I would love to see the concurrency that's set for a component in the host inventory output

For example:
```shell
➜ wash get inventory


  Host Inventory (NALS3CXBO7IK57655LUN4NIPA3BLCX5KCXYV3WE3G7O5LPC6KK5COTKZ)

  hostcore.os          linux
  hostcore.arch        x86_64
  hostcore.osfamily    unix

  Component ID         Name                   Image Reference                                   Max
  hello                http-hello-world       wasmcloud.azurecr.io/http-hello-world:0.1.0       999

  Provider ID          Name                   Image Reference
  http-server          http-server-provider   ghcr.io/wasmcloud/http-server:0.20.1
```

### Additional context

I actually wouldn't mind getting rid of the `Name` now that we have a unique ID that generally covers it, especially since claims are no longer required metadata.

**Comment by Aditya1404Sal** [comment]
I think I know how to add this feature, can I have this issue assigned please? Thank you!

**Comment by Aditya1404Sal** [comment]
![Screenshot from 2024-06-06 12-20-19](https://github.com/wasmCloud/wasmCloud/assets/91340059/ff3dc189-0299-49f3-802c-6ddbe8a66b0d)
So the plan is to add a new column called "Max count" which will show max instances, then i'll reposition "Name" with "ID" and get rid of "Name"

**Comment by Aditya1404Sal** [comment]
would it be alright if we got rid of `Name` from the Provider table too ? just so everything appears uniform
