### ISSUE TITLE
[BUG] Control topic `host.stop.<id>` needs empty payload

### ISSUE THREAD

**Issue by lachieh** [wasmCloud/wasmCloud#2113]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

Not really a bug per se but it'd probably be nice to adjust this behavior.

The `host.stop.<id>` topic for the control api requires an empty payload to work, but it doesn't really need one.

### Steps to reproduce

```
➜ nats request "wasmbus.ctl.v1.default.host.stop.NAJPHEQ347GXSFPJXOW7YOINDT6L33HEORKSY2E6CWSHQUTQJRCGKHP2" "" --raw | jq
{
  "success": false,
  "message": "failed to deserialize stop command"
}

➜ nats request "wasmbus.ctl.v1.default.host.stop.NAJPHEQ347GXSFPJXOW7YOINDT6L33HEORKSY2E6CWSHQUTQJRCGKHP2" "{}" --raw | jq
{
  "success": true,
  "message": ""
}
```

### Expected behavior

The first example above would ideally pass

### Environment

wasmCloud 1.0

**Comment by brooksmtownsend** [comment]
Yeah this is weird, we should just accept any payload if we don't need any parameters to carry out the request

**Comment by lachieh** [comment]
Didn't investigate if this happens with other commands, but it is fine with the queries that don't need parameters

**Comment by brooksmtownsend** [comment]
Ah so technically we're expecting a JSON deserializable object:
```rust
/// A command sent to request that the given host purge and stop
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct StopHostCommand {
    /// The ID of the target host
    #[serde(default)]
    pub host_id: String,
    /// An optional timeout, in seconds
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeout: Option<u64>,
}
// ...
        let StopHostCommand { timeout, .. } = serde_json::from_slice(payload.as_ref())
            .context("failed to deserialize stop command")?;
```

**Comment by thomastaylor312** [comment]
In wadm I had to just check if the body had no bytes and then default it
