### ISSUE TITLE
[BUG] Installing wasmCloud CLI on Intel-based Mac installs arm64 version of `wadm`

### ISSUE THREAD

**Issue by ChrisWhealy** [wasmCloud/wasmCloud#2134]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

```
wash up -d
>>> ⡋⠁  Starting wadm ...
🟨 Couldn't start wadm: Bad CPU type in executable (os error 86)

🛁 wash up completed successfully
🕸  NATS is running in the background at http://127.0.0.1:4222
📜 Logs for the host are being written to /Users/chris/.wash/downloads/wasmcloud.log

⬇️  To stop wasmCloud, run "wash down"
```

The executable file type for `wash` is correct

```
→  file $(which wash)
/Users/chris/.cargo/bin/wash: Mach-O 64-bit executable x86_64
```

But for `wadm` is

```
╰→  file ~/.wash/downloads/wadm
/Users/chris/.wash/downloads/wadm: Mach-O 64-bit executable arm64
```

### Steps to reproduce

I'm running MacOs Sonoma 14.4.1 on an Intel-based 2019 MacBook Pro

After installing wasmCloud using either `brew install wasmCloud/wasmCloud/wash` or `cargo install wash-cli`, the `wash up -d` command only partly succeeds.

As a precaution, I cleared the `cargo` cache, but did not change the outcome

### Expected behavior

I expected `wadm` to start when `wash up -d` was run

### Environment

- OS: macOs 14.4.1
- Shell `zsh`
- wasmcloud Version 0.18.2

### Screenshots / Logs / Additional context

After setting `RUST_LOG=debug` and `CARGO_HTTP_DEBUG=true` I ran `cargo install wash-cli`

[wash_install.log](https://github.com/wasmCloud/wasmCloud/files/15321362/wash_install.log)

**Comment by brooksmtownsend** [comment]
I tried to reproduce this in a Github action, and it did reproduce exactly. The NATS and wasmcloud binaries are correct, but not wadm https://github.com/brooksmtownsend/wasmCloud/actions/runs/9095919965/job/25000188542 😬 Still digging on the fix...

For anyone trying to work around this, you can simply download the correct architecture (amd64) from the wadm release https://github.com/wasmCloud/wadm/releases/tag/v0.11.1 and place it in `~/.wash/downloads/wadm`.

**Comment by brooksmtownsend** [comment]
Oh yay, GitHub swapped out their architecture by default to arm64 😮

**Comment by brooksmtownsend** [comment]
`v0.11.0` and `v0.11.2` will work here 👍🏻
