### ISSUE TITLE
[FEATURE] Add component metadata to inventory query

### ISSUE THREAD

**Issue by lachieh** [wasmCloud/wasmCloud#2138]
### Affected project(s)

- [X] wasmCloud host

### Describe the solution you'd like

It'd be neat to have the host determine the interfaces of the components (providers might be a little harder) and reply with this data in the host inventory query.

**Comment by brooksmtownsend** [comment]
I worry about this one, mostly because this ends up significantly increasing the size of the host inventory payload and we'll probably approach the 1MB NATS payload limit faster.

I do understand the need for this data though, is the ideal to have the original WIT document or moreso just the imports and exports? Or is it links?

**Comment by lachieh** [comment]
It's mostly to be able to display the imports/exports on the washboard and to be able to create links with some level of validation, but the wit may be useful. Maybe a secondary query for allthethings.gif could work?

**Comment by brooksmtownsend** [comment]
Ah, maybe this is a query for the component specification? for example:
```
➜ nats kv get LATTICEDATA_default COMPONENT_rust_http_kv-counter --raw | jq
{
  "url": "",
  "links": [
    {
      "source_id": "rust_http_kv-counter",
      "target": "rust_http_kv-kvredis",
      "name": "default",
      "wit_namespace": "wasi",
      "wit_package": "keyvalue",
      "interfaces": [
        "atomics",
        "eventual"
      ],
      "source_config": [],
      "target_config": [
        "rust_http_kv-redis_url"
      ]
    }
  ]
}
```

**Comment by lachieh** [comment]
Yeah that's the juice. Are you thinking it would get just the basic data? or more of a "give me all the data about this component"

**Comment by thomastaylor312** [comment]
(Or if we don't have all the data on the start events, emit a separate `ComponentMetadataUpdated` event

**Comment by lachieh** [comment]
Listening for events to update a cache is fine for updates, but I'd still need a way to query for the initial data.

I think a component metadata query will cover the 90%. It would need:

* name
* provider/component id
* hosts (instances)
* max instances
* image ref
* annotations
* interfaces/imports/exports

**Comment by lachieh** [comment]
no
