### ISSUE TITLE
[FEATURE] Enable custom templates

### ISSUE THREAD

**Issue by esoterra** [wasmCloud/wasmCloud#2191]
### Affected project(s)

- [X] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

I'm frustrated when I go to create a new component and there isn't a template for what I want.

### Describe the solution you'd like

I would like to be able to make my own templates in my project's repo or in other repos that can be used instead of the bundled ones.

### Describe alternatives you've considered

I considered adding the specific templates I need to WasmCloud, but I'm not yet sure exactly what they'll be or if WasmCloud will be interested in including them.

### Additional context

My specific current template needs are for a component template with
* a `build.rs` that calls `wit_deps::lock_sync()`
* a `wit/deps` dir containing a blanket ignore `*` file
* any other setup needed to make cargo workspaces work

I suspect our needs will evolve in ways that where giving us flexibility to make our own templates will be the best approach.

**Comment by thomastaylor312** [comment]
So it is a bit hard to find I'll admit, but you can do this now with specific flags set on `wash new component` (https://wasmcloud.com/docs/cli/new). You can use the `--path` flag or `--git` flag to specify a repo manually or you can use the `--favorites` flag to point to a toml file with a list of all your templates (you can see an example of that file [here](https://github.com/wasmCloud/wasmCloud/blob/main/crates/wash-lib/src/generate/favorites.toml)).

It would probably be nice to add some more docs around favorites and have an environment variable you can set for that flag so it is easier to configure once

**Comment by esoterra** [comment]
Thanks, I've filed https://github.com/wasmCloud/wasmcloud.com/issues/443 as a follow up on the docs side
