### ISSUE TITLE
[BUG] Can't deploy application or retrieve existing applications in WasmCloud

### ISSUE THREAD

**Issue by hasinthajanaka** [wasmCloud/wasmCloud#2204]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

I am trying to deploy a new application in the wasmcloud using the following command

`wash app deploy wadm.yaml`

It gives the following error,

`Error making model request: no responders: no responders`

The same error appears when I try to list down the existing application.

```
wash app list
Error making model request: no responders: no responders
```
What can be the reason for this

### Steps to reproduce

`wash app deploy wadm.yaml`

or

`wash app list`

### Expected behavior

when I deploy new application should be show the deploying logs in the terminal

or

list down existing  application

### Environment

- OS: [e.g. Linux, MacOS]
- Shell [e.g. bash, zsh, powershell]
- wasmcloud Version [e.g. 0.81.0]

### Screenshots / Logs / Additional context

wash 0.28.1

NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by thomastaylor312** [comment]
Hi there @hasinthajanaka! So generally that `no responders` error means that there isn't a NATS server running anywhere. Have you by chance run `wash up`?

**Comment by vados-cosmonic** [comment]
Hey @hasinthajanaka since a `no responders` error is usually indicative of a host not running (i.e. nothing to respond to the request) -- I'm going to close out this issue! Please comment if this wasn't your issue!

**Comment by crimeminister** [comment]
FWIW I am seeing this same issue on NixOS. I am running wasmCloud via `$ wash up --nats-websocket-port 8181 --disable-wadm -d`. I can confirm that NATS is available using `$ nats server check connection` which reports:
```
OK Connection OK:connected to nats://127.0.0.1:4222 in 913.441µs ...
```
but any attempt to run:
```
$ wash app deploy wadm.yaml
```
or
```
$ wash app list
```
returns the same issue, even when I specify the `--ctl-host` and `--ctl-port` flags:
```
$ wash app list --ctl-host=127.0.0.1 --ctl-port=4222
```

**Comment by vados-cosmonic** [comment]
Hey @crimeminister before I re-open this would you mind providing some more information?

Just some stuff I'm thinking about:

- Do you get the exact same error message? 
- What do the host logs look like (try running without `-d`)? 
- Can you start a regular component (ex. `wash start component ghcr.io/wasmcloud/components/http-hello-world-rust:0.1.0 hello-world `)

Also, please note that is you use `--disable-wadm` then [Wasmcloud Application Deployment Manager (wadm)](https://github.com/wasmCloud/wadm) won't run -- and that's a pretty key point in deploying apps (i.e. using `wash app deploy`) -- the manifests we try to deploy are wadm manifests. Do you have `wadm` running some other way?

**Comment by crimeminister** [comment]
> Hey @crimeminister before I re-open this would you mind providing some more information?

Sure thing!

> Just some stuff I'm thinking about:
> 
>     * Do you get the exact same error message?

Yes, I get the exact same message:

```
Error making model request: no responders: no responders
```

>     * What do the host logs look like (try running without `-d`)?

```
$ wash up --nats-websocket-port 8181
>>> ⠍⠀  Starting wadm ...                                                                                                                                                                
🟨 Couldn't start wadm: No such file or directory (os error 2)
🏃 Running in interactive mode.
🎛️   If you enabled --nats-websocket-port, start the dashboard by executing `wash ui`
🚪 Press `CTRL+c` at any time to exit
2024-07-04T18:28:05.443781Z  INFO async_nats::options: event: connected
2024-07-04T18:28:05.443885Z  INFO async_nats::options: event: connected
2024-07-04T18:28:05.443892Z  INFO async_nats::options: event: connected
2024-07-04T18:28:05.444424Z  INFO new:create_lattice_metadata_bucket{bucket="LATTICEDATA_default"}: wasmcloud_host::wasmbus: lattice metadata bucket LATTICEDATA_default already exists. Skipping creation.
2024-07-04T18:28:05.444988Z  INFO new: wasmcloud_host::wasmbus: wasmCloud host started host_id="NDN7E6T7KRQBMIHGMU4GY7JX3XKNXLT7336FWRRWF77YOWGPASMGIR3H"
```

NB: I disabled wadm in earlier testing because of the error message above ("Couldn't start wadm") assuming that the error was occurring in communication between the CLI and the running wasmCloud service; perhaps that's a faulty assumption?
 
>     * Can you start a regular component (ex. `wash start component ghcr.io/wasmcloud/components/http-hello-world-rust:0.1.0 hello-world `)

Running this command gives:

```
error: unrecognized subcommand 'component'
```

Running:

```
$ wash start --help
```

lists the available subcommands as: `actor`, `provider`, `help`. I assume this is a version discrepancy? My wash-cli version is `wash 0.24.0`.

When I run the command:

```
$ wash start actor ghcr.io/wasmcloud/components/http-hello-world-rust:0.1.0
```

I get the output:

```
Actor [<snip>] (ref: [ghcr.io/wasmcloud/components/http-hello-world-rust:0.1.0]) started on host [<snip>]
```

> Also, please note that is you use `--disable-wadm` then [Wasmcloud Application Deployment Manager (wadm)](https://github.com/wasmCloud/wadm) won't run -- and that's a pretty key point in deploying apps (i.e. using `wash app deploy`) -- the manifests we try to deploy are wadm manifests. Do you have `wadm` running some other way?

I don't have wadm running via other means, I'll have to dig into the cause of the inability for `wash up` to pull and execute `wadm` automagically, as I understand it's supposed to do. Possibly it's a system packaging issue.

I hope that's helpful, please let me know if there's any other information I can provide.

**Comment by vados-cosmonic** [comment]
Hey thanks for the detail @crimeminister ! 

The first that sticks out to me is probably the version of `wash` -- would you mind updating to a newer version? Right now v0.29.2 is the latest -- I personally install it with cargo ecosystem (`cargo install wash-cli`).

We've made a *bunch* of changes since v0.24, and a bunch of them are UX changes (IIRC stuff like trying to make sure when files are missing we print the path we were looking for, and removing "actor" from everywhere).

**Comment by crimeminister** [comment]
> The first that sticks out to me is probably the version of `wash` -- would you mind updating to a newer version? Right now v0.29.2 is the latest -- I personally install it with cargo ecosystem (`cargo install wash-cli`).

I have updated to `0.29.2` using `cargo install wash-cli` and also by installing an updated system package. In both cases I see the same error as before:

```
no responders: no responders
``` 

On the upside, some of the niggling issues from before are cleared up, e.g. the inability to install `wadm`.

> We've made a _bunch_ of changes since v0.24, and a bunch of them are UX changes (IIRC stuff like trying to make sure when files are missing we print the path we were looking for, and removing "actor" from everywhere).

I created a few different projects using `wash new component` but sadly remain unable to deploy anything. Holler if I can do any further investigation that might help.

**Comment by vados-cosmonic** [comment]
Hey @crimeminister are you on [the slack](https://slack.wasmcloud.com/) by any chance? I'd love to try and debug this live -- if `wadm` and the host are starting it should definitely work! You can find me in there under "Victor" pretty easily!

If I can't find you in the slack could you post your host logs and run `wash get inventory`?

I wonder if you even see a running host there at all

**Comment by crimeminister** [comment]
> Hey @crimeminister are you on [the slack](https://slack.wasmcloud.com/) by any chance? I'd love to try and debug this live -- if `wadm` and the host are starting it should definitely work! You can find me in there under "Victor" pretty easily!

Hey Victor, I'll be AFK for a little bit this coming week, but I'll look for you on Slack after I am back in the saddle.

> If I can't find you in the slack could you post your host logs and run `wash get inventory`?

Here's the output of `wash get inventory`:

```
$ wash get inventory

Failed to create NATS client

Caused by:
    0: Failed to connect to NATS 127.0.0.1:4222
       No credentials file was provided, you may need one to connect.
    1: IO error: Connection refused (os error 111)
```
 
> I wonder if you even see a running host there at all.

When running `wash up` I definitely see the NATS server starting up; I'm able to use the `nats` CLI tool to check the connection health and it checks out `ok`.
 
> [EDIT] Also, are you running multiple `nats-server` instances? You _should_ be able to run _only_ `wash up` with no args and everything will be running (and will show you the logs). `wash` starts _it's own_ NATS instance, `wadm`, _and_ the wasmCloud host.

I don't have multiple `nats` instances running. Without executing `wash up` first to run a `nats` instance I get:

```
$ nats server check connection
CRITICAL Connection Crit:connection failed
```

HTH!
