### ISSUE TITLE
naming consistency review & fix for all .smithy files

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wasmCloud#225]
Make a pass at naming consistency for all .smithy files before the 0.50 release. I intentionally made some adjustments to the naming to enable parallel independent development between capability providers and host, but we should clean these up before 0.50.

#### Case consistency

- Field names are pascal case with leading lower case, as in 'hostName', `linkName`. `actorRef`.
- Structures and operations are pascal case with leading upper-case letter, as in `HandleRequest`.
- Only the first letter of acronyms is capitalized, so `HttpRequest` not `HTTPRequest`, and `GetActorId` not `GetActorID`.

We are already pretty good on the second and third bullets, but I know of several structures that do not follow the first convention. The field name in the smithy file is the name used for serialization, but the code generator always generates the correct thing for the target language, so field `linkName` becomes `link_name` in rust, without any additional annotation.

When I created the core interfaces (namespace org.wasmcloud.core) in smithy, I wanted to develop capability providers that communicate with the wasmcloud otp host without requiring code changes for the host, so I added annotations for the serialized name for binary compatibility with the host. As an example, the LinkDefinition structure's providerId field is defined as:
```
    /// provider public key
    @required
    @serialization(name:"provider_id")
    providerId: String,
```
The field name follows the naming convention (bullet #1 above), but the serialization annotation will be deleted when we address the naming consistency. Rust clients will still see the field named "provider_id", but when we remove the `@serialization` annotation from the smithy file, the generated rust code will get a new annotation `#[serde(rename="providerId")]" to make the on-the-wire name `providerId`.. 

#### Terminology

This one is probably more important than case consistency, based on the goal of simplifying developer experience.  Various apis use `actor`, `actor_ref`, `actor_id`, or `actor_key` to refer to a string containing the actor's public key. If we can come up with consistent names for things like this, the developer won't need to refer to the documentation as often - they can just predict the name based on their experience with the same concept in other data structures or function args. If we get this right, it would be possible to add an appendix to the api/sdk documentation with definitions of common field names that are independent from the places where they are used.

These changes may be easier to do at the same time as, or shortly after, issue #224 (consolidate duplication in core libraries)

**Comment by soham117** [comment]
Hey #224 is closed. Can u assign this to me ? I will rename all required files. Thanks in advance.@stevelr

**Comment by stevelr** [comment]
@soham117 you're welcome to submit pull requests for this issue. It's filed in the wasmcloud repo, but fixes will be in more than one repository, including: interfaces, control-interface, and wasmcloud-otp, and possibly others, depending on which interfaces are modified. Please feel free to work on it. If you aren't already in the slack channel, join https://slack.wasmcloud.com/  and chat with us there!
