### ISSUE TITLE
[BUG] http-blobstore example 

### ISSUE THREAD

**Issue by ericliu0000** [wasmCloud/wasmCloud#2256]
### Affected project(s)

- [ ] documentation
- [X] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

In the `http-blobstore` example, the [wadm.yaml file](https://github.com/wasmCloud/wasmCloud/blob/main/examples/rust/components/http-blobstore/wadm.yaml#L22) contains definitions which appear out of date for the current version of wasmCloud. These differences are corroborated by the documentation present in the ["Migrating from 0.82.0" documentation page](https://wasmcloud.com/docs/ecosystem/wadm/migrating).

### Steps to reproduce

1. Clone the wasmCloud repository
2. Go to examples/rust/components/http-blobstore
3. Run `wash app deploy` after starting wasmCloud

### Expected behavior

I expected `wash app deploy wadm.yaml` in the relevant directory to correctly deploy the application.

### Environment

OS: Manjaro Linux (6.6.32)
Shell: zsh
wasmCloud version: 1.0.2

### Screenshots / Logs / Additional context

```
> wash app deploy wadm.yaml

Could not put manifest to deploy Validation Error: 
Should be able to parse object at: spec/components/ at index: 0 
Please check for missing or incorrect elements
```

**Comment by vados-cosmonic** [comment]
Hey @ericliu0000 thanks for reporting this! We've got a fix going through review right now, and we probably will release a new version (0.2.0) of the example since I found some other issues.
