### ISSUE TITLE
[FEATURE] Add append functionality through extension interface to blobstore-fs and blobstore-azure

### ISSUE THREAD

**Issue by esoterra** [wasmCloud/wasmCloud#2289]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

I would like to be able to develop distributed applications that take advantage of [Azure Append Blobs](https://learn.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs#about-append-blobs) for concurrent-safe append-only data. However, the `wasi:blobstore` interface does not have support for append and it's not clear when or if that will happen.

### Describe the solution you'd like

I discussed this with @brooksmtownsend and he suggested we add append as an extension interface to `blobstore-fs` and `blobstore-azure`. This seems like the right approach and would allow people to use concurrent-safe append if the provider they're using supports that functionality.

### Describe alternatives you've considered

We could wait for `wasi:blobstore` to add this feature but it might take a while or never happen at all.

### Additional context

I would like to volunteer to help get this done.

**Comment by brooksmtownsend** [comment]
Something we'll need to tackle as we start this is the right way to continue to use the `wrpc-interface-blobstore` crate and extend with additional interfaces. The blobstore providers seem more like a special case since they do not have a wit folder.

**Comment by thomastaylor312** [comment]
@esoterra I think I'm a fan of option 1 until wit gets support for adding additional methods to a type. Seems like it would be really easy to extend in that way. Was there one you were leaning towards?
