### ISSUE TITLE
[BUG] wadm binary is fetched on every invocation of wash up

### ISSUE THREAD

**Issue by deem0n** [wasmCloud/wasmCloud#2308]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

It is related to change of `wadm --version` output. recent versions of wadm returns something like `wadm-cli 0.12.0`. Old version returned `wadm 0.10.0`

Check for version string was not updated in wash sources :-(

Actually, I found the bug trying to solve the #2134 digging into source code

### Steps to reproduce

1. check wadm creation time with `ls -l ~/.wash/downloads/wadm`
2. run `wash up`
3. check creation time again, you have a fresh copy

### Expected behavior

Should not download `wadm` for every invocation

### Environment

- OS: All
- Shell: All
- wasmcloud Version 1.0.3

**Comment by deem0n** [comment]
Yes, I am on Intel Mac. But I believe the bug still present on all platforms. This check is not working correctly https://github.com/wasmCloud/wasmCloud/blob/c262023ea20c256686d7f1bdd1d6b21b031b55a6/crates/wash-lib/src/start/wadm.rs#L77

**Comment by brooksmtownsend** [comment]
@deem0n would you mind trying to run `~/.wash/downloads/wadm --version` with the downloaded copy?

**Comment by deem0n** [comment]
`~/.wash/downloads/wadm --version` = `wadm-cli 0.12.0`

**Comment by brooksmtownsend** [comment]
Ah I see what you mean, the binary changed so the logic removing just `wadm v` from the front doesn't work. Great catch

**Comment by deem0n** [comment]
This is the cause: https://github.com/wasmCloud/wadm/commit/7c3c5a5ac7dd19f7fad0fd446ba4e4a1c3d8ddeb#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542

<img width="651" alt="image" src="https://github.com/wasmCloud/wasmCloud/assets/871385/9bf95112-35fb-435e-b25e-5178d707972f">

**Comment by deem0n** [comment]
I will provide PR later today
