### ISSUE TITLE
[FEATURE] Remove every-commit releases of github packages

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#2323]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

Browsing the github packages for capability providers, wash, wasmCloud, etc it's difficult to see the latest tagged version because of the amount of commit-based builds we have in the packages.

### Describe the solution you'd like

I would love to be able to browse the GitHub packages directly to find the last couple of tagged versions of the provider, rather than seeing the commit hashes. 

### Describe alternatives you've considered

I can see the value in reproducing providers by commit, but I personally have not used a commit-released provider. I would much rather have a workflow dispatch action to be able to build a provider for a specific commit when we're attempting to diagnose a problem and keep the packages list clean. I know this is a tradeoff.

### Additional context

Simplifying the CI that we run also uses less power 🌎

**Comment by lachieh** [comment]
I like this. If there's a button, we can press it when necessary. Additionally, building from source is not an unreasonable ask for testing specific things.

**Comment by thomastaylor312** [comment]
We're still planning on pushing `canary` though, right? I would like to keep that, but otherwise am totally in favor

**Comment by brooksmtownsend** [comment]
Yeah I'm cool with `canary`, same with `latest` if we wanted to add that but we don't currently. This would just encapsulate removing the tagging by commit short/long hash

**Comment by brooksmtownsend** [comment]
Fixed by https://github.com/wasmCloud/wasmCloud/pull/2518#event-13575913890. If anyone is looking to do more work here we can add the manual build action as a condition as well, but that's totally optional and we can implement it when we actually need it
