### ISSUE TITLE
[BUG] wasmCloud:blobstore to wasi:blobstore

### ISSUE THREAD

**Issue by ricochet** [wasmCloud/wasmCloud#2328]
### Affected project(s)

- [X] documentation
- [X] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

We still have some vestiges of `wasmcloud:blobstore` in wasmCloud examples. We should move these to the wasi:blobstore 0.2.0 draft.

### Steps to reproduce

```
rg wasmcloud:blobstore

crates/provider-blobstore-s3/README.md
3:This capability provider is an implementation of the `wasmcloud:blobstore` contract.

crates/provider-blobstore-fs/README.md
3:This capability provider implements the `wasmcloud:blobstore` capability for Unix and Windows file systems.

examples/rust/components/http-blobstore/README.md
23:    --capid wasmcloud:blobstore \

...
```

### Expected behavior

Use WASI whenever we are confident in stability.

### Environment

- wasmcloud Version 1.0.2

**Comment by thomastaylor312** [comment]
I am going to be focusing on making sure the blobstore interface is ready once I finish work on `wasi:messaging`. So once we've done the work there, I'd feel confident moving over
