### ISSUE TITLE
[FEATURE] Auto bump provider references

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmCloud#2339]
### Affected project(s)

- [X] documentation
- [X] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the solution you'd like

It would be really nice if we didn't have to manually bump all of our examples to their latest provider versions. See #2336 for example

**Comment by vados-cosmonic** [comment]
Not stale, it would still be nice if we had a way to do this!

**Comment by markkovari** [comment]
If you do not mind a +1 tool in your repository; renovate is capable of this. With a regex in given files it should be able to identify newer OCI images like this https://docs.renovatebot.com/modules/manager/regex/#configuration-templates 🤔 You can assign it to me I'll can give it a try.

**Comment by vados-cosmonic** [comment]
Hey @markkovari thanks for noting that -- this is definitely something we want that people just didn't have the know-how (of renovate, evidently!) to do quickly without writing a script or something. Please take a shot at it!
