### ISSUE TITLE
[BUG] wash app delete fails, using the latest version

### ISSUE THREAD

**Issue by ossfellow** [wasmCloud/wasmCloud#2342]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

After testing the `echo-messaging` example, I was trying to delete the application, and got the following error:

> Invalid request: Unable to parse delete model request: Error("EOF while parsing a value", line: 1, column: 0)

Prior to test, I used `wash drain all` to ensure the environment is clean, and used the latest version of wash (i.e. 0.29.1).

### Steps to reproduce

1. Go to the `echo-messaging` Rust example directory.
2. Ensure wasmCloud is running by issuing the command `wash up --detached`.
3. Run command `wash app deploy ./wadm.yaml`.
4. Make sure the application is reconciled and deployed by running command `wash app list`.
5. Run command wash app delete `rust-echo-messaging`.

### Expected behavior

Application should be successfully deleted.

### Environment

- OS: MacOS
- Shell: zsh
- wash Version: 0.29.1
- wadm version: 0.12.0 (as reported by running `wadm --version`)

**Comment by brooksmtownsend** [comment]
Fixed by https://github.com/wasmCloud/wadm/pull/305
