### ISSUE TITLE
reduce overhead for creating tests

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wasmCloud#235]
there's a lot of overhead and boilerplate required to create any kind of test - unit, integration, performance, etc.

To create a unit test of a provider, you need to create an entire actor wasm project, link it with wasmcloud:builtin:logging, wasmcloud:httpserver, and the provider under test, issue wash commands to start the test actor, httpserver, and provider under test, link them all, then issue an http curl command to start the test.

Some ideas for reducing overhead:

- create a test interface (wasmcloud:testing) with a start-test command that can be issued by wash over rpc. that would eliminate the httpsrever requirement, and possibly the logging requirement, if the start-test command returned its logs to the caller.
- build some common infrastructure that can handle common test needs, such as
  - specifying a list of tests to run, executing them, and printing a pass/fail report
  - keeping track of time elapsed
  - initializes a test actor project that eliminates as much boilerplate as possible
With the combination of infrastructure and project-generation, it should be able to streamline actors to something very slim.

- another idea - write tests in a different language that isn't compiled, and have a test-actor load and then them. At least then we wouldn't have to create a whole actor project for a unit test.

- be able to load a provider directly from a cli (without a host), let it subscribe to nats, and load a test program that invokes the provider over rpc. this is fairly direct, and is similar to a test I wrote for the kv provider. Generalize this so it can be used for other providers. This won't work for all providers, though: (1) it won't work for builtin providers, (2) it can't test providers that send messages to actors (kvredis only responds to messages, never initiates), (3) can't test more complex configurations. However, for a basic unit test framework, it's pretty efficient.

- integrate testing with CI

**Comment by autodidaddict** [comment]
@stevelr There is an `escript` option available on the `wasmcloud_host` executable that comes out of a distillery release. This could be used to execute a script that loads actors, loads providers, puts link definitions, and then manually sends invocations (which is available as a function on all actors)

**Comment by stevelr** [comment]
there are now several tools for helping to write tests
- wasmcloud-test-util crate has tools for testing both actor and provider
- tools for loading capability providers, invoking rpc messages, and testing responses
- create a mock actor to test provider-to-actor messages
- Runner interface for invoking a list of tests and generating a status report of the results
- Start method for actors to initiate tests that run inside actors
