### ISSUE TITLE
[BUG] Host shutdown always fails due to epoch thread interrupt

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#2391]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

Whenever I use `wash stop host` to stop a wasmCloud host, it shows this error:
```
Error: failed to shutdown host

Caused by:
    epoch interrupt thread timed out
```

### Steps to reproduce

1. run wash up -d
2. use wash get hosts to get the host ID of the host
3. run wash stop host $host_id
4. see error

### Expected behavior

I don't expect to see this error message. Granted this isn't really a true issue as the host does successfully shut down, but it's misleading at best.

### Environment

- OS: [e.g. Linux, MacOS]
- Shell [e.g. bash, zsh, powershell]
- wasmcloud Version [e.g. 0.81.0]

**Comment by nitame** [comment]
Hello,
I didn't succeed to reproduced the bug.
From MacOs with wash (v0.29.2) installed with homebrew I got this message: `Host NB... acknowledged stop request`. And I got the same message when I execute wash from Docker with this image: ghcr.io/wasmcloud/wash:ae9cb82-wolfi.
Is there a specific version of wash which has this bug?
Thanks,

**Comment by brooksmtownsend** [comment]
@nitame I was using `wash 0.29.2` as well 🤔 but I didn't reproduce. Going to close for now just in case this was a temporary issue on my end
