### ISSUE TITLE
[BUG] When developing providers with local files, you must clear cache to get the updated build

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#2399]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

When I'm developing providers, I find myself seeing log messages and prints that I already removed in a previous build. We cache providers to avoid unnecessary OCI fetching, but when working with a local file we shouldn't cache the provider binary.

### Steps to reproduce

1. Run an example application, like the custom template Rust provider
2. Make a change to the provider, then `wash build`
3. `wash stop custom-template`
4. See that the previous functionality still exists

### Expected behavior

When developing a local file provider, I expect for it to be loaded fresh every time

### Environment

- OS: [e.g. Linux, MacOS]
- Shell [e.g. bash, zsh, powershell]
- wasmcloud Version [e.g. 0.81.0]

### Screenshots / Logs / Additional context

I believe this snippet of code is responsible. We should not be loading from a cache path for providers that are fetched from a file, instead we should be pulling the binary out every single time _or_ at the very least comparing the binary's hash to the cached provider https://github.com/wasmCloud/wasmCloud/blob/main/crates/host/src/par.rs#L82

**Comment by vados-cosmonic** [comment]
Hey @brooksmtownsend so the binaries for a local provider are actually cached (the EXEs)... I think this might not be as easy as it seems. A few things:

- Didn't we have an option that disabled the cache?
- Should we add an option that disables the various provider caches
- Should we instead cache the binaries in a content-addressable fashion? Right now we when we do [`par::read` it seems like we *always* load the thing from local disk, *then* check the cache and return that if we find it](https://github.com/wasmCloud/wasmCloud/blob/main/crates/host/src/par.rs#L72)...

**Comment by brooksmtownsend** [comment]
> Didn't we have an option that disabled the cache?
> Should we add an option that disables the various provider caches

I think that we do have that option, and it makes sense for OCI, but I don't really see the case where we'd want to cache the binary when the par is just on disk 🤔 Other than the case where we remove the par later on

> Should we instead cache the binaries in a content-addressable fashion?

Would this be based on, say, the claims in the provider archive? I do hear your point around this not being super easy, since we actually need to execute the provider.

**Comment by vados-cosmonic** [comment]
> I think that we do have that option, and it makes sense for OCI, but I don't really see the case where we'd want to cache the binary when the par is just on disk 🤔 Other than the case where we remove the par later on

Yeah I'm not sure exactly why we do that -- maybe to ensure consistency if the par is moved/removed?

Agree that it's a confusing/unexpected behavior, but I don't know the original reason for caching the binaries -- you'd think it was for speed up, but considering how the code looks now we always load the par from disk *first*, *then* check the cache as far as I can tell.

Bit of a chesterton's fence situation, but I certainly am not against just removing the cache for binaries all together.

> Would this be based on, say, the claims in the provider archive? I do hear your point around this not being super easy, since we actually need to execute the provider.

Yeah -- the claims could be included in the hash and/or directory structure so we can look them up... but at that point it might make more sense to just cache the whole archive (possibly compressing it beforehand) itself.

Then the problem would shift to us having like 10s or 100s of versions of a local provider in `wasmcloudcache`...

**Comment by deem0n** [comment]
> I believe this snippet of code is responsible. We should not be loading from a cache path for providers that are fetched from a file, instead we should be pulling the binary out every single time _or_ at the very least comparing the binary's hash to the cached provider https://github.com/wasmCloud/wasmCloud/blob/main/crates/host/src/par.rs#L82

I believe line 82 is fine, but look at 83,84:

```
    // Only write the file if it doesn't exist
    if let Some(mut file) = create(&exe).await? {
```

It seems we don't overwrite disk file if it already exists. It is easy fix to always put content into the `&exe` path on disk, effectively overwriting disk file every time.

Is that desired fix? I could make PR if so.

**Comment by brooksmtownsend** [comment]
not stale, we should def still fix this
