### ISSUE TITLE
[BUG] wash reg still documented in the help output (and docs site for v 1.0) but not supported anymore

### ISSUE THREAD

**Issue by deem0n** [wasmCloud/wasmCloud#2404]
### Affected project(s)

- [X] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

output for `wash help` contains

```
Publish:
  pull         Pull an artifact from an OCI compliant registry
  push         Push an artifact to an OCI compliant registry
  reg          Perform operations on an OCI registry
```

but reg command is not available and seems to be deprecated 

### Steps to reproduce

1. Run command `wash help`
2. See docs https://wasmcloud.com/docs/cli/reg

### Expected behavior

Info about `reg` command must be removed

### Environment

- OS: ALL
- Shell: ALL
- wash version:  0.29.2

**Comment by deem0n** [comment]
I can provide a quick fix for wash cli, but not sure about docs.

**Comment by vados-cosmonic** [comment]
Hey @deem0n our docs are over at https://github.com/wasmCloud/wasmcloud.com -- feel free to fork that and contribute that if you don't mind!

If not we can get on it as well, shouldn't be too hard of an update to make :)

**Comment by deem0n** [comment]
Should we recover `wash reg ping` in some way? I guess it is not so useful feature and we can forget it.

**Comment by brooksmtownsend** [comment]
@deem0n I liked the idea of `wash reg ping` but, in practice, it didn't really get much use and it would be pretty small functionality to put as a top level command. What we have considered is a `wash login` to authenticate to an OCI registry, which I think would bring that functionality essentially back and be able to manage pulling/pushing to that registry from then on. That should be a separate feature, I think.

**Comment by vados-cosmonic** [comment]
wash reg should be gone from everywhere now -- both PRs to `wash-cli` and docs have been merged -- let me know if I missed anything @deem0n and we'll re-open!

**Comment by deem0n** [comment]
@vados-cosmonic: Thanks! Everything seems to be fine.
