### ISSUE TITLE
Review and update README files in preparation for 0.50 release

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wasmCloud#244]
This is an org-wide issue affecting several repositories. 
README files in the repositories need to be reviewed and checked for helpful, accurate information, valid urls, etc.

- [x] capability-providers (top-level README and each provider)
- [x] control-interface
- [x] examples (top-level and each example) done in https://github.com/wasmCloud/examples/pull/93
- [x] interfaces (top-level and each interface)
- [x] project-templates
- [x] tutorials (either update or add a note that they are out of date)
- [x] wash (fixed by https://github.com/wasmCloud/wash/pull/182)
- [x] wasmcloud Make top-level README a landing site for all wasmcloud-related stuff; move pre-otp stuff into a subdirectory and/or a downloadable tar file
- [x] wasmcloud.com-dev
- [x] wasmcloud-dev-site (review/update documentation)
- [x] wasmcloud-js
- [x] wasmcloud-otp
- [x] wasmcloud-test
- [x] weld
- [x] actor-interfaces - update README to say those are deprecated and refer to interfaces and other documentation

**Comment by brooksmtownsend** [comment]
With our combined efforts we wrapped this up 👍🏻 Closing
