### ISSUE TITLE
Update GH Actions to create and publish release distributables

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wasmCloud#246]
This is an org-wide issue affecting several repositories.
Github actions need to created and/or updated to create release distributables and publish them.
Repos need access to the appropriate secrets.

- [x] capability-providers: publish releases to OCI and update index page with latest version num (done after https://github.com/wasmCloud/capability-providers/pull/94)
  - [x] create actions
  - [x] release all to azurecr
- [x] control-interface: publish to crates dot io (addressed in https://github.com/wasmCloud/control-interface/pull/10)
  - [x] create actions
  - [x] release to crates dot io (0.4.2)
- [x] examples: publish releases to OCI (template in https://github.com/wasmCloud/examples/pull/68, implementation to follow)
  - [x] create actions
  - [x] release to crates dot io
- [x] interfaces: publish releases to crates dot io (started in https://github.com/wasmCloud/interfaces/pull/12)
  - [x] create actions
  - [x] release to crates dot io (needed for factorial, httpserver, testing)
- [x] wash: build binary for various platforms and architectures, homebrew, debian repo, arch repo, etc.
  - [x] release 0.6.0 for various platforms (actions already in place)
- [x] wasmcloud-js: npm (done by @ks2211 )
- [x] wasmcloud-otp: distillery release, docker release, attach distillery releases to GH release
  - [x] modify action to attach artifacts to GH release (done in https://github.com/wasmCloud/wasmcloud-otp/pull/207)
  - [x] create release
- [x] wasmcloud-test: publish to crates dot io (tackled in https://github.com/wasmCloud/wasmcloud-test/pull/1)
  - [x] create action
  - [x] release to crates dot io
- [x] weld: publish to crates dot io
  - [x] create actions (done in https://github.com/wasmCloud/weld/pull/30)
  - [x] release to crates dot io

**Comment by stevelr** [comment]
We want to reduce code duplication as much as possible by sharing scripts, docker images, and/or custom github actions.
Also I would like to review whether there's a more effective way to share the secrets needed for publishing.

**Comment by brooksmtownsend** [comment]
Self-assigning here as I'm going to try to knock out as many as I can
