### ISSUE TITLE
[FEATURE] Support configuring additional CA certificates for OCI and OTEL clients

### ISSUE THREAD

**Issue by joonas** [wasmCloud/wasmCloud#2460]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

In environments where you may have non-WebPKI CA (i.e. self-hosted CA), you might need the ability to configure the wasmCloud Host to trust your custom CA without necessarily including it in the wasmCloud Host OS trust store (for example, if you're using/mirroring the upstream Docker images and don't wish to modify them to include your local CA).

### Describe the solution you'd like

It would be handy to have the ability to pass in a file path to load additional CA certificates from, possibly as a repeated option in case you needed multiple different CAs.

Ideally this would take the form of something like `--tls-ca-path` that could be repeated in case you needed to have multiple of these files loaded (as opposed to having them all be concatenated together in to a single file).

Optionally, this could also support passing in a path to directory instead of an individual file(s), which would then iterate all of the files in the directory (or perhaps filtering files based on a specific extension, `.crt` for example?) and attempt to parse them to certificates.

Parsing the provided argument to the set of files should be done as part of the host start process to ensure that the file(s) / directory of files is valid and failing fast with clear feedback if it's not.

**Comment by liamwh** [comment]
Great feature, looking forward to seeing this!

Here's a couple of thoughts that come to mind:

### Unified Certificate Loading

For the flag `--tls-ca-path`, I would expect this to accept both file paths and directory paths. I think the code should detect the path type and process accordingly. If a directory is provided, it should scan for files (non-recursive by default to avoid any unexpected behavior), where recursiveness could be added later with another flag or something should recursive functionality ever actually be needed. Maybe `--tls-ca-type` makes sense for the file type filtering when a directory is provided. 

### Configuration File Support

Forgive my ignorance as I'm on mobile and haven't looked this up: would it make sense to add this option also via a configuration file?

### Environment Variable Support

Does it make sense to use an environment variable (e.g., WASMCLOUD_TLS_CA_PATH) to set the certificate paths here? Maybe that makes it easier to configure in containerised environments, though maybe the config file should just always be preferred here?

Very curious to hear the opinions of others on these points. I don't feel particularly strongly either way, as long as it works 👍
