### ISSUE TITLE
[BUG] wash app delete impacts the http server provider used by another wadm deployment.

### ISSUE THREAD

**Issue by ritesh089** [wasmCloud/wasmCloud#2467]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

When we use the same version http server provider in multiple wadm deployments, the same http server provider gets reused, which is expected. But the problem is a wash app delete on the first  wadm results in the capability provider missing in the second app .

### Steps to reproduce

1) Wash app deploy a wadm with a http server capability provider 
 image: ghcr.io/wasmcloud/http-server:0.20.0
 
 2) Wash app Deploy another wadm with the same capability provider.
 Provider will not get redeployed , but we can call the app via CURL.
 
 3) Wash app delete the first wadm .
 
 4) Tests the component deployed with the second wadm  using CURL. You will get an error .

### Expected behavior

If a capability provider is shared by multiple components, wash app delete on one wadm should not remove it from others.

### Environment

- OS:  MacOS
- Shell  zsh
- wasmcloud Version : 0.29.2

**Comment by thomastaylor312** [comment]
Hey @ritesh089! This is a known issue/feature add we've already started brainstorming around in wadm: https://github.com/wasmCloud/wadm/issues/277. I'm going to close this in favor of that issue

**Comment by thomastaylor312** [comment]
Also, you can work around this for now by making sure to _not_ specify an `id` for the component. Wadm will create a unique ID for each one. It will be multiple providers, but they won't collide.

**Comment by brooksmtownsend** [comment]
Yeah I think as long as you are not overlapping unique identifiers, and the components listen on different ports, this shouldn't be an issue
