### ISSUE TITLE
[FEATURE] Support versions in links

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmCloud#2473]
Right now we do not support linking to specific and/or multiple versions of the same interface. This will definitely be required when wasi 0.2.1 releases in August. This should be a non-breaking, but fairly wide-reaching change. For backwards compatibility (and ease of use), we should have the `version` part of a link definition be optional. If no version is specified, we can ascertain the version from the component's world if needed or we can just assume that the only thing a user is linking matches. 

### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [X] control interface client
- [ ] other / not sure

**Comment by brooksmtownsend** [comment]
Note that wRPC fully supports this so this should be an additional field on the link but should not require any changes to the RPC mechanism 😄
