### ISSUE TITLE
Implement CHAOSS best practices

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wasmCloud#250]
CHAOSS group has some recommended best practices for open source projects. We already do most of these; we should look at what's left, and when sally are implemented, add the applicable badges.

https://chaoss.community/metric-cii-best-practices-badge/

https://chaoss.community/metric-spdx-document/

**Comment by brooksmtownsend** [comment]
Unfortunately that first link goes nowhere but I did find https://bestpractices.coreinfrastructure.org/en

**Comment by brooksmtownsend** [comment]
We're going to work on #319 first, then we could proceed with other best practices 😄
