### ISSUE TITLE
Implement support for WasmEdge

### ISSUE THREAD

**Issue by juntao** [wasmCloud/wasmCloud#251]
WasmCloud could support multiple alternative wasm runtimes to take advantage of the unique features and performance characteristics of each.

I would like to propose that WasmCloud add support for the WasmEdge Runtime through WasmEdge's Rust SDK.

https://github.com/WasmEdge/WasmEdge/tree/master/bindings/rust

If there is anything we could do to help. Please let me know. Thanks.

**Comment by brooksmtownsend** [comment]
Hey @juntao, it's been a little while! With the effort that @tessi recently just put into refactoring from wasmer to wasmtime, I think implementing wasmedge as well would really require the largest effort in writing the custom NIF. Are you aware of any efforts here? I just don't want this issue to go too stale 🙂

**Comment by tessi** [comment]
Hey! sorry @juanto

Wasm and with it all the different wasm engines is just moving to fast for me to maintain multiple engines. I just can't do that besides family and day job. If you or someone wants to give it a try, I'd be happy to give you an intro into the problem space and wasmex code base :)

**Comment by autodidaddict** [comment]
> Hey! sorry @juanto
> 
> Wasm and with it all the different wasm engines is just moving to fast for me to maintain multiple engines. I just can't do that besides family and day job. If you or someone wants to give it a try, I'd be happy to give you an intro into the problem space and wasmex code base :)

You've been putting in amazing effort. I don't think anybody would expect you to support swapping in and out of "all the engines"

**Comment by juntao** [comment]
No worries! Let me try to give a status update.

We have recently worked with several companies and projects to support WasmEdge together with wasmtime. The process is typically to replace wasmtime's GO or Rust SDKs with WasmEdge's. Those APIs are fairly similar. We have done it many times -- we are actually thinking about creating an abstract API on top of those SDKs to support easy switching. ;)

The typical reasons to support both runtimes are:

1 Supply chain security -- since wasmtime and WasmEdge are based on completely different tech stacks (Rust + Cranelift vs C++ + LLVM), they are unlikely to be affected by the same bugs. 

2 Additional features provided by WasmEdge such as web service, database, AI inference, Kubernetes / Docker and JavaScript support.

Of course, I understand different projects have different priorities. I am not that familiar with the Erlang / Elixir ecosystem but would love learn more to understand how we can better support it! 🙏🙏🙏

**Comment by tessi** [comment]
😊 thanks everyone! didn't mean this to be hunting for compliments 🙈 

> we are actually thinking about creating an abstract API on top of those SDKs to support easy switching

sounds very interesting especially if it's not a vendor lock-in and well maintained and on-par with wasmtime!
I probably continue the port to wasmtime first and investigate further steps from there.

> I [...] would love learn more to understand how we can better support it!

Is there anything specific you'd like to know? Feel free to reach out on [twitter](https://twitter.com/philipptessenow) or [@tessi on the elixir slack](https://elixir-slackin.herokuapp.com/) for wasmex-specifics and a more real time'ish chat and to not sidetrack this issue any further :)

**Comment by brooksmtownsend** [comment]
We've done a whole lot of reorganization around how we're running Wasm engines, and I think for now we're going to proceed with support for wasmtime as the engine under wasmCloud. As soon as we get to rethinking pluggable / replaceable engines, I'd love to consider putting wasmedge as one of those engines
