### ISSUE TITLE
Add --watch flag to wash commands that provide live info

### ISSUE THREAD

**Issue by liamwh** [wasmCloud/wasmCloud#2512]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the solution you'd like

Add --watch flag to at least `wash get inventory` but probably also more commands that give live info

**Comment by Aditya1404Sal** [comment]
`wash app list` would also be suitable for this flag right ? I'll start with these 2 Cmds for now

**Comment by brooksmtownsend** [comment]
@Aditya1404Sal what kind of design are you thinking for this one? I'd love to discuss some of the implementation details in the issue so we can have a clear definition of done for this one 🙂  Is it just a flag on specific commands? Will the user be able to specify a duration to refresh the watch, or is it something we refresh automatically based on events?

Devils advocate question, is this feature necessary when the [watch](https://linux.die.net/man/1/watch) command exists?

**Comment by Aditya1404Sal** [comment]
Hey @brooksmtownsend for starters I thought it'd be a simple implementation of just polling the model data in intervals (1-2 sec) and updating the modified data , but it felt a bit inefficient, then I looked at the `wash up` :: interactive mode and wondered if `mpsc` channel and spawing a separate process that'd listen to channel input from the client side, would do any good.
of course, In my mind the `--watch` flag would basically be a bool flag , a duration opt does seem crafty but then again do we really want users to think about how quick they want to see the changes (I'd want it to be instantaneous)
it would perpetually provide live info until `CTRL+C` signal triggered the termination

You have rightfully pointed out the `watch` command but wouldn't it make this feature linux only ?

**Comment by brooksmtownsend** [comment]
Yeah I think that polling in intervals is a great plan here. Too much customizability feels too complex 😄 

How about for `wash app list` we do every second, and for `wash get inventory` we can query every second too, with a list of host IDs. So it may be a good idea to refresh the list of hosts every 5 seconds and then query inventory every second.

Great point around `watch` being on Unix based systems and that some other tool would be needed on Windows. That's a good enough reason to support it in wash. I can see the bulk of the difficulty here coming from the right way to take over the terminal and refresh that information, unless we want to continually repeat output

**Comment by Aditya1404Sal** [comment]
That Sounds great :smile:  ! 

I think the intervals you specified for `wash app list` and `wash get inventory` are great :rocket: , and I agree with refreshing the list of host every 5 seconds.

Yeah so I thought the only way to refresh the information was to clear the  terminal before re-displaying the entire table again
until i came across [crossterm](https://docs.rs/crossterm/latest/crossterm/#) using this we can target ANSI escape commands to just the required information plus it's multi-platform compatible

**Comment by Aditya1404Sal** [comment]
@brooksmtownsend now that `wash app list` supports this feature. I'll start working on this for `wash get inventory`

**Comment by brooksmtownsend** [comment]
Sounds great @Aditya1404Sal ! You may want to take a look at https://github.com/wasmCloud/wasmCloud/issues/2772 as well, potentially as an extension to this, so that the output is ordered and not jumping around

**Comment by Aditya1404Sal** [comment]
Yes of course @brooksmtownsend 
I'll cover the proper ordering as well 😊
