### ISSUE TITLE
[BUG] TypeScript hello world component fails to call HTTP

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#2528]
### Affected project(s)

- [ ] documentation
- [X] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

```
~/tmp/ts-hello ➜ curl localhost:8080
failed to invoke `wrpc:http/incoming-handler.handle`: failed to call `wasi:http/incoming-handler.handle`: error while executing at wasm backtrace:
    0: 0x853340 - wit-component:shim!indirect-wasi:http/types@0.2.0-[method]outgoing-response.body
    1: 0x576756 - <unknown>!<wasm function 5939>
    2: 0x2ab0c9 - <unknown>!<wasm function 418>
    3: 0xc5edb - <unknown>!<wasm function 97>
    4: 0x2aa9f9 - <unknown>!<wasm function 417>
    5: 0x2aaf24 - <unknown>!<wasm function 418>
    6: 0x501a5f - <unknown>!<wasm function 3388>
    7: 0x3dca4e - <unknown>!<wasm function 1226>
    8: 0x3339af - <unknown>!<wasm function 678>
    9: 0x5832dd - <unknown>!wasi:http/incoming-handler@0.2.0#handle: unknown handle index 1
```

### Steps to reproduce

1. Run wash new component to generate the typescript hello world example
2. cd example
3. npm install
4. wash build
5. wash up -d
6. wash app deploy ./wadm.yaml
7. curl localhost:8080
8. see error

### Expected behavior

The example should return a successful response.

### Environment

- OS: [e.g. Linux, MacOS] MacOS
- Shell [e.g. bash, zsh, powershell] zsh
- wasmcloud Version [e.g. 0.81.0] 1.0.4

### Screenshots / Logs / Additional context

Note that this fails within wasmtime 18, 20 and 22 as well, so it is likely not a host bug.
```
ERROR wasmtime_cli::commands::serve: [0] :: Error {
    context: "error while executing at wasm backtrace:\n    0: 0x853340 - wit-component:shim!indirect-wasi:http/types@0.2.0-[method]outgoing-response.body\n    1: 0x576756 - <unknown>!<wasm function 5939>\n    2: 0x2ab0c9 - <unknown>!<wasm function 418>\n    3: 0xc5edb - <unknown>!<wasm function 97>\n    4: 0x2aa9f9 - <unknown>!<wasm function 417>\n    5: 0x2aaf24 - <unknown>!<wasm function 418>\n    6: 0x501a5f - <unknown>!<wasm function 3388>\n    7: 0x3dca4e - <unknown>!<wasm function 1226>\n    8: 0x3339af - <unknown>!<wasm function 678>\n    9: 0x5832dd - <unknown>!wasi:http/incoming-handler@0.2.0#handle",
    source: "unknown handle index 0",
}
```

**Comment by brooksmtownsend** [comment]
Just an extra note, I find this puzzling as I can't see anything in particular that changed about this example or ComponentizeJS to make this fail.

**Comment by vados-cosmonic** [comment]
This *might* be relevant to this [old bug report from `wasmtime` upstream](https://github.com/bytecodealliance/wasmtime/issues/7883) -- are the somehow using the same resource twice? Surprised a test didn't catch this

**Comment by teyckmans** [comment]
Using the typescript code from this docs page works: https://wasmcloud.com/docs/developer/components/generate
