### ISSUE TITLE
[FEATURE] Add option to re-use pre-existing Docker Credential Helper for `wash push` and `wash pull`

### ISSUE THREAD

**Issue by joonas** [wasmCloud/wasmCloud#2529]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

I have to manually provide credentials for `wash push` and `wash pull` when I already have pre-existing Docker Credentials stored locally for a given registry.

### Describe the solution you'd like

It would be helpful to have a flag that allows you to re-use pre-existing Docker Credentials with a given registry so that when you're switching between `docker push` and `wash push`, the same set of credentials would work without having to set environment variables or pass in credentials.

**Comment by vados-cosmonic** [comment]
Not stale, and soon to be resolved by https://github.com/wasmCloud/wasmCloud/pull/3073 thanks to @joonas !
