### ISSUE TITLE
[FEATURE] Add keyvalue-messaging example to the example-components workflow

### ISSUE THREAD

**Issue by ossfellow** [wasmCloud/wasmCloud#2559]
### Affected project(s)

- [ ] documentation
- [X] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

I noticed that I had forgotten to add the `keyvalue-messaging` example to the `example-components.yml` workflow, when I submitted PR #2217.  

### Describe the solution you'd like

I have a new PR to remediate this omission; so, this issue is for tracking purposes only.

**Comment by vados-cosmonic** [comment]
Hey @ossfellow this was resolved by #2560 right? If not, please let me know and we can re-open!
