### ISSUE TITLE
Claim exists but server keeps complaining about missing claim 

### ISSUE THREAD

**Issue by egimbernat** [wasmCloud/wasmCloud#257]
I'm trying to use SQL in one actor, but I haven't found the source of the issue because I have other claims that work.

```
wash claims inspect build/core_analysis_s.wasm                                      
                                                                          
                          core-analysis - Module                          
  Account       ADKIXJYKTZT6VUCQHRJXX23WXT7FZ5DUO534544LJR7C46R5P5RZ6RR3  
  Module        MD6XG6T2LNNPUJAX6FKGLG5YX2QIDSPVOVQVPYKKR75GTHS5ROBB2MSB  
  Expires                                                          never  
  Can Be Used                                                immediately  
  Version                                                      0.1.2 (0)  
  Call Alias                                                   (Not set)  
                               Capabilities                               
  wasmcloud:sqldb                                                         
  HTTP Server                                                             
  Logging                                                                 
                                   Tags                                   
  None                                                             
```
No matter if I clean and do a fresh start or sign it manually, I always see:

03:46:16.812 [error] Invocation failure: Guest call failed for method HttpServer.HandleRequest: actor: getting all rules: SqlDbError rpc: Host send error Invocation not authorized: missing claim for wasmcloud:sqldb

Any toughs?

**Comment by autodidaddict** [comment]
Try doing a `wash drain all` and then redeploy your actor. It's possible that the local artifact cache has a copy of your actor from before it was signed with the SQL DB capability provider. Also restart NATS to make sure that your test starts with an empty claims cache.

**Comment by brooksmtownsend** [comment]
Hi @egimbernat , in addition to what @autodidaddict suggested can you please send how you're creating your link definitions for your actor? It's possible that a misconfigured link definition would cause the `sqldb` invocation to be unauthorized.

**Comment by egimbernat** [comment]
Hi, thank you for the support I manage to solve it with `wash drain all`
