### ISSUE TITLE
Update `wasmcloud-host` and `wasmcloud` on crates.io

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#2587]
The entries for wasmcloud-host and wasmcloud are currently way old, dating back to an earlier iteration of the Rust wasmCloud runtime. Since these pages appear old, unmaintained, etc I feel it would give an impression that this project isn't active when in fact we're (of course) very active, and just not publishing these crates currently.

Part of the reasoning to hold this back was out of caution, knowing that the `host`, `runtime`, `component`, etc etc crates would break _frequently_ and are not 1.0 stable from a library perspective. I think we should bump these crates to the latest minor versions and get these out on crates.io, moving forward and breaking individual crates if needed.

Additionally, `wasmcloud` the binary should be published to crates.io as well. This may take a bit of effort to publish all the dependent crates, but with cargo smart-releaser we should be able to publish these crates well in the future.

**Comment by vados-cosmonic** [comment]
Definitely not stale, we're going to try and get this done *this week*! Big crate releases are underway :)

**Comment by vados-cosmonic** [comment]
Done!

**Comment by brooksmtownsend** [comment]
SO CLOSE!
