### ISSUE TITLE
[RFC] Swift Host Runtime

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#26]
As we think about what the 1.0 MVP of the wasmCloud "ecosystem" looks like, that should include the ability for iOS and Mac developers to be able to embed wasmCloud hosts within their applications. This allows those applications to host and execute arbitrary, zero-trust actor modules that can be retrieved from OCI registries or elsewhere, pushed via patches, etc.

A wasmCloud host runtime developed in Swift would allow mobile devices running iOS to not only execute actors, but communicate with a lattice, allowing actors running on that device to link to and communicate with capability providers running in the cloud or on other devices--anywhere in the lattice.

There are a few core requirements for a Swift host runtime in order for it to be able to participate as part of a lattice:

# WebAssembly Runtime
For obvious reasons, a Swift wasmCloud host would need to be able to load, verify, and interpret WebAssembly modules. This appears to be a solved problem already as there's a project called [cwasm3](https://github.com/shareup/cwasm3) that wraps the [wasm3](https://github.com/wasm3/wasm3) C library in a Swift interop/FFI package. To build a swift host runtime we would likely also build a `wapc-host` in Swift and then create a `wasmCloud` Swift library on top of that to allow developer opt-in at either abstraction level.

# MessagePack
The Swift runtime must be able to support MessagePack serialization and de-serialization as this is the format used to encode and decode messages exchanged with capability providers for things like link enabling and health checks and actor health checks.

# Lattice Connectivity
Connectivity to the lattice is of paramount importance for something like an iOS device, which, for all intents and purposes should be considered an _edge device_. It should be assumed that any such device can potentially have high latency connections or even connections that are sporadically unavailable. There is readily available support for web sockets within Swift, but we're not sure this is the best connectivity method for the intended use case here. If a user is active and interacting with a website, they probably are doing so with enough of a reliable connection to maintain a live websocket. However, if the compute is being executed in the background while the device or device owner is moving in and out of connectivity zones, switching cell towers, etc, then websockets are impractical.

A better potential solution here is to research the use of MQTT and embrace the "edge-like" nature of the device on which a Swift-based runtime would operate. Assuming poor connectivity doesn't make things worse if you have great connectivity (e.g. you're running on a Mac or your iOS device is on WiFi). Since this issue is designed as an RFC, we welcome comments here for potential alternatives to MQTT, downsides to using it, etc.

# Capability Providers
Support for capability providers needs to be possible, at least in the sense of the host runtime participating in a lattice. The bare minimum amount of support would assume that all providers are hosted elsewhere, and that this Swift host would be incapable of housing its own local providers.

There are a lot of very difficult to deal with edge cases around delivering native capability provider images to a Swift runtime, not the least of which includes the notion that you can deliver a perfectly valid Swift-based library file to a device and have it completely unable to load because it relies on Cocoa or some other piece of hardware that isn't there.

A potential middle-ground here would be to have the host be able to remotely consume capability providers, but also support some built-in providers, and allow the host runtime to deal with how they are satisfied. In other words, "fixed" providers rather than ones that are fully detachable via C FFI. Some possible candidates include:
* power - allow an actor to receive battery or power-related notifications
* location - allow an actor to query its current location as well as potentially higher-level functionality like creating a geofence and then being alerted to geofence enter/exit events (a device that never moves would just never get such events)
* phone - maybe allow an actor access to a basic set of functionality to place calls and receive notifications about call events?
* accelerometer - allow an actor access to current readings and receive events at a given sampling rate

One interesting scenario enabled by a provider like `location` is that it could be implemented so that it uses mobile GPS when running in Swift, it uses the browser's low-fidelity location API when running in a browser, uses an on-chip GPS when on a specialized device, and isn't available when running in the cloud, etc.

# ed25519 Signature Validation
A Swift wasmCloud host needs to be able to extract JWTs from retrieved `wasm` files and validate the signature on said JWT. This signature in our ecosystem is an `ed25519` signature, so the Swift runtime needs to be able to support that. I found two ed25519 libraries written for Swift [here](https://github.com/vzsg/ed25519) and [here](https://github.com/pebble8888/ed25519swift), so this appears technically feasible. Worst case scenario is this works but we have to do some additional work to support the NATS-style developer-friendly key encoding.

**Comment by brooksmtownsend** [comment]
Some additional possibilities for capability providers: https://messapps.com/allcategories/development/list-of-all-ios-permissions/.

Was thinking of Camera and Microphone, but this gives a good picture of what information you can gather as an iOS developer.

**Comment by autodidaddict** [comment]
Another thing that likely needs to be supported is multi-threading to allow for multiple actors to co-exist inside the same host while simultaneously interacting with the lattice/capability providers. It appears as though GCD is the way to go for that on iOS and according to [this repo](https://github.com/apple/swift-corelibs-libdispatch) it looks like libdispatch is available for/ported to Linux.

**Comment by average-bit** [comment]
https://crates.io/crates/quiche maybe an alternative for connectivity instead of MQTT could be some of the newer web protocols QUIC/HTTP3. Quiche is CloudFlares crate for interacting with them.

**Comment by brooksmtownsend** [comment]
https://github.com/shareup/wasm-interpreter-apple is a nice wrapper around cwasm3 that could be used

**Comment by brooksmtownsend** [comment]
Began progress on this with the waPC swift runtime, located here: https://github.com/wapc/wapc-swift. I believe our plan is to work on this on an experimental basis, but the swift runtime is not required for 0.19.
