### ISSUE TITLE
[RFC] Display community capability providers, allow promotion to "first party" provider

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#261]
## Community capability providers
This RFC submits the proposal that we display community capability providers in the https://github.com/wasmCloud/capability-providers repository under a `Community` header in the README. Additionally, it details a few possible criteria for "promoting" or "upgrading" community providers to first-party providers that the wasmCloud team supports (with the help of the original contributor, ideally.)

### Motivation
The intent behind designing our wasmCloud interfaces in a common abstraction and publishing them is to enable developers to code their own implementations of those contracts for the services they use. For example, `wasmcloud:keyvalue` was released with just a Redis implementation, but has since seen an in-memory, Hashicorp Vault, and DynamoDB implementations. Community members that create implementations for a specific service should be able to display those with pride, and others can easily pick up community implementations for their own needs.

Some capability providers will generally be better for testing and examples (keyvalue implementation with an in-memory hashmap) and some capability providers will be too purpose built to serve a broader community (capability provider that is intended to service an internal tool at an enterprise.) However, capability providers that implement common services, have some level of rigor in testing, and are gaining traction as providers that are in a common toolset for wasmCloud developers should be endorsed by the wasmCloud maintainers. For example, the filesystem provider from Mats Brorsson is a common capability that many will likely use in their applications.

### Implementation Detail
To display community capability providers, I propose we accept pull requests to add a capability provider directly into the README of the `capability-providers` repository, below our First Party providers and builtins. This entry should have the link to the open-source repository where the provider code lives, the author, and a public OCI reference or link to a github packages repository where the artifact can be downloaded from.

Additionally, we should consider some criteria to promote a community provider to a first-party provider. Vanity metrics like GitHub stars shouldn't be considered, instead a high percentage of code coverage (80%+), testimonials from users, and a general sense for if the service that the provider exposes is not an example service should be used. 

### Drawbacks
- Having hard criteria to "promote" a provider as a first party provider may turn people off of trying to upgrade. 
- If we accept too many capability providers, this can be a difficult aspect to scale for the wasmCloud team.

### Rationale and Alternatives
1. Directly accept capability provider PRs into the first-party providers list. This can lead to bloat and a high maintenance cost for wasmCloud devs.
2. Host capability providers under a `community` folder in the providers repo. The upside here is greater discoverability, the downside is the difficulties around managing future contributions from the creators.

**Comment by autodidaddict** [comment]
In terms of criteria for what constitutes a first-party provider, it boils down to the question, "Does the core wasmCloud maintainer team want to guarantee that we'll manage and keep this provider up to date and tested with the latest version of wasmCloud?"
