### ISSUE TITLE
[FEATURE] Validate secrets topic & policy topic as valid NATS subjects

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#2613]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

Currently, providing an invalid NATS topic to the `--secrets-topic` or `--policy-topic` results in questionable error messages, or worse, no error messages.

### Describe the solution you'd like

I would love to include some extra `ensure!` logic during the startup of a host to check that the secrets and policy topics are valid NATS subjects.

The following error message should fail with an invalid policy topic message.
```
~/.wash/downloads/v1.0.4/wasmcloud_host --policy-topic=""
```

**Comment by Aditya1404Sal** [comment]
Hey @brooksmtownsend, I believe I have a solution for this, can I have this issue assigned please ? Thank you!
