### ISSUE TITLE
[BUG] washboard provides strange Count parameter

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#2626]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

<img width="1216" alt="image" src="https://github.com/user-attachments/assets/fbb8e64f-368e-4d57-a386-4c75b8b7919e">

It appears that the "count" is both a duplicated heading and possibly wrong. I haven't taken a look at the code yet, but 56 seems suspiciously like that's counting the number of characters in a host ID.

### Steps to reproduce

1. Run wash new component to generate a hello-world project
2. run `wash up -d` to launch wasmCloud
3. cd component && wash build
4. wash app deploy ./wadm.yaml
5. wash ui
6. visit localhost:3030
7. see odd count

### Expected behavior

I think the `count` field should be removed, and in the dropdown of the component view we should be able to copy the host ID, not the number running on a specific host.
<img width="1210" alt="image" src="https://github.com/user-attachments/assets/18e12398-6262-4a43-9531-f8eb25f722db">

### Environment

- OS: [e.g. Linux, MacOS]
- Shell [e.g. bash, zsh, powershell]
- wasmcloud Version [e.g. 0.81.0]

**Comment by Ruby-rc** [comment]
Hello @brooksmtownsend. I would like to work on this.


I looked over the data and suppose the "hosts" field could be more accurately shown as "instance."

<img width="918" alt="image" src="https://github.com/user-attachments/assets/337c88fb-0329-490c-90ab-8d85dd307568">

Something like this, but need to confirm the field order and whether the "max-count"  should be displayed separately.

**Comment by brooksmtownsend** [comment]
Thank you @Ruby-rc ! That would be much appreciated. I think your intuition makes sense here, the components have a number of instances + we can display that alongside the hosts they are running on.

Please feel free to open a PR / draft PR when you have this working!
