### ISSUE TITLE
[BUG] washboard provider view shows "pending" perpetually

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#2627]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [X] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

The wasmCloud dashboard always shows that my provider is "Pending", even when the real state is "Running"

### Steps to reproduce

1. Run wash new component to generate a hello-world project
2. run wash up -d to launch wasmCloud
3. cd component && wash build
4. wash app deploy ./wadm.yaml
5. wash ui
6. visit localhost:3030
7. see Pending

### Expected behavior

I expect for the provider health to automatically 

### Environment

- OS: [e.g. Linux, MacOS]
- Shell [e.g. bash, zsh, powershell]
- wasmcloud Version [e.g. 0.81.0]

### Screenshots / Logs / Additional context

<img width="1286" alt="image" src="https://github.com/user-attachments/assets/e6291195-9a33-4b00-9905-c2bbf49595bc">

However, in wadm_state:
```
➜ nats kv get wadm_state provider_default --raw |jq
{
  "test-arbx_graph": {
    "id": "test-arbx_graph",
    "name": "Custom Provider",
    "issuer": "ABJ6WQ5FBGXECIJBBGA7BG73IKE7ITD2DRAURV5WB5ZUTYTNOOAYGPIG",
    "reference": "file:///Users/brooks/tmp/luk3/footest/fooprovider/build/wasmcloud-provider-custom-template.par.gz",
    "hosts": {
      "NBFN4TRTQ5Q6UANE5R2KAVHCXOIA464MWBCIROGIASV2DRWIBLU3VE5J": "Running"
    }
  }
}
```

**Comment by Alex-omosa** [comment]
Hello @brooksmtownsend. I would like to work on this.

**Comment by brooksmtownsend** [comment]
Thanks @Alex-omosa ! Let me know if you need additional pointers, I haven't poked around the washboard quite yet to see where this may be coming from

**Comment by Alex-omosa** [comment]
Ok  👍 @brooksmtownsend

**Comment by markkovari** [comment]
Hey @Alex-omosa, I was kinda struggling with other things so I went ahead and looked around this. (I was a bit annoyed that it never turns into "Running" too).

Not sure how far you have got with your version, but I made some progress with this
https://github.com/wasmCloud/wasmCloud/compare/main...markkovari:wasmCloud:fix/washboard/provider-status?diff=split&w=
but I am not the most confident that this is the best way to fetch the providers status. 🤔 
If you thing I can open a PR and we can work on it together. 🤝 


On the other hand I will be brave and ping @lachieh here too. Is this a generic enough fetch for the provider data or do what is the better way to get it?

**Comment by brooksmtownsend** [comment]
@markkovari I'm not @lachieh , so I'll let him respond, but I think that your diff looked reasonable and if it fixes the issue we'll take the PR!

**Comment by Alex-omosa** [comment]
@markkovari & @brooksmtownsend Please ignore the PR I just made.

**Comment by brooksmtownsend** [comment]
@Alex-omosa Sounds good, are you sure? Just let me know

**Comment by Alex-omosa** [comment]
I'm now very confident about my solution @brooksmtownsend . Maybe @lachieh can review that first.

**Comment by lachieh** [comment]
Ok, I've finally had the time to take a closer look at these changes. First of all, thanks to both @Alex-omosa and @markkovari for doing the digging on this one!

As @markkovari discovered, the reason the status isn't working is because the host info which is passed to the providers table doesn't actually contain the provider status. The data for a single provider row looks like this:

```json
{
    "id": "demo-blobstore",
    "name": "blobstore-fs-provider",
    "annotations": {
        "wasmcloud.dev/appspec": "wasmcloud-demo",
        "wasmcloud.dev/managed-by": "wadm",
        "wasmcloud.dev/scaler": "a4cc53c73b4dd40a97be9649d497248c2c416fea28f3f12bfac88294e580aff6",
        "wasmcloud.dev/spread_name": "default"
    },
    "image_ref": "ghcr.io/wasmcloud/blobstore-fs:0.9.0",
    "hosts": [
        "NB5453O72IYNEUNYO7V32YUN7V4FIOIKCLD3OQXTMT33NUZ52CV4FXMB"
    ]
}
```

The code for the health is assuming that the "hosts" key is actually an object with the status as the value, like is found in the wadm state bucket for providers. Here's the same provider data directly from the bucket:

```json
{
    "id": "wasmcloud_space-blobstore",
    "name": "blobstore-fs-provider",
    "issuer": "ACOJJN6WUP4ODD75XEBKKTCCUJJCY5ZKQ56XVKYK4BEJWGVAOOQHZMCW",
    "reference": "ghcr.io/wasmcloud/blobstore-fs:0.9.0",
    "hosts": {
      "NB5453O72IYNEUNYO7V32YUN7V4FIOIKCLD3OQXTMT33NUZ52CV4FXMB": "Running"
    }
  }
```

@markkovari's solution covers this by fetching the extra provider data and merging it with the host data so I think that is the solution to move this one across the line. Mark, if you want to open a PR, we can get the ball rolling on a merge and release.

@Alex-omosa, thanks again for your investigations!

**Comment by markkovari** [comment]
Oh my;

Currently the expanded row of a provider looks like this.

![image](https://github.com/user-attachments/assets/0d645f9e-41af-49dd-ab6f-6089e407cc40)

I think the column should say the status of the provider on/at the host and not the name.
Please let me know @lachieh @brooksmtownsend and @Alex-omosa if you think it is a go/no go, I can revert this.

 
<img width="1095" alt="Screenshot 2024-10-17 at 10 44 32" src="https://github.com/user-attachments/assets/dc7b63fb-8552-4e6f-902f-c554bcd9c2f7">

Respresents the following state:

```bash
nats kv get wadm_state provider_default --raw | jq
```

```json
{
  "rust_hello_world-httpserver_2": {
    "id": "rust_hello_world-httpserver_2",
    "name": "http-server-provider",
    "issuer": "ACOJJN6WUP4ODD75XEBKKTCCUJJCY5ZKQ56XVKYK4BEJWGVAOOQHZMCW",
    "reference": "ghcr.io/wasmcloud/http-server:0.23.1",
    "hosts": {
      "NA76VOLBN6PJIZA5YLE5PWVQ4VKNCLAJZZMJYG5F3FX5FMDN2CISAZ5Y": "Pending"
    }
  },
  "rust_hello_world_2-httpserver_2": {
    "id": "rust_hello_world_2-httpserver_2",
    "name": "http-server-provider",
    "issuer": "ACOJJN6WUP4ODD75XEBKKTCCUJJCY5ZKQ56XVKYK4BEJWGVAOOQHZMCW",
    "reference": "ghcr.io/wasmcloud/http-server:0.23.1",
    "hosts": {
      "NA76VOLBN6PJIZA5YLE5PWVQ4VKNCLAJZZMJYG5F3FX5FMDN2CISAZ5Y": "Running"
    }
  }
}
```

**Comment by lachieh** [comment]
Thanks! I'll update this thread once there is a new washboard release out.
