### ISSUE TITLE
[BUG] Failed to scale python component

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#2649]
### Affected project(s)

- [ ] documentation
- [X] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

```bash
2024-07-31T16:24:21.313394Z ERROR wasmcloud_host::wasmbus: failed to scale component component_ref=file:///Users/brooks/tmp/tut-tes
t/hello-py/build/http_hello_world_s.wasm component_id=python_hello_world-http_component err=failed to compile component

Caused by:
    memory index 0 has a minimum page size of 198 which exceeds the limit of 160
```

### Steps to reproduce

1. Run `wash new component` to generate a python component
2. wash build
3. wash up -d
4. wash app deploy ./wadm.yaml
5. See error

### Expected behavior

I expect for the python to component to start and work

### Environment

- OS: [e.g. Linux, MacOS]
- Shell [e.g. bash, zsh, powershell]
- wasmcloud Version [e.g. 0.81.0] v1.1.0-beta.2

**Comment by vados-cosmonic** [comment]
This is the size bug! Should be fixed by https://github.com/wasmCloud/wasmCloud/commit/3c414c52d4dfd31094b4cd2cee7e2f159cad639f, right? How big is the WASM component?

**Comment by brooksmtownsend** [comment]
> How big is the WASM component?

It's 36 mb 😢 

#2650 does fix this, but I'm leaving it in draft because even though it instantiates it doesn't successfully invoke

**Comment by vados-cosmonic** [comment]
Hey @brooksmtownsend this is fixed right?

**Comment by brooksmtownsend** [comment]
@vados-cosmonic yep!
