### ISSUE TITLE
Actors that spawn actors

### ISSUE THREAD

**Issue by benhathaway** [wasmCloud/wasmCloud#265]
As I understand it, Actors are different from microservices in one significant way: they can spawn other actors. 

Yes, they are also single-threaded and small - but it's the actor-spawning feature that allows us to blur the line between deployment-time and run-time, and between data partitions and infrastructure partitions. A new customer just signed up with your product? We can spawn a new set of actors just for that customer, with sub-actors expressing the particular feature set required and maybe even a custom component just for you.

Web-Assembly is perfect for this, and all of the other wasmCloud features (secure code modules, abstraction layers for impure providers, flat networking topology, a lattice of heterogeneous hardware) seem poised to offer exactly the kind of organic sea of flowing code that we were promised with Java but never quite received. 

Is there something along these lines in the works? Will I be able to dynamically create, configure and run sub-actors from my actors one day? Can you give us a hint what this might look like?

**Comment by benhathaway** [comment]
Actually - it looks like this is a duplicate of https://github.com/wasmCloud/wasmCloud/issues/51#issue-772215787
Sorry about that.

**Comment by brooksmtownsend** [comment]
@benhathaway this may be a somewhat duplicate but it's a great question that I wouldn't mind revisiting. We do have the ability for an actor to spawn actors now, which is neat, with the [lattice controller provider](https://github.com/wasmCloud/capability-providers/tree/main/lattice-controller). I get the sense that this isn't exactly what you're thinking of, though.

Do you have any examples of this kind of architecture where processes configure and use sub-processes for a neat use case? Would love to read up on this

**Comment by autodidaddict** [comment]
As Brooks pointed out, you can have actors start other actors today by using the lattice controller capability provider.

The wadm project is where we manage collections of actors as logical applications. This might be a good place to look at where or how we might do the relocation of actors to be closer to their providers, etc
