### ISSUE TITLE
[RFC] Overhaul and Upgrade Link Definition Management

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#266]
This is a request for comment on an evolution to the way in which link definitions are handled by hosts and within a lattice. 

## Motivation
The current state of link definition management is not nearly robust enough to support real-world, production workloads. It is far too easy for the state of host caches and stream caches to diverge over time and to potentially cause multiple instances of the same provider to have differing states. Further, dealing with link definition removal is awkward at best, and there's really no good way to support editing link definitions other than a non-atomic delete and put pair.

At any given time, you can inspect the contents of the link definition cache (a JetStream stream) and not be entirely sure if the running capability providers have the same view of the world. Worse, due to the "fire and forget" nature of much of this process (illustrated below in a sequence diagram), today we do not have a reliable way of detecting when application of link definitions fail or succeed.

## Current State
There are a couple of important flows necessary for understanding how link definitions work in the current (`0.57.x`) version of wasmCloud.
* **Host Startup** - When a host starts, it will create an _ephemeral consumer_ on the cache stream and receive all known link definitions, ignoring those with the `deleted` flag set to true.
* **Provider Startup** - When a capability provider first starts, the host will supply it with a list of known _applicable_ link definitions for that provider+link name. This data comes from the host's own in-memory cache of link definitions which is populated by virtue of an always-on subscription to the linkdef cache.
* **Control Interface Request** - An explicit request made on the wasmCloud control interface topic by a consumer. This request can be to `put` or `remove` a link definition. As mentioned below, `put` (or even `remove` in narrow edge cases) can cause divergence.

The following sequence diagram illustrates the basic flow by which a link definition is published and ultimately set in a capability provider.

```mermaid
sequenceDiagram
    participant CC as Control Client
    participant H as Host (ctl server)
    participant P as Provider
    participant C as Cache Stream
    CC->>+H: Put  link definition
    H-->>P: Advertise Link
    H-->>C: Put Link
    H->>-CC: ACK
```

In this flow, a consumer utilizing a [control interface client](https://github.com/wasmcloud/control-interface-client) makes a request to _the entire lattice_, asking that a given link definition be **put**. A psuedo-randomly chosen host (via _queue subscription_) handles the request. It then publishes the link definition advertisement message, which _may or may not_ be delivered to a waiting provider because providers are not required to be online when link definitions are set. Additionally, another message is published on a stream topic on which the lattice cache stream is listening.

Because the cache stream will, in the absence of low-level network failure, always accept the incoming message while capability providers can fail to accept the message or (hopefully rarely) panic during the application of a link definition, the link definitions known to capability providers and those known to the host and those known to the lattice cache can _all diverge_.

### Link Definition Cache
The link definition cache is a JetStream stream. This stream will be automatically created by a host on startup if it does not yet exist. By default, this stream is _in-memory_ and will completely disappear when the host for the given JS domain stops or is rebooted. 

📖 It's worth pointing out that this link definition cache feature actually predates the formalization of key-value and object stores on top of NATS's JetStream functionality. The raw stream was literally the only tool available to us at the time w/out adding another product into the list of requirements.

## Recommended Changes
The following is a list of changes that we think will correct the problems outlined at the beginning of this RFC.

### Convert Cache to NATS Key-Value Bucket
This would involve no longer using the `LATTICECACHE_{lattice-id}` raw stream and instead using a key-value bucket. The key for the link definition would remain similar to the topics used in the stream today as a hash of the following data:
* Actor public key
* Provider public key
* Provider link name

Providers currently only expose an implementation for a single contract and so the contract ID is technically not a piece of uniquely differentiating information. If, at some point in the distance future, we ever allow providers to support multiple contracts (which this author currently opposes), then we can always revisit the hash key at that point.

We get a couple of really good benefits from this approach out of the box. First, this gives us atomic read/write for each individual link definition. Second, we gain the ability to query the list of all stored link definitions by asking for the key list. We also get a robust _history_ mechanism built-in, which comes in handy for the next section.

Note: we're going to want to move the _claims cache_ over from the legacy "stream" style access mode to a key-value bucket as well. Right now we store a 1-deep "most recent wins" claims JSON payload for each public key we discover/start. We can probably use the same general-purpose lattice cache bucket and migrate to query model versus push.

### Emit and Store Errors and Success
When a capability provider attempts to apply a link definition, it should emit a failure event indicating that the application failed and, if available, the reason for the failure. This will go out on the standard `wasmbus.evt.{lattice-id}` topic. 

In addition to emitting success and failure, we should _store_ this. To do so, we'll use a key in the bucket that is the hash of the link definition (as discussed above) followed by a `.state` suffix. This gives us the ability to atomically push state data without risking last-write-wins conflicts on the actual raw data (configuration values) of the link definition. 

Using the _history_ functionality on a key value bucket, we can actually query the history of the changes to the `{hash}.state` key on demand. This gives dashboards, monitors, and control interface clients the ability to not only see whether a link definition is currently active, but whether and how many times it failed. We'll limit the number of historical copies of a key to something like `5` so we can retrieve just the most relevant state changes for a given link definition.

The combination of having a predictable key _and_ a useful and authoritative history of state changes feeds directly into the next section.

### Use the Key-Value Bucket as the Source of Truth
A problem with the current implementation of link definitions it that we have conflicting sources of truth. There is the in-memory cache of _each host_, the contents of the lattice cache stream, and the list of _valid_ and _accepted_ link definitions within each capability provider's memory.

The state of a link definition might have the following values (subject to change during actual implementation):
* `Idle` - the link definition exists, the most recent state is not an error, and one or more of the participants (actor or provider) are not online/discoverable
* `Active` - as above, but both the relevant actor and provider each have at least one running and discoverable instance in the lattice.
* `Error` - the most recent state of the link definition is a failure. This state occurs regardless of the online status of link participants.

The above states can correspond roughly to a "traffic light" indicator where active is green, error is red, and idle is yellow. Idle being yellow indicates that nothing is wrong, but it can't be used yet (e.g. "not ready").

During host start up, the host could simply query the cache for the data it needs.

The host could periodically true-up against the data in the key-value bucket cache to examine state (e.g. to purge failed link definitions) and to ensure that the host knows about all of the current link definitions.

Finally, treating the linkdef cache this way allows external entities to write configuration values. For example, there may be situations where we want to preload link definitions with secrets so that clients using `wash` or the control interface client don't see that data (encrypting link definitions a discussion for another day.

### Default to Disk Backed
When creating the key-value bucket for the first time, default to a persistent, disk-backed bucket. This may be the default in NATS now, but this is being included here for completeness to show that we're explicitly deciding we want this cache to be durable.

## Rationale and Alternatives
The rationale for each decision is explained in-context in all of the above discussion. There were no alternatives considered other than using an external cache other than NATS (which was quickly rejected).

## Drawbacks
There are no drawbacks here. Determining the current state of a link definition may require a tiny calculation, but since we don't have this capability today, that hardly seems like a drawback.

If a failure occurs when attempting to write the state data (e.g. a failure to accept the link by the provider), and we don't retry until it works, then we will introduce an inconsistency. This will be no worse than it is today, but we'll need to make sure we implement the appropriate "guaranteed write" logic when storing state changes.

**Comment by autodidaddict** [comment]
I edited the RFC to indicate that the claims cache basically comes along for the ride here since we're using the same stream right now for claims and link defs (the stream listens on the `lc.>` prefix)

**Comment by brooksmtownsend** [comment]
I know that https://github.com/wasmCloud/wasmcloud-otp/issues/361 has plagued us for a while, how do we think this could address this issue? Should capability providers be, rather than delivered link definitions at startup introducing this race condition, directly querying the keyvalue bucket instead? I may have missed this specifically in the RFC but this would be awesome to eliminate while we're at it.

For drawbacks, I would only add that this will be a breaking change for capability providers and we may create an incompatibility where capability providers will not work between versions of the host that support the stream and versions of the host that support the kv bucket.

**Comment by brooksmtownsend** [comment]
Another question that we never really solved with actor health requests, how do we deal with a link definition where one instance of a provider succeeded and one instance failed to establish the linkdef? In this case, the link definition would both be `Active` and `Error` (or `Idle`) but that would depend on which provider you query 🤔 

In theory, this could be a flaw in the provider design itself, but it is possible.

**Comment by brooksmtownsend** [comment]
@autodidaddict I believe this was partially addressed with the Jetstream KV changes. We're going to need to prioritize the linkdef success/error state issue then

**Comment by autodidaddict** [comment]
I am going to close this RFC as we've been running on "real" key-value store link definition data for a while now, and that addresses one of the main concerns of this RFC. I still think there is a lot that can and should be done to overhaul the way in which link definitions are managed within a lattice, but I think that merits an entirely new RFC.

**Comment by autodidaddict** [comment]
> We're going to need to prioritize the linkdef success/error state issue then

I've been doing a lot of thinking about this and the more I think about it the more this feels like addressing a symptom rather than the problem. I'm hoping there's a more holistic way to take care of some of the friction in linkdef management.
