### ISSUE TITLE
[BUG] blockingRead does not return error

### ISSUE THREAD

**Issue by peter-jerry-ye** [wasmCloud/wasmCloud#2666]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

`blockingRead` should throw the `StreamClosedError` when the read is finished while it didn't

### Steps to reproduce

1. Create a project with `wash new component hello-ts --template-name hello-world-typescript`
2. Add the following code to `http-hello-world.ts` after line 16
  ```typescript
  let inputBody = req.consume();
  let inputStream = inputBody.stream();

  let result = inputStream.blockingRead(100n);
  inputStream.blockingRead(100n);
  ```
3. Deploy with `pnpm i && wash build && wash app deploy wadm.yaml` (Also notice that the template seems to be missing `metadata.annotations.version`)
4. `curl -X PUT localhost:8080 -d "something"`

### Expected behavior

Expected: the server crashes, giving some response, same as wasmtime's behavior
Actual: hangs indefinitely

### Environment

- OS: MacOS
- Shell: zsh
- wasmcloud Version: 1.0.4
- httpserver: 0.22.0

**Comment by peter-jerry-ye** [comment]
Also tested on v1.1.0 with `wash up --wasmcloud-version 1.1.0`

**Comment by brooksmtownsend** [comment]
Does this show the error in `~/.wash/downloads/wasmcloud.log`? Curious if the typescript component is throwing an error, which it should, and wasmtime displays this in the output.

**Comment by peter-jerry-ye** [comment]
I didn't find the file `~/.wash/downloads/wasmcloud.log`. I've only got:
```
nats-server  nats.log  v1.1.0  wadm.log  washboard
nats.conf    nats.pid  wadm    wadm.pid  wasmcloud.pid
```

**Comment by brooksmtownsend** [comment]
Ah that might just be because the logs went to the foreground, makes sense.

**Comment by vados-cosmonic** [comment]
Hey @peter-jerry-ye have you tried this recently? On a branch I'm working on, I get [the stream closed error properly](https://github.com/wasmCloud/wasmCloud/pull/3369/files#diff-957215c506827c727c287b537247e8ae3c7a832b686bac4463f50517bbc9fe91R35).  You may need to update the versions of `jco` and `componentize-js` that you are using.

There are definitely some updates that need to to be made to the default examples, but you *should* get the errors, if you read enough data.

**Comment by peter-jerry-ye** [comment]
@vados-cosmonic I just tried. I confirm it's fixed. Thanks a lot!
