### ISSUE TITLE
[RFC] Web Browser (JavaScript) Host Runtime

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#27]
As we move toward a 1.0 MVP, we want to ensure that wasmCloud's ability to extend a lattice across cloud, device, edge, and everywhere in between also includes browsers. A browser should be treated just like any other potential target for deploying and executing wasmCloud actors. There are a couple of technical requirements that we need to ensure we can meet in order to create a host runtime like this:

# WebAssembly Runtime
For obvious reasons, we should have no problem interpreting WebAssembly inside a browser. As much as we dislike the automatic association between Web and WebAssembly (since we're building a runtime that includes more than browsers), it does make it easy to work with as all the major browsers support the core wasm specification.

# MessagePack
Wasmcloud uses MessagePack serialization to to communicate with capability providers and with actors to do things like health check, establish link configurations, etc. As such, any compatible host runtime would have to support messagepack serialization/de-serialization. We know through our own efforts with `waPC` and AssemblyScript that this is possible.

# Capability Providers
Just as with the Swift runtime (#26), we need to be able to support some subset of the capability provider syntax. The minimum we should support is to allow actors running in the JavaScript host to communicate and link with providers hosted elsewhere in the lattice (e.g. on other devices or in clouds or on-prem facilities, etc). Because of the dynamic nature of JavaScript, it might actually be pretty easy to build a pluggable capability provider system for JavaScript that is as flexible (or more so) than what we have for the Rust runtime via C FFI. We will, of course, need to conduct experiments to produce evidence to back up this hypothesis.

We can also take advantage of some of the intrinsic capabilities of a browser-hosted JavaScript engine, such as access to location and DOM apis, potentially exposing some "built-in" providers:
* DOM
* location
* message broker (could be supported by the NATS JavaScript/deno client, etc)

# Lattice Connectivity
We will need to be able to connect a browser-hosted wasmCloud runtime to a lattice in order to really satisfy the potential of this ecosystem. It makes the most sense to support this connectivity either through the NATS client or through straight websockets. We will have to evaluate the trade-offs between using the NATS client (which can run over NATS websockets) versus using raw websockets. The ultimate deciding factor will be whichever option provides the best developer experience.

# Signature Verification
In order to verify that modules downloaded over HTTP endpoints or via socket streams are valid and to validate their embedded claims, a browser-based wasmCloud runtime needs to verify the ed25519 signatures on the module-embedded JSON web tokens. It appears that there are multiple node and "regular" JavaScript libraries available for this, so we are less concerned about this aspect of the runtime than things like supporting lattice and capability providers.

**Comment by jsoverson** [comment]
A few questions off the top of my head:

What do you envision the app-to-wasmcloud interface looking like? On the server side, an actor can listen on a port and respond when poked, but what is the experience within an application environment?

Should the MVP be a host that can talk to the browser environment w/providers or a host that native JS can talk to via host APIs or messaging system? Or other?

Will actors that are identical outside of provider implementation be reusable across hosts? E.g. should an actor that uses a hypothetical http-request provider be used as-is across server, swift, and browser, with each host exposing the appropriate provider? This is the expectation now with par files and their bundled arch-specific binaries, but par files don't scale to the web and mobile with the memory, bandwidth, and performance constraints.

**Comment by autodidaddict** [comment]
Actors cannot listen on ports whether they're in a browser or not. all actors can do is receive messages from providers and respond to them. The MVP being discussed in this issue is a JavaScript runtime that allows wasmCloud actors to be executed and communicate with elsewhere-hosted capability providers over the lattice, and potentially have access to providers that run in a browser context for some fit-for-purpose task. For example, the NATS provider could actually be a local JavaScript provider that is acting as a NATS client rather than communicating with a remote NATS provider.

Identical actors hosted in multiple locations are considered "scaled instances" of actors. So if there's a copy of actor `foo` running in cloudA, another copy in cloudB, four running inside browsers, and one running on a Raspberry pi, the lattice will consider that there are 7 instances of actor foo running.

**Comment by jsoverson** [comment]
Thanks @autodidaddict.

Should a stated goal also be to provide support for nodejs? The bulk of wasmcloud business logic would be the same.

**Comment by autodidaddict** [comment]
I actually don't think this would be a goal. The goal is to support a browser, and by default that is likely to happen by way of being written in JavaScript/TypeScript. However, to your point, we could certainly look into something like [deno](https://deno.land/) that could potentially give us a huge chunk of node-interoperable code "for free".

**Comment by autodidaddict** [comment]
Also, to follow the pattern that we'd use with the [Swift runtime](#26), we would want to first build a `waPC` host that runs in the browser, and then package that and build the wasmCloud host on top.

**Comment by autodidaddict** [comment]
Also as mentioned in the Swift runtime issue, we'll need to support concurrency to allow for multiple actors to co-exist inside the same browser while interacting with providers (and also potentially each other). This should be feasible in modern browsers with workers but it's another thing we'll need to experiment with.

**Comment by pkedy** [comment]
I already have an initial JavaScript implementation [here](https://github.com/wapc/mandelbrot-example/blob/master/js/wapc.js) that I will pull out into its own repo and add to npm.
