### ISSUE TITLE
[FEATURE] Add ability to check references to `wash app validate`

### ISSUE THREAD

**Issue by vados-cosmonic** [wasmCloud/wasmCloud#2708]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

It's possible today to write WADM manifests that have bad references in them. It might be nice if `wash app validate` took a `--check-image-refs` or some such flag that checked to ensure that images referenced in the manifest were valid.

### Describe the solution you'd like

Add an option to `wash app validate` that causes checks whether image references are valid where present.

### Describe alternatives you've considered

N/A

**Comment by Aditya1404Sal** [comment]
Hey @vados-cosmonic -- Wouldn't it be better to include this functionality in the `wash app validate` cmd itself (natively)  instead of adding a flag to specify checking the img ref, Is there any use case that could benefit from having a dedicated flag ?

**Comment by brooksmtownsend** [comment]
I think a good benefit from having this toggleable, whether off or on by default, is that it might fail to validate simply by not having connectivity to the OCI repositories. I tend to agree that it would be nice by default to run the manifest through the whole suite of validation steps

**Comment by Aditya1404Sal** [comment]
I agree with your suggestion 😄 I'm leaning towards adding the oci reference check as a default validation step , however if connection to the oci registry isn't possible, validate continues with the rest of the suite with a warning message at the end stating something along the lines of "Validation skipped over Oci ref check, connectivity issue is highly probable"

**Comment by vados-cosmonic** [comment]
Hey @Aditya1404Sal that sounds great -- what would we do if we wanted to *make sure* that OCI references failed the test? If we added it as you're suggesting now, I'm afraid that we would have to add another thing to *force* the check to fail (or add some sort of logic to read the warnings produced)

This kind of test is quite important, so I'd assume that if someone was adding it, they really want it to pass, and it's a bit heavier than other checks (requires outside access), so that's why having it be opt-in might be reasonable.

That said, going with it being included as a default check + warning -- what would I do to figure out that the test failed if I really cared about it?

**Comment by Aditya1404Sal** [comment]
Hey @vados-cosmonic You're right, and I see now where I was mistaken. I didn't fully consider the issues that could arise with connectivity and how critical this check is for some users. Having it as an opt-in feature with a flag makes a lot more sense. This way, users who need to ensure their OCI references are valid can do so explicitly, without the risk of missing a failed check due to connectivity issues. Thanks for clarifying!

**Comment by vados-cosmonic** [comment]
Yeah we do certainly have some things that ARE warnings so it's not like we couldn't do it as a warning -- thanks for working on this! If you start implementing and feel like it just doesn't fit, let's re-discuss it, I'm pretty sure @brooksmtownsend is happy to go either way, and the DX/feel is so important here!

**Comment by Aditya1404Sal** [comment]
this issue can be closed!

**Comment by vados-cosmonic** [comment]
Ah thanks again for working on this @Aditya1404Sal, closing!
