### ISSUE TITLE
[FEATURE] the wasmCloud host should support a --nats-creds-file argument

### ISSUE THREAD

**Issue by protochron** [wasmCloud/wasmCloud#2724]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

The wasmCloud host currently only allows you to pass in nats credentials using two distinct arguments: `--nats-jwt` and `--nats-seed`. NATS credentials commonly are provided as a single file known as a _creds file_ that combines both the JWT and the seed key in a single file

### Describe the solution you'd like

We should add a `--nats-creds-file` argument that is mutually exclusive with the `--nats-jwt` and `--nats-seed` arguments that allows you to use a single NATS creds file.

**Comment by brooksmtownsend** [comment]
This is a great first issue! Thanks for filing & labeling @protochron.

**Comment by brooksmtownsend** [comment]
Worth noting that the implementer should mark this as a flag that conflicts with the jwt & seed arguments, which we have precedent for in the CLI

**Comment by Aditya1404Sal** [comment]
I would love to work on this issue ! can i pick this up ?

**Comment by joonas** [comment]
I believe this was addressed sufficiently in https://github.com/wasmCloud/wasmCloud/pull/2880, thoughts?
