### ISSUE TITLE
[FEATURE] move wasmcloud.toml to a different directory for a tinygo component

### ISSUE THREAD

**Issue by ritesh089** [wasmCloud/wasmCloud#2757]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

When i create a tinygo component, I am not able to move the wasmcloud.toml to a different directory other than the root.

### Describe the solution you'd like

I would like to have the ability to move the wasmcloud.toml to a different directory. I want to abstract out the specifics of wasmcloud host and provide an abstraction to the developer that looks like he/she s writing plain business logic in components.

**Comment by brooksmtownsend** [comment]
I think what would be the most useful thing to do here is add a `working_directory` or `build_directory` project configuration field to the wasmcloud.toml manifest that `wash` will use do change directory into (absolute, or relative to the wasmcloud.toml file) before attempting to run build commands.

This is a great first issue, and should almost entirely take place in the `wash-lib` crate

**Comment by brooksmtownsend** [comment]
I think in general for this issue, it would be valuable to be able to move the `wasmcloud.toml`, `wadm.yaml`, `build` and `wit` directories to other places and ensure that `wash build` can work out of the box
