### ISSUE TITLE
[FEATURE](wash) apply sort to wash get outputs

### ISSUE THREAD

**Issue by ricochet** [wasmCloud/wasmCloud#2772]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [x] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

The order of the `wash get` (list and other commands likely impacted) outputs changes. 

- inventory
- components
- links
- providers

So that the output is consistent. When running a watch, the reordering is not ideal. 

### Describe the solution you'd like

An alphabetical sort to our outputs should solve this

**Comment by brooksmtownsend** [comment]
#2883 addressed this!
