### ISSUE TITLE
[BUG] `wash build` does not support workspaces

### ISSUE THREAD

**Issue by rvolosatovs** [wasmCloud/wasmCloud#2802]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

`wash build` fails when run from within a crate in a workspace, most likely it fails to get the binary from `target` (which is not present in working directory in such case)

### Steps to reproduce

1. apply diff:
```diff
diff --git a/crates/provider-blobstore-fs/wasmcloud.toml b/crates/provider-blobstore-fs/wasmcloud.toml
new file mode 100644
index 00000000..9a41edbd
--- /dev/null
+++ b/crates/provider-blobstore-fs/wasmcloud.toml
@@ -0,0 +1,6 @@
+name = "Blobstore FS provider"
+language = "rust"
+type = "provider"
+
+[provider]
+vendor = "wasmCloud"
```

2. `cd crates/provider-blobstore-fs`
3. `/path/to/wash build`
4. observe:
```
   ...
   Compiling wasmcloud-provider-blobstore-fs v0.9.0 (/Users/rvolosatovs/src/github.com/wasmcloud/wasmCloud/crates/provider-blobstore-fs)
    Finished `release` profile [optimized] target(s) in 21.11s

No such file or directory (os error 2)
```

### Expected behavior

success

### Environment

- OS: MacOS
- Shell zsh
- wash Version v0.30.0

### Screenshots / Logs / Additional context

`wash` binary is not available in the environment, instead, the release binary is just used directly, if `wash` shells out to `wash`, that could be another reason for this bug

**Comment by rvolosatovs** [comment]
The fix was to use `src/bin/blobstore-fs-provider`

**Comment by vados-cosmonic** [comment]
Ah in particular (for people who might run into this): `wash build -p src/bin/blobstore-fs-provider` is the appropriate command for building a provider from the top level of the monorepo!
