### ISSUE TITLE
Deprecate the pre-1.0 wasmCloud Host Helm chart

### ISSUE THREAD

**Issue by joonas** [wasmCloud/wasmCloud#2868]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

With https://github.com/wasmCloud/wasmCloud/pull/2865 we've introduced a new `wasmcloud-host` helm chart that brings the helm chart to feature parity with the `wasmcloud-operator` deployed hosts in terms of being able to enable features on the host via configuration.

### Describe the solution you'd like

I would like to see the [old helm chart](https://github.com/wasmCloud/wasmCloud/tree/main/chart) deprecated

**Comment by joonas** [comment]
@brooksmtownsend please feel free to add any additional context you might have in mind for this 🙂

**Comment by brooksmtownsend** [comment]
I think really this should just have a quick release that updates the README in the chart to display on https://artifacthub.io/packages/helm/wasmcloud-chart/wasmcloud-chart that points to the new wasmcloud-host chart

**Comment by joonas** [comment]
This was addressed as part of #3605 and subsequently removed as part of https://github.com/wasmCloud/wasmCloud/pull/3646.
