### ISSUE TITLE
[BUG] wash snap not building components

### ISSUE THREAD

**Issue by r-carissimi** [wasmCloud/wasmCloud#2895]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

Installed wash following the [instructions provided](https://wasmcloud.com/docs/installation?os=snap), using snap. It seems not to work properly: `wash build` does not work as it cannot find `tinygo` or `rustc`. `wash new` doesn't work as it cannot find `git`. All of what is mentioned above is installed on the system. 

Thought about using the `--classic` flag when installing the snap, or write a warning on the website.

### Steps to reproduce

1. Install wash using [snap](https://wasmcloud.com/docs/installation?os=snap)
2. Install git on the host system
3. Create a new component, from a template `wash new component hello --template-name hello-world-tinygo` (or compile one using `wash build`)

### Expected behavior

I expect it to create/build the component.

### Environment

- OS: Ubuntu Linux, 24.04
- wash: 0.12.0

### Screenshots / Logs / Additional context

```
$ wash build
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wit-bindgen-go-0.30.0/src/lib.rs:337:18:
failed to spawn gofmt: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by markkovari** [comment]
Hey @r-carissimi,

I usually not use the snap store to install things, but I was able to reproduce the error mentioned above. It still persist with the following versions as well using the "edge" channel, which is mentioned in the docs as linked.


```bash
wash -V
```

```
wash          v0.35.0
├ nats-server v2.10.20
├ wadm        v0.17.0
└ wasmcloud   v1.3.0
```

my OS/kernel version is: Ubuntu 24.04.1 LTS (GNU/Linux 6.8.0-47-generic x86_64). 🤔 

I will try to look into this later as my time allows, but as an alternative you can install it with the script for the [Ubuntu/Debian](https://wasmcloud.com/docs/installation?os=ubuntudebian), it was working for me reliably.

I am definitely not a snap magician, but will look around why snap cannot see/invoke things in the path. 

@r-carissimi just for clarification, before I would jump on conclusion would you please confirm that you are on the same wash version please?


p.s.: I just realized that the "version" that is displayed might be incorrect too during snap install

```bash
sudo snap install wash --devmode --edge
```
led to 
```
wash (edge) 0.12.0 from wasmCloud installed
```

and the installed version (again) is

```
wash          v0.35.0
├ nats-server v2.10.20
├ wadm        v0.17.0
└ wasmcloud   v1.3.0
```

**Comment by markkovari** [comment]
I did not found the application in the [snapcraft site](https://snapcraft.io/) although the 
```bash
snap list
```
has the following output:

```
Name                       Version          Rev    Tracking         Publisher   Notes
bare                       1.0              5      latest/stable    canonical✓  base
core20                     20240911         2434   latest/stable    canonical✓  base
core22                     20240904         1621   latest/stable    canonical✓  base
firefox                    125.0.2-1        4173   latest/stable/…  mozilla✓    -
firmware-updater           0+git.7983059    147    latest/stable/…  canonical✓  -
gnome-42-2204              0+git.510a601    176    latest/stable/…  canonical✓  -
gtk-common-themes          0.1-81-g442e511  1535   latest/stable/…  canonical✓  -
snap-store                 0+git.4fcd62b7   1218   latest/stable/…  canonical✓  -
snapd                      2.63             21759  latest/stable    canonical✓  snapd
snapd-desktop-integration  0.9              253    latest/stable/…  canonical✓  -
wash                       0.12.0           92     latest/edge      wasmcloud   devmode
```

I am pretty sure this supposed to be `0.35.0` or `v0.35.0`, but please correct me if I am wrong.
Currently I am looking into some cryptic `strace` logs to see how/when the PATHs are inaccessible for the process.

**Comment by r-carissimi** [comment]
Hey @markkovari, thanks for your interest.
Indeed, I ended up installing wash using the link you kindly mentioned above.

Regarding the version: you're right! The (actual) version is the following, since I didn't make use of the edge channel

```
wash          v0.31.0
├ nats-server v2.10.18
├ wadm        v0.14.0
└ wasmcloud   v1.2.0
```

Let me know if you need further info!

**Comment by vados-cosmonic** [comment]
Hey @markkovari so I don't think many users in the wasmCloud ecosystem use snap right now... Most people install with `cargo` or via binary release, etc.

At the very least I personally don't run Ubuntu, and don't use snaps... So yeah it's unfortunate that this was broken, I'm a bit surprised that the version was completely different.

I don't know how easy it would be, but we could try to add a test to the [snap generating CI automation](https://github.com/wasmCloud/wasmCloud/blob/main/.github/workflows/wasmcloud.yml#L624), *just* to avoid this happening again (or at least be alerted/avoid publishing if it does.

**Comment by markkovari** [comment]
Thanks @vados-cosmonic, just for the record; the snap packages version is coming from here https://github.com/wasmCloud/wasmCloud/blob/main/crates/wash-cli/snap/snapcraft.yaml#L3 and it can be with a bit of magic overwritten it ten release pipeline. I am not entirely sure how people are using packages across distributions (maybe this can be snaps strenght?!). But if the documentation mentions it should be usable. 

I'll read a bit about the plugins, but as far as I understood the snaps have their own environment and they can communicate with the host if tehy are in classic confinement mode or the plugins allow them to do so.

**Comment by brooksmtownsend** [comment]
I just realized we don't even update the version on the snap 🤔 https://snapcraft.io/wash it seems like there's a lot we're not taking advantage of here.

Out of practicality, I'm going to suggest the unfortunate solution of removing the snapcraft package for now. I don't mind supporting many package managers, I just don't know if we have the maintainer expertise to keep the snap up-to-date like we do for homebrew. I'm curious if this would be a huge blocker to anyone running Linux, or if the apt/rpm fallbacks would work fine

**Comment by markkovari** [comment]
Yeah, totally agree. I mean not sure if snapcraft has meaningful download statistics (which are not bloated by bot invocations _- yes I am talking about npm -_ ). 

Should we just remove the option from the docs I guess? Not sure who is the owner of the snap org and or what is the deprecation process with these.
I might worth to add a nice message for the current discontinuation of the package if it would stay there for some time with the alternatives.

(Not sure if people can resume it later or not, the package is not searchable as is in the snapstore). 


Wow, snap has a nice little geolocation usage stats at the bottom.
