### ISSUE TITLE
[FEATURE] Component examples should use crates/libraries

### ISSUE THREAD

**Issue by ricochet** [wasmCloud/wasmCloud#2911]
### Affected project(s)

- [ ] documentation
- [X] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the solution you'd like

Our examples should establish best practices. There are libraries that are now enable more ergonomic workflows when working with WASI API's like wasi-rs and wasmcloud_component).

**Comment by brooksmtownsend** [comment]
YES PLEASE

**Comment by brooksmtownsend** [comment]
We're doing a much better job with this with `wasmcloud_component`, and the remaining work here is transitioning examples over to use that crate. For folks looking to contribute, this is a great first issue since it's constrained to just refactoring one example!
