### ISSUE TITLE
[FEATURE] Add command to generate markdown docs for wasmcloud host

### ISSUE THREAD

**Issue by lachieh** [wasmCloud/wasmCloud#2992]
### Affected project(s)

- [X] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

It'd be great to be able to generate docs from the clap options/env vars for wasmcloud host, similar to how @ericgregory [implemented this for wash](https://github.com/wasmCloud/wasmCloud/pull/2777).

### Describe the solution you'd like

The end goal is that docs get generated. I don't know that this functionality needs to be part of the wasmcloud host binary, and perhaps in could be included as part of wash.

### Additional context

This would help prevent problems like this: wasmCloud/wasmcloud.com#596

**Comment by peter-jerry-ye** [comment]
It will also help to keep the documents up to date as the current document actually lacks configurations related to the wasm resource control such as `WASMCLOUD_MAX_EXECUTION_TIME_MS`

**Comment by brooksmtownsend** [comment]
As a stopgap, or for intermediate use, https://docs.rs/wash-lib/0.30.0/wash_lib/parser/struct.WasmcloudDotToml.html is available and contains all the fields that the parser expects

**Comment by brooksmtownsend** [comment]
Fixed by #3607, great work @vangourd!
