### ISSUE TITLE
[BUG] Cannot import/use wasi:random/insecure

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmCloud#3003]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

If you have a component that uses `wasi:random/insecure` either through its world or via the wasmcloud_component crate, you end up with an error when starting:

```
2024-09-13T20:58:41.299045Z ERROR wasmcloud_host::wasmbus: failed to scale component component_ref=file:///Users/taylor/Documents/code/data-migration/migrator/build/migrator_s.wasm component_id=migrator err=failed to link item

Caused by:
    0: failed to instantiate `wasi:random/insecure@0.2.0` in the linker
    1: map entry `wasi:random/insecure@0.2.0` defined twice
 ```

**Comment by brooksmtownsend** [comment]
Should be fixed by https://github.com/wasmCloud/wasmCloud/pull/3031 !
