### ISSUE TITLE
[BUG] Quickstart example of `docker compose --file wasmcloud.yaml up` ends with a Prometheus related error

### ISSUE THREAD

**Issue by mlliarm** [wasmCloud/wasmCloud#3065]
### Affected project(s)

- [X] documentation
- [X] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

Hello,

I tried going through the [quickstart](https://wasmcloud.com/docs/tour/hello-world?env=docker&lang=tinygo) but I got the following error:

`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/michail/Documents/dev/docker/wasmCloud/prometheus.yml" to rootfs at "/etc/prometheus/prometheus.yml": create mount destination for /etc/prometheus/prometheus.yml mount: cannot mkdir in /var/lib/docker/overlay2/b6e168cb45139b542d5048e2c456a78216ff4b5a3110623b14bd2cfe92fcf84a/merged/etc/prometheus/prometheus.yml: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

### Steps to reproduce

1. Download the docker compose manifest [from here](https://github.com/wasmCloud/wasmCloud/blob/main/examples/docker/docker-compose-full.yml).
2. Run `docker compose --file docker-compose-full.yml up`
3. Wait (a bit)

### Expected behavior

I'd expect not to see any errors at the end, but most likely I'm missing something.

### Environment

- OS: Ubuntu 22.04.5 LTS, x86_64
- Shell: GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
- wasmcloud Version: wasmcloud@latest
- Docker: 27.2.1
- 

### Screenshots / Logs / Additional context

![image](https://github.com/user-attachments/assets/572695c1-e296-4bc2-b0ae-dcec6b7e4011)

**Comment by vados-cosmonic** [comment]
Hey @mlliarm thanks for reporting this! What folder are you running from? Do you happen to be running from a folder that *isn't* `wasmcloud/examples/docker` ?

It seems like `docker compose` is attempting to find `/home/michail/Documents/dev/docker/wasmCloud/prometheus.yml`, which I think should be `/home/michail/Documents/dev/docker/wasmCloud/examples/docker/prometheus.yml` if you have the project cloned?

**Comment by mlliarm** [comment]
Hey @vados-cosmonic, thanks for the fast response !

You're right, I'm running it from `~/Documents/dev/docker/wasmCloud/`.

But to be honest, if it's looking for a `prometheus.yml` locally, because I'm a rather noob still, shouldn't I have locally that file as well? 

Let me try creating those directories again and I'll rerun docker compose and update this issue.

It's most likely a documentation issue indeed, I wouldn't call it a bug, but couldn't find a more fitting option :) !

**Comment by mlliarm** [comment]
Actually I'm an idiot, I hadn't realized I had to have the repository cloned in order to run the `docker compose` example. 

I'm doing it now, and I'm sure it'll work just fine.

**Comment by mlliarm** [comment]
Yes, that did the trick. I only have a minor error now:

`Attaching to grafana-1, nats-1, otelcol-1, prometheus-1, registry-1, tempo-1, wadm-1, wasmcloud-1
Gracefully stopping... (press Ctrl+C again to force)
Error response from daemon: driver failed programming external connectivity on endpoint docker-registry-1 (c46cdc5b2e9ba35caf2f33bede58152230563ff6519cd7b5e16af2f27987680a): Bind for 0.0.0.0:5000 failed: port is already allocated`

This is what `docker ps` returns, if it helps:

```
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS          PORTS                                                                                                                             NAMES
f097035c7ff2   prom/prometheus:v2.49.1   "/bin/prometheus --c…"   33 seconds ago   Up 32 seconds   0.0.0.0:9090->9090/tcp, :::9090->9090/tcp                                                                                         docker-prometheus-1
029d6ac7d848   grafana/tempo:2.3.1       "/tempo -config.file…"   33 seconds ago   Up 32 seconds   0.0.0.0:7999->7999/tcp, :::7999->7999/tcp, 0.0.0.0:32777->4318/tcp, [::]:32777->4318/tcp                                          docker-tempo-1
70af015e5682   registry:2.8              "/entrypoint.sh /etc…"   4 minutes ago    Up 4 minutes    0.0.0.0:5000->5000/tcp, :::5000->5000/tcp                                                                                         wasmcloud-registry-1
c604701d1f25   nats:2.10-alpine          "docker-entrypoint.s…"   4 minutes ago    Up 4 minutes    0.0.0.0:4222->4222/tcp, :::4222->4222/tcp, 0.0.0.0:6222->6222/tcp, :::6222->6222/tcp, 0.0.0.0:8222->8222/tcp, :::8222->8222/tcp   wasmcloud-nats-1
```

**Comment by vados-cosmonic** [comment]
Thanks for putting fresh eyes on this -- our documentation is definitely flawed! If you want to make the contribution we'd love to have it, you could start making edits here:

https://github.com/wasmCloud/wasmcloud.com/blob/main/docs/tour/hello-world.mdx?plain=1#L50

Finding the odd points of the documentation is really useful to us, I'd be happy to review any changes that you think make it more straight forward for people to actually get started here! At the very least clearly we need to be up front about cloning & `cd`ing!

**Comment by mlliarm** [comment]
I'd love to help with the docs :)

**Comment by vados-cosmonic** [comment]
Thanks so much :bow: ! I'll keep an eye out for PRs -- feel free to throw up something and we can work on it together, also @ericgregory is our resident documentation expert so he might be chiming in (or might get to the review before me!) :)

**Comment by mlliarm** [comment]
Fixed the minor error I mentioned 3 comments earlier, it seems some containers were running that shouldn't and were blocking the port. I killed those two containers for the registry and nats, and when I reran `docker compose ... up`, everything started rolling as it should (Graphana logs etc). 

As this was inappropriate for the main product repo, I'll move to the documentation repo and close this.
