### ISSUE TITLE
[BUG] OpenTelemetry endpoints not set in provider host data config

### ISSUE THREAD

**Issue by jamesstocktonj1** [wasmCloud/wasmCloud#3080]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

The wasmcloud host does not pass on the OpenTelemetry endpoints when starting a new provider. This means that the `provider-sdk-go` is unable to retrieve the observability endpoint.

### Steps to reproduce

Start wasmcloud using the following environment variables:
```
WASMCLOUD_TRACES_ENABLED=true OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:4318 wash up
```

Using some logs, I am able to print the raw decoded HostData string within `provider-sdk-go`. The logs show that the tracing boolean is set to true but the traces endpoint is blank:
```
{
    "host_id": "NBDBBFKSOMZBNQHXU4NKJ4K3TRVWDWIG73HQIKTML2EVAJ5ZFDTFLUJP",
    ...
    "otel_config": {
        "enable_observability": false,
        "enable_traces": true,
        "enable_metrics": null,
        "enable_logs": null,
        "observability_endpoint": null,
        "traces_endpoint": null,
        "metrics_endpoint": null,
        "logs_endpoint": null,
        "protocol": "Http",
        "additional_ca_paths": [],
        "trace_level": "info"
    }
}
```

### Expected behavior

I expect to see `"otel_config": {"traces_endpoint": "http://localhost:4318"}` within the HostData config.

### Environment

- OS: [Linux]
- Shell [bash]
```
wash          v0.34.0
├ nats-server v2.10.18
├ wadm        v0.14.0
└ wasmcloud   v1.2.1
```

**Comment by brooksmtownsend** [comment]
Hey @jamesstocktonj1 , yes it looks like if we explicitly set the flags we will pass them down, but the environment variables don't "fill in" the OTEL configuration after the fact. I know @vados-cosmonic is working on something analogous here

**Comment by vados-cosmonic** [comment]
Just an update here -- we've fixed this on the Rust side in the new [`wasmcloud-provider-sdk` release (0.9.1)](https://crates.io/crates/wasmcloud-provider-sdk), but the *way* we've chosen to fix it is by using the config passed to the provider. 

The [pull request](https://github.com/wasmCloud/wasmCloud/pull/3088) has more details, but basically the most flexible way to ensure that you can configure providers and hosts separately going into the future is to make the config provider-specific, and *not* pass down the ENV because some client libs for OTEL ignore the in-code setting and always take the ENV override.

So what this means practically is that to solve this, we must add similar code in the Golang provider SDK that checks for relevant configuration and uploads accordingly -- [code similar to the lines in the Rust provider SDK](https://github.com/wasmCloud/wasmCloud/blob/main/crates/provider-sdk/src/otel.rs#L58)

**Comment by vados-cosmonic** [comment]
Another update -- since @joonas has [made the change to ensure that the values show up in host data](https://github.com/wasmCloud/wasmCloud/pull/3135), this should be solved at the next wasmCloud release & corresponding `wash` update (to use the new host version by default)

**Comment by vados-cosmonic** [comment]
Another update -- since @joonas has [made the change to ensure that the values show up in host data](https://github.com/wasmCloud/wasmCloud/pull/3135), this should be solved at the next wasmCloud release & corresponding `wash` update (to use the new host version by default)

**Comment by joonas** [comment]
@jamesstocktonj1 it's worth pointing out that when you are overriding an individual signal endpoint via `OTEL_EXPORTER_OTLP_<SIGNAL>_ENDPOINT`, I _think_ you'll also want to include the signal path (in this case `/v1/traces`) per the OpenTelemetry spec: https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/#otel_exporter_otlp_traces_endpoint

In the case of [Go](https://github.com/wasmCloud/provider-sdk-go/blob/56a33cfe9d79429ef913386b711dead1b13d3b8c/host.go#L115-L148) and [Rust](https://github.com/wasmCloud/wasmCloud/blob/ebe8ba9c7984a158c2c7e787bf02a420be62c530/crates/core/src/otel.rs#L81-L133), we handle this for you when you're using the plain `OTEL_EXPORTER_OTLP_ENDPOINT` variable, but in case of a specific signal (as is the case with `TRACE` here), we use the provided value exactly as provided.

**Comment by vados-cosmonic** [comment]
Hey @jamesstocktonj1 with the newest [wash-cli release (0.35.0)](https://crates.io/crates/wash-cli/0.35.0) ([Github Release](https://github.com/wasmCloud/wasmCloud/releases/tag/wash-cli-v0.35.0)) your providers *should* be getting the values from the host properly if you set ENV vars like `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` before running `wash up` -- would you mind confirming that it's fixed for you?

Ah note that you'll of course need to pipe through the values (they wont' be set on the ENV of the provider)

**Comment by vados-cosmonic** [comment]
No worries -- take your time!

**Comment by vados-cosmonic** [comment]
Hey let's close this and re-open if it's still an issue! I think the stalebot might get to it if we don't do anything in the meantime.
