### ISSUE TITLE
[BUG] Invocation of custom interfaces' functions will hang if 'link name' is set in Wadm manifests.

### ISSUE THREAD

**Issue by ossfellow** [wasmCloud/wasmCloud#3082]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [X] other / not sure

### Describe the bug

When `wasmCloud v1.2.0` and `Wadm v0.14.0` were released, suddenly my custom provider stopped responding to function invocations, or rather such calls would hang!
So, this weekend, I built a `debugging version` of wasmCloud, turned on `tracing`, and captured the interactions, which revealed `link name`, which I set for all links, is not being picked up (i.e. `default` is used no matter what), causing misconfiguration and a broken invocation path.

To rule out my custom provider as the root cause, I used the wasmCloud's example [custom-template provider](examples/rust/providers/custom-template) to reproduce the issue. I added `link names` to the `wadm.yaml` file (and corrected a typo in provider's image name):

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: custom-template-provider
  annotations:
    version: v0.0.1
    description: 'An application with a provider and component built for extending wasmCloud with custom capabilities'
spec:
  components:
    - name: test-component
      type: component
      properties:
        image: file://./component/build/custom_template_test_component.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        # Link the component to the provider on wasmcloud:example/system-info
        - type: link
          properties:
            name: system-info
            target: custom-template
            namespace: wasmcloud
            package: example
            interfaces: [system-info]

    - name: custom-template
      type: capability
      properties:
        image: file://./build/wasmcloud-provider-custom-template.par.gz
        id: custom-template
        config:
          - name: provider-config
            properties:
              foo: bar
      traits:
        # Link the provider to the component on wasmcloud:example/process-data
        - type: link
          properties:
            name: process-data
            target: test-component
            namespace: wasmcloud
            package: example
            interfaces: [process-data]
``` 

Here's a snippet of the `wasmcloud.log` file, which shows the actions resulting from issuing `wash call custom-template wasmcloud:example/system-info.call` command (`wasmcloud.log` file is attached, but I couldn't attach wadm.log):

```log
2024-09-22T21:32:35.684568Z TRACE handle_scale_component_task:start_component:instantiate_component:serve_wrpc:wit-bindgen import{module="logging" function="log"}: wasmcloud_runtime::capability::wasmtime_bindings::wasi::logging::logging: call level=Level::Info context="" "Data received: Data { name: \"sup\", count: 3 }"
2024-09-22T21:32:35.684701Z  INFO handle_scale_component_task:start_component:instantiate_component:serve_wrpc:wit-bindgen import{module="logging" function="log"}:log:log{level=Level::Info context="" "Data received: Data { name: \"sup\", count: 3 }"}: wasmcloud_host::wasmbus::handler: Data received: Data { name: "sup", count: 3 } component_id="custom_template_provider-test_component" level=Level::Info context=""
2024-09-22T21:32:35.684803Z TRACE handle_scale_component_task:start_component:instantiate_component:serve_wrpc:wit-bindgen import{module="logging" function="log"}: wasmcloud_runtime::capability::wasmtime_bindings::wasi::logging::logging: return result=Ok(())
2024-09-22T21:32:35.685272Z  WARN handle_scale_component_task:start_component:new:new:link_item:link_instance:link_item:link_function:invoke{instance="wasmcloud:example/system-info" func="request-info"}: wasmcloud_host::wasmbus::handler: no links with link name found for instance instance="wasmcloud:example/system-info" link_name="default" target_instance="wasmcloud:example/system-info" self.component_id="custom_template_provider-test_component"
```

Interestingly enough, the `component-to-provider` call succeeds, but the call from `provider-to-component` hangs, because as the `WARN` line shows, it's sent to a link with name `default`, which isn't the `name: process-data`, which was set in the `wadm.yaml` manifest.
In the case of my custom provider, the very first call hangs, but the message is the same, and shows the correct link name is not picked up.

[wasmcloud.log](https://github.com/user-attachments/files/17091884/wasmcloud.log)

### Steps to reproduce

1. Build `wasmCloud` for `[target.debug]`.
2. Run command `WASMCLOUD_LOG_LEVEL="trace" wash up --detached`.
3. Locally build and deploy the `custom-template` provider following [its instructions](examples/rust/providers/custom-template), making sure `link names` are added to its `wadm.yaml` before deployment (there's a typo in the provider's image name too; it should be `file://./build/wasmcloud-provider-custom-template.par.gz`).
4. Run command `wash call custom-template wasmcloud:example/system-info.call`.
5. Check `wasmcloud.log` and search for `WARN` term.

### Expected behavior

The user supplied `link names` should be used, which would solve the `call is hung` situation.

### Environment

- OS: `MacOS`
- Shell: `zsh`
- wasmCloud Version: `v1.2.1`
- Wadm version: `v0.14.0`

**Comment by brooksmtownsend** [comment]
https://github.com/wasmCloud/wasmCloud/pull/3060 likely assists with logging this

**Comment by brooksmtownsend** [comment]
https://github.com/wasmCloud/wasmCloud/pull/3060 should ensure this exits instead of hanging
