### ISSUE TITLE
Need the ability to use a local OCI registry for CI builds and offline development

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#31]
This is also needed for testing. There are a couple of use case scenarios where I'll need to put a particular revision of a file into an OCI registry so that  I can then attempt to do a live update , and I can't really pull this off using a public OCI registry.

Additionally, having this ability to have a "ready to use" OCI in our build pipelines will cut down on build times and probably keep costs down  :smile: 

@billyoung Any thoughts on approaches here?

**Comment by autodidaddict** [comment]
It appears as though this is what we need to do in order to have a local registry: https://docs.docker.com/registry/deploying/

**Comment by billyoung** [comment]
The local development piece of this should be solved by https://github.com/wasmCloud/wasmCloud/pull/43

Happy to assist in adding similar functionality to the CI pipeline, but would need to understand more about what we want the flow to look like. @autodidaddict

**Comment by brooksmtownsend** [comment]
This looks like it was closed in #43, @autodidaddict?

**Comment by autodidaddict** [comment]
Yeah I think that docker-compose works for manual, ad-hoc local availability.

As we discussed, we _could_ fake a cache so that the wasmcloud host running in the CI pipeline just uses the binaries we deem appropriate from the cache.
