### ISSUE TITLE
[BUG] wash up command can fail silently when trying to set up leaf node connections

### ISSUE THREAD

**Issue by laetho** [wasmCloud/wasmCloud#3109]
### Affected project(s)

- [X] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

`wash up` can fail silently  when setting up wasmcloud (--nats-remote-url) with a leaf node connection to a central cluster. 

It would be helpful to log information on where `wash up` writes the nats server config, so that can be more easily inspected and tested.

In our case, auth with credential file seemed to work, but a leaf node connection could not be created because of a config error on our end. But no indication was surfaced.

wasmcloud works locally, but no leafnode connections are set up.

### Steps to reproduce

Pre-requisite, faulty leafnode config on nats-server :)

wash up --nats-remote-url tls://your.nats.cluster --nats-credsfile /path/to/nats.creds --log-level DEBUG

### Expected behavior

- I would like to see a INFO log message on where the nats.conf gets written.
- If possible a mechanism to surface nats server errors to `wash up` logs.
- In the documentation there should be a hint to where the config is and how to debug it.

I found my issue the following way:

```
cd ~/.wash/downloads
nats-server -c nats.conf
```

### Environment

wash          v0.33.0
├ nats-server v2.10.18
├ wadm        v0.14.0
└ wasmcloud   v1.2.1

**Comment by vados-cosmonic** [comment]
Thanks for this @laetho -- silent failures are the worst. 

Saving the output of NATS server logs alongside `wash up` is definitely a great idea as well -- we're doing some work to change *where* wash logs get put, but that point is actually worth an issue in-and-of itself (I might make one just to make sure we get that solved)

As for the ensuring the information is printed/we avoid teh silent fail, are you up for contributing the fix, or should I take a look at it?

**Comment by laetho** [comment]
My journey into the wasmcloud ecosystem has just started, so confidence is low. Feel free to take a look at it.

**Comment by brooksmtownsend** [comment]
We've been doing a bit of brainstorming here around possibly embedding NATS/wadm/wasmCloud as things we run with `wash up` instead of separate binaries, this may help the notion of successfully starting up. That's somewhat an aside, though, and probably isn't the most efficient way to tackle this issue
