### ISSUE TITLE
[RFC] Multitenancy in wasmCloud

### ISSUE THREAD

**Issue by protochron** [wasmCloud/wasmCloud#3120]
### RFC Title

Multitenancy in wasmCloud

### Introduction

The goal of this work is to make it possible to run a wasmCloud host that is
capable of running workloads for multiple lattices at the same time. A host
should also be able to run a workload for *any* lattice if requested, which is
a very different way of looking at lattices compared to the current model.

As part of this work, we propose the following changes:

* Add a dedicated control plane to manage lattices and in the future provide
other cluster-level APIs
* Use NATS distributed authentication in order provide a security boundary
around lattices

### Motivation

([RFC2119](https://datatracker.ietf.org/doc/html/rfc2119) definitions used here)

* A wasmCloud host *must* be able to run workloads for multiple lattices at the
same time if properly configured.
* A wasmCloud host *must* be able to automatically pull credentials for a
lattice if using distributed auth with dedicated lattice accounts.
* A single wasmCloud host *must* be capable of running workloads for all
lattices if needed.
* The current single-lattice model *must* be preserved as an option along with
being the default for backwards compatibility and for less complex deployments.
* A control plane implementation *must* exist so that a wasmCloud host can
automatically be granted credentials to access a lattice if necessary.
* A wasmCloud host *should* be configured with a set of lattice IDs it is
allowed to run workloads for. The default will be to run workloads for all
available lattices.

### What is a lattice?

The [docs provide a good
overview](https://wasmcloud.com/docs/hosts/lattice-protocols/name) of the goals
of a lattice, but at a low level a lattice is just a NATS subject prefix.
Specifically it's the value set on `wasmbus.{ctl,rpc,evt}.{lattice}`.

Right now that value is a single string that is set when the host starts.

Lattices allow users to subdivide their wasmCloud clusters by isolating groups
of related applications in their own container. This allows you to have
multiple applications with the same name but running in different lattices,
which guarantees that application names must only be unique in the scope of a
lattice. They also serve as logical partitions for groups of related
applications, team boundaries or other non-technical requirements.

Implicit in this definition is that a lattice can be both a security boundary
and logical boundary. In wasmCloud cluster that does not use distributed
authentication, a lattice is only a logical boundary, or a means of separating
applications. Due to the way that distributed authentication works in NATS, you
could also use lattices as hard security boundary by provision lattices as
*dedicated NATS account*s.

The intent of this RFC is to allow hosts to run workloads for multiple
lattices, along with supporting a hard security boundary between lattices by
tying together a NATS account with a lattice when running in a multi-tenant
mode using NATS distributed auth.

### Background reading

* [NATS Distributed Auth](https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_intro/jwt)
* [NATS Auth Callout](https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_callout)

### Changes to wasmCloud

A multitenant wasmCloud can run in one of three modes:

#### Fully unauthenticated

This is the status quo only with hosts being able to choose which lattices they
should run workloads for. The default should be to run for every lattice in the
system, so all that should have to change is adding wildcards in the correct
places in the host

#### Distributed auth using a single lattice account

This is the mode that we should recommend for usage by small teams for
production-grade setups. It is *not* as secure as running with dedicated
accounts per lattice, but does lock down the cluster using distributed
authentication.

The advantages for end users are that they do not need to be responsible for
generating unique account keys per lattice, manage key revocation and all of
the other headaches of a fully secure setup. The downside is that wrpc traffic
is *not* isolated, so a user or host credential would be able to make requests
to any lattice as long as they are authenticated. This is the same level of
security as provided in the fully unauthenticated configuration, however the
tradeoff is likely worth it for end users that are not as concerned about
insider threats. However sophisticated end users could configure additional
account or user restrictions, and we will likely want to expose APIs for doing
so.

We will need to provide a script or a tool that bootstraps a basic NATS
hierarchy using a single operator (`wasmCloud Operator`) that has the following
accounts:

* `SYS`
* `WASMCLOUD SYSTEM`
* `WASMCLOUD USER AUTH`
* `WASMCLOUD HOST AUTH`
* `WASMcLOUD LATTICE`

The [distributed auth](#NATS-Distributed-Auth) section describes each of these
accounts in depth.

Hosts authenticate to the `WASMCLOUD HOST AUTH` account using a *sentinel
credential*, which is a shared NATS user with no pub-sub privileges. This
allows the host to connect to the cluster so that it is able to receive control
interface commands, configuration commands, and communicate with the lattice
API and other future control plane APIs.

Lattice traffic is delegated to another account, the `WASMCLOUD LATTICE`
account. Hosts create a separate connection to this account for handling wrpc.

Users also authenticate to the wasmCloud cluster using auth callout with a
fixed sentinel credential. In this mode, a user credential needs to be mapped
to the `WASMCLOUD SYSTEM` lattice with the same privileges as a host, with the
addition of being able to observe wrpc traffic for debugging.

The `WASMCLOUD SYSTEM` lattice stores all of the cluster-level state, which
includes the `LATTICEDATA_*` and `CONFIGDATA_*` buckets. Access to an
individual lattice’s storage can be restricted by imposing limitations on User
credentials, but a more fully featured isolation model is describe below.

#### Distributed auth using multiple accounts

This is the most secure mode that a wasmCloud cluster can run in and is
recommended for enterprise deployments. In this mode, each lattice is
configured as a dedicated NATS account. This makes a lattice a hard security
boundary in addition to being a logical partition for encapsulating groups of
related applications.

In order to enable this functionality, wasmCloud needs a concrete lattice
object stored in the NATS cluster in order to know which lattices exist. This
is because we need a mapping between a lattice and a NATS account, along with
potentially other parameters such as a particular role or signing key to use
for hosts.

The account hierarchy looks similar to what we configure for distributed auth
with a single lattice account:

* `SYS`
* `WASMCLOUD sYSTEM`
* `WASMCLOUD USER AUTH`
* `WASMCLOUD HOST AUTH`
* `$lattice`

In this mode the control plane creates a dedicated account each time a new
lattice is created. The account keys are stored in a centralized store and the
control plane is able to retrieve them on demand when handling auth callout to
lattice accounts. The wasmCloud host needs a flag  (`--client-per-lattice`) in
order to support this behavior, since it needs to be configured to use a
dedicated client per lattice. This is contrast to the single account model
where we only need to dedicated clients: one for control APIs and one for wrpc.

The downside to operating in this mode is that we no longer have the ability to
proxy all wasmCloud host connections through a leaf node out of the box. It is
possible to do so, but we’d likely need to either wrap a leaf node binary with
our own code to coordinate credential management between the host and the leaf
node to properly manage remotes *or* embed a leaf node in the wasmCloud host
itself to do the same thing.

We use auth callout in the same way as outlined above for host authentication
to the cluster. However user authentication will require a different model
since a user can manage multiple lattices.

We have two options here:

* Generate user credentials using signing keys on each lattice account and
cache credentials using a keyring in `wash`. This is the simplest way to handle
permissions since we can have a dedicated `user` role on each account and the
auth callout implementation makes the final decision on whether or not a user
is authorized to access a lattice.
* Generate unique NATS accounts *per user* as part of the auth callout flow as
they authenticate. These NATS accounts would effectively be a materialized view
of all of the permissions a given user in the cluster and would change whenever
their group membership changes or other permissions are granted in an external
system.

This affects scheduling with auctions, since the host needs to take lattice
allowlists into account.

### NATS Distributed Auth

Up until now the wasmCloud project has not made any recommendations for best
practices for implementing NATS authentication. The following describes our
recommended NATS hierarchy, and what the project will adopt as a best practice
moving forward.

A NATS hierarchy is rooted in a single *Operator* key, which is analogous to
a root CA certificate in TLS. An Operator is associated with a single NATS
server, cluster or supercluster and is responsible for signing *Account* JWTs
and applying limits to each account. Accounts can *import* and *export*
subjects to other accounts, which allows you to share subjects if needed.

An Account issues *User* JWTs that encode limits on what subjects a particular
user is allowed to access.

We will use a single Operator (the `wasmCloud Operator`) seeded on every NATS
server in a wasmCloud cluster. This is a standard practice for locking down
NATS clusters, and while you can add multiple *trusted operators* to a NATS
cluster in order to trust JWTs signed by Operators used by external NATS
clusters, doing so is an addtional complication on top of running a NATS
cluster or supercluster. We _may_ adopt recommendations on using multiple
Operators in a single cluster or supercluster as use cases emerge.

The following table outlines the NATS accounts we will require in a
production-grade wasmCloud cluster:

| Name                  | Description                                                                               |
| ---                   | ---                                                                                       |
| SYS                   | Needed for administrative actions in NATS                                                 |
| WASMCLOUD SYSTEM      | This account is what all wasmCloud hosts, wadm and the control plane APIs connect to.     |
| WASMCLOUD SYSTEM AUTH | This account configures auth callout for wasmCloud hosts and other control-plane services |
| WASMCLOUD USER AUTH   | This account configures auth callout for users interacting with wasmCloud using `wash`    |

#### SYS

The SYS account is the account used for NATS-server internal traffic, and is
also used for system-level [monitoring
events](https://docs.nats.io/running-a-nats-service/configuration/sys_accounts#system-account).
Enabling this account is a best practice and is required for advanced NATS
monitoring along with being able to update account JWTs once a cluster has
started.

#### WASMCLOUD SYSTEM

The `wasmCloud System` account is what wasmCloud uses for control-interface
traffic, the wadm API, secrets backends and other control-plane level APIs
which will be outlined in this RFC. Access to this account *must* be limited to
only those entities for security, however users will also need to be able to
run commands using `wash`, so we will need to be able to issue credentials that
can write to subjects in this account. We can do so using account *exports*
imported by a user-specific account.

| Name                        | Subject               |
| ---                         | ---                   |
| wadm                        | wadm.api.*.>          |
| wasmCloud Config            | wasmbus.cfg.*.>       |
| wasmCloud Control Interface | wasmbus.ctl.v1.*.>    |
| wasmCloud Events            | wasmbus.events.*.>    |
| wasmCloud Secrets           | wasmcloud.secrets.*.> |

Each of these subjects are the same subjects normally used by wasmCloud hosts
for command and control, however they include an additional level of nesting
(the `*` wildcard). In fully isolated wasmCloud configurations, this wildcard
is actually the *account public key* of the lattice account. For example, a
sample lattice called `test-lattice` with an account
`ADJEC6Y3SMQCFI4KBHOSOI24XZCF6DHCBQ3YGRPU3MKF7VDHZQEMLLJQ` would import the
`wasmbus.cfg.*.>` subject as
`wasmbus.cfg.ADJEC6Y3SMQCFI4KBHOSOI24XZCF6DHCBQ3YGRPU3MKF7VDHZQEMLLJQ.>`, with
a local remapping to `wasmbus.cfg.>`. That way if a user is authenticated to
the `test-lattice` account and issues a command to create a configuration
value, `wash` still writes out the same command as it would in an
unauthenticated lattice.

This only matters for subjects used by wash to issue commands to wasmCloud
hosts, and does not affect wrpc traffic. In fully isolated wasmCloud
configurations, wrpc traffic is fully isolated in the lattice account since it
doesn’t import the subject from the system account.

#### Lattice Accounts

A lattice account is either a shared account across all lattices in the default
configuration or a fully isolated account in enterprise deploys. In an
enterprise deployment, a lattice is 1:1 with a NATS account for a fully
isolated setup.

The lattice account needs to have the ability to generate credentials for hosts
to be able to handle wprc traffic.

### Auth Callout

A key feature in making multitenancy fully transparent to hosts and wasmCloud
user is [NATS Auth
Callout](https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_callout).
This allows us to delegate additional authorization decisions to the control
plane, and also make those decisions pluggable using WebAssembly.

Hosts or users connect to a wasmCloud cluster using a *sentinel credential*,
which is a NATS User that cannot publish or subscribe to any messages. It is
effectively a shared secret that lets you initially connect to a NATS cluster
and is configured at the account level. For hosts or users, this is the
credential we need to provide when connecting to a cluster.

We provide two different accounts with corresponding sentinel credentials: one
for hosts and one for users. This way a control plane server providing auth
callout can subscribe to authorization requests using two different accounts as
opposed to using a single account and determining if the request is for a host
or a user by inspecting the contents of the authorization request.

The process for a host is shown below:

![Multitenancy Auth Callout](https://github.com/user-attachments/assets/0fb335e0-27f7-4ca3-9e58-d46e08b9ae6f)

Out of the box, a wasmCloud control plane server will *not* authenticate
additional information provided by a host when connecting to a NATS cluster.
However, it will support the ability to run a component to run additional
validation checks as needed for both hosts and users. A full exploration of
this idea will be provided in a follow-up RFC.

### Control Plane (`Hub`?)

Inherent in this proposal is the need for a unified wasmCloud control plane. We
took a step in this direction by introducing [secrets
backends](https://github.com/wasmCloud/wasmCloud/issues/2190), which are
programs listening on a specific subject (`wasmcloud.secrets.$backend-name`) to
provide secrets for wasmCloud workloads. We now need to add an API for managing
lattices so that wasmCloud hosts are aware of which lattices exist in the
cluster. The primary reason for doing so is to map lattices to NATS accounts,
which means we need to store lattices as data instead of simply being ephemeral
subject prefixes. This idea isn’t new — both Kubernetes and Nomad require
namespaces to be created before resources can be deployed outside of the
default namespace which is bootstrapped when the system starts.

While we could add an additional binary similar to what we do with wadm, we
should instead move towards having a single set of control plane instances that
implement all cluster-level APIs *including a scheduler.*. While we could
maintain the split between the scheduler and runtime APIs, we should err on the
side of simplicity and move towards keeping the control plane simple and
contained within a single binary. This does raise the question of scaling,
which is why ex. Kubernetes control plane components are split out into
dedicated binaries. The key difference for us is that as long as API calls are
driven solely though NATS, we can retroactively decide to split out components
as needed in the future.

[This](#Hub-Configuration-Example) is an example of what configuring a unified
control plane might look like.

The control plane needs to implement the following services to start:

* Auth callout for hosts
* Auth callout for users
* The Lattice API

As part of this work, we should formalize the split between host-level APIs and
control-plane level APIs. Any api in the `wasmbus.>` subject space should be
considered an API targeting hosts and anything in the `wasmcloud.>` subject
space should be a control-plane API. Wadm is the odd duck in this formalization
since it is the only available scheduler, but not formally a part of the
control plane. We should consider promoting the wadm API to a control plane API
rooted at `wasmcloud.application` and allowing wadm to be embedded in the
control plane *or* satisfied by an external API. For now the latter requirement
requires no changes on our part other than changing the subjects that wadm
listens on and where wash issues commands.

Separate auth callout configuration for hosts and users matches our NATS
account hierarchy, which means that the control plane will run two identical
auth callout listeners, with the only distinction being which accounts they are
configured to listen on. Since auth callout is meant to be pluggable, we can
support additional authorization checks by instantiating a wasm component. This
sets us up for future work towards integrating with identity providers for user
authentication and other forms of authentication for hosts.

A WIT interface for an authorizer is provided below:

```wit
interface authorizer-types {
  use wasmcloud:secrets@0.1.0-draft/store.{secret-value};

  record error {
    // An error message
    message: option<string>,
    code: error-code,
  }

  record decision {
    // Indiates if the request should be allowed or denied
    allowed: bool,
    // An optional message to be returned to the caller
    metadata: option<list<tuple<string,string>>>,
  }

  enum error-code {
    // The check failed bcause of an error upstream of this component.
    upstream,
    // The check failed because of an internal, unknown error.
    internal,
  }

  record context {
    // The ID of the lattice the caller is attempting to access.
    lattice-id: string,

    // The values below are a subset of the values in
    // https://pkg.go.dev/github.com/nats-io/jwt/v2#ConnectOptions.

    // An opaque base64 encoded token that can be used to pass in any
    // additional information that should be parsed by the authorizer.
    token: option<string>,

    // A fixed set of credentials to use for authentication.
    username: option<string>,
    password: secret-value,

    // Client certificates if provided by the caller.
    tls: option<tls>,
  }


  // A subset of https://pkg.go.dev/github.com/nats-io/jwt/v2#ClientTLS, which
  // stores the client cerificate information of the caller.
  record tls {
    // The list of certificates provided by the client.
    // There are other fields the NATS client passes through such as the cipher
    //which we may want to include in the future.
    certificates: list<string>
  }
}


interface callout-authorizer {
  use authorizer-types.{context, error, decision};
  // Determine if a auth-callout request should be granted based on additional
  // context passed to this component.
  // This is not intended to replace the base set of auth-callout checks, but
  // is instead used by wasmCloud platform administrators to apply additional
  // verification or restrictions on user authentication.
  // The primary use case is for users or hosts to pass in opaque tokens that
  // can be used to assert the caller's identity.
  authorized: func(ctx: context) -> result<decision, error>;
}
```

The API is simple: just a single `authorized` function that takes in additional
context passed in with the initial NATS client configuration request. The
`context` parameter is defined above in WIT.

### Lattice API

Lattice state will be stored in a new KV bucket `WASMCLOUD_LATTICES`. This
bucket is stored in the `wasmCloud System` account and managed by the Lattice
API. Users with credentials to access the `wasmCloud System` lattice level will
be able to provision new lattices at will using `wash`.

An individual lattice entry will resemble the following

`wasmcloud_lattices.{LATTICE-ID}`:

```wit
record metadata {
  // The name of the object
  name: string,
  // The version of the object
  version: string,
  // The UID of the object. This is to distinguish between objects with the
  // same name that may have existed in different points in time.
  uid: string,
  // Set of annotations on the object. Meant for automated use.
  annotations: list<tuple<string, string>>,
  // Set of labels on the object. Meant for human use.
  labels: list<tuple<string, string>>,
}

record lattice {
  // Metadata relating to the lattice
  metadata: metadata,
  // The NATS account this lattice is bound to
  // If using a single account for all lattices then this field can be
  // omitted or set to the actual value.
  account: option<string>,

  // The sigining keys associated with the NATS account. We may want to expand
  // this to be map of signing key key to role names, since in our implementation
  // of  a hierarchy signing keys are *not* optional and we will be using role
  // names to identify them.
  signing-keys: option<list<string>>,

  // A description of the lattice
  description: option<string>,
  // Whether the lattice can be deleted. This needs to be true in order to
  // delete the lattice.
  deletable: bool,

  // Indicates if the lattice should be hidden from listing. We don’t
  // have a strong requirement here, but it could be useful for end users who value
  // compartmentalization. The server would need to enforce this setting to hide
  // lattices on list calls from any account that isn’t the `wasmCloud System`
  // lattice *or* the account that the lattice belongs to.
  private: bool,

  // The current status of the lattice
  status: lattice-status,
}
record lattice-status {
  // The current phase of the lattice
  // The phase idea is borrowed from Kubernetes, but the underlying states are not.
  phase: lattice-phase,
}

enum lattice-phase {
  provisioning,
  created,
  deleting,
}

record lattice-add-request {
  // The lattice to add
  lattice: lattice,
}

record lattice-add-response {
  // The version of the created lattice
  version: string,
}

record lattice-update {
  // The lattice to update
  lattice: string,
  // The account to bind the lattice to
  account: option<string>,
  // The signing keys to associate with the lattice
  signing-keys: option<list<string>>,
  // A description of the lattice
  description: option<string>,
  // Whether the lattice can be deleted
  deletable: option<bool>,
}

record lattice-update-request {
  // The lattice to update
  update: lattice-update,
  // The fields to update on the lattice
  update-mask: field-mask,
}

record lattice-update-response {
  // The updated lattice version
  version: string,
}

record lattice-delete-request {
  // The lattice to delete
  lattice: string
}

record lattice-delete-response {
  // The deleted lattice
  lattice: lattice,
}

record lattice-watch-request {
  // The lattices to watch
  lattices: option<list<string>>,
}

record lattice-get-request {
  // The lattices to get
  lattices: list<string>,
}

record lattice-get-response {
  // The list of requested lattices
  lattices: list<lattice>,
}

// A port of the protobuf FieldMask well known type.
// Should this just be a WIT flags type? It would work well for everything that
// doesn't require a nested field.
record field-mask {
  // The fields in the underlying type to update or manipulate. See
  // https://protobuf.dev/reference/protobuf/google.protobuf/#field-mask for
  // the inspiration behind this type
  paths: list<string>,
}

add: func(request: lattice-add-request) -> result<lattice-add-response, string>;
update: func(request: lattice-update-request) -> result<lattice-update-response, string>;
delete: func(request: lattice-delete-request) -> result<lattice-delete-response>;
watch: func(request: lattice-watch-request) -> result<stream<lattice>, string>;
get: func(request: lattice-get-request) -> result<lattice-get-response, string>;
```
#### wasmcloud.lattice.add.{LATTICE}

The payload is a lattice, as defined above.

#### wasmcloud.lattice.delete.{LATTICE}

Returns the lattice that was deleted.

Deleting a lattice *must* destroy all running applications in the lattice *or*
disallow deletes until the lattice does not contain any workloads.

#### wasmcloud.lattice.get.{LATTICE}

Returns a lattice definition, which is the same data structure defined above.

#### wasmcloud.lattice.update.{LATTICE}

Update details about the lattice

#### wasmcloud.lattice.get (list)

This API needs to be accessible to every user if we want to make listing
lattices an unprivileged operation. This means changing the default scope of a
signing key to include an import for `wasmcloud.lattice.get`.

Returns a list of lattices.

#### wasmcloud.lattice.watch

Subscribe to changes to lattices. This is effectively a proxy to NATS KV watch
on the bucket, only with certain fields removed and omitting any private
lattices.

### wash

wash needs a new `wash lattice` subcommand to manage lattices. Each command in
the `lattice` subcommand should correspond to the API calls defined above:

* `wash lattice add`
* `wash lattice get`
* `wash lattice delete`
* `wash lattice update`

We will also likely need to add either a new tool or additional subcommands for
common key manipulation tasks such as rotating keys or resigning JWTs. We will
also need APIs in the control plane for those operations.

### wadm

Once lattices are a first class construct in wasmCloud, we need to ensure that
wadm is aware of them. We should add an required `lattice` key to the metadata
of a manifest. It should be optional in the sense that wash must insert the the
lattice ID it is configured to operate against. This is actually the behavior
in both Kubernetes and Nomad, so it should be a fairly intuitive change for
anyone with a background in either of those systems.

```yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rust-hello-world
  # This might need to be a required annotation to maintain OAM compatibility
  lattice: my-lattice
  annotations: {}
```

wadm *must* refuse to deploy an application to a lattice that does not exist.
We will likely want to keep a cache of all lattices in memory in wadm so that
every call to deploy an application does not roundtrip through the lattice API.
Deleting a lattice through wadm’s API *must* also delete every application that
belongs to that lattice. A request to delete a lattice through wash *must*
prompt the user if they want to proceed with deleting the lattice. Optionally
we could default to refuse to delete a lattice if it has running applications
and require a `--force` flag to proceed anyway.

![wasmCloud Lattice Creation(3)](https://github.com/user-attachments/assets/36eaf15c-79aa-43d1-bd7d-7730df414151)

### Changes to the host

* mark the existing `--lattice-id` flag as optional
* add a new CLI flag (`--lattices`) that takes a comma-separated list of
lattices to run workloads for
  * if this flag is not provided *and* there isn't a corresponding
  `--lattice-id` flag, the host should run workloads for all lattices
  * if this flag is provided, the host should only run workloads for the
    specified lattices
* without auth everything should just work for multitenancy
* running in multitenant mode means that if creds are provided, those creds
must be issued from the `WASMCLOUD SYSTEM AUTH` account as part of the auth
callout flow for hosts.
* hosts in multitenant mode need to listen for requests to create clients that
listen to a lattice. These need to sub to all the same wasmbus topics that we
do now, so we'll have to shuffle code around to make that work. We'll also
need to shut them down whenever we stop all workloads on a lattice.

### Backwards Compatibility

The biggest change is that a lattice *must* be created before a host is able to run workloads for it. This can be mitigated by providing a script that can run against a nats cluster and create any observed lattices before upgrading to a version of the wasmCloud host that requires the control plane.

That being said, as outlined above the default behavior of a host should be able to run workloads for _all_ lattices, which would not need to poll the control plane for the existence of a lattice until an administrator wants to adopt distributed authentication.

### Alternatives Considered

* Instantiate a new copy of a host for every lattice, all within the scope of a
single wasmCloud host process.
  * Not the worst idea, but we don't need distinct host identities just to run
  workloads for multiple lattices
  * Lots of code duplication for no reason, since many of the options should
  just be reused for the new nats connections.
  * Still would require control plane changes to provision lattices, trigger
  host updates
* Stop using NATS accounts as a means of isolating lattices
  * In NATS there isn’t really a great alternative. You could create users for
  each lattice that belong to some top-level account, but you’d still need to
  dynamically provide credentials *and* establish new NATS connections so
  this feels like a non-starter.
* Do nothing
  * We need to be able to run workloads for multiple
  lattices at the same time so we don't really have a choice

### Unresolved Questions

- We currently use leaf nodes as sidecars to a host in order to restrict any local traffic between components or providers from going out to other hosts on the same lattice. We will have to rethink this approach in the fully isolated multitenancy model, since we would need to be able to dynamically add new leaf node remotes for new lattices.

### Conclusion

This RFC proposes a multitenancy model for wasmCloud powered by NATS distributed authorization. As part of the proposal, we will need a new set of APIs running cluster-wide, which means we will need a new control plane component running in the cluster much like wadm.

**Comment by protochron** [comment]
Opinions welcome on a name for a new control plane component. I used `Hub` as a conversation started, but `Warden` and `Nexus` have been suggested as alternatives

**Comment by ossfellow** [comment]
Thank you Dan; this is really great work.

In respect to the `add either a new tool or additional subcommands` topic in the `wash` section, I think adding subcommands through the `wash plugin` mechanism will be better than adding new tools, as CLI sprawl is a real thing, with all the cloud-native apps in use.

As for suggesting names, here are `our` nominees: 😂
- Mine - `Atlas`:  a bound collection of maps often including illustrations, informative tables, or textual matter.
- ChatGPT's - `Argus`: named after the many-eyed giant in Greek mythology, representing vigilance and oversight.

**Comment by tylerschoppe** [comment]
@protochron awesome stuff here. Still digesting some of the details but I wanted to get a few thoughts out.

A few months ago [we had a discussion](https://wasmcloud.slack.com/archives/CS38R7N9Y/p1711740871698279) that loosely pointed towards the decentralized auth option which is very exciting. I think it solves a lot for a secure enterprise deployment. It does make me wonder about the ability to bring your own account, as we already have an account per customer and it would be nice to build off of that rather than adding additional account overhead. Going slightly in the other direction it becomes an opportunity to help manage all these accounts, in and outside of wasmcloud use cases, as it is a pain like you mentioned.

The subject structure `wasmbus.{ctl,rpc,evt}.{lattice}.>` makes me think about a world where you could export lattice traffic into another account to meet your needs. Data ingest and centralized processing comes to mind to meet some use cases in my org.

Agreed with @ossfellow on utilizing `wash plugin` for subcommands.

Planning to read through again as my thoughts are fairly high level and hopefully helpful. Really appreciate this RFC and the direction things are headed!

**Comment by protochron** [comment]
@ossfellow that's a great idea on using a wash plugin to add new subcommands. We'd have to link in wrpc support in the wasmtime vm we run with wash, but that seems perfectly doable. `Nexus` was another name that was suggested

**Comment by protochron** [comment]
@tylerschoppe
> A few months ago [we had a discussion](https://wasmcloud.slack.com/archives/CS38R7N9Y/p1711740871698279) that loosely pointed towards the decentralized auth option which is very exciting. I think it solves a lot for a secure enterprise deployment. It does make me wonder about the ability to bring your own account, as we already have an account per customer and it would be nice to build off of that rather than adding additional account overhead. Going slightly in the other direction it becomes an opportunity to help manage all these accounts, in and outside of wasmcloud use cases, as it is a pain like you mentioned.
> 
> The subject structure `wasmbus.{ctl,rpc,evt}.{lattice}.>` makes me think about a world where you could export lattice traffic into another account to meet your needs. Data ingest and centralized processing comes to mind to meet some use cases in my org.

Would you also want to map customers to particular lattices? That's one of the use cases we were thinking of making available in this model. In terms of bringing your own accounts, I can't see why that would be an issue as long as you were fine with importing or exporting any required subjects for wasmCloud. A subtle point you might have missed is that one of the things we want to do is make it easier to generate accounts that meet your own requirements, which you can do in two ways:
* generate an account for a lattice by writing a component and having the control plane execute that code whenever it receives a request to create a lattice. That component could extend the common set of NATS claims or add your own that are tailored to your own use cases
* authenticate a client in the host to a lattice by using auth callout. Like adding a lattice, auth callout will be implemented using a component, so you could do something clever like map a lattice to an existing NATS account as long as the control plane has access to that account's signing key. The only real requirements for the host is that it is bootstrapped with a credential that lets it receive control interface commands and that any account associated with a lattice can receive RPC traffic imported from the account associated with the control interface. Technically speaking the latter part is actually optional since you could just fully isolated RPC traffic in a single account, but you might want to be able to re-export invocations to another account for doing things like data ingestion like you mentioned

**Comment by Solverj** [comment]
`super`-<something>

Can't this be semi-achieved through exporting of service through nats, e.g., wadm.* to your `super`-<something>

**Comment by ossfellow** [comment]
> Would you also want to map customers to particular lattices? That's one of the use cases we were thinking of making available in this model.

In the context of multi-tenancy, I think it's helpful to view a wasmCloud `lattice` the same as a Kubernetes `namespace`, which, its isolation model, can accommodate both applications and users.

Besides, the wasmCloud - and WASI Component model - have a very decent security model, and it'll be a missed opportunity if lattices can't be sealed.

**Comment by protochron** [comment]
> > Would you also want to map customers to particular lattices? That's one of the use cases we were thinking of making available in this model.
> 
> In the context of multi-tenancy, I think it's helpful to view a wasmCloud `lattice` the same as a Kubernetes `namespace`, which, its isolation model, can accommodate both applications and users.
> 
> Besides, the wasmCloud - and WASI Component model - have a very decent security model, and it'll be a missed opportunity if lattices can't be sealed.

I also tend to view a lattice similar to a k8s namespace. The key difference is that with lattices we not only have a logical boundary but also (optionally) a security boundary with NATS accounts.
