### ISSUE TITLE
[BUG] wash cli cannot build and deploy on windows

### ISSUE THREAD

**Issue by rajsite** [wasmCloud/wasmCloud#3185]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

Trying to workaround https://github.com/wasmCloud/wasmCloud/issues/3183

I manually ran `npm install` and `npm run build` for my project and tried the following to finish the workflow, none of which were successful:

Skip the build command (`wash build -p ./helloworld`) and after manually running `npm run build` above, try and deploy directly (`wash app deploy ./helloworld/wadm.yaml`).

~~Resulted in error:~~
```diff
-C:\Users\mraj\Desktop>wash app deploy ./helloworld/wadm.yaml
-
-Invalid request: Unable to parse manifest: unknown variant `component`, expected `actor` or `capability` at line 1 column 911
```
~~I'm not sure how to handle the error. I don't know which file is the "manifest" and the line and column number don't seem to correspond to anything in the project. i.e. the `wadm.yml` file and `wasmcloud.toml` files do not have line 1 lengths of 911  characters. Assumed that maybe `wash build` is required to succeed.~~

Edit: After upgrading the `wash` cli the deploy command was able to run but the build command is still failing as follows:

Tried to remove `build_command` from `wasmcloud.toml`. 
```
C:\Users\mraj\Desktop>wash build -p ./helloworld

build command is required for unsupported language typescript
```

Tried an empty command for `build_command = ""`:
```
C:\Users\mraj\Desktop>wash build -p ./helloworld

build command is supplied but empty
```

Tried a simple echo statement `build_command = "echo hi"` and an empty echo statement `build_command = "echo \"\""`
```
C:\Users\mraj\Desktop>wash build -p ./helloworld

failed to build component with custom command: "\nUnhandled Exception: System.ArgumentException: Illegal characters in path.\r\n   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)\r\n   at System.IO.Directory.InternalGetCurrentDirectory(Boolean checkHost)\r\n   at shim.ShimProgram.Main(String[] args)\n"
```

Tried a quick return `build_command = "return 0"` and `build_command = "exit 0"`

```
C:\Users\mraj\Desktop>wash build -p ./helloworld

`"exit"` was not found

C:\Users\mraj\Desktop>wash build -p ./helloworld

`"return"` was not found
```

### Steps to reproduce

See above

### Expected behavior

I can use the wash cli on Windows to build and deploy a component with wasmcloud

### Environment

- OS: Windows 10 21H2 (OS Build 19044.4529)
- Shell: cmd
- wasmcloud Version: 
```
C:\Users\mraj\Desktop>wash --version
wash          v0.34.1
├ nats-server v2.10.18
├ wadm        v0.14.0
└ wasmcloud   v1.2.1
```

**Comment by brooksmtownsend** [comment]
Hey @rajsite, what version of `wash` and `wadm` is running here? The error messages look quite old, so I think all we may need to do is update the version. If you installed via chocolatey, I'd want to make sure the latest `wash` is pushed up there

**Comment by rajsite** [comment]
Had the versions in the related issue but inlined them in the description as well. Looks like the latest wash version (v0.34.1).

> The error messages look quite old, so I think all we may need to do is update the version.

I'm betting you're referring to this error right?

> C:\Users\mraj\Desktop>wash app deploy ./helloworld/wadm.yaml
> 
> Invalid request: Unable to parse manifest: unknown variant `component`, expected `actor` or `capability` at line 1 column 911

That one I can't reproduce anymore. I know I did a `choco update` at some point so that may have resolved that. I'll update the description.

But the rest around `wash build -p ./helloworld` do still seem reproducible.

**Comment by rajsite** [comment]
Actually re-reading the issue I think #3183 covers the build command concerns so I'll close this issue since I can't reproduce (probably because I did an upgrade at some point)

**Comment by brooksmtownsend** [comment]
Sounds good @rajsite !
