### ISSUE TITLE
[RFC] Support Smart Link Defaults

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#320]
## Summary
This issue is a request for comment on the concept of **smart link defaults**. This topic arose from one of the Wednesday community meetings as folks brainstormed ideas for ways to make the developer experience easier and more flexible, especially in environments with multiple different host types. Special thanks to @jordan-rash for highlighting these use cases.

## Rationale
Today when developers want to make use of capabilities like number generation (random, guid, range, etc) or logging, they do so using the contract IDs `wasmcloud:builtin:login` and `wasmcloud:builtin:numbergen`. The historical context around this was that, in the early days of wasmCloud, we wanted to be able to explicitly choose whether we used a default provider or our own provider. For example, if we wanted to supply our own logging provider, we'd do so with a different contract.

Hindsight being what it is, this approach seems counter to some of the fundamental goals of wasmCloud, including portability and the runtime changing of capability providers. If the contract is `wasmcloud:builtin:login`, and in production someone wants to build a logger that emits logs to a custom collector or a NATS topic, then the actor needs to be compiled ahead of time with that knowledge, _and_ it must know when it's running in the right environment.

So the first thing we want to examine is things that are explicitly built in but should not. Secondarily, we also want to revisit things that _should_ be built in, but aren't, like the HTTP client[^1].

Further, whether a provider is built in or not should be something that can change depending on environment. One can easily imagine a bespoke host running on a microcontroller to have _nothing but_ built-in providers, while cloud ones might have logging, number generation, and HTTP client built in. 

In all of these cases, whether a provider is built-in or not _should be opaque to the actor_.

## Implementation
Implementing this involves a few steps. Some steps just involve changing documentation and contract IDs, while others require changing host behavior and impact any potential new hosts.

### Change Builtin Contract IDs
The first thing we'll want to do is change our contract IDs from `wasmcloud:builtin:logging` and `wasmcloud:builtin:numbergen` to `wasmcloud:logging` and `wasmcloud:numbergen` respectively. This also more closely aligns us for eventual adoption of wasi contracts like `wasi-logging`.

By changing these contract IDs, the contract itself no longer carries implicit information about implementation or location. Whether a contract will be satisfied as a built-in at runtime will no longer be information an actor has.

### Perform Smart Linking
When an actor makes a call via the host, the host will perform the following prioritized triage:

* If the contract ID is not among the actor's claims, reject the call (current behavior)
* If a link definition is present/discoverable between the source actor and a provider implementing the given contract, the call will be handled via RPC (current behavior)
* If the contract ID is among the host's _currently available built-ins_, then the call will be directed to the local built-in. Local built-ins **must not require per-link configuration**, as no configuration is passed from the actor.
* If none of the above, the call will fail

In other words, link definitions must override link-free defaults. This may seem controversial, but consider the scenario where someone has deployed a handful of OTP hosts (which comes with a built-in logger). Now they create a provider that logs and collects data the way they want it within their enterprise. If link definitions did not take precedence, then this new provider could never be used, even when there is a link definition.

The alternative, having hosts be able to disable their own builtins, creates a far more error-prone environment ripe for distributed system bugs.

### Update Documentation
Ensure that there is plenty of documentation in the specification area describing the requirements of a well-behaved host.

### Update OTP Host
Make the appropriate changes so that the OTP host provides its builtins using the new contract IDs and according to the new priority rules. The OTP host (and any other subsequent hosts) will add a new field to the labels map it emits. This labels map is used by tools like `wadm` and by operations people for holding auctions that determine workload scheduling. 

The new field is `hostcore.builtins` and it will be a comma-delimited list of contract IDs for which the host has a builtin provider. All hosts, OTP or otherwise, are required to populate the `hostcore.?` labels. If this field is missing entirely, the host should not be considered for any actors that rely on builtins (aka "link-free providers").

**Add a built-in HTTP Client** to the host. This way, if no one explicitly links to the HTTP client, actors will get an in-process HTTP client w/out the penalty of a NATS RPC round-trip.

### Update the wasmcloud Crate
Currently the `wasmcloud` Rust runtime library dispatches to builtins first, and only dispatches to the surrounding host environment when no builtins exist to satisfy the call. This priority needs to be reversed (or made reversible) so that link definitions (by way of the parent host) can take precedence over builtins. This could be done just by dispatching to the outer host first, and if the outer host returns some enum indicating that it was "unhandled", the Rust crate would then check for a suitable builtin. This also affords both the Rust library and the outer host the ability to maintain their own set of builtins.

## Risks
There are some potentially nasty edge cases here, but they _should_ be easily detected in an incorrectly set up environment. Consider a lattice with two kinds of hosts: one that has a builtin logger and one that doesn't. The lattice contains no link definitions between this actor and a logger provider because operations assumes builtins will take care of it. When this actor is deployed on the builtin-supporting host, everything works fine. When it is deployed on a non-builtin-supporting host, the actor crashes during every call because it fails to make a logger invocation ("no link between actor and provider" error).

[^1]: To make an HTTP client request from an actor today, it must leave the Wasm module, go through the host, go over NATS RPC to the remote capability provider, have the remote provider perform the request and return the value, and then supply the return value back to the actor component.

**Comment by jordan-rash** [comment]
WRT `wash`, what I would like to see is something like `wash ctl query builtins` IOT see what builtins I have access to, as well as having them appear on `wash ctl get inventory host` so I can identify what hosts are hosting them.  The cherry on top would be a new section on the washboard that displays this information as well

On the topic of the builtin httpclient: would we consider a feature flag for this.  Reason being, from a production security standpoint, do I want to provide all our actors with a linkless egress point?  I wouldn't think so?  I totally get this for a development environment....

**Comment by autodidaddict** [comment]
If the list of builtins is available in a host's annotations, then not only would you be able to use wash to query all of them, but you'd be able to use the `auction` functionality to find only those hosts with the builtins in question.

**Comment by autodidaddict** [comment]
> On the topic of the builtin httpclient: would we consider a feature flag for this. Reason being, from a production security standpoint, do I want to provide all our actors with a linkless egress point? I wouldn't think so? I totally get this for a development environment....

If the actor has the `wasmcloud:httpclient` claim in it, then it's allowed to use the HTTP client. The only difference here would be whether the HTTP client is locally in process or remote inside a capability provider. Which URLs can be accessed by the actor would be identical in either situation. In other words, you'd want to secure your egress regardless of whether an actor can use a host to make an HTTP call or use another host's provider.

**Comment by autodidaddict** [comment]
The more I think about it, the more I like your idea of also surfacing the builtins as visible inventory. There are two different use cases here. One is for auctioning and wadm-based scheduling (the annotations), and the other is for letting humans know what's running in a host, builtin or otherwise.

Something like this:

```
                   Host Inventory (NAAJK3PC7PQ63TXET6VDJZI2WRD2LMBZKKOU76HL7NX5AUR7A3HT3PCF)

  cosmonic_managed                   true
  kev                                true
  hostcore.arch                      aarch64
  hostcore.osfamily                  unix
  hostcore.os                        linux
  hostcore.builtins                  wasmcloud:httpclient, wasmcloud:logging, wasmcloud:numbergen

  No actors found

  Provider ID                                               Name                           Link Name          Image Reference
  (Builtin)                                                 HTTP Client         
  (Builtin)                                                 Logging
  (Builtin)                                                 Number Generation
  VD7EAHNS6X4PQDN5YQXMZQDPTXODBNEQW52ZTJXM3OAMTHONZPTPJE2U  HTTP Server - Wormhole         default            cosmonic.azurecr.io/httpserver_wormhole:0.5.3
  VAKKKUUZH6FWYPS3T6WVAESSPVQMQYJ2IRCXGSHYCOISSIUGCXVJYC6M  Built-in KeyValue - Cosmonic   default            cosmonic.azurecr.io/builtin_keyvalue:0.2.3
```

**Comment by autodidaddict** [comment]
Fun historical fact : this is what host inventory looked like on the original "gen 1" runtime 😁

**Comment by jordan-rash** [comment]
> Fun historical fact : this is what host inventory looked like on the original "gen 1" runtime 😁

The world goes around and around and around 🤣

**Comment by brooksmtownsend** [comment]
bad bot, this is good stuff and we should do it.

**Comment by yordis** [comment]
@connorsmith256 maybe add `pinned' https://github.com/wasmCloud/wasmCloud/blob/c73be47b2f4e813e72639063fa6455ac2d9f8f8e/.github/stale.yml#L7C5-L7C11 label

**Comment by vados-cosmonic** [comment]
Hey this is pretty old -- given the update to WIT-based components and providers I think we've accomplished this goal in wasmCloud 1.0+!

Closing for now -- please feel free to comment if you feel some part of the issues with the old capability specifications (& `builtin`s) is not yet covered!
