### ISSUE TITLE
[FEATURE] Oneliner docker install/quickstart

### ISSUE THREAD

**Issue by ricochet** [wasmCloud/wasmCloud#323]
Right now we have a docker compose, but I think we should have a single container that you can use to run wasmCloud so that getting started is easy. https://wasmcloud.com/docs/installation?os=docker

I'm not opposed to a docker compose, but it's a little harder, so I figure we can start with a "nice" experience.

```bash
docker run --rm -p 4000:4000 -it wasmcloud/wash
```

This command would effectively launch wash up , and people could interact with the wasmCloud dashboard locally. Additionally, they could do:
docker exec wash ctl get hosts to interact with the control interface, etc.

This method would get harder once requirements come in to interact with services like Redis, or OpenTelemetry collectors, but hey we can point people to our docker compose at this point.

**Comment by bhavyastar** [comment]
Hey, I would like to work on this issue.

**Comment by brooksmtownsend** [comment]
> Hey, I would like to work on this issue.

@bhavyastar That would be awesome! I tagged you as assigned so nobody ends up taking it. Let us know if you need any additional work done on the docker image to support this!

**Comment by rushikeshsuryawanshi** [comment]
@bhavyastar Hey, are u still working on this issue ?

**Comment by brooksmtownsend** [comment]
@rushikeshsuryawanshi if you're interested in taking this one, I can assign this to you if @bhavyastar doesn't get back to us for a few days 😄
