### ISSUE TITLE
[RFC] Transition Feature Focus to Rust

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#324]
## Summary
This request for comment seeks commentary on, as a project, the wasmCloud maintainers and community focusing the effort for new features with a new priority of Rust-first feature development.

## Rationale
Up until very recently, the only fully supported wasmCloud host runtime was the [OTP](https://github.com/wasmcloud/wasmcloud-otp) host. Now this repository is home to the Rust library that contains the core data type `Runtime`, which is used to build wasmCloud hosts. The OTP host now uses this library for all of its WebAssembly needs, including the experimental support for components.

In RFC #321 we discuss our plans to remove the web-based administrative console from the OTP host. With "washboard" removed from the host, the OTP host becomes not much more than a supervision tree husk and the control interface NATS servers wrapped around the inner Rust core.

As we add new features to the Rust library that are intended for many potential hosts, and not just the OTP host, we will be spending less and less time managing the OTP codebase.

### Rust Motivation and Elixir Retrospective
Almost 2 years ago, back in June of 2021, the team decided to switch [from Rust to Elixir](https://wasmcloud.github.io/adr/0010-otp.html), as outlined in our Architectural Decision Record. We've had two years to experience Elixir/OTP in real-world, production scenarios, gather evidence, and expose that codebase to more and more people as our team has grown from the 3 people working on it in 2021 to the large community we enjoy today.

So why would we want to go back on that decision? It comes down to environment, knowledge, experience, and learning things the hard way. One of the main lessons we learned is that Elixir applications aren't _really_ designed to be run like "regular apps". They are far more comfortable being deployed to servers. The developer experience of running an Elixir app and the team experience of building, testing, deploying, and lately cross-compiling, is very high in friction.

Even with the help of Dialyzer, the core team encountered many problems stemming from Elixir's dynamic typing. We got better at handling this over time and more diligent about writing up type specifications, but it's not a type safe language. 

We bet a lot on the benefits we would get from OTP. OTP has been around for what seems like forever. It is by far the single most battle-tested piece of our technology stack. Supervision trees are _enormously_ powerful, as is the entire `GenServer` model. If we compare the clean, concise code from well-written `GenServer`s to the kind of code we were writing with Actix back then, it's a night and day comparison with the Actix code being inscrutable.

The ability to run `recompile` inside an `iex` REPL as we're coding is a feature worth salivating over. GenServers are incredibly powerful. Horde and Erlang clustering give us so much power, we feel like we should be wielding it from our own private James Bond villain island lair. Supervisors and supervision trees and OTP processes and the entire stack are **absolutely** what we would pick if we were building a _single_, monolithic, real-time application that was being deployed to a target environment, and not being installed by consumers/customers.

But we're not building that. We're building a runtime that needs to be brain-dead simple to install. It needs to be small, fast, portable, type safe, memory safe, and everyone on our team needs to be able to be productive in it. We've learned a lot about Rust and how to build serious applications in Rust since the early days of wasmCloud.

Given the current circumstances, the current makeup of the team, the current interest of the community revolving around Rust, portable applications, embedded devices and development, edge computing, and, if we're honest, availability of modern, actively maintained open source libraries... Rust seems like the right choice.

This doesn't mean that Elixir/OTP was the wrong choice 2 years ago. It means that any good team needs to constantly re-evaluate its choices and apply critical thinking to all of its decisions. Applying what we've learned over the past 2 years to the current state of the universe, Rust seems like the right choice now.

## Implementation Plan
The plan is not to **deprecate** the OTP host right now. Rather, the plan is instead to focus on placing new features in the Rust library, which should make them available (mostly) automatically for the OTP host. As a Rust host that wraps the Rust runtime crate is developed, we should see more and more focus being made on the new Rust host.

The chart below should better illustrate the model we're planning, which is a general restriction against creating new features that exist only in the OTP host (with some exceptions, for example smart linking defaults as defined in #320 ).

![image](https://github.com/wasmCloud/wasmCloud/assets/13748641/414947aa-1ebd-45b2-9821-0136de87d0e9)

At the point where the Rust and OTP development efforts converge in the above chart, we will _then_ label the OTP host as deprecated. This feels like the safest way for us to transition to focusing on the Rust host while still supporting those who are currently using the Elixir host until the Rust and Elixir hosts reach feature parity, at which point it should be easy for developers to switch.

## Support and Compatibility Note
The OTP host will continue to be supported and we will continue to guarantee that it will be remain compatible with other hosts on the lattice. When we evaluate new features, we will seek to build them in the following triage priority:

* Can the new feature be built in the base `wasmcloud` crate (the `Runtime` library)? If so, place the feature here and update the OTP host NIF accordingly.
* If not, then we will see if the new feature can be implemented in the primary Rust host.
* Only if the feature is required to allow the OTP host to continue to maintain lattice compatibility with the Rust host will we add it to the OTP code directly.

**Comment by thomastaylor312** [comment]
I wholeheartedly agree with the plan as described here

**Comment by ricochet** [comment]
I support this plan. Another key point is that by building fully on NATS, much of the complexity in the host has been moved to the NATS layer.

**Comment by brooksmtownsend** [comment]
I agree with this plan as well 👍🏻

**Comment by connorsmith256** [comment]
~Don't blame me. _I_ voted for Kodos~

Let's do it 🚀

**Comment by VestigeJ** [comment]
✅

**Comment by aschrijver** [comment]
Just dropping a reference to another Rust + WebAssembly project you are probably well aware of already, for inspiration and (who knows) collab: [Lunatic Solutions](https://lunatic.solutions) ([repo](https://github.com/lunatic-solutions/lunatic)), an Erlang-inspired runtime for WebAssembly.

**Comment by autodidaddict** [comment]
Closing this as it has been converted to ADR form [here](https://github.com/wasmCloud/wasmCloud/blob/main/adr/0013-transition-feature-focus-to-rust.md)
