### ISSUE TITLE
[CNCF TOC] Public maintainers file

### ISSUE THREAD

**Issue by angellk** [wasmCloud/wasmCloud#3296]
The [current org and project maintainers](https://github.com/wasmCloud/wasmCloud/blob/main/.github/CODEOWNERS) list are not accessible publicly.

Please work to fix the [teams](https://github.com/orgs/wasmCloud/teams) permissions so the information can be shared publicly for the method you are using to automatically maintain your project maintainers list(s).

This is required to meet the requirements for CNCF Incubation.

xref: https://github.com/cncf/toc/issues/1338

**Comment by brooksmtownsend** [comment]
Test @wasmCloud/go-maintainers @wasmCloud/org-maintainers

**Comment by brooksmtownsend** [comment]
Hey @angellk, though organization teams cannot be shared publicly and are only visible to members of the organization (see ["People who are not members of the organization cannot view any teams."](https://docs.github.com/en/organizations/organizing-members-into-teams/changing-team-visibility)) we're compensating for this with #3300 and respective additions of a MAINTAINERS.md in the `wadm`, `wasmcloud-operator`, and `wasmcloud.com` projects.

**Comment by angellk** [comment]
Thank you @brooksmtownsend ! lgtm
