### ISSUE TITLE
[CNCF TOC] Cleanup references to Cosmonic Kubernetes Applier

### ISSUE THREAD

**Issue by angellk** [wasmCloud/wasmCloud#3297]
As Cosmonic donated the Kubernetes Applier to the CNCF with the wasmCloud project, please clean up references to, and the documentation of, the Cosmonic version of the Kubernetes Applier. Examples:

- https://github.com/wasmCloud/wasmcloud-otp/wasmcloud-host/chart/README.md
- https://github.com/wasmCloud/wasmCloud/chart/README.md

xref: https://github.com/cncf/toc/issues/1338

**Comment by brooksmtownsend** [comment]
Fixed with https://github.com/wasmCloud/wasmCloud/pull/3299 and https://github.com/wasmCloud/wasmcloud-otp/pull/650, @angellk feel free to close if this matches your requirement 🙂

**Comment by joonas** [comment]
Hi @angellk,

To make sure we clear up any potential confusion about the relationship between the Kubernetes Applier and the wasmcloud-operator, which supersedes and wholesale replaces the Applier, I went ahead and made the following changes:

1. Removed the reference to [Kubernetes Applier from the wasmcloud-otp repository](https://github.com/wasmCloud/wasmcloud-otp/pull/650)
2. Removed the reference to [Kubernetes Applier from the old wasmcloud host chart](https://github.com/wasmCloud/wasmCloud/pull/3299)
3. Archived the [Kubernetes Applier](https://github.com/cosmonic/kubernetes-applier) repository with a note redirecting folks to wasmCloud's officially supported [wasmCloud Operator](https://github.com/wasmcloud/wasmcloud-operator).

Please let me know if these changes don't satisfactorily address this issue.

**Comment by angellk** [comment]
thank you @brooksmtownsend ! and thank you @joonas for the additional changes. lgtm!
