### ISSUE TITLE
[BUG] Provider to provider calls are not working

### ISSUE THREAD

**Issue by atifsyedali** [wasmCloud/wasmCloud#3374]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [X] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

It looks like calls from one provider to another provider are not working. This is a minimal reproduction here: https://github.com/atifsyedali/repro-multi-link-call-failure/tree/provider-to-provider (note the `provider-to-provider` branch). Notice how the http-server is linked to the custom-template provider on port 8082, and to the component on 8081? So doing a curl localhost:8081 works, but curl localhost:8082 errors out with:

`curl: (7) Failed to connect to 127.0.0.1 port 8082 after 6 ms: Connection refused`

I am unsure whether I set up the incoming HTTP handler on the provider correctly. But, there doesn't seem to be any docs or examples on this use case either.

### Steps to reproduce

See https://github.com/atifsyedali/repro-multi-link-call-failure/tree/provider-to-provider (note the `provider-to-provider` branch)

### Expected behavior

Provider to provider calls work.

### Environment

- OS: [e.g. Linux, MacOS]
- Shell [e.g. bash, zsh, powershell]
- wasmcloud Version [e.g. 0.81.0]

**Comment by atifsyedali** [comment]
I think this might be a dupe of #3285 ...

**Comment by vados-cosmonic** [comment]
Ahhh Thanks for pointing this out @atifsyedali , we actually also [have another issue](https://github.com/wasmCloud/wasmCloud/issues/2806#issuecomment-2423857572) that has to do with duplicate links on the HTTP provider that I'm also looking at which might ALSO be relevant here, so I'll close this one in favor of those two. 

The work on the other ticket includes an overlapping link test, so I think we can add a test for the case in #3285 as well once it's fixed.
