### ISSUE TITLE
[BUG] cargo install wash-cli@0.35.0 error[E0308]: mismatched types

### ISSUE THREAD

**Issue by ptsgr** [wasmCloud/wasmCloud#3404]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

When I trying to install wash-cli v0.35.0 via cargo 
```bash
cargo install wash-cli@0.35.0
```
I got an issue `error[E0308]: mismatched types`
```
wash-lib-0.28.1/src/registry.rs:138:34
     |
138  |         extra_root_certificates: tls::NATIVE_ROOTS_OCI.to_vec(),
     |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `oci_distribution::client::Certificate`, found `oci_client::client::Certificate`
     |
     = note: `oci_client::client::Certificate` and `oci_distribution::client::Certificate` have similar names, but are actually distinct types
note: `oci_client::client::Certificate` is defined in crate `oci_client`

oci-client-0.13.0/src/client.rs:1780:1
     |
1780 | pub struct Certificate {
     | ^^^^^^^^^^^^^^^^^^^^^^
note: `oci_distribution::client::Certificate` is defined in crate `oci_distribution`
    --> /Users/ptsgr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/oci-distribution-0.11.0/src/client.rs:1563:1
     |
1563 | pub struct Certificate {
     | ^^^^^^^^^^^^^^^^^^^^^^


### Steps to reproduce

cargo install wash-cli@0.35.0

### Expected behavior

wash installed

### Environment

- OS: MacOS, Linux
- Shell bash, zsh


### Screenshots / Logs / Additional context

_No response_

**Comment by brooksmtownsend** [comment]
I attempted to publish a `wash-cli-0.35.1` but to no avail.

**Comment by vados-cosmonic** [comment]
Hey @ptsgr would you mind using:

```
cargo install --locked wash-cli@0.35.0
```

This fixes the issue on my machine -- the short explanation is that `cargo install` can actually update dependencies that *should* be semver compatible -- and it does this automatically by default. Normally this means getting helpful changes, performance improvements, etc for free.... But in this case it became an issue. 

Forcing cargo to install using the dependencies as specified in `Cargo.lock` at the time the crate was published will fix it :)

**Comment by vados-cosmonic** [comment]
Hey @ptsgr if you don't mind I'll close this for now, please re-open if you run into this again! 

Also, you *should* be able to install [the latest version (0.36.0)](https://crates.io/crates/wash-cli/0.36.0), @brooksmtownsend put in a super fast fix of the core issue I think, regular install works on my machine now!

**Comment by ptsgr** [comment]
Thanks @vados-cosmonic
```
cargo install --locked wash-cli@0.35.0
```
Helped with `wash 0.35.0`

Thanks @brooksmtownsend  
`wash 0.36.0` installs without problems.
