### ISSUE TITLE
[BUG] tinygo wash build does not create build dir

### ISSUE THREAD

**Issue by ricochet** [wasmCloud/wasmCloud#3434]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

tinygo is passed an output dir and tinygo doesn't pre-create the dir. Wash should always check and do this for all build commands.

### Steps to reproduce

Build for tinygo without a build dir and gen dir.

### Expected behavior

builds

### Environment

n/a

**Comment by brooksmtownsend** [comment]
I did try and reproduce and I notice that we will create the `build` dir as long as a custom `build_command` is not specified. 

We don't, however, create the directory for generated code. According to https://github.com/bytecodealliance/wasm-tools-go/blob/main/cmd/wit-bindgen-go/cmd/generate/generate.go#L165, this should be happening during the generate, so I'm not sure why it's not working

**Comment by brooksmtownsend** [comment]
nvm, it's here https://github.com/bytecodealliance/wasm-tools-go/blob/main/cmd/wit-bindgen-go/cmd/generate/generate.go#L109

**Comment by brooksmtownsend** [comment]
Resolved upstream with https://github.com/bytecodealliance/wasm-tools-go/pull/216
