### ISSUE TITLE
[FEATURE] pass tlsfirst parameter for nats client

### ISSUE THREAD

**Issue by peter-jerry-ye** [wasmCloud/wasmCloud#3455]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

I'm frustrated when I have a TLS terminating proxy for my cluster. I can't connect to it unless I pass the `--tlsfirst` parameter to nats client. As a result, I can't connect to my cluster with `wash`.

### Describe the solution you'd like

I would like to see add a `--ctl-tlsfirst` parameter that will be passed to the `ConnectOptions`

**Comment by brooksmtownsend** [comment]
Interesting, I wasn't aware this was an option. This is a great first issue 👍🏻

**Comment by brooksmtownsend** [comment]
Solved by #3473
