### ISSUE TITLE
[FEATURE] Check for `~/.wash/downloads/nats-server` version and update if it's old

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#3572]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Is your feature request related to a problem? Please describe.

During `wash up` and `wash dev`, we start a local `nats-server` as a part of the local platform. Currently if that `nats-server` version is out of date, `wash` does not download the latest version.

### Describe the solution you'd like

Following exactly what we do for `wadm`, we should check the version of the `nats-server` binary and if it's not the latest version as specified in the wash up configuration.

For example if I ran this:
```
➜ ~/.wash/downloads/nats-server version
nats-server: v2.9.12
```

and wash is configured to download v2.10.22, on the next `wash up` or `wash dev` we should download that latest version and replace the binary.

**Comment by vados-cosmonic** [comment]
+1 Excellent work @claytondus !
