### ISSUE TITLE
[BUG] `wash get links`s output is inconsistent

### ISSUE THREAD

**Issue by markkovari** [wasmCloud/wasmCloud#3584]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

Compered to other `wash get` subcommands, `wash get links` is producing a `.` (which is probably the first "frame" of a spinner)

It would be nice to keep the consistency between these commands.

### Steps to reproduce

1, Run a host with `wash up -d`
2, Issue the command `wash get links` a few times

### Expected behaviour

The output should be formatted similarly to the other `wash get` subcommands.

### Environment

wash          v0.36.1
├ nats-server v2.10.20
├ wadm        v0.18.0
└ wasmcloud   v1.4.0

macOS(Version 15.1 (24B83)) and Ubuntu 24.04.1 (6.8.0-48-generic)

### Screenshots / Logs / Additional context

Another interesting behaviour is that if I run the mentioned command multiple times the output is different. (attached pictures)
<img width="504" alt="Screenshot 2024-11-09 at 22 34 27" src="https://github.com/user-attachments/assets/ae01b938-43d3-488c-a93f-925c58524dc7">
<img width="537" alt="Screenshot 2024-11-09 at 22 33 46" src="https://github.com/user-attachments/assets/9ec28899-247f-4c0a-8399-55941159f3cc">

**Comment by Gohlub** [comment]
Hi, I would like to take a pass at this bug. I am wondering whether I should have anything in mind while attempting a fix: in [here](https://github.com/Gohlub/wasmCloud/blob/main/crates/wash-cli/README.md), there is a flag referencing that this crate will be deprecated and moved. Should I just attempt a fix here anyway, or wait?

**Comment by lachieh** [comment]
Hi @Gohlub, thanks for checking. The `wash-cli` crate is just moving to the `wash` name; the code will stay the same.

I've assigned you the issue, let us know if you need any feedback/assistance either here or in the [slack channel](https://wasmcloud.com/slack)

**Comment by brooksmtownsend** [comment]
Hey @Gohlub / @vados-cosmonic , is this one in a PR yet? Would love to get this one in 😄

**Comment by vados-cosmonic** [comment]
Hey @markkovari the PR just got merged :tada: and when I run off of `main` I don't see the stray `.` anymore :)
