### ISSUE TITLE
[BUG] wash app deploy should indicate that the manifest argument is missing

### ISSUE THREAD

**Issue by cpetig** [wasmCloud/wasmCloud#3604]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

If you run `wash app deploy` without any argument the error message isn't helpful.

### Steps to reproduce

`wash app deploy` without any argument gives:
```
app manifest loader timed out

Caused by:
    deadline has elapsed
```
which to me didn't indicate that the manifest argument was missing.

### Expected behavior

It should indicate something like
```
Manifest argument missing. Provide the manifest as the first argument, e.g. local.wadm.yaml.
```

### Environment

- OS: WSL2, ubuntu 22.04
- Shell: bash
- wasmcloud Version 0.28.1 (wash --version)

**Comment by cpetig** [comment]
I ran into this while reproducing https://github.com/wasmCloud/wasmCloud/issues/3034

**Comment by cpetig** [comment]
The shell running `wash up` reports
````
2024-11-14T18:36:30.487946Z ERROR wasmcloud_host::wasmbus: failed to scale component component_ref=file:///home/.../hello/build/http_hello_world_s.wasm component_id=rust_hello_world-http_component err=failed to fetch component

Caused by:
    0: failed to read component
    1: No such file or directory (os error 2)
2024-11-14T18:37:00.482627Z ERROR wasmcloud_host::wasmbus: failed to scale component component_ref=file:///home/.../hello/build/http_hello_world_s.wasm component_id=rust_hello_world-http_component err=failed to fetch component
```
while the shell I typed `wash app deploy local.wadm.yaml`
shows `Successfully deployed model rust-hello-world v0.0.1` which clearly is confusing.

**Comment by cpetig** [comment]
My guess is that this is `load_app_manifest("-".parse()?).await?` timing out (src/app/mod.rs:324)

**Comment by vados-cosmonic** [comment]
Hey @cpetig thanks for filing this -- yeah I think the issue is going to be related to the optional arg there -- we *should* be doing some checking and possibly printing an error message like you noted! Will take a look at this.

**Comment by vados-cosmonic** [comment]
Ah so this is actually working as intended -- we're enabling loading via STDIN with no arguments -- I'm going to make a PR to make the `-` explicit/require it...
