### ISSUE TITLE
[BUG] wash dev :: fails with the message :: Failed to build project: Failed to update dependencies

### ISSUE THREAD

**Issue by fbaube** [wasmCloud/wasmCloud#3620]
### Affected project(s)

- [X] documentation
- [X] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

I am trying the [Quick Start](https://wasmcloud.com/docs/tour/hello-world) with `go version go1.23.3 darwin/arm64`

```
~/WebAssemblyComponentModel/hello >> wash dev
ℹ️  Resolved wash session ID [RZok7m]
🚧 Starting a new host...
ℹ️  NATS server successfully started, using config @ [/Users/fbaube/.wash/downloads/nats.conf]
ℹ️  NATS server logs written to [/Users/fbaube/.wash/dev/RZok7m/nats.log]
👀 Found wadm version on the disk: wadm-cli 0.18.0
✅ Using wadm version [v0.18.0]
🔧 Successfully started wasmCloud instance
✅ Successfully started host, logs writing to /Users/fbaube/.wash/dev/RZok7m/wasmcloud.log
🚧 Building project...
⛔ Failed to build project:
Failed to update dependencies
👀 Watching for file changes (press Ctrl+c to stop)...
```

I am unable to figure out the meaning of the message `Failed to update dependencies` or what I can do to remedy it. 

I did try running `go get -u` in the `hello` directory and then re-running `wash dev` , but this did not change the outcome. 

### Steps to reproduce

at shell prompt, run: `wash dev `

### Expected behavior

`✨ HTTP Server: Access your application at http://127.0.0.1:8000`

### Environment

```
macOS 15.1
bash
go version go1.23.3 darwin/arm64
wash          v0.37.0
├ nats-server v2.10.20
├ wadm        v0.18.0
└ wasmcloud   v1.4.2
```

**Comment by fbaube** [comment]
Environment:
`tinygo version 0.34.0 darwin/arm64 (using go version go1.23.3 and LLVM version 18.1.2)`

wasm tools installed via homebrew.

**Comment by Piceh** [comment]
Hi I am having the same iissue. I am just trying to follow the examples in the docs. 

Seems like my setup is the exact same as yours.

macOS 15.1 (running on m4 macbook)

tinygo version 0.34.0 darwin/arm64 (using go version go1.23.3 and LLVM version 18.1.2)

wash          v0.37.0
├ nats-server v2.10.20
├ wadm        v0.18.0
└ wasmcloud   v1.4.2

This is the only log that is being linked to so hopefully this can help.

```
/.wash/dev/naOoYp/wasmcloud.log
2024-11-17T02:26:30.858351Z  INFO async_nats: event: connected
2024-11-17T02:26:30.858437Z  INFO async_nats: event: connected
2024-11-17T02:26:30.904625Z  INFO wasmcloud_host::wasmbus: bucket already exists. Skipping creation. bucket=LATTICEDATA_default
2024-11-17T02:26:30.904802Z  INFO wasmcloud_host::wasmbus: bucket already exists. Skipping creation. bucket=CONFIGDATA_default
2024-11-17T02:26:30.907125Z  INFO wasmcloud_host::wasmbus: wasmCloud host started host_id="NBYQ3FCFPCUP77ZGMF5IZ7QG6F6THYVWAGN2OEBVQMXHRVFGUT33QRMZ"
```

**Comment by fbaube** [comment]
The question of `public access to the GitHub OCI`. If I have an account at Github, do I have appropriate access to `ghcr.io`? So I could (in principle) write wasm modules to it as OCI objects ? I had a look at documentation about registries (scattered here & there) but I could not make heads nor tails of it. It would be extremely helpful to have a brief markdown document about what a registry does, how to establish one for private or public use, and how to use it with the various wasmCloud tools (and Tiny Go, where appropriate). 

Also, FWIW `wash new component ` is producing scaffolding with version 0.2.0 of everything, but it looks like version 0.2.2 has some big changes. I am trying to create a "kitchen sink" example for TinyGo that shows (very simply) how the tools work and what a project for the command line can look like. 

Also, for now

**Comment by brooksmtownsend** [comment]
Hey @fbaube, all public `ghcr.io` registry images don't require an account, but if you do have an account you can push Wasm components to the `ghcr.io` registry as a package 🙂 

For example: https://wasmcloud.com/docs/developer/components/publish#pushing-to-authenticated-registries

Regarding your comment of `0.2.2`, it does have some changes but is largely backwards compatible with `0.2.0`, and we would just need to update some of our examples to bring them up to the latest version. wasmCloud supports 0.2.0 / 0.2.1 / 0.2.2 so it should be no problem.

Regarding this issue, since you said it works for you now, I'm going to close it out but feel free to ask more questions / open another issue if you hit problems
