### ISSUE TITLE
Handle `wasmbus` requests concurrently

### ISSUE THREAD

**Issue by rvolosatovs** [wasmCloud/wasmCloud#367]
Curently, all `wasmbus` lattice requests are handled sequentially, which eliminates possibility of race conditions and weird behaviors caused by out-of-order request handling. This should be parallelized, but the decision making should happen on per-request basis.
For the most trivial example, no other requests should be handled after `host stop` command is received, most likely, in fact, all other requests should finish processing before that command is executed.

**Comment by brooksmtownsend** [comment]
Partially addressed by #716. Not handling requests after `host stop` isn't implemented but concurrent handling is

**Comment by connorsmith256** [comment]
@rvolosatovs @brooksmtownsend thoughts on closing this one and opening a new issue to track the host not handling requests after a `stop` message? The current title feels outdated

**Comment by brooksmtownsend** [comment]
I'm a fan of another issue that captures the desire to not accept more requests after host stop and finish other requests that we're currently executing when host stop is handled
