### ISSUE TITLE
[BUG] The "Hello World" program failed to run in Kubernetes (K8s)

### ISSUE THREAD

**Issue by tqq1994516** [wasmCloud/wasmCloud#3764]
### Affected project(s)

- [ ] documentation
- [X] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

I followed the installation guide of [Deploying wasmCloud on Kubernetes](https://wasmcloud.com/docs/deployment/k8s/#deployment-with-helm) and applied the application configuration, but the service didn't show up.
![image](https://github.com/user-attachments/assets/9dc5da99-d63f-442c-98c7-97cffaf00b64)
I checked the logs of `wasmcloud-operator` and it showed that

```
2024-12-04T15:04:57.613908Z ERROR controller::router: err=applications "hello-world" not found
```

### Steps to reproduce

1.I followed the installation guide of [Deploying wasmCloud on Kubernetes](https://wasmcloud.com/docs/deployment/k8s/#deployment-with-helm) and applied the application configuration, but the service didn't show up.

### Expected behavior

It's running normally.

### Environment

- OS: [Linux]
- Shell [bash]
- wasmcloud Version [1.x]

### Screenshots / Logs / Additional context

![image](https://github.com/user-attachments/assets/9dc5da99-d63f-442c-98c7-97cffaf00b64)
```
2024-12-04T15:04:57.613908Z ERROR controller::router: err=applications "hello-world" not found
```

**Comment by tqq1994516** [comment]
This is a problem with my own image.

**Comment by brooksmtownsend** [comment]
Hey @tqq1994516 , what did the problem end up being? Just in case others stumble on this later on
