### ISSUE TITLE
Add `wasmcloud-provider-macros` crate

### ISSUE THREAD

**Issue by rvolosatovs** [wasmCloud/wasmCloud#388]
`wasmcloud-provider-macros` crate should be added in `crates/provider/macros` once #387 is done

cc @vados-cosmonic

**Comment by connorsmith256** [comment]
Is `wasmcloud-provider-macros` supposed to be something different than `provider-wit-bindgen`?

**Comment by rvolosatovs** [comment]
no, this should have been closed by the PR
