### ISSUE TITLE
[BUG] TS http-hello-world example fails to build

### ISSUE THREAD

**Issue by atroche** [wasmCloud/wasmCloud#3882]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [X] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

I made a repo to help reproduction: https://github.com/atroche/wasmcloud-ts-issue-repro

I've been going through the tutorial, using typescript, trying to follow the instructions closely.
I'm at the step where I'm adding logging -- so far everything's worked well. I've added the import in world.wit and then in the TS src file:

```
  import wasi:logging/logging@0.1.0-draft; 
//@ts-expect-error -- these types aren't currently generated by JCO
import { log } from 'wasi:logging/logging';
```

but I'm seeing this (cleaned up linebreaks and removed my username):

```
❯ wash dev
ℹ️   Resolved wash session ID [D3Q126]
🚧 Starting a new host...
ℹ️   NATS server successfully started, using config @ [~/.wash/downloads/nats.conf]
ℹ️   NATS server logs written to [~/.wash/dev/D3Q126/nats.log]
👀 Found wadm version on the disk: wadm-cli 0.18.0
✅ Using wadm version [v0.18.0]
🔧 Successfully started wasmCloud instance
✅ Successfully started host, logs writing to ~/.wash/dev/D3Q126/wasmcloud.log
🚧 Building project...
⛔ Failed to build project:

failed to build component with custom command:
"Error opening file ./wasi__logging$logging.js (resolved to /var/folders/1v/rtt8x01j3tn_5k2w7x0zj8b00000gn/T/42aee0ad3a85/sources/wasi__logging$logging.js): No such file or directory

Error while evaluating top-level script, but no exception is pending. Aborting, since that doesn't seem recoverable at all.

Error: the `componentize.wizer` function trapped

Caused by:
    0: error while executing at wasm backtrace:
           0: 0x78f2b2 - <unknown>!<wasm function 12768>
           1: 0x78fc25 - <unknown>!<wasm function 12784>
           2: 0x217a6 - <unknown>!<wasm function 181>
           3: 0x20759 - <unknown>!<wasm function 179>
           4: 0xb8ae  - <unknown>!<wasm function 161>
           5: 0x226a6c - <unknown>!<wasm function 5087>

    1: Exited with i32 exit status 1

Error: Failed to initialize the compiled Wasm binary with Wizer:
Wizering failed to complete
    at componentize (file:///path/to/node_modules/@bytecodealliance/componentize-js/src/componentize.js:271:13)
    at async componentize (file:///path/to/node_modules/@bytecodealliance/jco/src/cmd/componentize.js:11:25)
    at async file:///path/to/node_modules/@bytecodealliance/jco/src/jco.js:200:9
"
```

any clues? if it's relevant, I am on latest node (v23.5), and on Mac OS 15.2.

I've uploaded my package-lock.json just in case, along with the current contents of world.wit and the TS src file:
https://gist.github.com/atroche/3f942030488fd8f3956f52d2d7d5dc93

### Steps to reproduce

```
git clone https://github.com/atroche/wasmcloud-ts-issue-repro
cd wasmcloud-ts-issue-repro
wash dev
```

### Expected behavior

I expected to see an info log in the `wash dev` output corresponding to the call to the log function imported in `src/http-hello-world.ts`.

### Environment

- OS: Mac OS 15.2
- Shell: fish
- Node: v23.5
- npm: 11.0.0

wash          v0.37.0
├ nats-server v2.10.20
├ wadm        v0.18.0
└ wasmcloud   v1.4.2

**Comment by lachieh** [comment]
Looks like this is a bug in the example code! Thanks for the issue!

Quickest fix is to change the line in `src/http-hello-world.ts` like this so that the import statement matches the version in the wit file:

```diff
- import { log } from 'wasi:logging/logging';
+ import { log } from 'wasi:logging/logging@0.1.0-draft';
```

Give that a go and let us know how you go.

**Comment by atroche** [comment]
thanks! working well now
