### ISSUE TITLE
SPIKE: Check if we can add in NATS header tracing simultaneously

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmCloud#394]
@connorsmith256 left [a comment](https://github.com/wasmCloud/wasmCloud/pull/393#pullrequestreview-1546661868) about maybe supporting NATS header tracing in the provider SDK still. I think the current plan is for the new provider SDK to just work for the new Rust host (i.e. not backwards compatible). The Rust host should probably support both for now, but I figure we should at least look into how hard it would be to add in to the current provider SDK.

One important requirement: adding this in MUST NOT expose async_nats in the public API. This was the cause of many dependency hell issues in the past and we won't want that

**Comment by connorsmith256** [comment]
Closing this since the new provider SDK is only intended for use with the new host, which does parse trace_context off the invocation body. The new host also attaches OTEL headers to the NATS message itself for the time being, to support legacy providers
