### ISSUE TITLE
Adopt `bors` or similar

### ISSUE THREAD

**Issue by rvolosatovs** [wasmCloud/wasmCloud#424]
Using a merge bot like https://bors.tech/ would let us avoid accidentally breaking `main`

refs https://github.com/wasmCloud/wasmCloud/pull/423

**Comment by rvolosatovs** [comment]
> Looks like Bors actually recommends using the GH merge queue feature on their main page: https://github.blog/2023-07-12-github-merge-queue-is-generally-available/

It's a new feature I have not had a chance to try yet, could you enable it?

**Comment by thomastaylor312** [comment]
Went to turn it on and it informed me of this change we need to do to our triggers: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions

Once we do that we can turn on the merge queue

**Comment by vados-cosmonic** [comment]
Since we now have merge queues enabled, we probably don't need this anymore! Let's re-open if we ever decide to switch to a smarter bot for merging PRs/doing other tasks.
