### ISSUE TITLE
wasmcloud-host oci pull should support insecure connections for local development

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#44]
Currently, the `fetch_oci_bytes` function in wasmcloud-host creates an `oci_distribution::client` with default values, which always prefers HTTPS. Because of this, insecure registry connections (like the docker local registry) cannot succeed as it connects over HTTP. HTTPS should be the default, but we should also support insecure connections (perhaps with an `allow_insecure` argument) in the case of local development

**Comment by tiptop96** [comment]
Opened a PR for this (#45). Not sure if this is what you were looking for but I thought I'd give it a shot.

**Comment by brooksmtownsend** [comment]
Closed by #45
