### ISSUE TITLE
Add basic error handling for provider linking operations

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmCloud#452]
Previously, wasmbus_rpc didn't really do anything with the errors returned from the `put_link` and `delete_link` functions in a provider. This means that currently those don't even return errors. Before we fully release the rust host, we should at least put some sort of error handling that the provider can send and the host can receive. 

NOTE: this explicitly does not include in scope the linkdef status stuff as discussed in #342 as that is a bigger overall change. However, this work should at least inform/enable that work down the line

**Comment by thomastaylor312** [comment]
I would love to have this, but I think it is going to have to be some sort of provider event since it will happen on config updates rather than on actual link

**Comment by vados-cosmonic** [comment]
This is done as we now have [the `Provider` trait using `Result`s](https://github.com/wasmCloud/wasmCloud/blob/00a9d5d9ab3e727607851f91de8e1e34479c1699/crates/provider-sdk/src/lib.rs#L183)
