### ISSUE TITLE
Figure out what we want to do with updating otel dependencies

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmCloud#453]
#407 updated the `opentelemetry` crate, but when we attempted this upgrade before for providers it means we have to update everything to match new structs and require a dep on protoc to build all the otel stuff. Previously, we've said this is a dependency we don't want provider authors to need to install. So we need to do two things to resolve this issue:

1. Decide how we want to handle the `protoc` dependency
2. Actually update all the tracing and otel crates to the latest version

**Comment by rvolosatovs** [comment]
In terms of CI, `protoc` is already installed, and I thought that the protobuf build library used internally vendors the binary for all common systems, doesn't it?

**Comment by thomastaylor312** [comment]
I was pulling up the link to the issue where it mentioned they were removing the vendored binary and it turns out the latest versions have removed the dependency on generating the files with `protoc`: https://github.com/open-telemetry/opentelemetry-rust/pull/881. So we should be able to update these as soon as we have spare cycles
