### ISSUE TITLE
[RFC] Per-interface links

### ISSUE THREAD

**Issue by rvolosatovs** [wasmCloud/wasmCloud#458]
# RFC: Per-interface links

## Introduction

This RFC is a feature request to allow per-interface links, i.e. being able to link an actor and provider using a "contract ID" of the following form: `package/interface`, for example `wasi:http/incoming-handler`

## Motivation

WIT package definitions may contain interfaces, that are meant to be implemented by two distinctly different providers

This is most prominent in standard WASI packages (#421), for example, `wasi:http` (https://github.com/WebAssembly/wasi-http)

- `wasi:http/incoming-handler` https://github.com/WebAssembly/wasi-http/blob/e01ac854a0a1756576d12f67f222f5a56fd9b77a/wit/incoming-handler.wit
- `wasi:http/outgoing-handler` https://github.com/WebAssembly/wasi-http/blob/e01ac854a0a1756576d12f67f222f5a56fd9b77a/wit/outgoing-handler.wit

These interfaces are represented by an HTTP server and HTTP client respectively in "wasmCloud universe", but existing wasmbus lattice protocol is incompatible with this approach. 

## Detailed Design

Rather than referring to package names, links, wascap contract names and everything else should refer to interface names.

In a transitional period we could allow both package-level links and interface links, but eventually we should fully migrate to the latter.

I will update this RFC with more detailed design later once I have more time and context.

## Backwards Compatibility

We'd need a transitional period supporting both link types or we should just introduce a different wasmbus lattice protocol version

## Alternatives Considered

none really, unless we persuade all WebAssembly component model ecosystem to rework almost all the existing packages to split interfaces per-package, which does not make much sense in WIT world

## Unresolved Questions

There are more incompatibilities with component model in existing wasmbus lattice protocol design, which deserves another RFC (or a few). It may be more worthwhile to fully rebuild the protocol with component model in mind.

## Conclusion

TBD

**Comment by brooksmtownsend** [comment]
This is proposed in #1389 and we'll track this effort there for simplicity 🙂
