### ISSUE TITLE
[Rust Host] Support non-default link names

### ISSUE THREAD

**Issue by connorsmith256** [wasmCloud/wasmCloud#461]
The Rust host uses `default` everywhere for link names. It should support setting and communicating on different link names

**Comment by rvolosatovs** [comment]
> That sounds good, but do note that this feature is specific to Wasm modules, since it's incompatible with component model.
> 
> A component cannot select a particular "link namespace" at runtime given just #421 . For example, consider `wasmcloud:messaging/consumer.publish`
> 
> https://github.com/wasmCloud/wasmCloud/blob/c9fecb99793649a6f9321b9224f85b9472889dec/wit/messaging/messaging.wit#L36
> 
> There is no way for the actor to provide a link name as part of the call.
> 
> We could introduce a custom WIT interface for this functionality, having something like `select_link(name, interface)`, which a component would need to call before e.g. calling `messaging.publish`, but a component would need to call this custom wasmCloud thing before each call, which is:
> 
>     1. Error-prone
> 
>     2. Tedious
> 
>     3. Locking users in a walled "wasmCloud" garden, since their components would depend on this proprietary API
> 
> 
> If you ask me, I am strongly against the proprietary API as described above.
> 
> In short, design of this feature for component model requires an RFC, but we probably want to implement it for the module world anyway to support legacy actors

Just a quick update here following an offline discussion: the consensus is to introduce a proprietary WIT API largely as outlined in https://github.com/wasmCloud/wasmCloud/issues/317, a PR will follow
