### ISSUE TITLE
[Rust Host] Determine security model around logging/tracing

### ISSUE THREAD

**Issue by connorsmith256** [wasmCloud/wasmCloud#468]
As mentioned in https://github.com/wasmCloud/wasmCloud/pull/466#pullrequestreview-1575882493, there is a security concern around enabling trace logs in the host, which may leak sensitive information

For now we're prioritizing the ability to debug release builds, but we should revisit this and determine what is acceptable to allow users to enable

**Comment by thomastaylor312** [comment]
Was going through wasmCloud 1.0 stuff and rediscovered this issue. I don't think there is anything to do here. Almost all the software I have ever used in production that hasn't been built custom for us (i.e. any software we download from an open source project) doesn't do anything to restrict log or tracing levels. If someone really wants this, we could have a feature flag, but I don't think this is necessary and we can close

**Comment by brooksmtownsend** [comment]
I'm in favor of closing and, if it's relevant, we can reopen in the future
