### ISSUE TITLE
Convert providers to use wit-bindgen-wasmcloud-provider

### ISSUE THREAD

**Issue by vados-cosmonic** [wasmCloud/wasmCloud#470]
Once the providers w/ `wasmcloud-provider-sdk` usage have stabilized, providers should be converted to use `wit-bindgen-wasmcloud-provider`.

**Comment by connorsmith256** [comment]
Not stale, this is in progress

**Comment by connorsmith256** [comment]
@vados-cosmonic are any providers left here, or can we close this as completed?

**Comment by vados-cosmonic** [comment]
I don't think we can close this as completed just yet since the `sqldb-*` providers are still left -- they *do* require some fundamental work though, because of how they were implemented originally. A straight forward port would be fastest, but the contract really needs to change. 

Maybe we can close this as completed since those other providers require fundamental changes?

**Comment by connorsmith256** [comment]
Ah right. Up to you. I'm okay closing and filing separate tasks for the sql providers, since they'll use new contracts

**Comment by vados-cosmonic** [comment]
Filed [an issue](https://github.com/wasmCloud/wasmCloud/issues/1408) for the other contracts, closing this for now!
