### ISSUE TITLE
[Rust Host] Actor (module) -> provider invocations don't make it to the bus

### ISSUE THREAD

**Issue by connorsmith256** [wasmCloud/wasmCloud#494]
From local debugging/print lines, the await on [read_to_end](https://github.com/wasmCloud/wasmCloud/blob/main/crates/host/src/wasmbus/mod.rs#L426) never resolves, so invocations don't make it onto `wasmbus.rpc`

Example to reproduce:
```
wash start actor wasmcloud.azurecr.io/kvcounter:0.4.2
wash start provider wasmcloud.azurecr.io/httpserver:0.19.1
wash start provider wasmcloud.azurecr.io/kvredis:0.22.0

wash link put MCFMFDWFHGKELOXPCNCDXKK5OFLHBVEWRAOXR5JSQUD2TOFRE3DFPM7E VAG3QITQQ2ODAOWB5TTQSDJ53XK3SHBEIFNK4AYJ5RKAX2UNSCAPHA5M wasmcloud:httpserver address=0.0.0.0:1234

wash link put -x default -p 4222 MCFMFDWFHGKELOXPCNCDXKK5OFLHBVEWRAOXR5JSQUD2TOFRE3DFPM7E VAZVC4RX54J2NVCMCW7BPCAHGGG5XZXDBXFUMDUXGESTMQEJLC3YVZWB wasmcloud:keyvalue

curl 127.0.0.1:1234/api/counter
```

If you `nats sub wasmbus.rpc.>`, you'll see the actor module invocation on the bus, but won't see the provider call

**Comment by rvolosatovs** [comment]
Host calls don't actually work in module world yet, that's blocked on #493 and impl in https://github.com/wasmCloud/wasmCloud/issues/469

**Comment by connorsmith256** [comment]
Thanks for the clarification. I updated the title and content to reflect this only applies to actors that are modules
