### ISSUE TITLE
[RFC] Wasifills

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmCloud#497]
# RFC: Wasifills

As wasmCloud moves to components, we've introduced the concept of a wasifill. These components help bridge the gap between pure wit interfaces and the logic needed to operate within wasmCloud.

This RFC provides basic architectural principles governing wasifills as well as how they should be stored and retrieved.

## Basic overview

Primarily, wasifills will be written only once for a custom interface (not for any of the wasi-cloud contracts, as those are built in to our host). Wasifills are standalone components that export interfaces that actors import, and import interfaces that actors export. Using these exports and imports a wasifill bridges them to the host by exporting a specific guestcall function that the host can use to call exports in the actor and providing translation to wasmbus calls.

Each contract _only requires a single wasifill_, no matter how many other implementations (i.e. providers) exist. Because this is Wasm, the wasifill can be written in any language that supports components and can be used with an actor component written in any other language. :tada: 

## Implementation details

The examples in this section will be based on the `wasmcloud:messaging` interface. This specific example will be built-in but is a great example interface because an actor can both export and import from this contract:

```
package wasmcloud:messaging@0.1.0
// Types common to message broker interactions
interface types {
    // A message sent to or received from a broker
    record broker-message {
        subject: string,
        body: option<list<u8>>,
        reply-to: option<string>,
    }
}
interface handler {
    use types.{broker-message}
    // Callback handled to invoke a function when a message is received from a subscription
    handle-message: func(msg: broker-message) -> result<_, string>
}
interface consumer {
    use types.{broker-message}
    // Perform a request operation on a subject
    request: func(subject: string, body: option<list<u8>>, timeout-ms: u32) -> result<broker-message, string>
    // Performs a request and collects multiple responses. If a non-zero timeout is supplied, this will finish a collection at that time, unless
    // maximum results is reached first. If both timeout-ms and max-results are 0, the provider will choose when to terminate
    request-multi: func(subject: string, body: option<list<u8>>, timeout-ms: u32, max-results: u32) -> result<list<broker-message>, string>
    // Publish a message to a subject without awaiting a response
    publish: func(msg: broker-message) -> result<_, string>
}
```

In this example, you can see that there is an interface called `handler` that allows you to handle an incoming message. This is the function that an actor component would export. The `consumer` interface on the other hand is an interface an actor component would consume in order to send messages. In wit terminology, this is described with what is called a `world`:

```
world messaging {
    import consumer
    export handler
}
```

This is saying that the actor will import the consumer interface for usage and that it will export a handler function that can be called.

With that out of the way, let's discuss how a wasifill is created.

### Imports and exports

The wit definition for the wasifill implementation in this example will look like this:

```
package wasmcloud:messaging-wasifill

interface guestcall-messaging {
    guestcall-messaging: func(operation: string) -> result<_, string>
}

world wasifill {
    export wasmcloud:messaging/consumer@0.1.0
    import wasmcloud:messaging/handler@0.1.0
    import wasmcloud:bus/host
    export guestcall-messaging
}
```

This wit definition will be automatically generated by `wash` when a new interface is created (this functionality does not yet exist). 

There are two key parts of this file. The first is the `guestcall-messaging` interface. This defines a single function which is the guestcall called by the host when it needs to call an exported function from the actor. In this specific case, if it is calling the `handle-message` function defined earlier.

The `world` defintion shows that this wasifill will export the functions from the messaging `consumer` interface for the actor to consume, it also shows that it will be importing the messaging `handler` interface functions to call. It also imports the wasmCloud `host` interface that lets us send calls over wasmbus. 

### Code example

Ok, that was a lot to take in. Let's describe the actual implementation in code with some snippets. Please note that these are for illustrative purposes only and might not be fully functional code.

The first thing will be pulling in the wasifill world as described above. This will generate the code needed to implement the functions we have to export

```rust
wit_bindgen::generate!("wasifill");
```

This next snippet shows the implementation of `guestcall-messaging`. Note that in this case, there is only one method, but if there were multiple exports from the actor component, this would have more `match` statement branches

```rust
struct WasifillImpl;

impl exports::wasmcloud::messaging_wasifill::guestcall_messaging::GuestcallMessaging
    for WasifillImpl
{
    fn guestcall_messaging(
        operation: ::wit_bindgen::rt::string::String,
    ) -> Result<(), ::wit_bindgen::rt::string::String> {
        // Please note that here we only have one operation, but there could be multiple 
        match operation.as_ref() {
            "Message.Handle" => {
                let mut de = ::rmp_serde::Deserializer::new(std::io::stdin());
                let msg = BrokerMessage::deserialize(&mut de).map_err(|e| e.to_string())?;
                // Here is where we call the `handle_message` import from the actor
                wasmcloud::messaging::handler::handle_message(&msg)
            }
            _ => Err(format!("unknown operation {}", operation)),
        }
    }
}
```

The next snippet shows how we can implement one of the functions of the `consumer` interface and translate the calls from the actor into a wasmbus invocation (read the annotation comments to follow along):

```rust
impl exports::wasmcloud::messaging::consumer::Consumer for WasifillImpl {
    fn request(
        subject: ::wit_bindgen::rt::string::String,
        body: Option<::wit_bindgen::rt::vec::Vec<u8>>,
        timeout_ms: u32,
    ) -> Result<
        exports::wasmcloud::messaging::consumer::BrokerMessage,
        ::wit_bindgen::rt::string::String,
    > {
        // Take all the parameters and serialize them to the opaque payload we need to send
        let body = ::rmp_serde::to_vec_named(&RequestBody {
            subject,
            body,
            timeout_ms,
        })
        .map_err(|e| e.to_string())?;

        // Use the host call function to send the body
        let (res, input, output) = wasmcloud::bus::host::call("Message.Request")?;
        let mut output_stream = ::wasmcloud_actor::OutputStreamWriter::from(output);
        output_stream.write_all(&body).map_err(|e| e.to_string())?;

        let input_stream = ::wasmcloud_actor::InputStreamReader::from(input);

        let mut de = ::rmp_serde::Deserializer::new(input_stream);
        // Get the response data back from the host call
        match BrokerMessage::deserialize(&mut de) {
            // elided for brevity
        }
    }
}
```

### Creating a wasifill

By default, we plan on including tooling in `wash` that will automatically generate a wasifill for you from your wit defintions. However, it is important to note that users have the flexibility to write any custom wasifill they desire. By default, we use messagepack encoding for the opaque payload sent to actors and providers. However, some advanced use cases might included encryption or other encoding formats. These can be supported by modifying the generated wasifill. The fully implemented example for the messaging contract is around 185 lines of Rust code and so these should not be too difficult to write if you desire a custom wasifill

### The Multiplexer

You may have noticed that the function name for the guestcall was `guestcall-messaging`. Obviously the host cannot know the name of your custom contract. However, there are many use cases when an actor component may export multiple contracts (e.g. an actor that can respond to an http request _or_ a message). The wasmbus protocol provides enough information to know how to route the message to the appropriate guestcall. This component will inspect the method name (i.e. `Messaging.HandleRequest`) and then route the guestcall to `guestcall-messaging`.

This component will be automatically created when `wash build` is run and then composed together with the actor component and wasifill. This should _always_ be transparent to the user

### Putting it all together

This diagram shows how all the different parts fit together. In it are two custom contracts `foo` and `bar`. This shows how all of the imports and exports are satisfied

![image](https://github.com/wasmCloud/wasmCloud/assets/4294228/e51d6ad6-6f72-4940-8010-450556bca755)

Another way to state this is after all the parts are smooshed (yes, that is _totally_ the technical term) together, you have a `world` that looks like this because all of the other exports and imports are satisfied internally:

```
world actor-component {
    import hostcall
    export guestcall
}
```

Please note that this world is not accurate for components that just consume wasi interfaces. Wasi-only components will not need wasifills or multiplexers.

## Storing and Retrieving Wasifills

Until a wasm-aware registry solution is generally available, we will need a place to store wasifill components for use when building actors. As we are already using OCI registries, this RFC proposes storing and retrieving wasifills from OCI registries

When tagging OCI manifests for wasifills, implementors SHOULD use the following format:

```
<registry-url>/<package-org>/<package-name>:<package-version>
```

In context of wasmCloud, to keep parity with our current requirements around versioning, _all_ custom contracts and wasifills built from them MUST be versioned and MUST match the version of the package (e.g. if you have mything:foo@0.1.0, it can't be tagged as 0.2.0)

Some examples below:

| Wit package name | Example reference | 
| -------- | -------- | 
| package wasmcloud:foobar@0.1.0     | wasmcloud.azurecr.io/wasmcloud/foobar:0.1.0     |
| package thomastaylor312:coolcontract@1.0.0-alpha.1 | another.oci.reg/thomastaylor312/coolcontract:1.0.0-alpha.1 |
| package mycompany:superduper | Invalid, as there is no version |

`wash push` will need to have added functionality that can validate that the version is correct before pushing a wasifill.

**Comment by connorsmith256** [comment]
@rvolosatovs Would you mind summarizing the latest thinking on this?

**Comment by thomastaylor312** [comment]
I actually can summarize here and close since this has been supplanted by work that has already landed. Because a component is self describing, we can actually dynamically call the interfaces just based on what is exposed from the component. So we now do the "generation" on the fly for a custom contract (it is actually closer to reflection). This is partially implemented, but we are in progress on other RFCs like #1128 that will allow us to do everything. So the tl;dr is that wasifills will no longer be needed.

I'll close this for now, but feel free to add more if you'd like to @rvolosatovs
