### ISSUE TITLE
Rename bindings to links

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#5]
In the "old" version, we used the word "bindings", but it seems that this is slightly confusing because it has connotations from other aspects of programming, configuration, actor models, etc. Instead, we want to refer to them as links.

A _link_ is a _declared_, free-standing entity that consists of a source entity (the actor), a target entity (the capability provider), and a logical instance name for that provider. metadata belonging to this link also includes the contract ID of the provider in question.

A link is "up" when both the actor and the provider (no matter how many instances within a lattice) are running. That link can be "up" even if neither the actor nor the provider are running in the same host. A link is "Down" when _no_ participants are detectable in the lattice, and a link is "Pending" when 1 of the 2 required participants are detectable within the lattice.

From a code perspective, this really just means changing the `set_binding` function on the `Host` struct to `set_link` (or maybe `define_link`). It should also change all in-code documentation and any error messages, trace output, logging, etc to reflect the new terminology. The control plane interface functions probably also need to be renamed.

**Comment by mikezupper** [comment]
Im taking a look at this issue. Just so I am clear, the function set_binding of the impl Host struct (host.rs) should be changed to set_binding? what about the names of the variables? For instance, binding_name is referenced in many places of the host.rs file.

**Comment by autodidaddict** [comment]
I get over a 100 matches when I search for the word `binding` in the existing codebase. I don't know off hand if all of that needs to be changed. A couple that I can think of off the top of my head:

* the `set_binding` function in the host impl in host.rs should be changed to `set_link`
* the data definition for the manifest contains a `bindings` section that should be renamed to `links`
* binding name should also probably be renamed to `link_name` wherever appropriate.
* the message bus responds to a `FindBindings` and an `AdvertiseBinding` message, those should be renamed to `FindLinks` and `AdvertiseLink`.
    * downstream there are a number of places that refer to "advertise binding" that should all be renamed, this includes the `advertise_binding` method on the lattice provider

There's probably a handful of others.

**Comment by autodidaddict** [comment]
the `bindings_cache` internal variable should change to `links_cache` etc.

**Comment by autodidaddict** [comment]
From a conceptual level, a `Link` is , as its name implies, a link between an actor and a capability provider, that bears the following information:

* Actor - 56 character all-uppercase string that always begins with the letter **M**
* Capability Provider's public key (provider links are required to be tied to _specific_ providers and not just to the contract ID) - a 56-character all-uppercase string that always begins with the letter **V**
* Contract ID (not a key value, but required metadata) - e.g. `wascc:keyvalue` or `wascc:http_server`
* Link Name (formerly binding name) - e.g. `default` or `cache` or `customer`

A "link name" is a logical name given to the capability provider when it is loaded into a host. By default, the link names are always `default`. But, let's say you want your actor to access 1 key-value provider for "customer" data and another key-value provider for "cart" data. If you wanted, you could then load a redis provider with a link name of `cart` and another redis (or cassandra or whatever) provider with a link name of `customer`. Then, in the actor code, you differentiate between which host provided capability you're talking to by supplying the link name.

**Comment by mikezupper** [comment]
i created a PR for this issue. Please take a look
