### ISSUE TITLE
[Rust Host] Consider caching claims/linkdefs in memory

### ISSUE THREAD

**Issue by connorsmith256** [wasmCloud/wasmCloud#507]
This is a potential optimization to avoid having to do a full KV scan on incoming requests to query claims/linkdefs

**Comment by Iceber** [comment]
I've found that for links and claims, the control-interface client already prefers to query the kvstore, and only requests `get.claims` if it doesn't provide a jetstream address. **So if there's no other logic in the host that would use claims**, there's not much of a need to cache it, this is just my personal opinion. This is just my personal opinion.

If requesting `get.claims` is the main way to get claims, then I would recommend caching them to optimize the query, but it's not

**Comment by connorsmith256** [comment]
That's correct, most clients (e.g. wash) will use the control interface client to query links/claims via the KV bucket directly.

However, there is one major exception: multi-tenant wadm setups. In those cases, wadm does not have the ability to query the KV bucket, since wadm runs in a different NATS account than (at least some of) the lattices it manages. As a result, in the simplest multi-tenant setup, wadm queries hosts for links/claims.

(This is accomplished by using NATS subject imports/exports, to expose the control interface topics across accounts. In theory we might be able to expose the underlying stream topics for the KV bucket, but I'm not sure we've investigated an approach like that. @brooksmtownsend might be able to provide more information)
