### ISSUE TITLE
Actor supervision model

### ISSUE THREAD

**Issue by shafqatevo** [wasmCloud/wasmCloud#51]
Hi,

Is there any plan to support actor supervision hierarchies (parent-child trees) like Erlang or Akka? Or is the supervision, fault tolerance and fault isolation model different in wasmCloud?

Thanks!

**Comment by autodidaddict** [comment]
In short we're waiting for more experience stories from consumers running workloads in production or test environments to figure out how far down the supervision rabbit hole we go.

In today's (0.15.0, to be released in the next week or two) code, we do not have explicit supervision. Actors cannot spawn child actors, and actors are not automatically restarted by the host runtime when they crash. I suspect we need to add an issue to the backlog to support the host runtime restarting actors that fail their internal health check (the runtime issues a heartbeat ping to all providers and actors running on a configurable interval).

Supervision hierarchies are hard, both to code and to use as a developer. One of our current primary goals is to dramatically reduce the amount of boilerplate, complexity, and friction experienced by developers when building distributed applications that run anywhere. Any design we come up with for actor supervision needs to be something that actually makes developer lives easier and doesn't instead foist more complexity upon them.

We also don't currently have any known use cases for an actor that spawns a child hierarchy. The devil is in the details there - for example, there are a whole set of rules that need to be determined for how actor hierarchies would work within the context of a lattice.

Per your other issue, I think if we do an RFC to design a supervision hierarchy strategy, that would also be an ideal time to think about local actor pools.

**Comment by shafqatevo** [comment]
Thanks @autodidaddict !

Yeah, early days only. The journey has just started. Hopefully these aspects will shape up. I have a clearer idea now.

**Comment by brooksmtownsend** [comment]
Depends on #54

**Comment by brooksmtownsend** [comment]
Hey @shafqatevo it's been a while, I think you'd be very interested in our new main runtime that has an Elixir/OTP supervision foundation. You can check it out [here](https://github.com/wasmCloud/wasmcloud-otp)
