### ISSUE TITLE
Add tracing vars to HostData

### ISSUE THREAD

**Issue by connorsmith256** [wasmCloud/wasmCloud#523]
As of https://github.com/wasmCloud/wasmCloud/pull/522 the host will no longer proxy environment variables to providers, so providers will need to receive `OTEL_TRACES_EXPORTER` and `OTEL_EXPORTER_OTLP_ENDPOINT` from the host via `HostData`

Both the host and provider SDK need to be updated:
- the host should send the two OTEL config values via the `HostData` JSON
- the provider SDK should be updated to read the two OTEL config values from this data

**Comment by Iceber** [comment]
> Providers should not implicitly receive environment variables from the host, since this is a security risk.

I couldn't agree more with this, but no longer using environment variables passed to the provider seems to lead to incompatibility with older providers, maybe I'm overlooking something.

https://github.com/wasmCloud/wasmCloud/blob/5f922256e679091e6acbb3e0f39852abb840c8b0/crates/host/src/wasmbus/mod.rs#L1987-L1987

Is it possible to clean up the environment variables and then set some specified environment variables?

**Comment by connorsmith256** [comment]
@Iceber I did a quick check of all known wasmCloud providers and confirmed that env vars weren't the only way to set config: they all support parsing from `config_json` in the `HostData`, and/or link def values

We should update all providers to not use `env::var` at all anymore though. I've filed that [here](https://github.com/wasmCloud/wasmCloud/issues/535)

**Comment by Iceber** [comment]
I see that reading about OTEL* configurations still uses environment variables and that this is a capability of the [wasmbus-rpc](https://github.com/wasmCloud/weld/blob/7c259adad92c359c4c5a070feb2e29c967309923/rpc-rs/src/provider_main.rs#L385)/provider-sdk framework. Do we also need to make these two frameworks no longer use environment variables?

**Comment by connorsmith256** [comment]
That's right, this ticket should capture both sides of the work:
- the host should send the two OTEL config values via the `HostData` JSON
- the provider SDK should be updated to read the two OTEL config values from this data

I've updated the description of this ticket to mention that explicitly 👍
