### ISSUE TITLE
Community Chat (slack? matrix?)

### ISSUE THREAD

**Issue by floriankoch** [wasmCloud/wasmCloud#53]
i think its a good idea to have a community chat aviable, its easier to ask questions in a chat as in github issues

**Comment by autodidaddict** [comment]
We already have a community slack. Let us know your email and we'll send you an invite.

We also have a regular community zoom call on Wednesdays at 1pm est.

**Comment by LiamRandall** [comment]
We run a slack right now, which is hard as it's private atm.  I could try and open up a click through shared public channel?  We tried this for previous events, like "exploreWasm.com".

We also have a community call on Wednesdays at 1:00

We have discussed discord and slack - once we get through the .15 release (early Q1) I think this would be a good topic.  Do you have any suggestions?

**Comment by floriankoch** [comment]
@autodidaddict florian.koch1981.gmail.com

@LiamRandall  i don't know discrod , and slack ....its slack
1:00 UTC+-/?

**Comment by delokman** [comment]
hi,
please invite me to wasmcloud slack and discord community
email: rostami.aws@gmail.com

@LiamRandall 
@autodidaddict

**Comment by LiamRandall** [comment]
Hey buddy, you are already on the slack - I just sent you an email!

**Comment by delokman** [comment]
Thanks a lot 😊

**Comment by jcuffe** [comment]
Please add me as well, if open to new members! I'm interested in learning more about the platform, and possibly contributing

jcuffe@gmail.com

**Comment by autodidaddict** [comment]
check out https://slack.wasmcloud.com
