### ISSUE TITLE
[RFC] "Project bandWAgon" (Agones for wasmCloud)

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#55]
# The What
In short, this issue is here to address the question, "Can we provide an on-ramp for developing online multiplayer gaming backends for wasmCloud in a similar way that Agones provides a _gaming server_ infrastructure?" More importantly, can we do so in a way that is _easier_, _faster_, and dare-we-say more _fun_ than building against Agones?

# The Why
We've built a couple experimental gaming backends so far: a very brittle _distributed ECS_, and a demo that stitched together disparate infrastructures but would not be good for a true realtime backend. The purpose isn't really to build a gaming backend service, the purpose is to determine if wasmCloud makes such a thing possible. This would be an eating our dogfood project. In short, if you can build an Agones competitor on wasmCloud (without the hosted infrastructure bit that GKE has), then wasmCloud is a success as a tool for platform builders and we've verified that wasmCloud can indeed scale and meet performance demands while also ensuring secure, rapid deployment.

# Agones 
The following is an incomplete list of some of the key features that Agones provides or enables:

* A Game server SDK
  * Lifecycle management 
* A kubectl plugin to scale the game server fleet
* A gateway that bridges a dozen or so client SDKs (including Unreal) to your backend game server fleet
* Player Tracking (available as an in-memory cache as part of the SDK, e.g. realtime access w/out network query)
* Ability to run a local game server (this actually looks pretty high-friction, still requires Kube and doesn't include managed Agones environment). 
* Latency testing services

In Agones the unit of deployment is a docker image with the Agones pre-requisites (e.g. the "_sidecar_" that bridges client SDKs to the backend server SDK)

References:
* Agones tutorial - [Build and Run a Simple GameServer in Rust](https://agones.dev/site/docs/tutorials/simple-gameserver-rust/)

# Implementation Options
There are a couple of different things we could do to build this, and should discuss the various options.

## Agones Capability Provider
In this option, instead of building something that does what Agones does, we instead make it so that developers can deploy custom wasmCloud hosts into the Agones ecosystem by giving actors access to the Agones client SDK. This could "easily" by done by wrapping the Rust client SDK in a capability provider.

While this would certainly be faster and easier to build, what would we learn from doing so?

## Full Project bandwAgon

The one thing that is beyond the realm of responsibility of wasmCloud is the launching of processes. Once you have a host process running and it's connected to a lattice, wasmCloud is responsible for anything that happens _inside_ that process. Where Agones can let you use Kubernetes to spin up as many containers as you like, and wasmCloud will let you spin up as many actors as you like, we need to be aware of the fact that wasmCloud doesn't have a provision for starting new host processes.

I think the other important thing to keep in mind in a potential project like this is not to simply duplicate Agones functionality, but to take a look at the requirements that drove the development of Agones and see how we could solve those requirements and more using wasmCloud in a way that is optimized for wasmCloud's strengths - e.g. leveraging the small, portable actors and loosely coupled capability provider mechanism and the lattice connectivity to provide an easy way for people to build online gaming backends.

# Deliverables
I think we would be successful if we either delivered an actual product / framework or if we delivered a set of architectural guidelines and instructions on _how to build_ such a product, assuming we could back it up with enough proof that it would scale properly.

**Comment by autodidaddict** [comment]
cc @brooksmtownsend

**Comment by autodidaddict** [comment]
Updated the original comment to include the notion that we can either build an Agones alternative, or we can simply build a capability provider that talks to the Agones SDK, though there are obviously tradeoffs there and I'm not convinced we would learn anything from the latter.

**Comment by VestigeJ** [comment]
It might be helpful to target an existing open game with a lot of active development. Veloren is a bit of a showcase you've probably read about if you read the weekly Rust news. It's built with amethyst.rs an ECS game engine. 

https://veloren.net/

https://gitlab.com/veloren/veloren

https://amethyst.rs/

**Comment by autodidaddict** [comment]
Without having spent much time reading up on Veloren, we should also classify the type of back-end we're looking to build (or support the building of). For example, Agones seems very specifically focused on the concept of spinning up dedicated monoliths (microliths?) that host a given set of players, likely as a result of some kind of out-of-band matchmaking process.

The other type of backend is the "traditional" MMO backend - each logical area within the game is represented by a cluster of servers, and then instanced areas within the game are spun up on demand for each group or raid party. One could probably make the argument that if you support the first type (spinning up on-demand servers designed to handle a given subset of a game universe), then you can create the second type by building on the first ... but I'm certainly open to hearing arguments that this is not the case.

**Comment by VestigeJ** [comment]
I've been in or around a few teams trying to get away from those "instanced" paradigms and are shooting for the open world feeling again. That being said I agree you could focus on the "microlith" being an on demand spin up of the game mechanics for a certain region/ number of players. I've seen a good example for this type of auto scaling with the Aether Engine https://hadean.com/spatial-simulation/
https://youtu.be/U5fELaMK8Vw

**Comment by autodidaddict** [comment]
Yeah that's conceptually the idea that a lot of different backends go with now. The microliths are spun up to handle some subset of the universe (whether it's a single all-encompassing universe or a single 4X live match with 3 players). I'm still on the fence about whether a distributed ECS to maintain a single, unified backend simulation is a good idea.

**Comment by autodidaddict** [comment]
No one has the time for this.
