### ISSUE TITLE
Validate actor and provider claims upon start

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#554]
When starting actors and providers, their claims should be verified to ensure that the component hasn't been tampered with.

**Comment by ceejimus** [comment]
Where would be a good point start digging into this; where could I look in the original host source code for existing logic and where (roughly) would it go in the destination?

Thanks!

**Comment by brooksmtownsend** [comment]
Hey @ceejimus ! Here is the place in the NIF where we, after extracting the claims, verify that the signature is valid / not expired etc https://github.com/wasmCloud/wasmcloud-otp/blob/main/host_core/native/hostcore_wasmcloud_native/src/lib.rs#L462-L499

Here's the claims metadata struct that each Actor will embed: https://docs.rs/wascap/0.11.0/wascap/jwt/struct.Actor.html, and here's where we have access to claims during the launch actor process: https://github.com/wasmCloud/wasmCloud/blob/main/crates/host/src/wasmbus/mod.rs#L1829

And last but not least, you can see that [wascap::wasm::extract_claims](https://docs.rs/wascap/0.11.0/wascap/wasm/fn.extract_claims.html) takes care of validating the hash automatically, so as long as we're extracting the claims using wascap we're already ensuring that the hash hasn't been tampered with.

**Comment by ceejimus** [comment]
@brooksmtownsend Getting my feet wet, trying to put it all together.

First, recent commits shifted the file lines; were you pointing me to the `start_actor` function inside the `host/src/wasmbus/mod.rs`? If so, inside this function, when we get the claims @ [`let claims = actor.claims()...` ](https://github.com/wasmCloud/wasmCloud/blame/f2246c07cf38a6f142d7ce58e0623f8da5adbe83/crates/host/src/wasmbus/mod.rs#L1760)are we not already validating claims [here](https://github.com/wasmCloud/wasmCloud/blame/f2246c07cf38a6f142d7ce58e0623f8da5adbe83/crates/runtime/src/actor/mod.rs#L41)?

Is there something beyond this that we're trying to do, or am I looking in the wrong place?

I haven't looked at the provider side of things, yet.

Thanks!

**Comment by ceejimus** [comment]
@brooksmtownsend I've started digging into the code. I did a little workflow analysis, and maybe I'm lost in the woods but, hey...learning experience XD I haven't looked into the start provider workflow yet.

Anyways, a question have I.

Recent commits shifted the file lines; were you pointing me to the start_actor function inside the host/src/wasmbus/mod.rs? If so, inside this function, when we get the [claims](https://github.com/wasmCloud/wasmCloud/blob/f2246c07cf38a6f142d7ce58e0623f8da5adbe83/crates/host/src/wasmbus/mod.rs#L1760) from the actor aren't the claims already validated (see below?)

lmk if I'm being silly

### ceej's newb claims validation workflow analysis
 - [`claims`](https://github.com/wasmCloud/wasmCloud/blob/f2246c07cf38a6f142d7ce58e0623f8da5adbe83/crates/runtime/src/actor/mod.rs#L42) calls to [`wascap::wasm::extract_claims`](https://github.com/wasmCloud/wascap/blob/a1299cc722a122cbde590047bcad9d3edb57d6c2/src/wasm.rs#L32) which validates module hash and then validates dates and signature

 - [`Module::new`](https://github.com/wasmCloud/wasmCloud/blob/f2246c07cf38a6f142d7ce58e0623f8da5adbe83/crates/runtime/src/actor/module/mod.rs#L229) uses `claims` above
- [`Component::new`](https://github.com/wasmCloud/wasmCloud/blob/f2246c07cf38a6f142d7ce58e0623f8da5adbe83/crates/runtime/src/actor/component/mod.rs#L310) uses `claims` above

 - [`Actor::new`](https://github.com/wasmCloud/wasmCloud/blob/f2246c07cf38a6f142d7ce58e0623f8da5adbe83/crates/runtime/src/actor/mod.rs#L81-L83) uses the parser which calls `Module::new` or `Component::new` above

 - [`fetch_actor`](https://github.com/wasmCloud/wasmCloud/blob/f2246c07cf38a6f142d7ce58e0623f8da5adbe83/crates/host/src/wasmbus/mod.rs#L1931) uses the `Actor::new` constructor from (file/registry?)

 - `start_actor` called from fetched_actor:
   - [`handle_scale_actor`](https://github.com/wasmCloud/wasmCloud/blob/f2246c07cf38a6f142d7ce58e0623f8da5adbe83/crates/host/src/wasmbus/mod.rs#L1970)
   - [`handle_launch_actor_task`](https://github.com/wasmCloud/wasmCloud/blob/f2246c07cf38a6f142d7ce58e0623f8da5adbe83/crates/host/src/wasmbus/mod.rs#L2062)

**Comment by brooksmtownsend** [comment]
> If so, inside this function, when we get the [claims](https://github.com/wasmCloud/wasmCloud/blob/f2246c07cf38a6f142d7ce58e0623f8da5adbe83/crates/host/src/wasmbus/mod.rs#L1760) from the actor aren't the claims already validated (see below)?

@ceejimus I think you're right, the function below there validates the claims 😄
