### ISSUE TITLE
Add features to wasmCloud Cargo.toml

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#56]
The `wasmcloud-host` crate includes feature flags for selecting underlying wasm engines. The top level `wasmcloud` crate (e.g. the Cargo.toml in the root of this repository) should also include the feature flags there so users can select their wasm engine directly with the `wasmcloud` binary.

**Comment by ChrisRx** [comment]
I just ran into this and wanted to leave this as something to keep in mind for addressing this issue later:

[Cargo feature rules](https://doc.rust-lang.org/cargo/reference/features.html#rules) make all features opt-in except for the default feature, which must be opted out of for the feature to not be included.  So specifying the feature `wasmtime` for `wasmcloud-host` when building will still included the `wasm3-provider` dependency unless something like `--no-default-features` is specified.  For crates like `wasmcloud` which specify `wasmcloud-host` as a dependency, this cargo flag will not have an effect on disabling the default features of the `wasmcloud-host`.  This is not a problem but just something to keep in mind going forward with this issue.
