### ISSUE TITLE
Make OTEL settings discoverable

### ISSUE THREAD

**Issue by connorsmith256** [wasmCloud/wasmCloud#568]
As of https://github.com/wasmCloud/wasmCloud/pull/565, the host will send OTEL configuration to providers, based off env vars provided to the host. While this is a "standard" way of specifying OTEL config, not everyone who wants tracing configured will know that. We should explore making this information more discoverable to users. Some ideas:
- add config to the CLI arguments
- use custom help text on the host?

Note that a documentation page [exists already](https://wasmcloud.com/docs/production/tracing#tracing-setup-for-your-project)

**Comment by brooksmtownsend** [comment]
This might be a scenario where we draw the line in the sand for what we add to the CLI configuration, so I'm totally open to debate on this one. Perhaps documentation is sufficient here for anyone configuring tracing, I just want to avoid a scenario where we're looking for an environment variable in the codebase and that makes it difficult to know how to enable a feature

**Comment by Iceber** [comment]
I see that provider-sdk in pr is no longer compatible with environment variables, which will result in products created by provider-sdk not being able to use OTEL on wasmcloud-otp, and providers created by wasmbus-rpc will not be able to use OTEL on WasmCloud.

Of course, if the above mentioned repositories are updated in a unified way, they will be compatible with each other, but of course user-defined providers will still need to upgrade their dependencies.

Can our plan users choose to use WasmClould-OTP and WasmCloud at the same time, or will WasmCloud replace WasmCloud-OTP?

**Comment by connorsmith256** [comment]
Providers built using the new SDK won't be compatible with the OTP host. That's not _only_ because env vars (including OTEL-related ones) were removed, but also because the new SDK creates providers from wit definitions

However, we would like to be able to continue running legacy providers on the Rust host, at least for a while. This is a good callout and is something I should be able to handle in https://github.com/wasmCloud/wasmCloud/pull/572. We will have the host pass the two OTEL environment variables to legacy providers 👍
