### ISSUE TITLE
[RFC] The Provider image supports the OCI Manifest Index

### ISSUE THREAD

**Issue by Iceber** [wasmCloud/wasmCloud#587]
# RFC: The Provider image supports the OCI Manifest Index

## Introduction

The current provider image only supports OCI Manifest, where the binaries for all platforms are compressed together and placed in a layer with media-type "application/vnd.wasmcloud.provider.archive.layer.v1+par".
```json
{
  "digest": "sha256:e9e10c6b2ebf69fe1aeb89e0c53a21beb08db3141b88616ff8034fad774e6b6b",
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "size": 384,
  "config": {
    "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
    "mediaType": "application/vnd.wasmcloud.provider.archive.config",
    "size": 2
  },
  "layers": [
    {
      "digest": "sha256:9019dc3a53288e78b26c6dfe89f3e2c8e67320adc99886f8bfea0fcdf961188a",
      "mediaType": "application/vnd.wasmcloud.provider.archive.layer.v1+par",
      "size": 5558498
    }
  ]
}
```
Host pulls the layer and caches it into wasmcloud_ocicache, then parses claims.jwt and the corresponding platform binary from the layer.

We only need the binary of the corresponding platform and claims.jwt, we don't need to pull the binary of other platforms, using a unified par file will affect the speed of the Provider's distribution.
```bash
$ ll /var/folders/3l/zj_w4kws5c7b7h7723nvdrqh0000gn/T/wasmcloud_ocicache
-rw-r--r--  1 icebergu  staff   5.3M Aug 29 13:47 ghcr_io_iceber_wasmcloud_httpserver_0_17_0-index.bin
-rw-r--r--  1 icebergu  staff    71B Aug 29 13:47 ghcr_io_iceber_wasmcloud_httpserver_0_17_0-index.digest
-rw-r--r--  1 icebergu  staff    42M Aug 28 14:32 ghcr_io_iceber_wasmcloud_httpserver_0_17_0.bin
-rw-r--r--  1 icebergu  staff    71B Aug 28 14:32 ghcr_io_iceber_wasmcloud_httpserver_0_17_0.digest
```
**5.3M vs 42M**

## Motivation

Propose to support OCI Manifest Index format for Provider image.

With Manifest Index, we can put the binary compressed files of different platforms in a separate Manifest, and by default, when pulling, we will only pull the content of the Manifest of the corresponding platform, which will greatly speed up the distribution speed.
```json
{
  "annotations": {},
  "manifests": [
    {
      "digest": "sha256:65bc0fc7b380c42a85efa165123ea78f4c65da66de08399645ecbe681da42001",
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "platform": {
        "architecture": "amd64",
        "os": "windows"
      },
      "size": 385
    },
    {
      "digest": "sha256:c518c7ed8ff3c135fa1e4bc6bc6a74d0e4ad425d96af771dbc7bb6d5f75b97c0",
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "platform": {
        "architecture": "amd64",
        "os": "darwin"
      },
      "size": 384
    },
    {
      "digest": "sha256:ad961d1c9ecf681bc0465756952f65141b07b0682f4e87e71b9e714924351bf6",
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      },
      "size": 384
    },
    {
      "digest": "sha256:8e38f37c9ed8b8112394e8dbc092d5bc1ecdd97a7507550806b32f1a18adf3b3",
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "platform": {
        "architecture": "armv7",
        "os": "linux"
      },
      "size": 384
    },
    {
      "digest": "sha256:e9e10c6b2ebf69fe1aeb89e0c53a21beb08db3141b88616ff8034fad774e6b6b",
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "platform": {
        "architecture": "arm64",
        "os": "darwin"
      },
      "size": 384
    },
    {
      "digest": "sha256:0b96f2f3664dd97dc16b341463f6a72ab48781d12f2bfa535aa9d2a1fda2d4f4",
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      },
      "size": 384
    }
  ],
  "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
  "schemaVersion": 2
```
> Due to *oci-distribution*, the meditType of my build of Manifest is *application/vnd.docker.distribution.manifest.list.v2*, but that doesn't affect usage.

You can try out Manifest Index directly using the [ghcr.io/iceber/wasmcloud/httpserver:0.17.0-index](https://github.com/users/Iceber/packages/container/package/wasmcloud%2Fhttpserver) I built.
## Backwards Compatibility
Does not affect the use of the Provider in Manifest format.
## Unresolved Questions

I think there are a few more things that need to be discussed right now, just in relation to the Manifest Index scenario:
* Whether claims are still packaged with the binary, or whether they are just stored in annotations in the Manifest Index.

Other things that need to be done
* **wash needs to support it in a suitable way, which will involve changes to *provider-archive* and *oci-distribution*.**
* If the claims are still packaged with the binary, the `wasmcloud host` will just need to do some bug fixes and no major changes.
* 
## Conclusion

**Comment by connorsmith256** [comment]
I really like this idea. Pulling the entire par.gz when the host only needs one binary has bothered me for a long time :)

I'm unfamiliar with OCI manifest indexes. Is this the right spec? https://github.com/opencontainers/image-spec/blob/main/image-index.md

**Comment by Iceber** [comment]
>  Is this the right spec? https://github.com/opencontainers/image-spec/blob/main/image-index.md

yes

**Comment by brooksmtownsend** [comment]
This feels a lot like what bindle does for only downloading the correct artifacts for what you need, rather than downloading the entire set of artifacts. I'd love for @thomastaylor312 to weigh in here.

My main question is can we maintain backwards compatibility with "older" versions of the wasmCloud host with manifest indexes, and can we support forwards-compatibility in order to pull "older" providers with this change?

**Comment by brooksmtownsend** [comment]
Note that I'm removing this from the 1.0.0 milestone as I think it can be added post 1.0, but this is a welcome inclusion in 1.0 if it's done in time 😄
