### ISSUE TITLE
please add suport for unix SIGTERM for ease of use with a process manager

### ISSUE THREAD

**Issue by pgray** [wasmCloud/wasmCloud#595]
most process managers use [SIGTERM](https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html) to signify a process should stop gracefully

this was the behavior on the OTP host so it would be nice to add support for it in the rust host as well

Thanks!

I think it'd look something like:
```
 353 + │     let mut stream = signal::unix::signal(signal::unix::SignalKind::terminate())?;
 354   │     select! {
 355   │         sig = signal::ctrl_c() => sig.context("failed to wait for Ctrl-C")?,
 356 + │         _ = stream.recv().await => {},
 357   │         _ = host.stopped() => {},
 358   │     };
```

**Comment by connorsmith256** [comment]
Closed by #596
