### ISSUE TITLE
`wasmcloud-host` FFI

### ISSUE THREAD

**Issue by rvolosatovs** [wasmCloud/wasmCloud#633]
We had a brief discussion at WasmCon about FFI support with @charypar and it seems that we could introduce that using https://github.com/mozilla/uniffi-rs

**Comment by charypar** [comment]
What I had in mind specifically was the idea of embedding a wasmCloud host in a client-side app, mobile or web, using the rust host as a library, through and FFI from Swift/Kotlin/Java/JS.

I'll try to find some time to have a play around with the idea, see if I hit any serious difficulties.

**Comment by rvolosatovs** [comment]
@pgray just got NATS and Cosmonic running on Android! :tada:

**Comment by pgray** [comment]
I used [termux](https://f-droid.org/en/packages/com.termux/) for running them.

compile steps:
```
git clone git@github.com:nats-io/nats-server.git && cd nats-server
CGO_ENABLED=0 GOOS=android GOARCH=arm64 go build .

# assumes android studio, ndk, etc is setup
# example env vars:
# ANDROID_SDK_ROOT=/Users/pgray/Library/Android/sdk
# ANDROID_API=33
# ANDROID_NDK_ROOT=/Users/pgray/Library/Android/sdk/ndk
cd .. && git clone git@github.com/wasmcloud/wasmcloud.git && cd wasmcloud
cargo ndk -t arm64-v8a build --release
```

**Comment by rvolosatovs** [comment]
With #636 merged we now have the minimal foundation to build this feature upon, it is already possible to link to wasmCloud-the-library and start a complete host using default config, which I was able to do from C.
It, of course, gets much more complicated when we want to add things like config and/or support for lower-level functionality, @charypar would https://github.com/mozilla/uniffi-rs help us address that?

**Comment by charypar** [comment]
@rvolosatovs I've been getting my head around the rust host codebase to understand what it would take to run 'as a library'. It's a learning curve, not going to lie, but I'm getting there slowly.

In terms of UniFFI, I think it can help pass more complex data across the FFI boundary for something like configuration, but its IDL (called UDL) type system [is somewhat limited](https://mozilla.github.io/uniffi-rs/udl_file_spec.html).

My open questions for embedding are largely around how much the host can (and how much it should) control the host, e.g. can it prevent it from downloading capability providers, since starting separate processes may not be possible in the 'library' scneario. 

Separately, it seems to me that to create a capability provider local to the mobile app, it would be better done as a standalone library running in the same process, connected to the same lattice, but not interacting directly with the host. Does that sounds right?

What do you think a host application would want to be doing to the host, other than starting it? What I can think of is controlling the lifecycle - e.g. explicitly signalling that the app is going in the background and the host will disconnect.

**Comment by rvolosatovs** [comment]
> My open questions for embedding are largely around how much the host can (and how much it should) control the host, e.g. can it prevent it from downloading capability providers, since starting separate processes may not be possible in the 'library' scneario.

In an ideal world, providers are Wasm binaries, where the issue of starting processes is not relevant anymore. I can't comment on when that would land, but I do expect a significant amount of progress on this part within a year or so. We could add a feature to `wasmCloud`, which would disable binary provider loading altogether?

> Separately, it seems to me that to create a capability provider local to the mobile app, it would be better done as a standalone library running in the same process, connected to the same lattice, but not interacting directly with the host. Does that sounds right?

Seems like Wasm providers would address that issue, do I understand that correctly?
Would you still need native providers here (e.g. a library) if Wasm providers existed? One use case I can think of would be direct hardware access, GPIO etc., but maybe there are ways how we could abstract that using Wasm component model interfaces

> What do you think a host application would want to be doing to the host, other than starting it? What I can think of is controlling the lifecycle - e.g. explicitly signalling that the app is going in the background and the host will disconnect.

Currently, host can be stopped directly or via NATS command, the existing FFI only allows stopping via NATS at this point. In current design, really, all the commands are handled via NATS, so there's not much that can be done to the host if I understand your question correctly.

Maybe you could expand on your use case and then we could figure out a set of functionality that *should be* exposed by the host?

**Comment by charypar** [comment]
> In an ideal world, providers are Wasm binaries, where the issue of starting processes is not relevant anymore. I can't comment on when that would land, but I do expect a significant amount of progress on this part within a year or so. We could add a feature to wasmCloud, which would disable (native) binary provider loading altogether?

It would help to make it optional with configuration for the use-case I have in mind (see below), I think.

> Seems like Wasm providers would address that issue, do I understand that correctly?

I'm not entirely sure - it would address the issue of the mobile app host being able to run other capabilities, but not the other part I've got in mind such as... 

> Would you still need native providers here (e.g. a library) if Wasm providers existed? One use case I can think of would be direct hardware access, GPIO etc., but maybe there are ways how we could abstract that using Wasm component model interfaces

... this kind of usecase. I imagine the solution can be either here - either native, or with an ability to supply some of the interfaces the components import "through" the host - i.e. host FFI would have to expose the WIT interface imported by the capability provider for implementation of the mobile app. App implements a host FFI, which in turn implements the WIT - seems needlessly complicated. It feels to me that providing a capability that needs, say, a biometric authentication access via Apple's SDKs would be easier done as a provider connected via NATS that just happens to run in the same iOS process as the host, but it doesn't have to.

>Maybe you could expand on your use case and then we could figure out a set of functionality that should be exposed by the host?

Sure thing! I'm thinking of a distributed application with a native mobile (iOS or Android) user-facing app, in which the running apps also join the lattice - either A) as just a capability provider (that might actually be sufficient), or B) as both a capability provider _and_ a host.

The latter would mean the distributed runtime scales directly with the number of active users, and a lot of work can be done fully on-device without data ever leaving it. For example, if this hypothetical app was a banking app, in a loan application journey, the actor responsible for credit scoring the loan application could simply run on the device and do the decisioning there. 

The other benefit of both approches (A and B) would be eliminating what would normally be a GraphQL or REST API hop to a public web API, which then translates into a NATS message to reach an actor. Instead, that communication could be done by a bespoke provider - from the perspective of the mobile app, it would act as an SDK library, but from the perspective of the distributed wasmCloud application it would be an instance of a capability for that particular client/user. All network communication would be handled via NATS in that scenario. In a way, there would be almost no difference between a client and a server in that architecture.

Is that a mad idea?

**Comment by charypar** [comment]
Maybe a github issue is not the right place for a discussion of potential directions, but would be nice to not let that conversation completely disapear 😅
