### ISSUE TITLE
Cloudevents for rpc invocations

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wasmCloud#637]
For compatibility with otp host, and per [ADR 11](adr/0011-split-rpc-events.md), implement cloudevents for rpc invocations.

As a reminder, fields include:
- lattice_id, host_id, source id, target id, operation, payload size, contract_id, link_name, status (success/fail), timestamp

**Feature request: two more fields**

- elapsed time for round-trip message
- host_id of recipient (I think, host_id in the otp implementation is for the sender only)

My use case is that I want to test different scalar algorithms and need to know the association of actor and host. Elapsed time is useful for understanding performance, detecting host or network congestion, etc.

[Edit: does adding host_id of recipient require adding host_id to the InvocationResponse struct?]

**Enable/disable switch**

For performance benchmarking, we might want this feature enabled or disabled by a host environment variable. (for multi-tenancy, a per-lattice variable). For a very large number of messages in a short time period, per-message events might introduce measurable changes in cpu and nats overhead.

**Alternate implementation**

Maintain internal counters and gauges organized by key dimensions (source-id, source-host, dest-id, dest-host, contract-id, link, operation, success, etc.). Add two configuration settings: MAX_MESSAGES and MAX_INTERVAL, where an event with aggregate metrics is emitted when either of the limits is reached. By setting MAX_MESSAGES=1,MAX_INTERVAL=0 the original behavior is retained: one Cloudevent per message. The setting MAX_MESSAGES=0,MAX_INTERVAL=30 emits one event with aggregate metrics every 30 seconds, regardless of the number of messages received during that interval. The pair of settings (# messages and time period) is similar to the way some logging tools are configured.
 
Bonus (future feature): The counter implementation makes it trivial to add a prometheus export endpoint to each host to report these stats, or to add a collector process that subscribes to the nats rpc event summaries and provides a prometheus export.

**Comment by stevelr** [comment]
Are you open to a PR with the counter/aggregate approach?

**Comment by connorsmith256** [comment]
@stevelr thanks for bringing this up. We've been discussing RPC events/metrics and @pgray volunteered to write an RFC on this in the next week or two. Our thinking so far is to omit RPC events due to the performance concern you highlighted, and instead include invocation counts/failures in aggregate metrics from each host. We'll also discuss metrics during next week's community call. If/when the RFC becomes an ADR, we're definitely open to PRs adding said implementation to the new host 🙌

**Comment by stevelr** [comment]
Great. Thanks.
I'd like to keep this issue open until the superseding ~~RPC RFC~~ Metrics RFC is posted

**Comment by thomastaylor312** [comment]
Got 👍 from @stevelr so going to close
