### ISSUE TITLE
Command interface timeouts

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#64]
When using the control interface, specifically in the context of local development with the REPL / a local wasmcloud host, a timeout can occur when the user attempts to start a provider or an actor.

There are 2 calls that happen when someone calls `wash ctl start provider wasmcloud.azurecr.io/redis:0.9.2`, first is an auction to find a suitable host and second is to download, unpack, and load the provider in the suitable host. The second control interface function is what's most vulnerable to a timeout, especially when running in `debug` mode where unpacking `.par.gz`s is slower.

Currently the `wash` timeout is `5` seconds, which is generally insufficient to download a provider (I'll keep using `redis` as an example) and get it started in a host. It's worth noting here that the 5 second timeout is only how long we wait to get the `StartProviderAck`, and often the provider does download and start in the host successfully after the timeout is returned. 

I'd like to start a discussion here about how we can best tackle this problem. A few approaches come to my mind immediately:
- Set the default timeout to a higher value, say `30` seconds. It's not guaranteed that it will be a high enough timeout, and for a different error that could arise we may be waiting for no reason.
- Change the return value of the `start provider` and `start actor` commands as they are intensive (especially in low network conditions) on download speed and binary run mode (`debug` vs `release`). Similar to `link` we could return an Ack to acknowledge that the start command was received, but not an acknowledgement that the command has been executed. Though this does not guarantee to the user that the resource will start as we did before, we would remove the false timeout error.
- Include better error verbosity, e.g. when a timeout occurs we can add additional information such as "the request to start a provider was received but did not finish, check your host inventory to see if it finished". This feels unpolished from my perspective, but with enough specificity it would hint to the user to increase the timeout.

**Comment by autodidaddict** [comment]
@brooksmtownsend is this issue still open after the fixes for early acks?

**Comment by brooksmtownsend** [comment]
@autodidaddict I say we close it, your last PR addressed this well
