### ISSUE TITLE
[BUG] Relative Path in Image URI

### ISSUE THREAD

**Issue by vances** [wasmCloud/wasmCloud#642]
**Describe the bug**
Relative paths are not supported in `file://` URIs.

**To Reproduce**
1. Run command 'wash start actor file://foo_s.wasm`
2. See error:  failed to convert `file://foo_s.wasm/` to a file path

**Expected behavior**
A missing `/` after `file://` indicates a relative path. In the example above the Wasm file should be found in the same directory where the wasmCloud Host was started. The `wadm` model definition documentation specifically note that relative paths are supported. 

**Screenshots**
```
catalyst@box ~ % wash start actor file://c23_0_601_actor_service_inventory_s.wasm 

Failed to start actor [file://c23_0_601_actor_service_inventory_s.wasm] on host [NA...]

Caused by:
    failed to fetch actor: failed to convert `file://c23_0_601_actor_service_inventory_s.wasm/` to a file path
```

**Environment (please complete the following information) **
 - OS:  Linux and MacOS
 - Shell bash and zsh
 - wash Version 0.20.2

**Additional context**
Same error in `wadm` (`wash app deploy`) and `wash` (`wash start actor`).

**Comment by connorsmith256** [comment]
Piggy-backing off @brooksmtownsend's comment: I did some more investigation today and ran into all sorts of edge cases related to relative paths. The host path parsing code will be much simpler if we require absolute paths. That means clients such as wash and wadm need to convert relative paths into absolute paths before sending the control interface request to the host

**Comment by brooksmtownsend** [comment]
> That means clients such as wash and wadm need to convert relative paths into absolute paths before sending the control interface request to the host

Right, I think the host should only support absolute paths, but writing
```
wash start actor ./myactor_s.wasm
```

Should work, where `wash` fills in the `file://$(pwd)/` prefix.

**Comment by vances** [comment]
Absolute paths aren't a practical option, and just really bad form.

Linux:       `/home/{username}`
macOS:	`/Users/⟨username⟩`
Android:	`/data/media/⟨userid⟩`
Windows: `⟨root⟩\Documents and Settings\⟨username⟩`

**Comment by brooksmtownsend** [comment]
> Absolute paths aren't a practical option, and just really bad form.
> 
> 
> 
> Linux:       `/home/{username}`
> 
> macOS:	`/Users/⟨username⟩`
> 
> Android:	`/data/media/⟨userid⟩`
> 
> Windows: `⟨root⟩\Documents and Settings\⟨username⟩`

I acknowledge that different platforms have different file system base paths, and I think loading an actor from a file assumes knowledge of the file system the host is running on. If you're outside of local development and running actors from a file, you're going to be doing it from a path that you know about. I'm happy to be wrong about this, though, if your use case would depend on relative paths we can revisit this!

What I was suggesting for wash would nicely address the localdev use case, and require that wadm manifests specify absolute paths for localdev so you can predictably deploy your actors even if you ran `wash up` from different directories.

**Comment by vances** [comment]
An application specification for `wadm` deployment:
  
```
spec:
  components:
  - name: runs-anywhere
    type: actor
    properties:
      image: file:///wasm/anywhere_s.wasm
    traits:
    - type: daemonscaler
      properties:
        replicas: 10
        spread:
        - name: nanopi
          requirements:
            zone:: global
```

The relative path makes this super simple.

**Comment by brooksmtownsend** [comment]
It does look simple, but the complexity comes from knowing _where_ that path is relative to. Is it relative to where wadm is running? WasmCloud? Wash? Intuitively I may think it's relative to wherever the manifest lives, but that's only correct if you also run wasmCloud from the same directory. We can add relative path support to the host but I think it will cause more confusion than pain that it will solve

**Comment by vances** [comment]
The behaviour is documented (which makes this a bug):

[INFO](https://github.com/wasmCloud/wasmcloud.com-dev/blob/f4586238c59b1b886f0fe59e3b8fede2df7e5a1c/docs/fundamentals/wadm/model.md?plain=1#L67)
