### ISSUE TITLE
Make Claims a concrete type

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmCloud#643]
Currently, claims are represented by a map of string -> string. The historical reason for this was because we didn't know everything we wanted in it. Given how this data has essentially remained unchanged for over a year (and possibly longer), I propose we create a concrete type for claims and start using that instead of a hashmap

**Comment by connorsmith256** [comment]
This is related to https://github.com/wasmCloud/wasmCloud/issues/508 right?

**Comment by connorsmith256** [comment]
Closing in favor of https://github.com/wasmCloud/wasmCloud/issues/1093, which includes the dependency chain of types and explains why updating the control interface isn't straightforward today
