### ISSUE TITLE
Acknowledge commands early for control interface

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#65]
In the current implementation the control interface waits to acknowledge the receipt of the "start actor" and "start provider" commands until after the start has completed. In situations with high-latency networks or where the download of an OCI image may take a while after not having been cached, this can present consumers and CLI clients (e.g. `wash`) with long delays that can exceed timeout periods, giving consumers a false sense of failure.

If clients want deterministic notification of when actors and providers start, they should listen to the appropriate events on the control interface's `events` stream.

**Comment by autodidaddict** [comment]
This is required for 0.15.0.

**Comment by brooksmtownsend** [comment]
Related to #64
