### ISSUE TITLE
Fail to decode -> NATs Timeout 

### ISSUE THREAD

**Issue by jordan-rash** [wasmCloud/wasmCloud#674]
Testing done with rc10

When an invocation fails to decode, nats is timing out as opposed to the error being return to the provider.

Host error: 
```
2023-09-22T20:19:17.971124Z ERROR handle_message: wasmcloud_host::wasmbus: failed to decode invocation subject="wasmbus.rpc.default.MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5" e=Syntax("invalid type: unit value, expected a map")
```

Seen from user's side 
```
└─❯ curl 100.69.102.124:8085
nats: timeout%    
```

I would expect to see the decode error and not the NATs timeout.

**Comment by connorsmith256** [comment]
@jordan-rash I thought this would be an easy fix, but am now conflicted:

If the host fails to deserialize an invocation from a provider, the host doesn't have access to the (attempted) invocation's ID. So if the host were to reply with an `InvocationResponse` containing the error, what ID should the host pass?

I tried double-checking whether providers ensure the invocation ID on the response matches the ID on the request ([like the host does](https://github.com/wasmCloud/wasmCloud/blob/ab9a2e3796cf9a33924c5017d69276ab31a3db2b/crates/host/src/wasmbus/mod.rs#L347C54-L347C54)) but I don't think they do. If that's the case, we could reply with a sentinel value of some sort, like `UNKNOWN`, and at least give a reply to the provider in response to a malformed invocation.

What do you think?

**Comment by jordan-rash** [comment]
I think the "malformed invocation" is a bad error, albeit accurate.  The host has access to the inbox that the provider/actor is listening on, so I would suspect if the host can't send back an "InvocationResponse", maybe it should send back some data structure like "HostError".  Just letting the connection timeout should be the last resort.  These types of errors (or there lack of) make troubleshooting extremely difficult

**Comment by connorsmith256** [comment]
Agreed. I think we should send back a valid(-ish) `InvocationResponse` and use a sentinel value for the invocation ID. That allows all clients(?) which parse invocation responses to remain as they are, and it enables troubleshooting 👍 

If you don't mind, I'll update the title/description of this issue. Otherwise I can file a new one and link to this one

**Comment by jordan-rash** [comment]
i dont care....you do you
