### ISSUE TITLE
Migrate chart to repo

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmCloud#684]
The wasmCloud chart should be migrated from the old OTP repo: https://github.com/wasmCloud/wasmcloud-otp/tree/main/wasmcloud_host/chart. Now that we have rolled out the new rust host, it should also be updated to use the latest rust host (and actually tested that it works)

Needed steps

- [ ] Move chart to this repo
- [ ] Update app version to use the latest rust host images
- [ ] Make sure the build pipeline for publishing the chart is also migrates (it will involve GH pages being enabled)
- [ ] Test the chart to make sure it deploys properly

**Comment by joonas** [comment]
Given #788, #802, #806 and #918, I think this can be considered done now?
