### ISSUE TITLE
[REQUEST] Runtime Host Tags

### ISSUE THREAD

**Issue by jordan-rash** [wasmCloud/wasmCloud#692]
I would like to be able to create tags on the host at runtime.

Something along the lines of 
`wash host <host-id> my:tag`

This would be a powerful way to start tuning the host without restart.  Currently, a problem I have is that if I forget to add a tag/label to the host, it requires a restart of the host. 

Ref: https://wasmcloud.slack.com/archives/C04RVMJJH17/p1695735058510099

**Comment by connorsmith256** [comment]
I love this idea 🙌 

I think we'll want some more technical details ironed out:
- when you say "tags", do you mean the existing host labels, or a new, separate set of metadata?
- how will the host receive updates?
  - presumably a new topic on the control interface?
  - will the payload be treated as a full replacement, or an "upsert"?

**Comment by jordan-rash** [comment]
By tags, I mean host labels (my mistake)

I don't know how the host should best receive them, but I do think they should be an insert and not a replace.

`wash host add-label <host-id> my:tag`
`wash host del-label <host-id> my`

**Comment by connorsmith256** [comment]
@jordan-rash check out https://github.com/wasmCloud/wasmCloud/pull/780 and let me know if you have any feedback! Once the host/control interface supports this API, we can add it to wash pretty easily

**Comment by connorsmith256** [comment]
@jordan-rash bump?

**Comment by jordan-rash** [comment]
#780 looks great to me
