### ISSUE TITLE
[REQUEST] Lame Duck Mode

### ISSUE THREAD

**Issue by jordan-rash** [wasmCloud/wasmCloud#693]
As an extension to #692, I would like to see the "lame duck" tag implemented.

Similar to NATs [lame duck mode](https://docs.nats.io/running-a-nats-service/nats_admin/lame_duck_mode), it would cause the host to drain itself and block further deployments (from `wash` and `wadm`) to the host.  This would allow for easier updates of the host in place.

Ref: https://wasmcloud.slack.com/archives/C04RVMJJH17/p1695735058510099

**Comment by connorsmith256** [comment]
Some questions on this one: 
- once in lame duck mode, should the host refuse to process any new control interface commands, or is this mode "just' part of what's returned by host pings/inventory requests?
- once the host has drained its contents, will it shut down, or does it remain in lame duck mode?
  - if the host stays running, should there be a way to switch out of lame duck mode, or is this a terminal state?

**Comment by jordan-rash** [comment]
IMO:
- once lame duck mode is enabled, no "new" commands should be processed.  All existing workloads should be shutdown _nicely_ (up to some TTL and then killed)
- I think once it is shutdown, it would remain on and continue to not respond to request.  Reason for this is, 
  1) maybe I was just troubleshooting something and will take it out of lame duck mode once I am done or 
  2) Doing some sort of load testing
- I def believe lame duck mode should be toggleable

**Comment by protochron** [comment]
We've chatted about this before, and I'd also like to see this as a feature. Conceptually I think it as being closer to Kubernetes' [drain/cordon behavior](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/) or Nomad's [node draining/eligibility feature](https://developer.hashicorp.com/nomad/docs/commands/node/drain).

**Comment by jordan-rash** [comment]
> We've chatted about this before, and I'd also like to see this as a feature. Conceptually I think it as being closer to Kubernetes' [drain/cordon behavior](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/) or Nomad's [node draining/eligibility feature](https://developer.hashicorp.com/nomad/docs/commands/node/drain).

But Dan def things that the feature should have _duck_ in the name...right, RIGHT?!?!?

**Comment by thomastaylor312** [comment]
@jordan-rash did you mean to close this?

**Comment by vados-cosmonic** [comment]
Going to re-open -- pretty sure this shouldn't have been closed

**Comment by thomastaylor312** [comment]
One note here is that lame duck mode should probably be entered automatically if it receives a kill signal
