### ISSUE TITLE
Placeholder: Using streams for long running requests/processing

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmCloud#697]
In the [9/27 community call](https://wasmcloud.com/community/2023/09/27/community-meeting), we had an extensive discussion around how we wanted to handle long running requests on actors (i.e. image processing, long running calculations, etc.)

The output of that conversation was that if actors receive a stream, then they should keep running until that stream closes. An actor can then respond on that stream when it has completed work. In order to do that, we'll need streams to be stabilized as part of wasi preview 2 (which is already in flight) and that work internalized in wasmCloud. Because that won't be for a few months, but we wanted to put it on the roadmap and have a place to discuss it so we decided to open this placeholder issue. 

If anyone from the community is feeling brave, feel free to try hacking around with this now! From a core maintainer perspective, we'll probably get to it around to working on it. Once anyone has tried spiking this work, they could write an RFC, which would supersede this issue

**Comment by connorsmith256** [comment]
@thomastaylor312 what would you like to do with this issue? Should I pin it?

**Comment by thomastaylor312** [comment]
I'm curious if this will just come automagically once we get #1128 implemented (as we'll be able to use streams). For now I'll pin this and we can come revisit once we get past that implementation
