### ISSUE TITLE
[FEATURE] Add fuzz testing

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#717]
**Is your feature request related to a problem? Please describe.**
We currently do not do fuzz testing on wasmCloud and it would be great to ensure that we're passing fuzz tests on each PR.

**Describe the solution you'd like**
Ideally, wasmCloud should be able to handle a variety of fuzzing on:
1. The CLI (arguments and environment variables passed at runtime)
2. The control interface (NATS messages sent on `wasmbus.ctl.>` to request ctl operations)
3. The Actor RPC topics (NATS messages on `wasmbus.rpc.<lattice>.<actor_id>` when that actor is running)

This should all be pretty simple to build based off our current wasmbus suite of tests.

**Describe alternatives you've considered**
Not fuzz testing, and that's what we do now, but it's better to fuzz test!

**Additional context**
https://github.com/rust-fuzz/cargo-fuzz is a great tool for Rust projects 😄

**Comment by cdmurph32** [comment]
I've never done any fuzzing, so this is just based on what I've learned in the last 30 minutes.
Taking a quick look at the code:
1. CLI arguments: Fuzz [CliCommand](https://github.com/wasmCloud/wasmCloud/blob/main/crates/wash-cli/src/bin/wash.rs#L130). This is probably more effective than just fuzzing [Cli = Parser::parse()](https://github.com/wasmCloud/wasmCloud/blob/main/crates/wash-cli/src/bin/wash.rs#L242)
2. The control interface: Fuzz message in [async fn handle_ctl_message(self: Arc<Self>, message: async_nats::Message)](https://github.com/wasmCloud/wasmCloud/blob/79d93ae1f86c491cbaec8a498be97e7f1978481d/crates/host/src/wasmbus/mod.rs#L3789) 
3. The actor RPC topics isn't as clear to me, there are a couple of places in the host/wasmbus crate that could be fuzzed.

Am I correct in assuming the wasmbus suite of tests is `/tests/wasmbus.rs`?

**Comment by brooksmtownsend** [comment]
Yep that's right @cdmurph32 ! Fuzzing on the CLI is nice to make sure we can't just straight up break the runtime with a malformed string. Fuzzing on the control interface is what I really think we'd benefit from, make sure that receiving garbage payloads doesn't cause any undefined behavior

**Comment by cdmurph32** [comment]
I'm going to defer this until Host in https://github.com/wasmCloud/wasmCloud/blob/main/crates/host/src/wasmbus/mod.rs has been refactored into more easily mockable parts.

**Comment by brooksmtownsend** [comment]
@cdmurph32 getting closer here, in https://github.com/wasmCloud/wasmCloud/pull/1588 I refactored a bunch of the handlers to return strongly typed data. More refactors to come for the code but just a note on the progress
