### ISSUE TITLE
[FEATURE] Produce a benchmark suite that we can update/publish regularly

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmCloud#718]
**Is your feature request related to a problem? Please describe.**

Many users would like to have performance/benchmark numbers about how wasmCloud performs

**Describe the solution you'd like**

Ideally we should have a test anyone can run (e.g. a script) that tests at least the following things:

- Direct actor call time
- Actor to actor call round trip
- Actor to provider call round trip
- Provider to actor call round trip
- Time to start an actor (with and without cache)
- Time to start a provider (with and without cache)

**Comment by connorsmith256** [comment]
Depending on how costly it is, this would be a great thing to run regularly against the host, so we can track performance improvements/regressions 👍
