### ISSUE TITLE
[FEATURE] Unflatten provider errors from invocation errors

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmCloud#719]
**Is your feature request related to a problem? Please describe.**

Right now we take errors from provider methods and send them as part of an invocation error. Instead, we should be serializing the `Result` type from the provider and then sending that message back.

**Describe the solution you'd like**

Provider macro generation will need to be updated to send back serialized data and the `dispatch` method on the `MessageDispatch` trait in the provider SDK will need to be updated to only return an `InvocationError`.

This will also mean we need to update our adapters for the wasi-cloud interfaces to send back serialized `Result`s rather than flattening the error

**Comment by connorsmith256** [comment]
@brooksmtownsend @thomastaylor312 does this need to be on 1.0? Would this be a backwards-incompatible change?

**Comment by brooksmtownsend** [comment]
This feels like something that could be handled internal to providers/the host, but incompatible with previous versions so I think this would be a good one to get done pre-1.0. Leaving to @thomastaylor312 in case I misunderstand.

**Comment by connorsmith256** [comment]
Okay, that's what I thought. I'll add to the 1.0 milestone. @vados-cosmonic expressed interest in working on this 🙏

**Comment by thomastaylor312** [comment]
You were correct @brooksmtownsend, this would be a breaking change
