### ISSUE TITLE
[RFC] Snapcraft / Snap packages for app delivery

### ISSUE THREAD

**Issue by average-bit** [wasmCloud/wasmCloud#74]
Should we publish various wasmCloud bins as Snaps?  
Snaps are from Canonical the makers of Ubuntu - https://snapcraft.io/

Actively promoted by Canonical, Snaps are software packages meant to easily cross distribution boundaries and can be installed on: Arch, Debian, ElementaryOS,Fedora, KDE Neon, Kubuntu, Manjaro, Linux Mint, OpenSUSE, RedHat, and Ubuntu out of the box. Snaps auto update and check for updates four times per day, if the update for whichever channel the user is locked to fails it will automatically rollback to the previously working version.

"Snaps" are a well known (maybe not perfectly loved) method of app delivery that Canonical have made available for people to install software with some nice functionality baked in. Since they've created it and moved many apps for both Ubuntu Desktop/Server into this app delivery pipeline. I think it would be wise to consider setting up a GitHub action to generate Snaps and ideally get on that platform for more exposure. I think this would be ideal to target people intending to use Ubuntu Server or Ubuntu IoT core images for wasmCloud.

There are definitely some cons with this I think the biggest one in the short term could be the amount of extra-curricular support requests it may generate. I've personally seen this balloon the number of "issues" on other GitHub repositories with people who may not have the best understanding of how Snaps work and interact with the system.

**Comment by average-bit** [comment]
@billyoung

**Comment by brooksmtownsend** [comment]
This shouldn't be too hard of a lift, high level: define the snap configuration file, create a ubuntu snap account, and there are gh actions available for the build+push of the snap package
