### ISSUE TITLE
Set up build pipeline

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmCloud#8]
Should do the usual tasks that were already being performed in the original repository. Should also support creating both the `wasccd` and `wasccd-lite` binaries for multiple target architectures and operating systems as part of each release tag.

**Comment by mikezupper** [comment]
Can you elaborate on this task? What did the old build pipeline do? Where can I find the steps it ran? Where did this pipeline run?

**Comment by autodidaddict** [comment]
I think @billyoung might have some more thoughts on where this is headed, since we're trying to get wasccd and wash binaries included in brew, apt, and so on. As far as what the old one did, it was a github action yaml that can be found [here](https://github.com/wascc/wascc-host/tree/master/.github/workflows)

**Comment by brooksmtownsend** [comment]
In addition to this build pipeline, dependabot / some sort of maintainer approval check would be good for PRs

**Comment by brooksmtownsend** [comment]
Is this complete @autodidaddict @billyoung ? 😄

**Comment by billyoung** [comment]
Yes, this was completed with the addition of our GH actions @brooksmtownsend. Go ahead and close or :+1: and I will :smile:

**Comment by autodidaddict** [comment]
:+1:
