### ISSUE TITLE
Make `get_caps` function usable by other clients

### ISSUE THREAD

**Issue by aish-where-ya** [wasmCloud/wasmCloud#800]
The `is_wasm` function in wash, specifically under [`inspect`](https://github.com/wasmCloud/wasmCloud/blob/main/wash/crates/wash-lib/src/cli/inspect.rs) needs to be made public for reusability.

**Comment by connorsmith256** [comment]
Another option, since `is_wasm` is pretty low-level and takes a byte array, is to refactor `get_caps` and `handle_provider_archive` to be consumable by other clients. Something like `inspect(path)` which can handle either an actor or par and return claims

**Comment by brooksmtownsend** [comment]
If we implement #1219 , the `get_caps` function will also go away

**Comment by thomastaylor312** [comment]
@brooksmtownsend I think we can close this now, right?

**Comment by brooksmtownsend** [comment]
Yep!
