### ISSUE TITLE
Make tests predictable without timers

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#83]
Currently there are tests that depend on lenient timer delays (**cough** **cough** _distributed_echo_). Relying on timers doesn't effectively test the wasmCloud functionality that we are targeting as it may arbitrarily hide performance issues.

In order to make these tests more predictable, one solution might be monitoring the lattice event stream for certain events like "ActorStarted", "HostStarted", "PutLink", etc. This would allow tests to wait for specific **events** and then assert that the state of the program is how it should be.

**Comment by brooksmtownsend** [comment]
Investigation needed here for removing the `--test-threads=1` flag as a requirement

**Comment by autodidaddict** [comment]
Closing this as it's a duplicate.
