### ISSUE TITLE
[FEATURE] integrate `wasmcloud-control-interface` into the repo

### ISSUE THREAD

**Issue by rvolosatovs** [wasmCloud/wasmCloud#831]
**Is your feature request related to a problem? Please describe.**
Move `wasmcloud-control-interface` crate into the shared cargo workspace

**Describe the solution you'd like**
1. `git subtree add -P crates/control-interface https://github.com/wasmcloud/wasmcloud-control-interface.git main`
2. modify `Cargo.toml` and other things in `crates/control-interface` to properly utilize the workspace, inherit license and deps from the root
3. integrate crate release CI, if any (check `wasmcloud.yml` `crates` job)
4. Add `path` workspace dependency in root `Cargo.toml` on control interface just like all other subcrates

**Comment by connorsmith256** [comment]
Resolved by https://github.com/wasmCloud/wasmCloud/pull/927
