### ISSUE TITLE
[BUG] Homebrew breaks Rust environment on MacOS

### ISSUE THREAD

**Issue by tdensmore** [wasmCloud/wasmCloud#840]
**Describe the bug**
Installing `wash` via Homebrew breaks my WASM development setup by installing a newer version of Rust and confusing `wasm-pack build`.

**To Reproduce**
I am trying to follow [this tutorial](https://rustwasm.github.io/docs/book/game-of-life/hello-world.html) but `wasm-pack build` gives me this:
```
[INFO]: 🎯  Checking for the Wasm target...
Error: wasm32-unknown-unknown target not found in sysroot: "/opt/homebrew/Cellar/rust/1.68.2"
Used rustc from the following path: "/opt/homebrew/bin/rustc"
It looks like Rustup is not being used. For non-Rustup setups, the wasm32-unknown-unknown target needs to be installed manually. See https://rustwasm.github.io/wasm-pack/book/prerequisites/non-rustup-setups.html on how to do this.
Caused by: wasm32-unknown-unknown target not found in sysroot: "/opt/homebrew/Cellar/rust/1.68.2"
Used rustc from the following path: "/opt/homebrew/bin/rustc"
It looks like Rustup is not being used. For non-Rustup setups, the wasm32-unknown-unknown target needs to be installed manually. See https://rustwasm.github.io/wasm-pack/book/prerequisites/non-rustup-setups.html on how to do this.
```
NOTE: the version in the above error is interesting because it says I am using Rust version 1.68.2 that Homebrew installed. But if I check the rust version I get :
```
rustc --version
rustc 1.67.1 (d5a82bbd2 2023-02-07)
```
and
```
which rustc
/Users/todd/.cargo/bin/rustc
```
Anyway, I downloaded the correct tarball, dropped it into 
mv rust-std-1.67.1-wasm32-unknown-unknown /Users/todd/.rustup/toolchains/stable-aarch64-apple-darwin/
but it still does not work.
`brew` shows me that I installed `rust` and `rustup-init`
However `rustup self uninstall` gives me this: 
```
error: self-uninstall is disabled for this build of rustup
error: you should probably use your system package manager to uninstall rustup`
```

**Expected behavior**

**Workaround**
Removing wash with 
`brew uninstall wash`

**Screenshots**

**Environment (please complete the following information) **
 - OS: [e.g. Linux, MacOS]
 - Shell [e.g. bash, zsh, powershell]
 - wash Version [e.g. 0.2.0]

**Additional context**

**Comment by connorsmith256** [comment]
As of wash v0.23.0, the homebrew formula now installs from published binary artifacts, instead of compiling from source. As a result, the formula should no longer break your Rust environment! Thank you for your patience as we've invested in fixing this 🙏
