### ISSUE TITLE
[FEATURE] add/remove/list actor claims with wash

### ISSUE THREAD

**Issue by lachieh** [wasmCloud/wasmCloud#842]
> Note that this should probably not start until wasmCloud/wash#538 has been decided upon and implemented.

It would be nice to be able to add claims/capabilities to an actor's `wasmcloud.toml` file without having to edit it directly. Less chance for squishy human errors.

- `wash claims add <name>`
- `wash claims list`
- `wash claims remove <name>`

As a stretch goal, autocomplete for the <name> argument would be nice. Could suggest official wasmcloud contracts for `add`  and list existing claims for `remove`

**Comment by connorsmith256** [comment]
Just noting if https://github.com/wasmCloud/wasmCloud/issues/1219 is accepted, I think this becomes unnecessary

**Comment by lachieh** [comment]
Closing in favor of #1219. Work is slated to be added to 1.0 release.
