### ISSUE TITLE
[FEATURE] Washboard should display assets that are managed by wadm

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#844]
**Is your feature request related to a problem? Please describe.**
As we develop wadm, I realized that there's not an easy way to determine if a resource is managed by wadm or not. This can be a little confusing in the dashboard, since you could issue a request to stop the 5 running actors only for them to instantly return.

**Describe the solution you'd like**
There should be an indicator, like the hotwatch button, in the dashboard that displays if an actor is managed by wadm. Optional additional information like the appspec name is nice, but not necessary. I think that we'll get a good idea of what we need to display over time, but we should at least have an indicator that a resource is being watched by wadm to avoid confusion.

**Describe alternatives you've considered**
1. Do nothing (lame)
2. Add additional UI views for wadm apps (neat, but time consuming, and we'll want to fully release wadm 0.4.0 before we consider this I think)

**Additional context**
`wadm` is the application deployment manager for wasmCloud and manages application resources. A key part of this is a number of replicas of actors, and if wadm is watching an actor resource to ensure it's running 100 copies then any user attempt to stop those actors will result in wadm starting them again. It's unlikely that a developer hits this _on accident_ but would still be nice to fix.

If you're considering taking this one, it's a great first issue for contributors! Just drop a comment and we'll assign it to you so we don't duplicate work 😄

**Comment by markkovari** [comment]
Just out of curiosity @brooksmtownsend, I know it has been a year since this issue was created 😄 

I've been looking up where the labels are managed on the wadm side and pretty much found it and added a dummy implementation on the washboard-ui.
Only for Providers and Components, am I correct?

<img width="1270" alt="Screenshot 2024-07-04 at 12 08 49" src="https://github.com/wasmCloud/wasmCloud/assets/33259514/46bda8bd-4eaf-42a5-8306-b459146b7571">

Or should it be indicated differently?

Other than trying to align the column to the right if possible.

**Comment by brooksmtownsend** [comment]
@markkovari yep just for providers and components! Technically links and config are managed as well, but we don't have an annotation for them so that's the best we can do. I personally think having a managed column looks great, the only other option I could think of is to put the application name in a column to indicate that it's a part of a broader app.

@lachieh what do you think we should do here? If the logo + column looks good as is, I think #2447 could be ready to go.

**Comment by lachieh** [comment]
Yep, logo in the column works for me! If you would like to go deeper, I think you could probably add an option in the [display settings](https://github.com/wasmCloud/wasmCloud/blob/b2ccdeb6ddfcf2dfc7d92041a877e99741e9d103/washboard-ui/packages/washboard-ui/src/app/components/settings.tsx#L35-L38) for how to display the contents of the column, but would accept the PR with just the logo.

**Comment by markkovari** [comment]
Hey @lachieh if I understood you correctly you meant exposing this feature switch to users? Hopefully yes 😄 . Can you please take a look. And you are more than welcome to help me out with the wording if anything is questionable even a little bit. Thanks

**Comment by lachieh** [comment]
#2447 is approved and in the merge queue 💪
