### ISSUE TITLE
[BUG] --branch option in wash new doesn't work

### ISSUE THREAD

**Issue by connorsmith256** [wasmCloud/wasmCloud#845]
**Describe the bug**
I wanted to `wash new actor` from a branch of a git repo, but wash gives an error when trying to check out the branch:

```bash
wash new actor --git https://github.com/wasmcloud/project-templates --subfolder actor/hello --branch fix/update-deps  
🤷   Project Name : hello3
🔧   Cloning template from repo https://github.com/wasmcloud/project-templates subfolder actor/hello...

git checkout error: error: pathspec 'fix/update-deps' did not match any file(s) known to git
```

**To Reproduce**
1. Run `wash new actor --git https://github.com/wasmcloud/project-templates --subfolder actor/hello --branch fix/update-deps  `

**Comment by brooksmtownsend** [comment]
I hit this today 😢
