### ISSUE TITLE
[FEATURE] `wash up` should be idempotent

### ISSUE THREAD

**Issue by connorsmith256** [wasmCloud/wasmCloud#846]
Running `wash up` multiple times on the same machine makes for cool demos, but can also lead to a confusing user experience, or worse, in the case where `wash up` is programmatically being invoked

`wash up` should be idempotent by default. If a wasmCloud host is already running, a friendly message should be displayed indicating the state

For users who do want to run multiple hosts, a flag (defaults to false) should be added to allow a second host to connect to the NATS server. Naming is hard and I haven't thought much about what the name should be, so I'll throw out a strawman and hope someone else has a better idea: `wash up --increment` 

This might be resolved incidentally by https://github.com/wasmCloud/wash/pull/556, though I'm not sure what message will be displayed

**Comment by cdmurph32** [comment]
In my PR, I went with the most basic approach, which is just to allow more hosts to be created with `--scale`. Things would get a more complicated if we wanted to specify how many hosts to create, ie `--scale 2`, so it seemed like a good place to start.
If we go with the more complicated version:
- `--scale` might be a bit confusing. Let's say I have 5 hosts running and I run `wash up --scale 2`. Would the use expect a result of 7 hosts or 2 hosts? If the desired behavior is the latter, then we are now merging the functionality of `wash up` and `wash down`.
- Would we want to add `--scale` to `wash down` as well?

**Comment by brooksmtownsend** [comment]
@cdmurph32 In the interest of keeping this simple... do we need to support a `--scale` function? What if we just supported launching one locally? IMO there's only a few scenarios where you really want to launch multiple hosts locally, do we want to save `--scale` for a future enhancement?

**Comment by brooksmtownsend** [comment]
To actually answer your question though, I think the desired behavior here would be for `--scale N` to ensure there are `N` running hosts, whether that means scaling up or down. `wash down` could just be an alias for `--scale 0`

**Comment by cdmurph32** [comment]
Sounds. Good. Sorry I just saw this. Gmail is awful.

**Comment by cdmurph32** [comment]
Hey @brooksmtownsend. I'm looking into it not. 

- Would that message only be printed if `-d` is passed? Do we just treat it as if `-d` was passed if a host is already running?
- It looks like the code allows you to pass a wadm manifest, but `wash up --help` doesn't seem to show those options. Should a wadm manifest still be applied if there is already a host running?

**Comment by brooksmtownsend** [comment]
> Would that message only be printed if -d is passed? Do we just treat it as if -d was passed if a host is already running?

That's a good question 🤔 I think that the _best_ behavior would be to attach to the existing host, though that may bring in some additional complexities. The ideal there would be that new logs stream to the existing terminal, and a CTRL+c will bring down the local wasmCloud infrastructure. For a first pass I'd be okay with logs noting that a host/NATS server/wadm is already running

> It looks like the code allows you to pass a wadm manifest. Should a wadm manifest still be applied if there is already a host running?

Given that `--wadm-manifest` is essentially just a helper to deploy a manifest, I think we can deploy a manifest whether the host is a new one or already launched before

**Comment by brooksmtownsend** [comment]
Completed with #2236
