### ISSUE TITLE
[FEATURE] Outdated version warning

### ISSUE THREAD

**Issue by vados-cosmonic** [wasmCloud/wasmCloud#848]
**Is your feature request related to a problem? Please describe.**
As `wash` updates and newer versions are available, it would be useful to have a warning when versions fall behind (and we run them from CLI)

**Describe the solution you'd like**
Add a warning for outdated versions to wash.

**Describe alternatives you've considered**
N/A

**Additional context**

This is going to require a few things, since there's no real definition of the "right" `wash` version (people may be on older versions purposefully)...

**Comment by connorsmith256** [comment]
Ah, so in terms of maintainer workflow, would we commit a change to this file only once all installation paths have been updated?

**Comment by t3hmrman** [comment]
So I think what might work here is a file that we can update as different mechanisms change -- like if we had a JSON file with a format like this:

```json
{
  "version" : "0.0.1", 
  "metatdata": [
    {
      "os": "macos",
      "arch": "aarc64",
      "installMethod": "brew",
      "config": {
        ... some free form config that clients can read/use to make decisions ...
      },
      "versions": {
        "wash": {
          "latest": "v0.21.2"
        }
      }        
    }
  }
}
```

We can have `wash` pull this file and use the information it knows about to figure out what the latest version is and whether the client could reasonably have access to it/whether to show the warning.

That said, all of this probably can be avoided pretty easily if we make sure all releases go everywhere every time a new release is made... But in the absence of that requirement (and the acknowledgment that sometimes things go wrong) then a scheme like this would make it easy to get this information to clients (`wash` running locally, in this case, but could be other things in the future).

**Comment by vados-cosmonic** [comment]
So I think what might work here is a file that we can update as different mechanisms change -- like if we had a JSON file with a format like this:

```json
{
  "version" : "0.0.1", 
  "metatdata": [
    {
      "os": "macos",
      "arch": "aarc64",
      "installMethod": "brew",
      "config": {
        "cfgKey": "... some free form config that clients can read/use to make decisions ..."
      },
      "versions": {
        "wash": {
          "latest": "v0.21.2"
        }
      }        
    }
  ]
}
```

We can have `wash` pull this file and use the information it knows about to figure out what the latest version is and whether the client could reasonably have access to it/whether to show the warning.

We can also lay this out as a deeply nested map to make lookups more efficient as well (maybe in a future version?). 

That said, all of this probably can be avoided pretty easily if we make sure all releases go everywhere every time a new release is made... But in the absence of that requirement (and the acknowledgment that sometimes things go wrong) then a scheme like this would make it easy to get this information to clients (`wash` running locally, in this case, but could be other things in the future).

**Comment by vados-cosmonic** [comment]
Yup, updating this file would be the final step, and it can be done *after* the release -- there's no need to tie the update of this file to the time we make a release, since there will be other notifications that go out. 

Maybe we allow a little time to pass and make the update. If you want to do it as soon as a new version is available then we can do it either piece meal or all at once.
