### ISSUE TITLE
[FEATURE] Add support for riscv64 to wash

### ISSUE THREAD

**Issue by matsbror** [wasmCloud/wasmCloud#853]
**Is your feature request related to a problem? Please describe.**

I'd like to get a wasmcloud host up and running on a riscv64 architecture. Currently building wash-cli failes on when trying to compile ring on rscv64.

**Describe the solution you'd like**
A wash-cli not dependent on any crates which cannot build on riscv64.

**Describe alternatives you've considered**
Fixing ring for riscv64.

**Additional context**

```
ubuntu@vf2:~$ uname -a
Linux vf2 6.2.0-31-generic wasmCloud/wash#31.1-Ubuntu SMP Fri Aug 25 22:33:13 UTC 2023 riscv64 riscv64 riscv64 GNU/Linux
ubuntu@vf2:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 23.04
Release:        23.04
Codename:       lunar
```

**Comment by rvolosatovs** [comment]
This will automatically be done once #724 is done, since both binaries are part of a single workspace
