### ISSUE TITLE
[REQUEST] Redistribute deployment

### ISSUE THREAD

**Issue by jordan-rash** [wasmCloud/wasmCloud#855]
Given the following situation: 

1. Start a single wasmcloud host
2. Deploy a multi-part application via wadm or wash
3. Start additional hosts in lattice
4. [REQUEST] Normalize workload

In conjunction with wasmcloud/wasmcloud#693, I would like to be able to "normalize" the workload when a new host comes online.  At the moment, that can be done with `wadm` and a hack (wash scale 0) but this isn't ideal and there is no way to redistribute `wash start` based assets

Ref: https://wasmcloud.slack.com/archives/C04RVMJJH17/p1695735058510099

**Comment by connorsmith256** [comment]
@jordan-rash closing for now since we haven't had discussion in a while
