### ISSUE TITLE
[FEATURE] --label key=value to add a host label instead of HOST_key=value

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#856]
**Is your feature request related to a problem? Please describe.**
Currently you can only define labels on a host by using a documented but hidden environment variable syntax `HOST_key=value`, which will put a label on the host of `key=value`. For example, `HOST_cloud=aws` puts the label `cloud=aws` on the host.

**Describe the solution you'd like**
I would love to be able to attach labels on the host using a CLI flag instead, like `wash up --label cloud=aws -l region=us-east-1`. Additionally, the help text for the `-l,--label` CLI flag should indicate the proper environment variable as well.

**Describe alternatives you've considered**
We could add this as a flag on the wasmCloud binary itself, and I see no reason not to extend this functionality there as well.

**Additional context**
With no flag on the wasmCloud binary, adding a label should be parsed and turned into the environment variable syntax before being passed to the host.

**Comment by connorsmith256** [comment]
Note the host added support for `--label` in #706. The remaining work for this task is to add proxy support in wash 🙂
