### ISSUE TITLE
[FEATURE] `wash keys` clarity, renames, and error handling

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmCloud#863]
**Is your feature request related to a problem? Please describe.**
`wash keys` is our utility for generating NKEY public/private keypairs for signing WebAssembly components, capability providers, cluster invocations, etc etc. It is a loose wrapper around the [nkeys]() crate

There is also a problem with `wash keys` in that it always defaults to a module key, when that's not great behavior. A user may type in the following and expect a host key, but instead they get a module key:
```bash
wash keys gen host

Public Key: MDTWJTKYUGUZOS3DFYFKSDBQRD2IHVQDQXHRTHZPZ2IJIXC2V7HJBSJ7
```

**Describe the solution you'd like**
First and foremost we should make a few changes to the naming of the keys we generate. The keytype appears to default to module even if the input is invalid, but we should error out with an unknown keytype if invalid input is inserted.
```
wash keys gen --help
Generates a keypair

Usage: wash keys gen [OPTIONS] <KEYTYPE>

Arguments:
  <KEYTYPE>  The type of keypair to generate. May be Account, User, Module (Actor), Service (Capability Provider), Server, Operator, Cluster
```

Additionally, some of the keypair types are descriptive but others require clarifications in parenthesis. We should rename these at the wash level:
1. wash keys gen module -> wash keys gen actor
2. wash keys gen service -> wash keys gen provider
3. wash keys gen server -> wash keys gen host

These should be done with clap aliases so that we can make this change in a backwards compatible manner. It would be great if we could easily see the types of keypairs to generate instead of relying on the help text.

**Describe alternatives you've considered**
We could additionally argue that `wash keys gen <type>` doesn't quite fit the current set of CLI commands but for now this is a simple and backwards compatible change that we can make.

**Comment by ahmedtadde** [comment]
hey @brooksmtownsend, i have a PR out for this. Let me know if it is adequate. You mentioned 
```It would be great if we could easily see the types of keypairs to generate instead of relying on the help text.```
Is there a command for which we've done something similar? Or, do you have specific in mind to achieve that.

**Comment by thomastaylor312** [comment]
Closed in #882

**Comment by connorsmith256** [comment]
@thomastaylor312 ICYMI, I didn't close this since there was an open question for @brooksmtownsend above

**Comment by brooksmtownsend** [comment]
The thing I think we're still missing is the ability to do `wash keys gen actor` to generate an actor module key, and the others above. I don't feel like we need anything else in the help text but it would be beneficial to have the help text only mention the keys that we can generate.

To put it another way, the only other thing is to alias `actor` to `module`, `provider` to `service`, `host` to `server`, and then update the help text to 
```
The type of keypair to generate. May be account, user, actor, provider, server, operator, cluster
```

**Comment by ahmedtadde** [comment]
hey @brooksmtownsend 

I could be missing something. based on this [test](https://github.com/ahmedtadde/wasmCloud/blob/69db9efcf9d8352bd3a85caea45422162d883f32/crates/wash-cli/src/keys.rs#L272),  isn't it be the case that `wash keys gen actor` is now supported (same questions for the others)?

**Comment by thomastaylor312** [comment]
Yeah that is why I closed, I thought we now had mappings for those based on what I read in @ahmedtadde's PR

**Comment by connorsmith256** [comment]
I opened #965 to possibly help @brooksmtownsend feel good about closing this? I'm not sure what else is left
