### ISSUE TITLE
[BUG] `wash app` commands do not respect wash context

### ISSUE THREAD

**Issue by connorsmith256** [wasmCloud/wasmCloud#864]
**Describe the bug**
`wash app` commands do not use the lattice prefix from the current wash context

**To Reproduce**
1. `wash up -d -x foobar`
2. `wash ctx new foobar`
2a. `wash ctx edit --editor code foobar` (update lattice_prefix to `foobar`)
1. `wash app deploy ~/Downloads/hello.yaml`
1. _wait a few seconds for wadm to reconcile_
2. `wash get inventory`
3. _notice the host is empty_
4. `wash app deploy -x foobar ~/Downloads/hello.yaml`
5. _wait a few seconds for wadm to reconcile_
6. `wash get inventory`
7. _notice the host is now running things_

**Expected behavior**
When a context is set, `wash app` commands should respect that context

**Steps to Fix**
This one should be pretty easy to fix. Note for most commands, we get a [WashConnectionOptions](https://github.com/wasmCloud/wash/blob/44b56b22bf67aeb164a713eb50242ca8477a3eb7/crates/wash-lib/src/cli/get.rs#L59), which takes the context into account. For app commands, however, we're explicitly [using the lattice prefix on the command itself](https://github.com/wasmCloud/wash/blob/44b56b22bf67aeb164a713eb50242ca8477a3eb7/src/app/mod.rs#L179), which is ignoring the context. We should use the prefix from the `WashConnectionOptions` for all the app commands

**Comment by ahmedtadde** [comment]
hey @connorsmith256 ,

so, do we want to ignore/remove the `lattice_prefix` cmd option altogether? or do we want to do the following:
- if `lattice_prefix` cmd option is provided, use it and ignore `WashConnectionOptions.lattice_prefix`
- else, use `WashConnectionOptions.lattice_prefix` as the default

**Comment by connorsmith256** [comment]
@ahmedtadde I think the priority order you described is right 👍

**Comment by connorsmith256** [comment]
Resolved by #954
