### ISSUE TITLE
[BUG] Running `wash ctx default <...>` seems to be clearing `contexts/index.json`

### ISSUE THREAD

**Issue by vados-cosmonic** [wasmCloud/wasmCloud#866]
**Describe the bug**
When running `wash ctx`, [@jordan-rash ran into a ill-described parsing error](https://wasmcloud.slack.com/archives/C04RVMJJH17/p1697490577999699), which *seems* t be caused by the 

**To Reproduce**
1. use `wash ctx default <anything>`
1. check for `~/.wash/contexts/index.json` to be possibly empty
1. See error

**Expected behavior**

`wash ctx default <anything>` should not empty out host configuration 

**Screenshots**

**Environment (please complete the following information) **
 - OS: [e.g. Linux, MacOS]
 - Shell [e.g. bash, zsh, powershell]
 - wash Version [e.g. 0.2.0]

**Additional context**
See [wasmCloud slack discussion](https://wasmcloud.slack.com/archives/C04RVMJJH17/p1697490577999699)

**Comment by brooksmtownsend** [comment]
Fixed by #934
