### ISSUE TITLE
[FEATURE] Update `brew install wash` to use new binaries from monorepo releases

### ISSUE THREAD

**Issue by lachieh** [wasmCloud/wasmCloud#870]
Now that everything is moving into a monorepo, the homebrew recipes need to be updated to point to the new assets

**Describe the solution you'd like**
`brew install wash` should install the latest binary for the target arch for wash.

**Additional context**
Currently, the brew installation for wash will break rust environments. This should resolve that issue also.
- https://github.com/wasmCloud/wasmCloud/issues/840

**Comment by joonas** [comment]
I would love to take a pass at fixing this up, it sounds like we'd like to:

1. Use the pre-built binaries for every platform they are readily available for (and quite possibly expand the platforms we make them available for).
2. Avoid installing Rust if it's already available on the machine.

Anything else you can think of?

**Comment by rvolosatovs** [comment]
We already have binaries for aarch64/x86_64 darwin (including a universal LIPO), aarch64/x86_64 linux static, aarch64 android and x86_64 Windows MSVC, so platform support-wise I think we have enough.

RISCV is coming soon as well

**Comment by connorsmith256** [comment]
Resolved by https://github.com/wasmCloud/homebrew-wasmcloud/pull/51
