### ISSUE TITLE
[BUG] Possible race condition with linkdef cache

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmCloud#940]
**Describe the bug**

There could be a race condition on host startup where a user deletes a link (or a claim) when a new host is starting up, but that link could still exist in the cache. 

**To Reproduce**

TO BE CLEAR: I haven't observed this yet, but noticed it when working on the host. Unlike many of the other caching things we've done across the wasmCloud project, our implementation [here](https://github.com/wasmCloud/wasmCloud/blob/d4041b200b1013324136cddfa0d91fdf01dfe2c9/crates/host/src/wasmbus/mod.rs#L2109) doesn't wait to start processing events until after the initial data read. The correct order is:

1. Start the key value watch, but do not consume anything from the stream yet.
2. Read the exiting data in the bucket
3. Start handling events from the bucket

ONCE AGAIN: This is going to be highly unlikely and transitive, but wanted to call it out so we get around to fixing it eventually. There is no rush to do this right now

**Comment by connorsmith256** [comment]
@thomastaylor312 I was thinking about this last week while on a walk but forgot to bring it up, so thank you 🙏

**Comment by connorsmith256** [comment]
Note to self: I went to implement this, but ran into `Watch` (and `Ordered` consumers) not being `Clone`, so it's not as straightforward as creating the consumer in the main thread and cloning into the watcher thread (which we would then spawn only after the initial data read)

Maybe an alternative is to grab `data.stream.info().await?.state.last_sequence` in the main thread, and construct the watcher consumer manually inside the thread 😕

**Comment by brooksmtownsend** [comment]
@thomastaylor312 I know this is a possible race condition, but doesn't this work the other way? In the above case where you handle existing data and THEN handle events, couldn't we have missed events during that time?

**Comment by thomastaylor312** [comment]
So it shouldn't. The reason being you start the watch before you query the data (which means you'll get events from when you started that watch). After you've queried the data, you get all the most recent updates or deletes from the watch, which applies all changes from the point at which you started the watch (which was before you queried the data)
