### ISSUE TITLE
[BUG] wasmCloud UI doesn't load in browser

### ISSUE THREAD

**Issue by jackcarey** [wasmCloud/wasmCloud#962]
**Describe the bug**
The web UI for wasmCloud doesn't load.

**To Reproduce**
0. Folowing the commands on https://wasmcloud.com/docs/installation?os=windows
1. Open Powershell as administrator. Run: `choco install wash`
2. Run `wash new actor -t hello hello` to generate a template project
3. change directory into '/hello'.
4. Run `wash app deploy wadm.yaml`, to deploy the app.
5. Navigate to `localhost:8080` in your browser. It should load, displaying "Hello World" text.
6. In a new Powershell admin window, run `wash ui --experimental`. The terminal should say `Washboard running on http://localhost:3030 Hit CTRL-C to stop`.
7. Navigate to `localhost:3030` in your browser. You'll receive the error message below.

**Expected behavior**
The web UI should load to a usable state.

**Screenshots**
```
Unexpected Application Error!
Failed to execute 'createElement' on 'Document': The tag name provided ('/assets/logo-wide-0e72ceaf.svg') is not a valid name.
Error: Failed to execute 'createElement' on 'Document': The tag name provided ('/assets/logo-wide-0e72ceaf.svg') is not a valid name.
    at UE (http://localhost:3030/assets/index-3587af0c.js:40:16783)
    at Gx (http://localhost:3030/assets/index-3587af0c.js:40:40071)
    at Wx (http://localhost:3030/assets/index-3587af0c.js:40:39824)
    at GE (http://localhost:3030/assets/index-3587af0c.js:40:39691)
    at gc (http://localhost:3030/assets/index-3587af0c.js:40:39545)
    at Fh (http://localhost:3030/assets/index-3587af0c.js:40:35913)
    at Bx (http://localhost:3030/assets/index-3587af0c.js:40:34864)
    at P (http://localhost:3030/assets/index-3587af0c.js:25:1602)
    at MessagePort.L (http://localhost:3030/assets/index-3587af0c.js:25:1973)
```
![image](https://github.com/wasmCloud/wasmCloud/assets/35701383/5e36579f-dd96-4098-9f7d-ae7db9ff400e)

**Environment (please complete the following information) **
 - OS: Windows 11
 - Shell: Powershell
 - wasmcloud Version: 0.80.0

**Additional context**
N/A

**Comment by connorsmith256** [comment]
Hey @jackcarey, we're working on releasing a new version of wash where the UI will be downloaded from an official release. That should be available by the end of the week. In the meantime, there are a few ways to run the UI:
- check out this repo and run locally using `npm`: https://github.com/wasmCloud/wasmCloud/blob/main/washboard-ui/CONTRIBUTING.md#start-a-local-ui-development-server
- compile `wash` from latest source and run `wash ui`, which should download the released assets
- download and serve the assets yourself from https://github.com/wasmCloud/wasmCloud/releases/tag/washboard-ui-v0.1.0

**Comment by connorsmith256** [comment]
@jackcarey Thank you for your patience. wash v0.23.0 has been released to chocolatey and shouldn't have this issue anymore 🙏
