### ISSUE TITLE
[BUG] default wash context not respected in windows?

### ISSUE THREAD

**Issue by connorsmith256** [wasmCloud/wasmCloud#966]
**Describe the bug**
A new test may have exposed [a bug in windows](https://github.com/wasmCloud/wasmCloud/pull/954#issuecomment-1800472883) where the default context is not correctly written/read. We should ensure all 

**To Reproduce**
1. On windows, remove the `#[cfg(not(target_family = "windows"))]` from `test_lattice_prefix`
2. Run `cargo test test_lattice_prefix` and notice the test fails on the last assert

**Expected behavior**
Writing to/reading from the default context should work on windows

**Additional context**
See the failed test output in CI here: https://github.com/wasmCloud/wasmCloud/actions/runs/6791345626/job/18462674072

**Comment by rimbi** [comment]
I would like to start working on this.

**Comment by brooksmtownsend** [comment]
That sounds great @rimbi ! Assigned to you for now to avoid duplicate efforts

**Comment by rimbi** [comment]
I don't have the proper windows env. I am stopping working on this issue.

**Comment by brooksmtownsend** [comment]
No problem @rimbi thanks for taking a look 👍🏻
