### ISSUE TITLE
[FEATURE] Improve WasmCloud Helm Chart for modern k8s security expectations

### ISSUE THREAD

**Issue by VestigeJ** [wasmCloud/wasmCloud#978]
**Is your feature request related to a problem? Please describe.**
When deploying wasmcloud as a helm chart on most recent k8s versions you're met with security warnings violations.  

```
Pulled: ghcr.io/wasmcloud/wasmcloud-chart:0.7.0
Digest: sha256:e89daefd2590a024acee95bdbed660366d9b417419cc90659c2522b4164378c5
W1109 19:30:00.954074  111030 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (containers "wasmcloud-chart", "nats" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (containers "wasmcloud-chart", "nats" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or containers "wasmcloud-chart", "nats" must set securityContext.runAsNonRoot=true), seccompProfile (pod or containers "wasmcloud-chart", "nats" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

**Describe the solution you'd like**

Ideally the helm chart deployment incorporates the security best practices expected on modern k8s deployments to reflect the already awesome internal security considerations.

**Describe alternatives you've considered**
Alternatives are to create a less secure more permissive namespace for wasmcloud/nats to function with root permissions inside of the clusters pods.

**Additional context**

**Comment by joonas** [comment]
@VestigeJ first off, thanks for taking the time to write this feedback down, it's always great to hear from folks how we can make things better!

Let me take a look at this and see what we can do with our chart to make the story better.

I'll make sure to include this issue and ping you on the PR once we've got the necessary improvements ready to go.
