### ISSUE TITLE
Running tests on linux intermittently causes a SIGSEGV

### ISSUE THREAD

**Issue by ChrisRx** [wasmCloud/wasmCloud#98]
When running tests on linux there is a high probability of the process exiting with `SIGSEGV: invalid memory reference`.  This is an intermittent issue, but occurs very frequently running the tests with:

```shell
❯ cargo test --no-fail-fast --verbose -- --test-threads=1 --nocapture
```

The backtrace in gdb gives some hints as to what is happening:

```shell
...
Thread 19 "integration-60e" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc6142640 (LWP 1112379)]
0x00005555563c1910 in core::ptr::drop_in_place<alloc::boxed::Box<CapabilityProvider, alloc::alloc::Global>> ()
...
```

The destructor for the boxed `CapabilityProvider` is getting called to cause the segfault, implying that the underlying resource may no longer be valid.  The libloading crate thankfully already has the issue documented with a potential fix: https://github.com/nagisa/rust_libloading/issues/41

The issue itself ends up being the destructor gets called for the resource a small time AFTER the thread with the shared library terminates.  The fix (at least for the time being) looks to be passing the `RTLD_NODELETE` flag (only on linux/WSL) when loading the library so that calls to `dlclose` do not actually unload the shared library.  This does have the adverse effect of keeping the library in-memory until the process ends.

**Comment by autodidaddict** [comment]
Do you think the fix for using `RTLD_NODELETE` is something that we should only use when running in a test context, or should this be applied to the host runtime all the time?

**Comment by ChrisRx** [comment]
It seems like it isn't very safe to not use it all the time, unfortunately.  Anything that causes a library unload could potentially trigger the behavior.
