### ISSUE TITLE
[FEATURE] Replace `env_logger` with `tracing`

### ISSUE THREAD

**Issue by vados-cosmonic** [wasmCloud/wasmCloud#994]
**Is your feature request related to a problem? Please describe.**

`wash` historically used [`env_logger`](https://crates.io/crates/env_logger) for logging, and while that works it would be ideal to use [`tracing`](https://crates.io/crates/tracing) like the rest of the crates in the monorepo

**Describe the solution you'd like**

Convert the `wash` codebase to use `tracing` rather than `env_logger`

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by thomastaylor312** [comment]
Hi @Shreya111111! @MeenuyD already opened #997 to do this, but we haven't had a response in a few days. If that PR goes stale, then we'd be more than willing to pass it on to you!

**Comment by vados-cosmonic** [comment]
Ah sorry I missed this (thanks @thomastaylor312)  -- fully agreed @Shreya111111 please go ahead and give it a shot
