### ISSUE TITLE
[FEATURE] log level toggle with a control command

### ISSUE THREAD

**Issue by protochron** [wasmCloud/wasmCloud#998]
**Is your feature request related to a problem? Please describe.**
Right now the only way to change the log and tracing level in the wasmcloud host is to update the environment variable or flag and restart the process. This means that if you're trying to actively debug an issue as it is occurring, you will need to redeploy your host which may mask any issues or make it harder to reproduce a problem

**Describe the solution you'd like**
The wasmcloud host should support a control interface command to toggle the verbosity of the logging level at runtime. There is plenty of prior art in this space, ex. NATS now supports a command to dump a pprof with a SYS topic command.

**Describe alternatives you've considered**

**Additional context**

**Comment by thomastaylor312** [comment]
Another possible alternative: using a feature flagging library of some kind. I recently learned about https://openfeature.dev/, but still need to evaluate it to see if it could work

**Comment by protochron** [comment]
@thomastaylor312 I don't have a strong preference as long as it's something that can be changed at runtime. I proposed the control interface topic since it's what we have now, but if something like OpenFeature works better then I'm all for it
